### ISSUE TITLE
listen() dosen't work with cluster on "node -e"

### ISSUE THREAD

**Issue by FCO** [nodejs/node-v0.x-archive#14168]
on node v0.12.0

Show my simple test module using **cluster**

``` bash
(master) [fcorrea@dev04c6 ~/olx_push_service]$ cat use_cluster.js 
```

``` javascript
var cluster = require('cluster');
var http = require('http');
var numCPUs = require('os').cpus().length;

function CallCluster(cb) {
    this.server = http.createServer(function(req, res) {
        res.writeHead(200);
        res.end("hello world\n");
    });
}
CallCluster.prototype.listen = function(port, cb) {
    console.log("running...");
    if (cluster.isMaster) {
        cluster.fork();
        cluster.on('listening', function(){console.log("listening...")});
        cluster.on('exit', function(worker, code, signal) {
            console.log('worker ' + worker.process.pid + ' died');
        });
    } else {
        this.server.listen(port);
        setImmediate(cb.bind(http));
    }
};

module.exports = CallCluster;
```

A simple script to call the module

``` bash
(master) [fcorrea@dev04c6 ~/olx_push_service]$ cat call_call_cluster.js 
```

``` javascript
var CallCluster = require("./use_cluster.js");

var cc = new CallCluster();

cc.listen(9999, function(){console.log("listening")});
```

Running that file, everything works, the listen() calls its callback and the script keeps running.

``` bash
(master) [fcorrea@dev04c6 ~/olx_push_service]$ node call_call_cluster.js 
running...
running...
listening
listening...
^C
```

Running the same script by "node -e" does't call the listen() callback, the worker dies and the script stops running

``` bash
(master) [fcorrea@dev04c6 ~/olx_push_service]$ node -e '                       
var CallCluster = require("./use_cluster.js");

var cc = new CallCluster();

cc.listen(9999, function(){console.log("listening")});

'
running...
running...
listening
worker 16384 died
(master) [fcorrea@dev04c6 ~/olx_push_service]$
```

Is that a bug? Why isn't that working?

**Comment by misterdjules** [comment]
Thank you for reporting this issue!

It's a bug in the sense that using `node -e` doesn't setup [what's necessary for workers to be functional](https://github.com/joyent/node/blob/v0.12.1-release/src/node.js#L98-L104).'

I don't know if that's intentional. I don't see any strong reason why one couldn't use the cluster module with `node -e`, but I can understand why it's not a very common use case. @sam-github @cjihrig What do you think?

The sample code you used to reproduce the problem has another issue: it basically executes `call_call_cluster.js` twice, as a child process created by `child_process.fork` doesn't resume its execution from where `fork` was called, but spawns a new node process that runs the same file that was passed on the command line to run the original program.

This bug can be reproduced with the example provided in the [cluster's API documentation](https://nodejs.org/api/cluster.html).

Thank you again!

**Comment by FCO** [comment]
I had another problem with the "-e" flag:
using the -e flag (without cluster) the listen()'s callback isn't called until the first request.

calling the code by a file, the listen()'s callback is called "immediately"
```bash
(master) [fcorrea@dev04c6 ~/olx_rest]$ cat test2-e.js 
```
```javascript
    require("http").createServer(function(req, res) {
        res.writeHead(200);
        res.end("hello world\n");
    }).listen(9999, function(){console.log("bla")});
```

```bash
(master) [fcorrea@dev04c6 ~/olx_rest]$ node test2-e.js 
bla
^C
```

When I run the same code with "node -e" the callback waits until the first http request to run
```bash
(master) [fcorrea@dev04c6 ~/olx_rest]$ node -e '
    require("http").createServer(function(req, res) {
        res.writeHead(200);
        res.end("hello world\n");
    }).listen(9999, function(){console.log("bla")});
'
^C
(master) [fcorrea@dev04c6 ~/olx_rest]$
(master) [fcorrea@dev04c6 ~/olx_rest]$ node -e '

    require("http").createServer(function(req, res) {
        res.writeHead(200);
        res.end("hello world\n");
    }).listen(9999, function(){console.log("bla")});
' &
[1] 27557
(master) [fcorrea@dev04c6 ~/olx_rest]$ curl 127.0.0.1:9999
bla
hello world
(master) [fcorrea@dev04c6 ~/olx_rest]$
```

**Comment by cjihrig** [comment]
I don't really see a use case for using the `cluster` module with `-e`. When you call `cluster.fork()`, there isn't going to be a module to pass to `child_process.fork()` (`cluster` forks based on the process settings, not on the module it was called from). IMO, this isn't really the ideal use case for `cluster`. Using `child_process` directly would probably be better.

**Comment by sam-github** [comment]
You can't call cluster.fork() from the node REPL, either. Use `cluster.setupMaster()` if you aren't running a file.
