### ISSUE TITLE
Documentation on streams is incorrect

### ISSUE THREAD

**Issue by mucus** [nodejs/node-v0.x-archive#14351]
`transform._flush` is not called before the readable emits end. It's called after the writable has emitted a finish or prefinish.

**Comment by misterdjules** [comment]
From what I understand, these two statements are actually true, so the documentation seems to be consistent with node's behavior.

 `_flush` [is called on `prefinish`](https://github.com/joyent/node/blob/v0.12.1-release/lib/_stream_transform.js#L128-L130), and [calls done when it's done](https://github.com/joyent/node/blob/v0.12.1-release/lib/_stream_transform.js#L131), which in turns [emits `'end'`](https://github.com/joyent/node/blob/v0.12.1-release/lib/_stream_transform.js#L203).

Do you see some behavior that is not consistent with that in some code? If so, could you please share that code with us?

Thank you!
