### ISSUE TITLE
Allow to add build-in modules on compile time

### ISSUE THREAD

**Issue by piranna** [nodejs/node-v0.x-archive#14354]
Node.js convert build-in modules (child_process, path...) to C++ sources and add them to the Node.js binary on build time. Add a compile option to add some custom packages the same way so they are available with require() without needing to install them manually.

(If you are curious, I want to add [kexec](https://www.npmjs.com/package/kexec) so it can be used on [NodeOS](https://github.com/NodeOS/NodeOS) on our own Javascript-based [`/usr/bin/env`](https://github.com/NodeOS/NodeOS/blob/master/node_modules/nodeos-initramfs/env.js) instead of `child_process` :-) )

**Comment by misterdjules** [comment]
@piranna I wonder if you could use something like [nad](https://github.com/thlorenz/nad) and use [some existing work from @thlorenz](https://github.com/joyent/node/pull/8386)?

**Comment by piranna** [comment]
@misterdjules, sorry for the delay. Yes, seems i would be using them, only it doesn't seem clear to me if ```nad``` is XCode oriented or not (I'm using Ubuntu) nor if it's building Node addons or injecting the code in the Node.js code base (docs are not clear on both points). In fact, I was expecting to have a config flag that were pointing to a ```node_modules``` folder it would be recursively integrated on the final Node.js binary, it wouldn't be easier than that... :-D

Just to be sure before going down that path: would it be faster to require() the module code being it integrated in the Node.js binary than as an independent module?

**Comment by jasnell** [comment]
@piranna @misterdjules .... any further thoughts on this? My inclination is to close this here or to defer it to the convergence repo.

**Comment by piranna** [comment]
No more comments by the moment, I think this can be moved to the convergence repo, thanks :-)
