### ISSUE TITLE
Incorrect checksum for node.lib with v0.11.14 in SHASUM256.txt

### ISSUE THREAD

**Issue by mattharvs** [nodejs/node-v0.x-archive#14417]
I have been trying to execute `node "C:\Projects\kitematic-master\node_modules\node-gyp\bin\node-gyp.js" rebuild` and receive the following error:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.11.14 | win32 | x64
gyp http GET http://nodejs.org/dist/v0.11.14/node-v0.11.14.tar.gz
gyp http 200 http://nodejs.org/dist/v0.11.14/node-v0.11.14.tar.gz
gyp http GET http://nodejs.org/dist/v0.11.14/SHASUMS256.txt
gyp http GET http://nodejs.org/dist/v0.11.14/node.lib
gyp http GET http://nodejs.org/dist/v0.11.14/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.11.14/SHASUMS256.txt
gyp http 200 http://nodejs.org/dist/v0.11.14/node.lib
gyp http 200 http://nodejs.org/dist/v0.11.14/x64/node.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: node.lib local checksum 2ff781f90f3daf5a0b76c7c338cefba5992f6f9a6cfa7d8af2f9d7250a9a336e not match remote 163b53c9a6d0efe9905f6b184e917b48d98451664bd57972b9a7d2d1c4599d6b
gyp ERR! stack     at deref (C:\Projects\kitematic-master\node_modules\node-gyp\lib\install.js:299:20)
gyp ERR! stack     at Request.<anonymous> (C:\Projects\kitematic-master\node_modules\node-gyp\lib\install.js:409:24)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (C:\Projects\kitematic-master\node_modules\request\request.js:1150:12)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:907:16
gyp ERR! stack     at process._tickCallback (node.js:372:11)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Projects\\kitematic-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
```

I've downloaded the file `http://nodejs.org/dist/v0.11.14/node.lib` on several computers and have generated a SHA256 checksum using SlavaSoft HashCalc program and the online tool at `http://hash.online-convert.com/sha256-generator`.
Every time I receive the checksum `2ff781f90f3daf5a0b76c7c338cefba5992f6f9a6cfa7d8af2f9d7250a9a336e`, which differs from the checksum `163b53c9a6d0efe9905f6b184e917b48d98451664bd57972b9a7d2d1c4599d6b` specified within the file `http://nodejs.org/dist/v0.11.14/SHASUMS256.txt`.

**Comment by misterdjules** [comment]
@tjfontaine I think you had created new checksums files (with a `-win` suffix) with the correct shasums for Windows binaries. Is there any reason why we didn't want to overwrite the original SHASUMS* files?

@mattharvs This issue is fixed in subsequent 0.11.x and 0.12.x releases. Is there any reason why you cannot upgrade to them?

Thank you!

**Comment by mattharvs** [comment]
@misterdjules Yes I am upgrading to the latest version of Node, now that my internet has been reset for the month. Just reported the issue in case someone needed to use that version for whatever reason.

**Comment by jasnell** [comment]
@misterdjules ... do we need to keep this one open at this point?
