### ISSUE TITLE
Compile error on Ubuntu Server

### ISSUE THREAD

**Issue by sholladay** [nodejs/node-v0.x-archive#14422]
On an Amazon EC2 machine, `make install` is taking a very long time, eventually ending with this:

``` sh
deps/v8/tools/gyp/v8_snapshot.target.mk:13: recipe for target '/tmp/node20150403-1444-5qwfpa/node-v0.12.1/out/Release/obj.target/v8_snapshot/geni/snapshot.cc' failed
make[1]: *** [/tmp/node20150403-1444-5qwfpa/node-v0.12.1/out/Release/obj.target/v8_snapshot/geni/snapshot.cc] Error 127
make[1]: Leaving directory '/tmp/node20150403-1444-5qwfpa/node-v0.12.1/out'
Makefile:45: recipe for target 'node' failed
make: *** [node] Error 2
```

I imagine that's not very helpful. The installation strategy is via [linuxbrew](https://github.com/Homebrew/linuxbrew), which is doing this:

``` sh
./configure --prefix=/home/sholladay/.linuxbrew/Cellar/node/0.12.1 --without-npm --without-ssl2 --without-ssl3
make install
```

You can see exactly what it is doing in the [Node installation formula](https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/node.rb).

**OS:**
`Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-46-generic x86_64)`
**CPU:**
`Intel Xeon E5-2651 v2 @ 1.80GHz`
**Node Version:**
`0.12.1` (but seems to apply to older ones as well)
Downloaded from: https://nodejs.org/dist/v0.12.1/node-v0.12.1.tar.gz

The closest thing I could find on here is #9163, but my case does not involve the Pi or ARM, at all. Regardless, I tried `--without-snapshot`, which did not help.

Are there any techniques for getting more useful output in this situation?

**Comment by misterdjules** [comment]
Could you please paste the whole make output (when run from scratch) somewhere (not necessarily in this issue's comments if the output is long)? An error code of `127` usually indicates that the shell couldn't find the program that was invoked by make.

**Comment by sholladay** [comment]
If memory serves, that was actually the entire output. Will double check tomorrow, in case I am wrong.

**Comment by misterdjules** [comment]
You could set the `V=1` flag when running make like this:
``
make V=1
``
Also, is there a way for you to provide us with access to that box?

**Comment by sholladay** [comment]
@misterdjules Will be doing this later today. Assuming `V-1` does not provide anything helpful, I would be willing to give access to anyone reputable (or acting on behalf of a company, etc). However, they would need to clearly document the cause and exact fix steps, as we will have to re-apply the fix to other clones of the existing machine image.

**Comment by jasnell** [comment]
@sholladay ... any updates on this?

**Comment by sholladay** [comment]
Hi @jasnell I can still reproduce this, but haven't been able to figure out why it fails this way when installing via Linuxbrew (which doesn't do anything crazy, it's a [very simple script](https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/node.rb)). However, I managed to compile it using apt-get. It's not an apples to apples comparison, but I did at least use the same command line flags. Therefor, despite the fact that the error is coming from within Node's build process, if you guys want to cleanup tickets, I'm content with trying to move this over to the Linuxbrew tracker until I can do more debugging.

**Comment by obscaenvs** [comment]
`$ nvm install 0.12.4` fails similarly on FreeBSD 10.1 :
```
 -ffunction-sections -O3 -fno-rtti -fno-exceptions -MMD -MF /usr/home/fcar/.nvm/src/node-v0.12.4/out/Release/.deps//usr/home/fcar/.nvm/src/node-v0.12.4/out/Release/obj.target/v8_libbase/deps/v8/src/base/platform/platform-freebsd.o.d.raw  -c -o /usr/home/fcar/.nvm/src/node-v0.12.4/out/Release/obj.target/v8_libbase/deps/v8/src/base/platform/platform-freebsd.o ../deps/v8/src/base/platform/platform-freebsd.cc
../deps/v8/src/base/platform/platform-freebsd.cc:159:11: error: member reference base type 'int' is not a structure or union
    result.push_back(SharedLibraryAddress(start_of_path, start, end));
    ~~~~~~^~~~~~~~~~
1 error generated.
deps/v8/tools/gyp/v8_libbase.target.mk:100: recipe for target '/usr/home/fcar/.nvm/src/node-v0.12.4/out/Release/obj.target/v8_libbase/deps/v8/src/base/platform/platform-freebsd.o' failed
gmake[1]: *** [/usr/home/fcar/.nvm/src/node-v0.12.4/out/Release/obj.target/v8_libbase/deps/v8/src/base/platform/platform-freebsd.o] Error 1
gmake[1]: Leaving directory '/usr/home/fcar/.nvm/src/node-v0.12.4/out'
Makefile:45: recipe for target 'node' failed
gmake: *** [node] Error 2
nvm: install v0.12.4 failed!
```
