### ISSUE TITLE
tls: errors no longer emitted on cleartext objects in 0.12

### ISSUE THREAD

**Issue by mscdex** [nodejs/node-v0.x-archive#14475]
This is a regression since at least node v0.10. Latest io.js behaves like v0.10 in this regard, so it would be nice to see a fix for this in v0.12.

To reproduce:

``` javascript
var tls = require('tls'),
    net = require('net');

var sock = new net.Socket();
var clear = tls.connect({ socket: sock });

clear.on('error', function(err) {
  console.log('clear err: ' + err);
});

sock.connect(9993, 'localhost');
```

**Comment by misterdjules** [comment]
Fixed in io.js by https://github.com/iojs/io.js/pull/1046, however that fix depends on [StreamWrap](https://github.com/iojs/io.js/blob/v1.x/lib/_stream_wrap.js) and possibly other changes that have not landed in node.js.
