### ISSUE TITLE
node 0.10.38 has wrong openssl sha256/512 Makefile, x64 fails to compile.

### ISSUE THREAD

**Issue by vjukic** [nodejs/node-v0.x-archive#14481]
deps/openssl/openssl/crypto/sha/Makefile

sha256-x86_64.s:asm/sha512-x86_64.pl;   $(PERL) asm/sha512-x86_64.pl $(PERLASM_SCHEME) $@

should be 

sha256-x86_64.s:asm/sha256-x86_64.pl;   $(PERL) asm/sha256-x86_64.pl $(PERLASM_SCHEME) $@

since 

deps/openssl/openssl/crypto/sha/asm/sha512-x86_64.pl
does not have the 'if 256' statement and 256bit has been moved to:
deps/openssl/openssl/crypto/sha/asm/sha256-x86_64.pl

changing the Makefile to make correct asembler file for sha256 prevent the linker to report double initit of sha512 public vars when compiling for shared and asm blocks.

Pls correct it.

Vedran

**Comment by shigeki** [comment]
`deps/openssl/openssl/crypto/sha/Makefile` is no longer used in building Node.  It uses `deps/openssl/asm/x64-elf-gas/sha/sha256-x86_64.s` via GYP and these asm files was pre-generated with `deps/openssl/asm/Makefile`. 

Why do you need to use `deps/openssl/openssl/crypto/sha/Makefile`?

**Comment by vjukic** [comment]
to make shared library(es) using standard ./Configure and make. Along Node.JS, I need to use ssl (crypto) and V8 shared libraries in c/c++ threads (modules) on limited disk (and) memory arm space - and copy the source/structure on a devel x64 system.


Vedran.

**Comment by shigeki** [comment]
It's unexpected use for me. 
Anyway, the issue came from 88744453120fa55b0f1634efc084a5e4c42b0927 and it's easy to fix but I leave its decision to @misterdjules or other core team members.

**Comment by misterdjules** [comment]
@vjukic Is it possible for you to configure node with `./configure --shared-openssl` and build/manage the OpenSSL library on your system as is suitable for your use case?

**Comment by vjukic** [comment]
yes, indeed. Node compile and link with shared libraries just fine - for both arm and x64
the NODE configure command is the following:
./configure --without-snapshot --dest-cpu=x64 --dest-os=linux --prefix=../build/x64 --shared-v8 --shared-v8-include=deps/v8/include --shared-v8-libpath=../build/x64/lib --shared-v8-libname=v8 --shared-openssl --shared-openssl-include=../build/x64/include/openssl --shared-openssl-libpath=../build/x64/lib --shared-zlib --shared-zlib-includes=../build/x64/include --shared-zlib-libpath=../build/x64/lib

make

The problem WAS (in your case still is) with building the openssl shared libraries, that - wihout the change in the SHA child Makefile will not compile the 256bit sha (but twice the 512bit sha) code.
To build shared libssl the following configure is used (also the libz is build shared)
(in deps/openssl/openssl)
./config shared --openssldir=../../../build/x64 zlib-dynamic --prefix=../../../build/x64 -L../../../build/x64/lib -I../../../build/x64/include -lz -fPIC
make
make install

by the way - to compile the v8 as shared i needed to copy the test folder from original v8 repository, and run 
make x64.release library=shared snapshot=off

that would do it (and copy the v8.so to ../../../build/x64/lib)

Vedran.

**Comment by misterdjules** [comment]
@vjukic What I meant is: can you build OpenSSL from the OpenSSL source, not from `deps/openssl`, and build a node binary that links to that shared OpenSSL?
