### ISSUE TITLE
app.listen(port) doesn't using IPv4 but using IPv6

### ISSUE THREAD

**Issue by sxyizhiren** [nodejs/node-v0.x-archive#14575]
issue is:
"app.listen(port);" doesn't use ipv4  but using ipv6. and nodejs doc say it should use IPv4.

current it only appear on my winXp PC

nodejs version is v0.12
D:>node -v
v0.12.1

===the info for analysing================================================
```js
var net = require('net');
var app = net.createServer();

var port=81;
app.listen(port);

console.log('listen on',port);
```

C:>netstat -an
 ......
 TCP    [::]:23                [::]:0                 LISTENING       0
 TCP    [::]:81                [::]:0                 LISTENING       0
 TCP    [::]:135               [::]:0                 LISTENING       0
 ......

And telent 127.0.0.1 fail
C:>telnet 127.0.0.1 81
Connecting To 127.0.0.1...Could not open connection to the host, on port 81: Connect failed

but "telnet 0:0:0:0:0:0:0:1 81"  succeed!!

====nodejs doc say, the default host is IPv4 INADDR_ANY(0.0.0.0)=============
server.listen(port[, host][, backlog][, callback])#
Begin accepting connections on the specified port and host. If the host is omitted, the server will accept connections directed to any IPv4 address (INADDR_ANY). A port value of zero will assign a random port.

====this is the "ipconfig" of this pc===================================
C:>ipconfig

Windows IP Configuration

Ethernet adapter 10.71:

```
    Connection-specific DNS Suffix  . : china.******.net
    IP Address. . . . . . . . . . . . : 10.140.15.71
    Subnet Mask . . . . . . . . . . . : 255.255.255.0
    IP Address. . . . . . . . . . . . : fe80::d267:e5ff:fef0:be09%7
    Default Gateway . . . . . . . . . : 10.140.15.1
```

Ethernet adapter Connect to TADCPRI:

```
    Connection-specific DNS Suffix  . :
    IP Address. . . . . . . . . . . . : 192.168.254.16
    Subnet Mask . . . . . . . . . . . : 255.255.255.0
    IP Address. . . . . . . . . . . . : fe80::210:18ff:feaf:9c30%8
    Default Gateway . . . . . . . . . :
```

Tunnel adapter Teredo Tunneling Pseudo-Interface:

```
    Connection-specific DNS Suffix  . :
    IP Address. . . . . . . . . . . . : fe80::ffff:ffff:fffd%6
    Default Gateway . . . . . . . . . :
```

Tunnel adapter Automatic Tunneling Pseudo-Interface:

```
    Connection-specific DNS Suffix  . :
    IP Address. . . . . . . . . . . . : fe80::5efe:192.168.254.16%2
    Default Gateway . . . . . . . . . :
```

Tunnel adapter Automatic Tunneling Pseudo-Interface:

```
    Connection-specific DNS Suffix  . : china.******.net
    IP Address. . . . . . . . . . . . : fe80::5efe:10.140.15.71%2
    Default Gateway . . . . . . . . . :
```

**Comment by cjihrig** [comment]
This sounds like it could be related to #9195.

**Comment by aleqx** [comment]
This still happens on nodejs 7.10.0 at least on a Ubuntu 16.04.2

**Comment by gibfahn** [comment]
@aleqx could you raise a new issue in https://github.com/nodejs/node? This is an archive and isn't looked at.
