### ISSUE TITLE
Not documented misfeature: net.Socket.bufferSize may become `undefined` when write() error occur.

### ISSUE THREAD

**Issue by socketpair** [nodejs/node-v0.x-archive#14595]
Please document that or fix bug (not set stream.bufferSize to undefined).

**Comment by misterdjules** [comment]
@socketpair Are you referring to `net.Socket.bufferSize`? Also, which version of node do you refer to?

**Comment by socketpair** [comment]
Yes, I mean that.

OOPS. I checked v0.10.25. 

Will try to reproduce in 0.12....

**Comment by socketpair** [comment]
Do you know good PPA for ubuntu ? :shame:

**Comment by socketpair** [comment]
Yes, reproduced in v0.12.2

**Comment by misterdjules** [comment]
[`net.Socket.bufferSize`'s documentation](https://nodejs.org/api/net.html#net_socket_buffersize) doesn't state that its value is always a number and is never undefined, but I agree that it could be more explicit.

@socketpair Would you have some time to submit a PR to make the documentation more explicit in this regard? The best way to do that would be to submit a PR against the v0.10 branch, and the change would be ported to v0.12 (and eventually master) when v0.10 is merged into v0.12.

Thank you!
