### ISSUE TITLE
error parameter of stream.Writable.write's callback not documented

### ISSUE THREAD

**Issue by socketpair** [nodejs/node-v0.x-archive#14594]
Really, this callback is called with argument if error occured. This is VERY NICE, since I should not setup 'error' event handler on the stream ! But this is NOT documented.
1. Please also add in documentation (to stream) that this callback is not the same as callback on 'drain' event.
2. Please also add in documentation that this callback will be called in any case, including errors occured while writing.

If everything is true, please fix.

**Comment by misterdjules** [comment]
@socketpair I agree that the documentation could be more detailed in this area. Thank you for raising that up! Would you have some time to submit a PR?

**Comment by socketpair** [comment]
1. No, my English is bad :(
2. Also, someone should check that this behaviour is implemented in all type of streams. I have check only for TCP.
