### ISSUE TITLE
SNICallback can be used without any browser?

### ISSUE THREAD

**Issue by efkan** [nodejs/node-v0.x-archive#14815]
Hello,

I want to use SNICallback on my project for separate two HTTPS addresses on the same port.
One of the addresses is used for API calls like `https://api.myDomain.com/products` and between two computers without any browser.

But I've read the below sentence on http://en.wikipedia.org/wiki/Server_Name_Indication
> To make use of SNI practical, the vast majority of users must use web browsers that implement it.

I'm wondering '*can I use SNICallback without any browser?*'

**Comment by brendanashworth** [comment]
I'm not really sure but I'll close this in favor of discussion in https://github.com/nodejs/node-v0.x-archive/issues/14814 (to merge issues).

**Comment by bnoordhuis** [comment]
For people coming here from Google:

> can I use SNICallback without any browser?

Yes, but both client and server need to speak SNI.  It's just that the majority of clients are browsers.
