### ISSUE TITLE
Nodejs 0.12.2 SIGSEGV crash on GC

### ISSUE THREAD

**Issue by wangjia184** [nodejs/node-v0.x-archive#15446]
This happens very frequently on our production servers after upgrading to node 0.12.2,  Operation system is CentOS 6.6 Final (docker latest image)

you can pull the docker image by this command

```
sudo docker pull wangjia184/nodejs:v0.12.2
```

Here is the backtrace for the crash

```
/lib64/libc.so.6(+0x326a0)[0x7f0602d576a0]
/usr/bin/node(_ZN2v88internal23PointersUpdatingVisitor12VisitPointerEPPNS0_6ObjectE+0x18)[0x91ee98]
/usr/bin/node(_ZN2v88internal13ObjectVisitor14VisitCodeEntryEPh+0x28)[0xa3e588]
/usr/bin/node(_ZN2v88internal20MarkCompactCollector29EvacuateNewSpaceAndCandidatesEv+0xeb9)[0x93ea19]
/usr/bin/node(_ZN2v88internal20MarkCompactCollector11SweepSpacesEv+0x2f1)[0x964421]
/usr/bin/node(_ZN2v88internal20MarkCompactCollector14CollectGarbageEv+0x2a)[0x96c0da]
/usr/bin/node(_ZN2v88internal4Heap11MarkCompactEv+0x9f)[0x8e831f]
/usr/bin/node(_ZN2v88internal4Heap24PerformGarbageCollectionENS0_16GarbageCollectorENS_15GCCallbackFlagsE+0x288)[0x8f8aa8]
/usr/bin/node(_ZN2v88internal4Heap14CollectGarbageENS0_16GarbageCollectorEPKcS4_NS_15GCCallbackFlagsE+0xce)[0x8f913e]
```

It seems something wrong happened in V8 GC.

And I found someone encountered similar issue here. https://code.google.com/p/chromium/issues/detail?id=408380

I have to rollback to nodejs v0.10.36

**Comment by misterdjules** [comment]
@wangjia184 Thank you very much for filing this issue, and my apologies for the late response. This issue seems to be similar to other issues reported by other users, like https://github.com/joyent/node/issues/25648.

How do you reproduce this problem? If we can reproduce it reliably, that'll help us a lot in finding the root cause of the problem.

Thank you!

**Comment by wangjia184** [comment]
This issue only happened randomly,  2 or 3 times per day.
I couldn't find a way to reproduce it.

And my NodeJS has some native plugins (*.so).  I was wondering if it is caused by bug of native plugin -- maybe the V8 object was not freed correctly there? As you know, there is some breaking changes in V8 / libuv between nodejs 0.10 & 0.12,  hence the plugin has to be adapter for the new version. I checked the code in plugin and don't have no luck so far
