### ISSUE TITLE
Exception in RoundRobinHandle (0.12.2)

### ISSUE THREAD

**Issue by shunanya** [nodejs/node-v0.x-archive#15519]
The strange exception in Node.js 0.12.2
Error: channel closed
    at ChildProcess.target.send (child_process.js:414:26)
    at sendHelper (cluster.js:676:8)
    at RoundRobinHandle.handoff (cluster.js:198:3)
    at RoundRobinHandle.distribute (cluster.js:184:20)

**Comment by dayuoba** [comment]
@shunanya may you show your test code to reproduce this exception?

**Comment by shunanya** [comment]
Oh, it's a clustered HTTP server (3 workers) that works under big load (more than 80 req/sec). The code is quite big. It works under Debian 7. I have downloaded the source and compiled it. Sometimes, it got a mentioned exception. Unfortunately, I had to back to the previous version (0.10.32) that is working much stabler.
