### ISSUE TITLE
CLI option to not print out the trailing newline character

### ISSUE THREAD

**Issue by redchair123** [nodejs/node-v0.x-archive#16525]
The option is similar to echo's `-n` argument to suppress the newline character.

**Comment by evanlucas** [comment]
Would be nice. As a workaround, one could use `process.stdout.write()`

**Comment by bahamas10** [comment]
:+1: on this... i've used this in the past

    node -pe '5 * 5' | tr -d '\n'

but it's not perfect as it will strip ALL newlines

**Comment by misterdjules** [comment]
That sounds like a reasonable feature request to me, thank you! /cc @joyent/node-coreteam.

@Niggler @bahamas10 @Niggler Would any of you be interested in submitting a PR for that?

**Comment by jasnell** [comment]
+1 this would be useful
