### ISSUE TITLE
TLS Peer certificate exponent listed as "10001"

### ISSUE THREAD

**Issue by iamthechad** [nodejs/node-v0.x-archive#17202]
The exponent should probably be stored in the peer certificate object as the number `65537` instead of the binary`10001` (unless there's a reason for the binary representation).

**Comment by misterdjules** [comment]
@iamthechad `10001` is an hexadecimal representation, not a binary representation. The exponent is not stored in any specific human readable representation, `10001` is just the way [it's converted by node's native layer](https://github.com/joyent/node/blob/v0.12.2-release/src/node_crypto.cc#L1222-L1223).

What is the problem with using this specific representation?

**Comment by iamthechad** [comment]
There's no problem per se. It's just inconsistent with tools that show the decimal value by default. (Although, if I can't tell binary and hex apart I have worse issues. Admittedly, other tools show it as `0x10001` which makes it more obvious.)

**Comment by misterdjules** [comment]
@iamthechad I agree it is definitely confusing, and some clearer output would be beneficial. 

@joyent/node-coreteam I wonder if that would be considered an API change. Even though the API documentation doesn't mention the exponent, some users could be relying on its format to parse `getPeerCertificate`'s output.

I would suggest considering it's an API change and submitting a PR against master to have both the decimal and hexadecimal forms of the exponent displayed, or at least to prefix the hexadecimal form with `0x`.

Thoughts?

**Comment by indutny** [comment]
This is certainly would be a breaking change. What do you think about just documenting it?

**Comment by misterdjules** [comment]
Documenting in v0.10/v0.12 and making it clearer by changing the output in v0.13 sounds good to me.

**Comment by indutny** [comment]
Ok, makes sense :)

**Comment by misterdjules** [comment]
@iamthechad Do you have some time to make the changes as described [in my previous comment](https://github.com/joyent/node/issues/17202#issuecomment-98885573)?

**Comment by iamthechad** [comment]
I'd be happy to take a stab at it. Where should I make the changes - against the `v0.10` and `v0.12` tags?

**Comment by misterdjules** [comment]
@iamthechad For the documentation changes, that would be against v0.10. For the code changes, that would be against master. Thank you :+1:

**Comment by iamthechad** [comment]
I've submitted doc changes. Are you also asking if I could make the code changes? I can certainly take a stab at it. Is there any documentation around for setting up a dev environment for Node? I'd love to be able to load things into a decent IDE so I can at least navigate easier.

**Comment by misterdjules** [comment]
@iamthechad If you're interested in making the code changes, of course that would be great too! Make sure you read the [README.md file](https://github.com/joyent/node/blob/master/README.md) and the [CONTRIBUTING.md file too](https://github.com/joyent/node/blob/master/CONTRIBUTING.md).

There isn't any instruction on how to build node with specific IDEs yet as far as I know.

If you have any question, some of the node contributors are in the #libuv IRC channel on the Freenode servers.

**Comment by jasnell** [comment]
@iamthechad ... if IDE's are your thing, eclipse has fairly good node/js editing support and you can configure it to use the config/makefile build. It's a bit... "heavyweight"... tho.

**Comment by misterdjules** [comment]
I'm available to guide anyone willing to pick this issue up and submit a PR that changes the output to make it clearer as mentioned in https://github.com/joyent/node/issues/17202#issuecomment-98882408. Ping me on GitHub by mentioning @misterdjules or find me on IRC (jgi in #libuv on Freenode).

**Comment by iamthechad** [comment]
@misterdjules I'd be more than happy to pick this up. I've successfully submitted a doc change against 0.12, so I have a better understanding of the expected PR format, but it would definitely be nice to have a guide.

**Comment by misterdjules** [comment]
@iamthechad Excellent! If you have any question, please join #libuv on Freenode (IRC) and ping me (I'm jgi in that channel).

**Comment by misterdjules** [comment]
@iamthechad I'm also available by email at jgilli at fastmail dot fm.

**Comment by misterdjules** [comment]
Closing, as code/behavior changes landed in node v4.0.0 and later with https://github.com/nodejs/node/commit/847459c29b365a5b5928d42a5d4f60e9f9fc156a, and documentation changes for v0.10 and v0.12 are tracked with https://github.com/nodejs/node-v0.x-archive/pull/25142.

Thank you again @iamthechad!
