### ISSUE TITLE
fs.createWriteStream should support "autoClose": false

### ISSUE THREAD

**Issue by Pauan** [nodejs/node-v0.x-archive#20880]
The title is self-explanatory.

Because I'm manually closing the file descriptor, I don't want `fs.createWriteStream` to close it for me, but it lacks the `"autoClose": false` option.

I'm currently working around this by setting `stream.closed = true`, but that's a hack that relies upon internal details of how `fs.createWriteStream` is implemented, so I'd rather not rely upon it.

**Comment by misterdjules** [comment]
That sounds like a reasonable feature to add. @joyent/node-coreteam Thoughts?

@Pauan I would suggest submitting a PR targeted to v0.12, do you have some time for that?

**Comment by Pauan** [comment]
@misterdjules The fix itself is easy (just a handful of lines of code in lib/fs.js), but I don't have time to download the source for Node, make the changes, write unit tests for the changes, compile, run the unit tests, etc.

**Comment by misterdjules** [comment]
@Pauan No problem! Thank you for filing this issue :+1:

**Comment by saquibkhan** [comment]
@misterdjules May I attempt to submit this feature?

**Comment by cjihrig** [comment]
@saquibkhan go for it!

**Comment by saquibkhan** [comment]
@cjihrig ok thanks!

**Comment by saquibkhan** [comment]
Created a PR that fixes the issue: #25275. Thank you @Pauan , @misterdjules , @cjihrig
