### ISSUE TITLE
fs.symlink wrong error message

### ISSUE THREAD

**Issue by dmail** [nodejs/node-v0.x-archive#21852]
When I run `require('fs').symlinkSync('existing/folder/path', 'bad/folder/path', 'dir')`

Results in 
`Error: ENOENT, no such file or directory 'existing/folder/path'`
Instead of
`Error: ENOENT, no such file or directory 'bad/folder/path'`

**Comment by eezstreet** [comment]
It might be due to the trailing /, but I'm not an expert on this.

**Comment by dmail** [comment]
Sorry for the trailing slash, it was a typo, I've edited my message.

**Comment by CGavrila** [comment]
I might be getting this wrong, but why would it complain about the target directory? The error message seems to indicate that the source folder does not exist, even though you claim that it does. 

Do you get true if you do `fs.existsSync('existing/folder/path')` ?

**Comment by dmail** [comment]
`require('fs').symlinkSync('./a', 'b', 'dir');`
succeeds, but
`require('fs').symlinkSync('./a', 'unexisting-folder/b', 'dir');`
results in
`Error: ENOENT, no such file or directory './a'`
instead of
`Error: ENOENT, no such file or directory 'unexisting-folder'`

**Comment by CGavrila** [comment]
Right, can confirm that this happens in v0.12, but not in v0.10.

**Comment by piscisaureus** [comment]
The error message is incorrect indeed. 
I fix in io.js already exists for this - https://github.com/iojs/io.js/commit/bc2c85ceef7ac034830e4a4357d0aef69cd6e386
