### ISSUE TITLE
require() problems when using symlink as node_modules

### ISSUE THREAD

**Issue by foxx** [nodejs/node-v0.x-archive#25090]
In some situations, `node_modules` needs to be kept on `/tmp` and used in another directory as a symlink. For example, when using Vagrant shared folders, having `node_modules` would result in things either breaking or becoming slow, due to the way it does shared host/guest folders.

However, this seems to break dependancy resolving for most packages. For example, if your own package dependancy required `q`, but then another package you depended on also required `q`, it would result in the other package not being able to find `q`.

This would result in errors such as;

```
Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/tmp.bXj3vtPi7x/gulp/index.js:5:13)
```

To fix this, I had to use the following horrible hack;

```js
  // horrible symlink hack
  process.env.NODE_PATH = __dirname + '/node_modules';
  require('module').Module._initPaths();
```

I'd like to say this is a bug within Node, but I don't know enough about the internals of `module.js` to make a sound judgement.

Some thoughts/feedback would be appreciated, thank you

**Comment by vmadman** [comment]
Yeah, I'm running into this one as well.  We're forced to do the Vagrant symlink workaround because of a seemingly simple issue with Vagrant/VirtualBox and windows paths that no one cares to fix.

I'm also in the same boat about calling it a bug, I assume it is, but really do not know.

At least I have a workaround to try, so thanks for that @foxx.

**Comment by foxx** [comment]
I actually found a better fix for this @vmadman, discussed [here](https://github.com/npm/npm/issues/9479#issuecomment-146519463).

In short, the symlink directory source needs to be called "node_modules" as well, seen here;

```
ln -sv /tmp/node_modules ./node_modules
```

**Comment by foxx** [comment]
Closing this out in favour of https://github.com/npm/npm/issues/9479#issuecomment-146519463

**Comment by vmadman** [comment]
oh, wow, nice.  Thanks a lot :)
