### ISSUE TITLE
inconsistent behaviour between osx and windows when network is disconnected during an http download.

### ISSUE THREAD

**Issue by kessler** [nodejs/node-v0.x-archive#25104]
Hi,

The following code behaves differently on OSX and Windows:
```javascript
var http = require('http')
var fs = require('fs')

var url = 'http://mirror.internode.on.net/pub/test/1000meg.test'

try {
	fs.unlinkSync('testdownload')
} catch (e) {
	console.error(e)
}

var file = fs.createWriteStream('testdownload')
var req = http.get(url)

req.on('response', function(res) {
	setInterval(function() {
		console.log(file.bytesWritten)
	}, 1000).unref()

	res.pipe(file)
})
```
On OSX when the network is disconnected and then reconnected again, the file will continue to download after a short delay. With Windows on the other hand, the file will never continue to download once the network was restored.

Tested on OSX yosemite 10.10.1 and windows 7 / windows 8.1 using node 0.12.0

I couldn't find any issues about this and frankly not so much material on the wild internet as well. I do find it hard to believe I'm the only one who ran into this issue on the other hand. Did I do something wrong in this simple code?

If indeed its an inherit problem in the underlying OS, should we implement something that will make this behave consistently across platforms? (e.g. cluster module round robin)

**Comment by robozevel** [comment]
Couldn't reproduce on Windows 7, seems to be resuming just fine. Still curious why no error was thrown (ENETDOWN?)

**Comment by kessler** [comment]
Maybe its a Virtual Machine thing, will test on a real machine with 8.1 shortly

**Comment by kessler** [comment]
ok tested on a real Win 7.0, it does resumes.

looking for a real windows 8.1 machine.

**Comment by kessler** [comment]
@robozevel any chance you can get yaron to test this code on a real 8.1 machine. It seems everyone around here is using 7.0 :-)
