### ISSUE TITLE
make test fails on `ln -fs out/Release/node node` - Debian Wheezy

### ISSUE THREAD

**Issue by mdeguzis** [nodejs/node-v0.x-archive#25101]
OS: Debian 7 Wheezy
Python: /usr/bin/python
Python ver. 2.7.3

When running make test, I encounter:

```
ln -fs out/Release/node node
Installation failure!
```

**Comment by misterdjules** [comment]
With what version of node did you have this problem? Can you provide someone withaccess to the machine or an equivalent setup where we can reproduce the problem to investigate more?

**Comment by ProfessorKaos64** [comment]
This was during the make process, how would I have node installed? Can you expand a little bit on what you would like log out put for? I'll gladly attach that this evening.

**Comment by misterdjules** [comment]
@ProfessorKaos64 Sorry, I meant "With what branch of node did you have this problem, and at what commit?".  In other words, what is the output of `git rev-parse HEAD` before running make? Having the whole make command log in a gist would also be helpful.

**Comment by ProfessorKaos64** [comment]
Ok, I'll make sure to save that into a gist when I try tonight, thank you for your help.

**Comment by sam-github** [comment]
Any updates @ProfessorKaos64, or have you worked this out, and the issue can be closed?

**Comment by ProfessorKaos64** [comment]
Thanks for the reminder! I'll try this again soon. Very busy with family today.

**Comment by cmyk** [comment]
Failing for me as well.

``[02:40|% 100|+ 788|-   7]: Done ``                                             
``make: *** [test] Fehler 1``
