### ISSUE TITLE
backport NODE_DEPRECATED fixes from io.js

### ISSUE THREAD

**Issue by misterdjules** [nodejs/node-v0.x-archive#25267]
@bnoordhuis has [fixed the `NODE_DEPRECATED` macro](https://github.com/bnoordhuis/io.js/commit/609fa0de039f4285c402ac3f646fcd5d4828d3aa) which wasn't effective anymore (@trevnorris had [already spotted this a while ago](https://github.com/joyent/node/pull/8158#issuecomment-52667211)).  There's [another change](https://github.com/iojs/io.js/pull/1626) that fix a problem when the first change would trigger a compilation error on older compilers.

I suggest porting both changes in v0.12.

/cc @joyent/node-coreteam.

**Comment by cjihrig** [comment]
+1 to both commits.

**Comment by jasnell** [comment]
+1
