### ISSUE TITLE
Debugger: emits `compileError` instead of `afterCompile` every time.

### ISSUE THREAD

**Issue by 3y3** [nodejs/node-v0.x-archive#25266]
So every time then new script is required and compiled we expect to receive `afterCompile` event from debugger. Instead of this there is `compileError` event.
I can't reproduce this error on iojs.

**Comment by jasnell** [comment]
@3y3 ... thanks for this. Would it be possible to provide a test case that can be used to reproduce the problem?

**Comment by 3y3** [comment]
Sure.
```js
var fs = require('fs'),
    Net = require('net'),
    Protocol = require('_debugger').Protocol,
    spawn = require('child_process').spawn,
    assert = require('assert');

var connection,
    protocol = new Protocol(),
    assertInfo = [];
    
protocol.onResponse = function(message) {
  if (message.body.type === 'event')
    assertInfo.push(message.body.event);

  if (assertInfo.length == 2)
    process.nextTick(function() {
      assert.deepEqual(assertInfo, ['afterCompile', 'break']);
      process.exit(0);
    });
};
    
function Debug(argv){
  connection = Net.createConnection(5858)
    .on('connect', resume)
    .on('data', protocol.execute.bind(protocol))
    .on('error', function() {});
}

function resume() {
  var data = JSON.stringify({seq: 0, type: 'request', command: 'continue'});
  connection.write('Content-Length: ' + Buffer.byteLength(data, 'utf8') + '\r\n\r\n' + data);
}

function test() {
  fs.writeFileSync('test.js', '');
  spawn('node', ['--debug-brk', 'test']);
  Debug();
}

test();
```

**Comment by jasnell** [comment]
Ok, not seeing an issue running this test case with v0.12 on macosx. Just need a bit more data. Which version of node are you running? What is the output you're expecting vs. the output you're actually seeing.

**Comment by 3y3** [comment]
I test it on node 0.12.2 on Win8.1 x64.
I'm expecting
`assertInfo == ['afterCompile', 'break']`
but actually I'm seeing 
`assertInfo == ['compileError', 'break']`

**Comment by jasnell** [comment]
Thank you @3y3, it's on my list of items to investigate further!

**Comment by bajtos** [comment]
@bnoordhuis here is the issue for the problem I was describing your yesterday. Here is my code reproducing the problem - it passes on Node v0.10 and io.js 2.1.1, but fails on Node v0.12.

```js
if (process.send) {
  // child process
  setTimeout(function() { console.log('hello world'); }, 500);
  return;
}

var cp = require('child_process');
var net = require('net');
var Protocol = require('_debugger').Protocol;
var assert = require('assert');

var child = cp.fork( __filename, [], { execArgv: ['--debug-brk'] });
process.on('exit', function() { child.kill(); });

// Wait for the child to start
setTimeout(debug, 500);

function debug() {
  var client = net.connect(5858);
  var protocol = new Protocol();

  client.on('data', protocol.execute.bind(protocol)).setEncoding('utf-8');
  protocol.onResponse = function(msg) {
    if (msg.body && msg.body.type === 'event') {
      assert.equal(msg.body.event, 'afterCompile');
      console.log('PASSED');
      client.end();
      child.kill();
      process.exit();
    }
    // console.log(' <-- ', msg.body || msg);
  };

  client.on('connect', function() {
    var msg = JSON.stringify({ seq: 1, type: 'request', command: 'continue' });
    var header = 'Content-Length: ' + Buffer.byteLength(msg, 'utf-8');
    client.write(header + '\r\n\r\n' + msg);
  });
}
```

**Comment by sam-github** [comment]
Its not an exact science, but I estimated this as P-2, see https://nodejs.org/contribute/code_contributions/workflow.html#workflow_md_values, @bajtos, is its effect worse than that?

**Comment by bajtos** [comment]
@sam-github I'd personally call it P-1.

Any debugger client that keeps track of files loaded by V8/Node will not show any files that were loaded (require()d) after the debugging session started. This is especially important for the case of `--debug-brk`, where the process starts with only a handful of files and everything else is loaded later.

There are workarounds - Node Inspector explicitly queries V8 when it receives a break event in a file that is not loaded inside VM, I am treating `compileError` as `afterCompile` when running on Node v0.12.

I think other popular debuggers like [WebStorm](https://www.jetbrains.com/webstorm/) and [Node.js Tools for Visual Studio](https://github.com/Microsoft/nodejstools) may be affected (especially when debugging a remote process), but I don't know this for sure and I don't know if they have implemented any workaround by now.

**Comment by nidaca** [comment]
I think this is a P-1, not a P-2. Isn't debugging a significant tool for node developers community ?
