### ISSUE TITLE
Is PSK (Pre-shared keys) supported by Node.js?

### ISSUE THREAD

**Issue by ghost** [nodejs/node-v0.x-archive#25277]
I'm trying to implement a client in node.js that can field a request that wants to handshake using pre-shared keys (PSK) with a MQTT server (Mosquitto) which supports PSK. I can't seem to find any samples or documentation that talks about how you'd set this up. Is this mechanism supported by node.js? Thanks in advance for your help!

**Comment by dnakamura** [comment]
It looks like PSK is not supported

https://github.com/joyent/node/blob/master/lib/_tls_wrap.js#L514
http://stackoverflow.com/questions/22998229/preshared-keys-tls-psk-with-aes-256-cbc-sha-with-node-js-server

**Comment by jasnell** [comment]
Yeah, had to do a bit of investigation on this myself but it does not look to be supported at this time. (unless I've missed something.. /cc @joyent/node-coreteam ?)

**Comment by jasnell** [comment]
@flyingmouse: we can potentially look at adding support for PSK in the future.
