### ISSUE TITLE
Intolerance to TLS False Start

### ISSUE THREAD

**Issue by cconcolato** [nodejs/node-v0.x-archive#25276]
This issue started as [issue 485080 on Google Chrome](https://code.google.com/p/chromium/issues/detail?id=485080). 

To reproduce the issue, on a Linux Ubuntu (14.04):
1. Clone the repository https://github.com/cconcolato/http2-push
2. Edit the server to replace 'localhost' by your IP address
3. Run the server with nodejs v0.12.2 
4. Open Chrome on the same machine or on a separate machine and navigate to https://<serverIP>:8091/client.html
5. Bypass the certificate warning "Proceed to <IP> (unsafe)"
6. You should see Chrome displaying ERR_CONNECTION_CLOSED.
7. Change Google Chrome Policy (see Chrome's issue for detail), you should see ERR_CONNECTION_RESET

According to [Chrome's people analysis](https://code.google.com/p/chromium/issues/detail?id=485080#c6), Node seems to have a problem with TLS False Start.

**Comment by jasnell** [comment]
Yep, this is unsurprising. Not sure quite yet what would need to change to address this but it's definitely something we should look at. Going to mark this as a feature request.
