### ISSUE TITLE
test: Fix make jslint to include test scripts too.

### ISSUE THREAD

**Issue by saquibkhan** [nodejs/node-v0.x-archive#25280]
Lint doesn't run on test scripts and errors are caught at later stage during code review.

We should fix ```make jshint``` to include test scripts too.

**Comment by saquibkhan** [comment]
Can you give your feedback? /cc @joyent/node-coreteam @misterdjules

**Comment by jasnell** [comment]
+1 this would definitely be helpful. PR? :-D

**Comment by saquibkhan** [comment]
@jasnell I can work on this if coreteam thinks its useful. 
Should the PR go in master?

**Comment by jasnell** [comment]
Yes, for something like this, master would be the target. 

/cc @joyent/node-coreteam

**Comment by saquibkhan** [comment]
Please find lint log after we run it on test
**Found 2090 errors, including 814 new errors, in 302 files (742 files OK).**

**Comment by misterdjules** [comment]
@saquibkhan Just to make sure there's no confusion, jshint is not used by node currently to lint JavaScript source, instead it uses Closure.

**Comment by saquibkhan** [comment]
@misterdjules Can you tell me how to fix ```Multi-line strings are not allowed``` ?

**Comment by saquibkhan** [comment]
@misterdjules @jasnell Please find the PR #25288 for this.
Fixed 2077 errors in 302 files.
**Open issues:**
1 file 13 errors [Gist](https://gist.github.com/saquibkhan/eb429d530e716335fb76)
1 test failed node/test/message/throw_in_line_with_tabs.js

**Comment by silverwind** [comment]
FYI, we've switched to eslint on io.js so this can only land on the 0.12 branch. A bit of unfortunate that I haven't noticed this issue before, or else I'd have adviced doing it on the io.js tree.

https://github.com/nodejs/io.js/issues/1721 is pending to include test linting for eslint.

**Comment by brendanashworth** [comment]
I doubt this will land on the 0.12 branch, so I'll close this. Eslint is now used in node 4, anyways.
