### ISSUE TITLE
fs.watchFile regression in 0.12

### ISSUE THREAD

**Issue by kanongil** [nodejs/node-v0.x-archive#25345]
When `fs.watchFile(path, callback)` is called on an non-existing file, the `0.12` behavior is different than `0.10`.

In `0.10.38`, the callback is never called.

In `0.12.2`, the callback is called immediately with this object as `curr` and `prev`:
```js
{ dev: 0,
  mode: 0,
  nlink: 0,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 0,
  ino: 0,
  size: 0,
  blocks: 0,
  atime: Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
  mtime: Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
  ctime: Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
  birthtime: Thu Jan 01 1970 01:00:00 GMT+0100 (CET) }
```

This new behavior breaks one of my scripts.

**Comment by dnakamura** [comment]
what platform are you running on?

**Comment by kanongil** [comment]
I get the same results on Linux, Mac OS X and Win 8.1.

**Comment by dnakamura** [comment]
Node versions affected: 0.12.2
Platforms affected: linux, win, mac
High priority/critical category: no
recommended priority: P-2
Existing io.js issue: N/A
Pull request included: no
Reproducible: yes
Exists in later version: 0.13.0-pre
@joyent/node-coreteam

**Comment by brendanashworth** [comment]
FWIW it was decided in io.js to accept the behaviour and document it: https://github.com/nodejs/io.js/pull/2169. This can probably be closed, idk if doc changes get backported?

**Comment by thefourtheye** [comment]
https://github.com/nodejs/io.js/pull/2169 has a test case as well.

**Comment by brendanashworth** [comment]
I'll close this as it is fixed on node 4. If anyone thinks the doc change should be backported, it is possible, but I guess that'll sit.
