### ISSUE TITLE
Return cancel function from process.nextTick()

### ISSUE THREAD

**Issue by zenflow** [nodejs/node-v0.x-archive#25355]
Would be great to be able to cancel nextTick callback without having to wrap nextTick, similar to clearTimeout, clearImmediate, cancelAnimationFrame, etc., except maybe with different syntax. I suggest the following...

``` js
var cancel = process.nextTick(functionThatNeverGetsCalled);
cancel();
```

**Comment by jasnell** [comment]
I think we'd want to figure out our larger strategy around Promises first. If we ever did bring Promises into the stdlib, it would make more sense to have nextTick return a Promise object.

**Comment by zenflow** [comment]
Then what about
```js
var placeholder = process.nextTick(functionThatNeverGetsCalled);
placeholder.cancel()
```
in the meantime?

Of course it begs the question of whether one should be able to cancel a promise. 

Personally I try to only make Promises when I know I won't want to back out. What is the performance overhead (thinking garbage collection) of wrapping nextTick with a function like [cancellableNextTick](https://github.com/zenflow/cancellable-next-tick/blob/master/lib/index.js) for those times I might want to back out? If it is significant when callbacks are repetitively cancelled and reinstated, then It may be worthwhile to abstain from promising nextTick to allow us to optionally cancel.

> The biggest problem we have with `Promise`s is that they're insufficient to represent all forms of asynchrony. Like cancelable actions. *- Guillermo Rauch via twitter*

**Comment by jasnell** [comment]
I cannot imagine that this is a change that we'd make any time soon, particularly not within the `v0.x` stream. What I would recommend is opening an issue as a feature-request in either http://github.com/nodejs/node or http://github.com/nodejs/io.js.

**Comment by vkurchatkin** [comment]
With promises you don't need nextTick at all. This code is mostly equivalent:

```javascript
Promise.resolve().then(callback);
```

**Comment by dayuoba** [comment]
what's the scene of using cancle for process.nextTick()?

**Comment by zenflow** [comment]
Here is an [example use-case](https://github.com/zenflow/cancellable-next-tick/tree/master/examples/model)

Another example is [waitr](https://github.com/zenflow/waitr).

**Comment by zenflow** [comment]
And I'm sure I'm not the only person dreaming up use-cases for this, since we have clearTimeout, clearImmediate & cancelAnimationFrame
