### ISSUE TITLE
node debug: `cont` past the end of the script freezes the debugger

### ISSUE THREAD

**Issue by ackalker** [nodejs/node-v0.x-archive#25358]
Using Node v0.12.3 on Arch Linux x86_64.

Steps to reproduce:

``` sh
$ touch trivial.js # empty script
$ node debug trivial.js
< Debugger listening on port 5858
debug> . ok
break in trivial.js:2
  1 
> 2 });
debug> cont
debug> cont
```

At this point, the debugger is completely frozen, keyboard input doesn't echo and neither hitting ^C nor ^D is able to either regain control or exit the debugger. I have to switch to another terminal and forcibly kill the node process.

Besides the breakpoint line number being wrong (putting a `console.log("Hello, world");` in trivial.js does give a correct line number, but the freeze problem remains), I would expect the first `cont` command to cause the debugger to display a message like "program terminated" or some such.
The second `cont` should at least display an error message, at which point users should still have the chance to either `restart` the script or exit the ebugger.
Users have come to expect this kind of behaviour from debuggers like GDB, etc.

**Comment by dnakamura** [comment]
Node versions affected: 0.12.3
Platforms affected: windows, linux
High priority/critical category: no
recommended priority:P2
Existing io.js issue: N/A
Pull request included: no
Reproducible: yes
Exists in later version: n/a
@joyent/node-coreteam

**Comment by jasnell** [comment]
Able to reproduce on OSX 10.10.3

**Comment by piotrtomiak** [comment]
We have run into the same problem debugging over TCP. Basically, the nodejs process, if run with --debug-brk, never ends. Protocol seems to have started to behave strange in version 0.11.13, where "compileError" message was introduced and it plainly replaced "afterCompile" messages. If there is a compile error in a script the process just terminates without sending compileError message. Anyway, in versions 0.11.15 and over (including 0.12.0 and over) the process never terminates, if we call "continue" command after hitting the initial breakpoint. And that's a huge problem, as you have to manually kill the process, which should terminate by itself. It looks like some thread never finishes or so. This is a pretty bad user exprience if someone is debugging nodejs... Can you put a higher priority on this?

**Comment by mcshaman** [comment]
Same problem please fix

**Comment by CermakM** [comment]
Reproduced on GNU/Linux Fedora release 26
```
$node --version
v6.11.2
```
