### ISSUE TITLE
Segfault in v0.11.0+ on Darwin when using Buffer.toString()

### ISSUE THREAD

**Issue by lmorchard** [nodejs/node-v0.x-archive#25357]
[Here's an attempt at a reduced test case that reliably causes the issue on my machine.](https://github.com/lmorchard/nodejs-buffer-bug-case)

I'm experiencing a segfault with node v0.11.0+ while processing a bunch of data in buffers with `Buffer.toString()`. 

It does _not_ seem to occur on v0.10.38.

It does _not_ occur on my Ubuntu VM.

It also appears to be somewhat non-deterministic - the segfault does not occur on the same buffer contents every time, and on rare occasions does not happen at all. But, it usually happens, given enough data & time. I'm hoping the stuff in my test case repo offers enough of both to reproduce elsewhere.

**Comment by epc** [comment]
It's line 222 in unicode.cc, part of the v8 code embedded in node:
```byte third = str[2] ^ 0x80;```

**Comment by lmorchard** [comment]
If / when someone fixes this, it would be great to know if there happens to be a practical workaround for folks who still have earlier node versions installed. I thought I had a magical fix, but it turned out only to make the problem more rare.

**Comment by lmorchard** [comment]
FWIW, I did some amateur `git bisect` work and it seems to happen in de9ee2a, but not 74c08403d89366d184089bee9a2ccd4e46cd05c4. Not sure how helpful that is, though, since the bad commit is an upgrade of libuv

**Comment by myndzi** [comment]
I seem to be intermittently getting a segfault related to this issue. I don't know what input caused the crash, and it only happens occasionally. I got a dump from node-segfault-handler here: https://gist.github.com/myndzi/d9a56baa33456b339f2e

I compiled with `./configure --debug` and enabled core dumps, am waiting for it to happen again. The test case in the OP does not cause a crash for me. I'm using node 0.12.4.

**Comment by lmorchard** [comment]
FWIW, I suspect this issue was fixed in https://github.com/joyent/node/commit/78b0e30954111cfaba0edbeee85450d8cbc6fdf6

Haven't had a chance to try it out yet, though.

**Comment by myndzi** [comment]
I suspect you're right, but it'd be good to be certain. Your original report sounded very much like the bug I experienced, but the comment by epc had me thinking it was unrelated; I wound up posting a separate issue which lead to that patch.
