### ISSUE TITLE
inconsistent emit end event

### ISSUE THREAD

**Issue by martingg88** [nodejs/node-v0.x-archive#25381]
I have issued 10 requests and get back 10 response as well. however i do have an issue that the "end" event may be emitted less than 10. Any idea how to fix this issue?

**Comment by sparkida** [comment]
Could you provide an example of how to produce this issue?

**Comment by martingg88** [comment]
here we go. you may need this async library.

https://github.com/caolan/async

var max_try = 1000;

var tasks = [];

for(var i = 0; i < max_try; i++){
tasks.push(function(cb){
send(cb);

});
}

var end_count = 0;
var response_count = 0;
function send(cb){

var req = request('http://localhost:6767');
req.on('error', function(error){return cb(error);});
req.on('end', function(){
    //end_count may not be equal to max_try
    //here may not run the callback because end event is not emitted.
    end_count++;
    return cb();
});
req.on('response', function(response){
    //response_count will always be equal to max_try
    response_count++;
});

req.on('data', function(data){
    //here could be possible the data is not received in complete for request in parallel
});
}

// here will run tha tasks concurrently up to max_try at a time.
async.parallelLimit(tasks, max_try, function(error, result){

if (error){
    return cb(error);
}

return cb();
});

**Comment by martingg88** [comment]
are u able to reproduce the issue?

**Comment by martingg88** [comment]
i realized that some requests in batch will only emit data event half way and hang there forever. feel strange on this issue.

**Comment by martingg88** [comment]
here is the outcome i have after debug http.request. 

if we issue 100 http.request in parallel and thus we may be some request emit data half way and hang over there. any idea what can cause this issue?

**Comment by sparkida** [comment]
@martingg88 I'm having trouble replicating the issue, could you provide a test that I can run? Here's what I have right now:
```javascript
var max_try = 100;
var tasks = [];
var async = require('async');
var request = require('request');
var http = require('http');
var express = require('express');
var app = express();
var instance = http.createServer(app);
var end_count = 0;
var response_count = 0;

instance.listen(6767);
app.get('/', function (req, res) {
    res.send('hello');
});

for(var i = 0; i < max_try; i++){
    tasks.push(function(cb){
        send(cb);
    });
}

function send (cb) {
    var req = request('http://localhost:6767');
    req.on('error', function (error) {
        return cb(error);
    });
    req.on('end', function () {
        //end_count may not be equal to max_try
        //here may not run the callback because end event is not emitted.
        end_count++;
        return cb(null, end_count);
    });
    req.on('response', function (response) {
        //response_count will always be equal to max_try
        response_count++;
        console.log('res');
    });
    req.on('data', function (data) {
        //here could be possible the data is not received in complete for request in parallel
        console.log(response_count, data.toString());
    });
}

// here will run tha tasks concurrently up to max_try at a time.
async.parallelLimit(tasks, max_try, function(error, result){
    console.log('done', error, result);
});
```

**Comment by martingg88** [comment]
i try to provide the simple steps to produce this issue. lets me know if you have any issue. 

1. first get youtube url as follows:
	a. visit to http://en.savefrom.net/ and paste the following link into text box.
	   https://www.youtube.com/watch?v=cFP4QFDG3vE
	b. after that, right click "download" button can copy the link address and put it in text file first

2. download the fast-download to track the request issue. try to put focus on "//comment:" in FastDownload.js file.
	a. here is the link to npm download fast-download library. 
		https://github.com/martingg88/node-fast-download.git

	b.  use the script below to run the download etc(node download.js > log.txt).
		after run this script, you should be able to 
		see output in console that show number of end events is not equal to "chunksAtOnce"  size.
		
		var fast_download = require('fast-download');

		var download = {
			resumeFile: true,
			chunksAtOnce: 100,
			destFile: 'C:\\project\\app\\stream\\.tmp\\upload\\video.mp4'
		};

		var youtube_encoded_url = "paste your youtube encode url here";
		
		var dl = new fast_download(youtube_encoded_url, download);

		dl.on('start', function(dl){
			console.log('start: ');
		})

		dl.on('error', function(err){
			console.log('error: ');
		})

		dl.on('end', function(){
			console.log('end: ');
		})

		dl.on('finish', function(){
			console.log('finish: ');
		})

**Comment by sparkida** [comment]
@martingg88 can you replicate this issue without the third party "fast-download" module? If not I would presume it is because of that module and [Issue #2](https://github.com/zenflow/node-fast-download/issues/2). To determine this for certain, could you provide a test I can run by just copying and pasting? Otherwise there are just many possibilities to say for certain this is a Node specific issue.

**Comment by martingg88** [comment]
sure. i have create a pure script to produce this issue without the third party module. But we must include async module to produce this issue due the concurrency technique applied here. 

as usual, you have to get youtube encode url to test this script (download.js);

1. Get youtube url as follows:
a. visit to http://en.savefrom.net/ and paste the following link into text box.
https://www.youtube.com/watch?v=cFP4QFDG3vE
b. after that, right click "download" button can copy the link address.
c. put the copied link into variable "youtube_encode_url" in download.js file. 

2. run the script as follows:
a. put the copied link into  "youtube_encode_url"  variable in download.js file. 
b.  you can change "destination_file_path" variable in download.js to your prefer path in order to save the download file. 
c. you can adjust "chunk_size" variable to lowest or highest value to see the outcome. by default it is set to 100 chunk size that most likely to produce this issue. 
d. node download.js > log.txt

var http = require('http');
var url = require('url');
var fs = require('fs');
var _ = require('lodash');
var async = require('async');

http.globalAgent.maxSockets = 999;

/* ------ Start Setting -------- */

var youtube_encode_url = 'http://r5---sn-8qj-q5qd.googlevideo.com/videoplayback?ratebypass=yes&sver=3&dur=87.214&expire=1432888908&upn=STPPPH0vVnA&key=yt5&mime=video%2Fmp4&initcwndbps=2552500&pcm2cms=yes&signature=4EB71E87AEE7842E35874E557463D1C94E7B53E0.73C790E638CC49B22A8DB47CC680B73315E0207C&ipbits=0&itag=22&mm=31&ip=113.160.248.219&mv=m&mt=1432867284&ms=au&pl=24&id=o-AFgFJjCdZFW38lRYRfQM5CBe2MAHtzGzOSyzUthpGeAZ&source=youtube&fexp=916104%2C9406614%2C9407440%2C9407535%2C9408142%2C9408366%2C9408588%2C9408710%2C9409208%2C9412773%2C9413150%2C9413503%2C9414629%2C9414875%2C9415304%2C9415447%2C952612&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Csource%2Cupn%2Cexpire&title=Batman+Unlimited-+Animal+Instincts+Trailer+2015';
var chunk_size = 100;
var destination_file_path = "C:\\project\\app\\stream\\.tmp\\upload"

/* ------ End Setting -------- */

var headers = null;

var file_size = null;

var start_position = 0;
var end_position = 0;
var total_download_length = 0;

var total_download_length_for_each_chunk = 0;

var response_end_count = 0;

async.series({

   'getRedirectUurl' : function(callback){
   
       var uri = url.parse(youtube_encode_url);
   
       var req = http.request({'method' : 'HEAD', 'host': uri.host, 'path': uri.path}, function(res){
	   
			youtube_encode_url = res.headers.location;
			
			callback();
			
	   });
	   
	   req.on('error', function(err){
	   
		   callback(err);
	   });
	   
	   req.end();
   },
   
   'headers' : function(callback){
   
       var uri = url.parse(youtube_encode_url);
       var req = http.request({'method' : 'HEAD', 'host': uri.host, 'path': uri.path}, function(res){
			headers = res.headers;
			callback();
	   });
	   
	   req.on('error', function(err){
		   callback(err);
	   });
	   
	   req.end();
   },
   
   'download' : function(callback){
   

        var uri = url.parse(youtube_encode_url);
		file_size = headers['content-length'];
		start_position = 0;
		end_position = file_size;
		total_download_length = end_position  - start_position;
		
		total_download_length_for_each_chunk = Math.ceil(total_download_length/chunk_size);
		
		console.log('Total file size : ', total_download_length);
		console.log('Total file size for each chunk : ', total_download_length_for_each_chunk);
		
		var chunk_size_arr = _.range(chunk_size);
		var tasks = _.map(chunk_size_arr, function(number){
		
			 return function(callback){
				var range_start = start_position + (number * total_download_length_for_each_chunk);
			    var range_end = (range_start + Math.min(total_download_length_for_each_chunk, total_download_length - (number * total_download_length_for_each_chunk))) - 1;
				var range = 'bytes=' + (range_start) + '-' + (range_end);

				var req = http.request({'method' : 'GET', 'host': uri.host, 'path': uri.path, 'headers' : {'range' : range}}, function(res){
				
				
					    console.log('response status code at chunk postion ' + number + ' : ', res.statusCode);
						console.log('response content-length at chunk postion ' + number + ' : ', res.headers['content-length']);
		 
						res.on('error', function(err){
						   console.log('response error at chunk postion ' + number + ' : ', err);
						});
						
						// number of end event emitted is not equal to 'chunk_size'	
						// due to data event will emit half way for certain request. 			
						res.on('end', function(){
							console.log('response end count at chunk postion ' + number + ' : ',  response_end_count++);
							callback();
							
						});
						
						// data event will emit half way for certain request. 
						res.on('data', function(data){
							//console.log(data.length);
						});
						
						
						// you will have number of files stored in your specified directory. 
						// number of files will be equal to 'chunk_size'.
						// If you find response_end_count != chunk_size, then it means some files is missing data. 
						// for example, chunk_size = 100, response_end_count = 98 (zero-based-index), then you will have 100 - (98 + 1) = 1 and thus 1 file is missing data.
						// you can check file size to determine whether the file is missing data.	  
                        // file size for each file most likely equal to 'total_download_length_for_each_chunk'						
						res.pipe(fs.createWriteStream(destination_file_path + "\\" + number + '.mp4'));
						
						
				});
			   
			    req.on('error', function(err){
				    console.log('request error at chunk postion ' + number + ' : ', err);
				    callback();
		        });
			   
			   	req.end();
				  
				
				
			};
		});
		
		
		async.parallelLimit(tasks, chunk_size, function(error){
			callback();
		});
   }
   
}, function(err, result){

     //finally, you will see this outcome if not hang. otherwise you won't see it. 
     console.log('-------------- Script Outcome -----------------');
	 console.log('Done : ', true);
	 console.log('-------------- End Script Outcome -----------------');
	 
});

**Comment by martingg88** [comment]
@sparkida let me know if you have issue about the script. thanks.

**Comment by martingg88** [comment]
@sparkida  are you able to produce this issue?

**Comment by martingg88** [comment]
anyone who can solve this issue? please.
