### ISSUE TITLE
Problem with Zlib

### ISSUE THREAD

**Issue by Ciloe** [nodejs/node-v0.x-archive#25476]
Hi, 

I have a problem with Zlib. I have this error : 

```shell
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: invalid code lengths set
    at Zlib._binding.onerror (zlib.js:296:17)
npm ERR! weird error 8
npm ERR! not ok code 0
```

I have this code when I use zlib. But I don't know if it's here I have the bug...

```javascript
                archivesName.forEach(function (archive) {
                    Model.parseDateRefProduit(archive);
                    fs.createReadStream(archive)
                        .pipe(zlib.createGunzip())
                        .pipe(createFile);
                });
```

I need help to understand...

Thank you !

**Comment by jasnell** [comment]
@Ciloe ... in order to determine what may be happening, we'd need a bit more information -- preferably in the form of a simple test case that reliably reproduces the issue.

**Comment by Ciloe** [comment]
Hi, 

I'm sorry, I can't say more (my client forbids me). Because I d'ont know when, in the code, Zlib crach.

I will see more, and tel you later if I see the problem.

thank you :)

**Comment by brendanashworth** [comment]
I'm going to close this for now, as @jasnell says, there isn't anything to go off of. If you can create some sort of code test or give us some more debugging information, please open a new issue @ https://github.com/nodejs/node.
