### ISSUE TITLE
Some V8 Fatal error while working with buffers.

### ISSUE THREAD

**Issue by Somebi** [nodejs/node-v0.x-archive#25480]
Was working on my own Websocket implementation and after serious load got this error:

Frame is not yet complete, mask is missing.
# 
# Fatal error in ../deps/v8/src/heap/incremental-marking.cc, line                                                                                                                              488
# CHECK(success) failed
# 

Worker 1982 died
2015-06-04T15:47:17.709Z slave spawned, process id:1984

==== C stack trace ===============================

 1: V8_Fatal
 2: ??
 3: v8::internal::IncrementalMarking::OldSpaceStep(long)
 4: v8::internal::FreeList::Allocate(int)
 5: v8::internal::Heap::AllocateRaw(int, v8::internal::Allocation                                                                                                                             Space, v8::internal::AllocationSpace)
 6: v8::internal::Heap::AllocateMap(v8::internal::InstanceType, i                                                                                                                             nt, v8::internal::ElementsKind)
 7: v8::internal::Factory::NewMap(v8::internal::InstanceType, int                                                                                                                             , v8::internal::ElementsKind)
 8: v8::internal::Map::RawCopy(v8::internal::Handle<v8::internal:                                                                                                                             :Map>, int)
 9: v8::internal::Map::CopyReplaceDescriptors(v8::internal::Handl                                                                                                                             ev8::internal::Map, v8::internal::Handle<v8::internal::Descript                                                                                                                             orArray>, v8::internal::TransitionFlag, v8::internal::MaybeHandle                                                                                                                             v8::internal::Name, v8::internal::SimpleTransitionFlag)
10: v8::internal::Map::CopyGeneralizeAllRepresentations(v8::inter                                                                                                                             nal::Handlev8::internal::Map, int, v8::internal::StoreMode, Pro                                                                                                                             pertyAttributes, char const_)
11: v8::internal::Map::CopyGeneralizeAllRepresentations(v8::inter                                                                                                                             nal::Handlev8::internal::Map, int, v8::internal::StoreMode, cha                                                                                                                             r const_)
12: v8::internal::Map::GeneralizeRepresentation(v8::internal::Han                                                                                                                             dlev8::internal::Map, int, v8::internal::Representation, v8::in                                                                                                                             ternal::Handle<v8::internal::TypeImpl<v8::internal::HeapTypeConfi                                                                                                                             g> >, v8::internal::StoreMode)
13: v8::internal::Map::PrepareForDataProperty(v8::internal::Handl                                                                                                                             ev8::internal::Map, int, v8::internal::Handle<v8::internal::Obj                                                                                                                             ect>)
14: v8::internal::LookupIterator::PrepareForDataProperty(v8::inte                                                                                                                             rnal::Handlev8::internal::Object)
15: v8::internal::Object::SetDataProperty(v8::internal::LookupIte                                                                                                                             rator_, v8::internal::Handlev8::internal::Object)
16: v8::internal::Object::SetProperty(v8::internal::LookupIterato                                                                                                                             r_, v8::internal::Handlev8::internal::Object, v8::internal::Str                                                                                                                             ictMode, v8::internal::Object::StoreFromKeyed)
17: v8::internal::Object::SetProperty(v8::internal::Handle<v8::in                                                                                                                             ternal::Object>, v8::internal::Handlev8::internal::Name, v8::in                                                                                                                             ternal::Handlev8::internal::Object, v8::internal::StrictMode, v                                                                                                                             8::internal::Object::StoreFromKeyed)
18: v8::internal::StoreIC::Store(v8::internal::Handle<v8::interna                                                                                                                             l::Object>, v8::internal::Handlev8::internal::Name, v8::interna                                                                                                                             l::Handlev8::internal::Object, v8::internal::Object::StoreFromK                                                                                                                             eyed)
19: v8::internal::StoreIC_Miss(int, v8::internal::Object*_, v8::i                                                                                                                             nternal::Isolate_)
20: ??
Stats:
Current rps: 557.6
Reqs 207254 / 187753 / 0 (started/finished/failed)
Pages 187753 / 187753 / 0 (success/finished/failed)
Web socket opened connections: 1900
Frame is not yet complete, length is missing.
Frame is not yet complete, length is missing.
Frame is not yet complete, length is missing.
Frame is not yet complete, mask is missing.
Frame is not yet complete, length is missing.
Frame is not yet complete, mask is missing.
Frame is not yet complete, mask is missing.

**Comment by jasnell** [comment]
@Somebi ... could you provide a simple test case that reliably reproduces the issue?

**Comment by jasnell** [comment]
@domenic

**Comment by domenic** [comment]
Can you try next-nightly where buffer is entirely rewritten and V8 is updated? https://iojs.org/download/next-nightly/

**Comment by jasnell** [comment]
@Somebi ... any updates?

**Comment by bradisbell** [comment]
I don't have a test case... just a note that this occurred to me when running a simple `forever restartall`.  Node.js v0.12.6 on Ubuntu 14.04 x64.  Forever 0.14.2.

```
$ forever restartall


#
# Fatal error in ../deps/v8/src/heap/incremental-marking.cc, line 488
# CHECK(success) failed
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::internal::IncrementalMarking::StartMarking(v8::internal::IncrementalMarking::CompactionFlag)
 3: v8::internal::IncrementalMarking::Start(v8::internal::IncrementalMarking::CompactionFlag)
 4: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags)
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag)
 6: v8::internal::Factory::NewProperSubString(v8::internal::Handle<v8::internal::String>, int, int)
 7: v8::internal::Runtime_StringSplit(int, v8::internal::Object**, v8::internal::Isolate*)
 8: ??
Illegal instruction (core dumped)

```
