### ISSUE TITLE
SSLCARevocationFile and  SSLVerifyDepth equivalents in https.server ?

### ISSUE THREAD

**Issue by com2** [nodejs/node-v0.x-archive#25496]
In the https.server options I don't see equivalents listed of these Apache options. Any plans to include them?

**Comment by misterdjules** [comment]
Not that I know of. @indutny Thoughts?

**Comment by indutny** [comment]
I don't think that we have APIs for VerifyDepth, but we have `crl` option for `tls.Server`.
