### ISSUE TITLE
Behaviour of writeHead()

### ISSUE THREAD

**Issue by FlorianLoch** [nodejs/node-v0.x-archive#25490]
Hi guys,
I noticed the following - in my eyes quite strange - behaviour of ````writeHead()```` called on a ````http.ServerResponse```` instance. If the second parameter (````statusMessage````) is omitted it works as expected, also if a value is given. I am using v0.12.4 on a Windows machine and an older release (v0.10.38 on Ubuntu).

But when giving ````undefined```` as second parameter it does not skip setting the default status message, but it skips setting the headers as given via the third parameter. 

```javascript
var http = require("http");

var someValue = undefined; //Not assigned during flow...

http.createServer(function (req, res) {
  res.writeHead(200, req.headers);
  res.end();
}).listen(8090);

http.createServer(function (req, res) {
  res.writeHead(200, someValue, req.headers);
  res.end();
}).listen(8091);

http.createServer(function (req, res) {
  res.writeHead(200, "My fancy status message", req.headers);
  res.end();
}).listen(8092);

http.createServer(function (req, res) {
  res.writeHead(200, "", req.headers);
  res.end();
}).listen(8093);
```

Please check yourself via ````curl -v http://localhost:809x````

Update: I took a look at the source in ````lib/_http_server.js```` - I guess line 187 should be replaced by something like the following:

````javascript
if (util.isNullOrUndefined(obj)) {
  obj = reason;
}
````

This would prevent overwriting a potenially set third parameter by an empty second one,

**Comment by FlorianLoch** [comment]
Is there anybody willing to have a look at this? I mean it isn't crucial at all, but it might lead (in my case it did) to confusion.

**Comment by brendanashworth** [comment]
This is just how the http module handles optional arguments. You need to specify the second argument (in some manner, shape or form) in order for core to pick up the third argument.

Closing as a non-issue, please reopen if you disagree.
