### ISSUE TITLE
Segfault in node v.0.10.36

### ISSUE THREAD

**Issue by dstibrany** [nodejs/node-v0.x-archive#25495]
OS: Ubuntu 12.04.4 LTS
Node version: v0.10.36

We run batch jobs nightly (web scrapers) and I am running into segfaults maybe once a week. I cannot reproduce (at will) and the majority of the time if I re-run the batch jobs after a crash, everything will work fine.

I added node-segfault-handler and always get more or less the following stack trace: (https://gist.github.com/dstibrany/8bf2e4a4f55a6d610660)

I haven't had much success getting a core dump with debug symbols. The problem is that when I run my app with the Debug version of node, I run into issues similar to this (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/nodejs/5oWZwM7esD0/uKhWqgLf6zkJ):

```
#
# Fatal error in ../deps/v8/src/hydrogen-instructions.cc, line 641
# CHECK(cur == other_operand) failed
#
```

Any advice on how I should proceed?

**Comment by misterdjules** [comment]
@dstibrany Thank you for reporting this problem. I created another issue to track the crash with debug builds of node here: https://github.com/joyent/node/issues/25498.
