### ISSUE TITLE
execfile fail when a 'bat' file's path contain "("  

### ISSUE THREAD

**Issue by sxyizhiren** [nodejs/node-v0.x-archive#25505]
if a bat file's path contain "(" then execfile will fail. i test it on XP/WIN7/WIN10. only WIN7 could work correctly.
i have pull request to libuv.  https://github.com/libuv/libuv/pull/392.
i write here FYI

```
var batch = require('child_process');
var fileName = 'C:/nodecode/a(b/abc.bat'; 

var execOption = { 
    encoding: 'utf8',
    timeout: 10000, 
    maxBuffer: 200*1024,
    killSignal: 'SIGTERM',
    cwd: null,
    env: null };

batch.execFile(fileName,null,execOption,function (err,stdout,stderr) {
    console.log('err:',err,'stdout',stdout,'stderr',stderr);
});
```

it will raise error like:
'c:\nodecode\a' balabala...

**Comment by piscisaureus** [comment]
@sxyizhiren 

Did it not work to just add "(" to the wspbrk() search list.
I think the issue would also be fixed if you just quoted all paths that contain a (.

**Comment by sxyizhiren** [comment]
@piscisaureus 
i did such test before, in uv_spawn, before call CreateProcessW, i add quote to arguments, but still fail.
```
// here i use wsnprintf(buf,L"\"%s\"",arguments);
if (!CreateProcessW(application_path,
                     buf, // replace arguements
                     NULL,
                     NULL,
                     1,
                     process_flags,
                     env,
                     cwd,
                     &startup,
                     &info)) {
```
