### ISSUE TITLE
npm install results in segmentation fault

### ISSUE THREAD

**Issue by saiprasadbutta** [nodejs/node-v0.x-archive#25528]
Hi,

```
I am trying to install node.js on TI platform(AM437x) through Yocto. But i am facing  problem. After i install when i run npm install it results in segmentation fault. Version of node source is 0.12.4. I have followed the below steps to install node.js
```

./configure --without-snapshot --dest-cpu=arm --dest-os=linux --with-arm-float-abi=softfp
make 
make install
  Please let me know why this issue is caused and how it can be resolved.

Best Regards,
Sai

**Comment by sam-github** [comment]
Can you post a gist of the command output? Its not clear at all what segfaulted. Node? gcc? make?

I'm not familiar with the `AM37x`, are you sure this is supported architecture?
