### ISSUE TITLE
An error about cluster.js

### ISSUE THREAD

**Issue by XadillaX** [nodejs/node-v0.x-archive#25529]
``` sh
TypeError: Cannot read property 'apply' of undefined
    at ChildProcess.<anonymous> (cluster.js:692:7)
    at ChildProcess.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
```

The error was occurred here:

``` javascript
// Returns an internalMessage listener that hands off normal messages
// to the callback but intercepts and redirects ACK messages.
function internal(worker, cb) {
  return function(message, handle) {
    'use strict';

    if (message.cmd !== 'NODE_CLUSTER') return;
    var fn = cb;
    if (!util.isUndefined(message.ack)) {
      fn = callbacks[message.ack];
      delete callbacks[message.ack];
    }
    fn.apply(worker, arguments);
  };
}
```

It may crash [PM2](https://github.com/Unitech/PM2/issues/1101). I think this issue should be solved by not only PM2 but also node.js itself.

Help, thanx.

**Comment by cjihrig** [comment]
@XadillaX are you able to provide a self contained piece of code that reproduces the issue?

**Comment by sam-github** [comment]
@XadillaX also, what is your node version (`node -v`) and platform?

**Comment by XadillaX** [comment]
@sam-github 0.12.2

@cjihrig sorry, i don't know which part occurred this error.

and i'm not sure that the author said that https://github.com/Unitech/PM2/commit/0ab72488054a95a562c1c9e5b31f4e036b3723d4 should fix this error.

**Comment by sam-github** [comment]
OK, I'll take a look at the cluster code. That is a horrible pm2 hack, btw. `process.send()` is supposed to throw if the process is not connected. Its not supposed to throw with the error you pasted above, but it is supposed to throw.
