### ISSUE TITLE
path.extname produce type error : undefined is not a function time to time

### ISSUE THREAD

**Issue by solshark** [nodejs/node-v0.x-archive#25539]
Hi,

I have very weird behavior. Time to time function path.extname throws error TypeError: undefined is not a function.

It happens randomly. It might happened if filename contains '[' or ']' or '.' or anything else - but cannot reproduce constantly.

``` coffee
filename += path.extname req.query.s3_object_name
```

I cannot deliver example (can't make something which will reproduce it), but it happens on my server time to time for few weeks for now. Restarting process allow it to work for some time, before next strange filename will be used. 

Same file which caused error after restart will be processed ok.

Any idea?

**Comment by dnakamura** [comment]
What platform and version are you running. Also if you could post the stacktrace that would be usefull

**Comment by jasnell** [comment]
A simple test case that at least reproduces the problem part of the time would be helpful also. I know that can be difficult to provide at times, but without it, it's very difficult to test and debug.
