### ISSUE TITLE
Need a synchronous version of Readline

### ISSUE THREAD

**Issue by manikawnth** [nodejs/node-v0.x-archive#25546]
Readline continuously emits 'line' events.
We need a synchronous capability with an option {pause:true} where after every 'line' event it goes to paused mode. And only after the consumer listens the event, he should invoke 'resume' to resume the next line event.

There are many use cases for file read stream as input for readline

**Comment by jasnell** [comment]
Realistically, it's not very likely that this would get implemented in the core API. You ought to be able to use a module like `async` to accomplish something like this, however.... (or perhaps one of the available Promise implementations)
