### ISSUE TITLE
fs.renameSync ignoring files with parameters

### ISSUE THREAD

**Issue by krishna383** [nodejs/node-v0.x-archive#25550]
When a file is renamed and when I use renameSync to update the files, it does not work when the file reference includes few parameters.

For instance:

My css file includes below line:

src: url('../fonts/fontawesome-webfont.eot?v=4.3.0');

On executing 

fs.renameSync('src/main/webapp/dist/assets/fonts/fontawesome-webfont.eot', 'src/main/webapp/dist/assets/fonts/fba865de.fontawesome-webfont.eot')

The line in my css is ignored and not replaced.

**Comment by cjihrig** [comment]
Are you saying the file is not renamed in the file system, or the file is not renamed inside your CSS file. The former would be a bug, the latter won't happen.
