### ISSUE TITLE
Unable to get stdout or stderr on interactive child process

### ISSUE THREAD

**Issue by jung-kim** [nodejs/node-v0.x-archive#25555]
node: v0.10.35

I want to be interactive with a child process however below stdout or stderr is not being called. Is this because a buffer is not filled or something?  Below code works if I change to `.spawn('git', ['status]')`

What is worse is that this result in hanging processes although I did not detached them.

```
var cp = require('child_process');
var childProcess = cp.spawn('git', ['add', '--patch']);

childProcess.stdout.on("data", function(data) { console.log(1, data.toString()); });
childProcess.stderr.on("data", function(data) { console.log(2, data.toString()); });

childProcess.stdin.write('e');
```

**Comment by dnakamura** [comment]
what platoform are you running on? Appears to work correctly on win 7 x64
