### ISSUE TITLE
gcc 5.x detection in configure

### ISSUE THREAD

**Issue by marguerite** [nodejs/node-v0.x-archive#25578]
Hi,

In "configure", gcc version is determined by `o['variables']['gcc_version'] = 10 * cc_version[0] + cc_version[1]`, while cc_version is from `cc_version, is_clang = compiler_version()`, in this case:

it assumed function `compiler_version()` will surely return a version tuple which length is 2 or more.

but that is not always `true`.

on some systems like openSUSE Tumbleweed w/ gcc 5.1.1), `cc=gcc-5`, and `cc -dumpversion` will return `5`, then `version = (5, )`. 

Here's my patch:

<pre>
ndex: node-v0.12.5/configure
===================================================================
--- node-v0.12.5.orig/configure
+++ node-v0.12.5/configure
@@ -479,6 +479,14 @@ def compiler_version():
                           stdout=subprocess.PIPE)
   version = tuple(map(int, proc.communicate()[0].split('.')))

+  # gcc-5 returns "(5,)", but later cc_version requires at least 2 parameters
+  # existing in version tuple.
+  if len(version) < 2 :
+    proc = subprocess.Popen(shlex.split(CC) + ['--version'],
+                          stdout=subprocess.PIPE)
+    minor_version = int(proc.communicate()[0].split('.')[1])
+    version = (version[0],minor_version)
+
   return (version, is_clang)
</pre>

**Comment by jasnell** [comment]
Can you provide a PR?
