### ISSUE TITLE
Require doesn't work the same way in sub-module dependencies when running in VM sandbox as it does for the top level Javascript

### ISSUE THREAD

**Issue by tjcarroll2** [nodejs/node-v0.x-archive#25598]
Use runInNewContext with a sandbox that sets require: myRequire.
The myRequest method calls Module's require.
Let's call the code to run in the new context as module A.
Module A requires module B.   Module B requires Module C.
When Module A is run and starts executing the require('ModuleB') statement,
see the call to myRequire.
However, when myRequire call require it appears that the module construction of Module B doesn't run in the same sandbox context.   So, when module B calls require('Module C'), myRequire is no longer used and instead the standard Module#require is called.  
If myRequire is being used to validate require requests then there doesn't appear to be a way to do this with submodules.

**Comment by jasnell** [comment]
Can you provide a test case that reliably demonstrates the problem?
