### ISSUE TITLE
net: Wrong localPort on using the same socket object for multiple connect/destroy

### ISSUE THREAD

**Issue by phanikumars** [nodejs/node-v0.x-archive#25621]
When the same socket object is used for multiple .connect(), the socket.localPort is not refreshing with new localPort used by the OS.

See the discussion on mailing list:
https://groups.google.com/d/topic/nodejs/eT3xanyP83U/discussion

**Comment by cjihrig** [comment]
Related io.js PR - https://github.com/nodejs/io.js/pull/2095

**Comment by rmg** [comment]
AFAICT, this bug is present in 0.10, 0.12, and iojs. I didn't bother looking back any further, but I suspect it has been around for a little while.

**Comment by rmg** [comment]
I've also opened PR #25753 in this repo in case it is more convenient.
