### ISSUE TITLE
Include LD_LIBRARY_PATH with all compiled modules

### ISSUE THREAD

**Issue by piranna** [nodejs/node-v0.x-archive#25627]
Or something similar :-)

After adapting node-canvas to be able to compile it as a [statically linked dynamic library](https://github.com/Automattic/node-canvas/issues/551), that seems [it's the recomended way to create compiled modules](https://n8.io/converting-a-c-library-to-gyp/) so they don't depend on globally installed dynamic libraries, I've found that some complex libraries like node-canvas can have several fairly big libraries like Cairo, libpng... that are complex to compile and otherwise would be shared with other modules, specially now with npm@3 having a flat depencies tree. That's why I think this library depencies (cairo, libpng, libjpeg-turbo and so) could be moved to their own modules and node-canvas (and others) use them as dependencies). With Javascript modules this is easy since it's already managed by ```require()```... problem here is that a compiled module is using another compiled module.

The solution I'm proposing here is that since the compiled modules (the .node files) are .so files with a different extension, Node.js would update the LD_LIBRARY_PATH to include the location of the .node files of its dependencies (somewhat related to https://github.com/npm/npm/issues/6437), or maybe simpler ```require()``` itself could navigate over the node_modules folders of the project searching for these dependencies (probably defined on the package.json in a sharedDependencies or dynamicDependencies or similar?) so all the modules symbols can be loaded just before the module itself gets loaded. This way the modules gets simpler and easier to test, compile and distribute, and make installations faster.

**Comment by saghul** [comment]
> I've found that some complex libraries like node-canvas can have several fairly big libraries like Cairo, libpng... that are complex to compile and otherwise would be shared with other modules,

Isn't this exactly what installing the library system wide offers you?

**Comment by piranna** [comment]
Yes it does, but it has the requeriment to need administrative permissions to install them globally and also there could be version conflicts, too. On the other hand, what Node.js/npm propose is to remove all system wide dependencies by having them in the node_modules folder and don't need to depend on system wide libraries that has different ways to be installed for each platform, that's why the recomended way to generate a compiled module is as a statically linked dynamic library. My proposal has the advantages of both point of views, the reutilization of globally installed shared libraries with the isolation of the node_modules folder and the npm administration.

**Comment by ghost** [comment]
I have a somewhat related issue. I have a compiled .node addon which is using a shared object that lies in the same folder as the .node addon. I need to set LD_LIBRARY_PATH before starting Node.js to get it to work. I cannot set process.env.LD_LIBRARY_PATH, it doesn't work - in that case I need to fork the process and kill the parent to get the updated path (I guess).

One solution would be to statically compile everything but that is just silly.

**Comment by bnoordhuis** [comment]
@alexhultman Try adding `-Wl,-rpath,/path/to/libraries` or `-Wl,-rpath,$ORIGIN` to the `'ldflags'` sections of your binding.gyp.  OS X has a slightly different rpath syntax, `man ld` should have the details.  Good luck.

I'll close the issue, this is something that can be solved from a binding.gyp.

**Comment by piranna** [comment]
@alexhultman problem is NOT related to my original request, if you re-read my original post what I was asking for is for a mechanism so `.node` files on a module can use the `.node` files from other modules as dynamic libraries so there's no need to compile everything statically or use globally installed dynamic libraries, NOT how to use dynamic libraries in the same module where the correct solution is to compile it statically.

@bnoordhuis, please re-open this since @alexhultman problem is out of the scope of this issue.

**Comment by ghost** [comment]
To be technical, my example shows an _identical_ problem.

First off, a .node file is really just a renamed .so file. Secondly, consider the case where you buy a license for a proprietary, binary-only, shared object (.so) which you _have to_ link dynamically to. Then you see that my problem is _identical_ to yours, the only difference is that you want to link to .node files and I want to link to .so files (which are technically the same).

Hold your fucking horses, I'm only trying to help out by supporting your cause.

**Comment by piranna** [comment]
I know `.node` files are renamed `.so` ones, that's why I asked about `LD_LIBRARY_PATH`. Point it, when both your `.node` and licensed `.so` file are on the same module you can set the link flags on the `binding.gyp` file since you know the location of the `.so` file, that's fine with me (and probably the only solution, since the licensed library is only available as `.so` and not `.a`, so it can't be linked statically). My problem comes when your module `.node` file depends on the symbols available on other module `.node` file, since you can't be able to know it's location since it can be in several places on the fisical filesystem inside the dependencies tree (`./node_modules`, `../node_modules`, `../../node_modules`...).

What I'm asking for in this issue is to extend the modules path resolution to compiled modules. @alexhultman, your use case is a valid one too, but I think using the links flags is a better solution for you. Other thing is that you rename your licensed library and store it in the `node_modules` hierarchy tree, maybe because you are working on your project with several compiled modules that make use of it, then in that case we have _exactly_ the same problem here ;-)

**Comment by bnoordhuis** [comment]
@piranna Why would `-rpath` not work for your use case?

**Comment by piranna** [comment]
> @piranna Why would -rpath not work for your use case?

Because it's not know the location of the module with the `.node` file used as dependency, and it can change. Yes, it could be looked for when compiling the module and set `-rpath`, but modules paths will be hardcoded and if they change its location later then it will fail. It would need to be tested though, besides that problem maybe it could work and it would be only a matter of tune-up the `binding.gyp` file of the projects or integrate its support on `node-gyp`...

**Comment by bnoordhuis** [comment]
I don't get it.  How would LD_LIBRARY_PATH help if the library you depend on isn't in a fixed location?  With `-rpath` you can at least specify a path relative to the .node with `$ORIGIN`.

**Comment by piranna** [comment]
> With -rpath you can at least specify a path relative to the .node with $ORIGIN.

You can do this at compile time, but if their location changes, on runtime it will fail, that's why I said about update dynamically `LD_LIBRARY_PATH` before loading each module.

**Comment by bnoordhuis** [comment]
I still don't get it.  How would you expect node to do that automatically for you?  Just set LD_LIBRARY_PATH manually in the environment before starting node.
