### ISSUE TITLE
.then(Promise.all) fails

### ISSUE THREAD

**Issue by fschargorosdky** [nodejs/node-v0.x-archive#25623]
I want to chain a promise that resolves to an array to Promise.all.
Using it inside a function works fine:
```javascript
Promise.resolve([1, 2, 3])
  .then(function (promises) {
     return Promise.all(promises);
   })
  .then(function () {
    console.log('works');
  })
  .catch(function (err) {
    console.log(err.stack);
  });
```
But if I pass Promise.all as the argument of .then, it breaks:
```javascript
Promise.resolve([1, 2, 3])
  .then(Promise.all)
  .then(function () {
    console.log('works');
  })
  .catch(function (err) {
    console.log(err.stack);
  });
```
Result:
```
TypeError: undefined is not a function
    at defer (native)
    at all (native)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```
I tried changing the array to an array of promises but it fails the same way:
```javascript
Promise.resolve([Promise.resolve(1), Promise.resolve(2), Promise.resolve(3)])
  .then(Promise.all)
  .then(function () {
    console.log('works');
  })
  .catch(function (err) {
    console.log(err.stack);
  });
```
Doing it with Bluebird works correctly:
```javascript
var BPromise = require('bluebird');

BPromise.resolve([1, 2, 3])
  .then(BPromise.all)
  .then(function () {
    console.log('works');
  })
  .catch(function (err) {
    console.log(err.stack);
  });
```

**Comment by thefourtheye** [comment]
You need to bind the `all` to the `Promise` object, like this

    Promise.resolve([1, 2, 3])
    	.then(Promise.all.bind(Promise))
    	.then(function() {
    	    console.log('works');
    	}).catch(function(err) {
    	    console.log(err.stack);
    	});

**Comment by a0viedo** [comment]
@fschargorosdky `Promise.all` receives an array, so it should be:

```js
Promise.all([Promise.resolve(1), Promise.resolve(2), Promise.resolve(3)])
  .then(function () {
    console.log('works');
  })
  .catch(function (err) {
    console.log(err.stack);
  });
```
Although the alternative proposed by @thefourtheye works, it losses semantic and readability.

**Comment by fschargorosdky** [comment]
@a0viedo That works but I what I wanted to do was pass a promise that resolves to an array to Promise.all

``` js
Promise.resolve([1, 2, 3])
  .then(Promise.all)
  .then(function () {
    console.log('works');
  })
  .catch(function (err) {
    console.log(err.stack);
  });
```

**Comment by a0viedo** [comment]
@fschargorosdky in that case, what @thefourtheye suggested seems more fit.

**Comment by thefourtheye** [comment]
@fschargorosdky It doesn't work because `all` function expects the `this` to be a `Promise` object. That is why it fails in your case.

**Comment by ChALkeR** [comment]
`.then(Promise.all)` should fail with `TypeError` per spec: http://www.ecma-international.org/ecma-262/6.0/#sec-promise.all.

> 1. Let `C` be the **this** value.
> 2. If `Type(C)` is not `Object`, throw a **TypeError** exception.

If you pass `Promise.all` as a function without [binding it](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Function/bind), `this` is not defined there.

`Bluebird` behaviour is incorrect here and it's causing confusion.

**Comment by thefourtheye** [comment]
@ChALkeR The "Note" in that section is also very important.

**Comment by ChALkeR** [comment]
@thefourtheye I guess that those two are enough here, but yes, «Note» also clarifies things a bit:

> NOTE The **all** function requires its **this** value to be a constructor function that supports the parameter conventions of the **Promise** constructor.
