### ISSUE TITLE
v0.12: periodic performance drop due to GC

### ISSUE THREAD

**Issue by bsnote** [nodejs/node-v0.x-archive#25628]
We have a pub/sub system which is running fine on v0.10. When I tried to run it on v0.12, it failed after some time - the system went unreachable. I made the assumption that this has something to do with GC. My next step was to try to specify --max_old_space_size value. I set it to 364 MB (10% of freeMem). This time it didn't crash but every 3 hours performance dropped. See New Relic stats:
![stats](https://cloud.githubusercontent.com/assets/139410/8508055/54c1022a-2269-11e5-8735-44b33cc6843c.png)

System details:
It's running on Amazon EC2 c3.large instance:
CPU: 2 cores
memory: 3.68 GB
OS: Amazon Linux (3.14.44-32.39.amzn1.x86_64)

**Comment by CGavrila** [comment]
Not sure if this is such a great idea, but I'm just going to throw it here.

You could try having a `gc();` call somewhere inside some piece of code which is executed frequently and run your app with `--expose_gc`. This way you might at least spread the load, even though I'm not sure if you'd want this as a permanent solution.

**Comment by bsnote** [comment]
Thanks @CGavrila . Still, I think, it's a common problem that needs to be addressed.

**Comment by bsnote** [comment]
What is the best way to diagnose this issue?
cc @bnoordhuis

**Comment by bsnote** [comment]
Same problem when running on iojs v2.3.4.

**Comment by ChALkeR** [comment]
@bsnote Is this still an issue with recent Node.js versions (v4.x / v5.x)?

**Comment by bsnote** [comment]
It's running OK with Node.js v4.x/v5.x.
