### ISSUE TITLE
`fs.access` is unreliable on windows for directories (effecting npm@3)

### ISSUE THREAD

**Issue by lukeapage** [nodejs/node-v0.x-archive#25657]
from https://github.com/npm/npm/issues/8869#issuecomment-120430739

1. Open a shell in admin mode
2. Create a directory *outside* of the users directory
3. Create a file inside that directory
4. run node
```
> var fs = require("fs");
> fs.access("c:\\dev\\testdel", fs.W_OK, function() { console.log(arguments); })
> fs.access("c:\\dev\\testdel\\test", fs.W_OK, function() { console.log(arguments); })
```
(where `testdel` was my new test directory and `test` the file I created).

Results in node 0.12.6
```
> { '0': { [Error: EPERM, access 'c:\dev\testdel'] errno: -4048, code: 'EPERM', path: 'c:\\dev\\testdel' } }
> { '0': null, '1': 0 }
```

Expected Results
```
> { '0': null, '1': 0 }
> { '0': null, '1': 0 }
```

Note: I seem to get a write access error against every directory outside my users directory.

**Comment by lukeapage** [comment]
![evidence](https://cloud.githubusercontent.com/assets/309321/8621758/443797ce-271f-11e5-8be9-cc2ac167a51f.png)

**Comment by lukeapage** [comment]
![evidence](https://cloud.githubusercontent.com/assets/309321/8621867/e18aadf4-271f-11e5-9364-eac38a352294.png)

**Comment by lukeapage** [comment]
Its a libuv bug that was fixed
https://github.com/libuv/libuv/commit/7dcc3e0cf02e54efc99b041f3cd871107f19ebf1

**Comment by ChALkeR** [comment]
@lukeapage Is this still an issue with recent (v4.x / v5.x) Node.js versions?

**Comment by lukeapage** [comment]
I dont think so, as it looks like they have recent libuv builds.
