### ISSUE TITLE
Broken wiki page - "Projects, Applications, and Companies Using Node"

### ISSUE THREAD

**Issue by hliyan** [nodejs/node-v0.x-archive#25651]
Latest edit seems to have broken the Markdown:

https://github.com/joyent/node/wiki/projects,-applications,-and-companies-using-node

![image](https://cloud.githubusercontent.com/assets/6211831/8588263/3b821802-2625-11e5-9018-f5be42eee0ba.png)

**Comment by justin-umesh** [comment]
yes

**Comment by brendanashworth** [comment]
Closing, as this isn't really applicable to the project anymore. Thanks for telling us about it though!
