### ISSUE TITLE
TLS server missing CRL for an array of CAs prevents authentication

### ISSUE THREAD

**Issue by AlanUnderwood** [nodejs/node-v0.x-archive#25668]
Using Node.js 0.12.7 on Linux (Ubuntu 15.04 & Centos 6)

If you create an https/tls server with an array of CAs and an array of CRLs, but one of the CAs does not have a matching CRL, then an authenticating client signed by that CA cannot connect. If there are no CRLs at all, then an authenticating client signed by that CA can connect i.e. you should be allowed to connect even if there is no CRL.
## Steps to reproduce
1. Create two Certificate Authorities, `CA1` & `CA2`.
2. Create two user certificate, `userA` & `userB` signed by `CA1` and `CA2` respectively.
3. Create a server certificate for the Node.js server signed by `CA1`.
4. Create two Certificate Revocation Lists, one each for `CA1` and `CA2`.
5. Add both CAs and user certificates to you browser as trusted authorities and user certificates respectively.
6. Create a simple https Node.js app that uses both CAs, and CRLs in its options and start it.
7. Start your browser and connect to the server, selecting `userA` certificate...success!
8. Restart your browser and connect to the server, selecting `userB` certificate...success!
9. Edit the Node.js app to remove the CRL for `CA2` and restart server.
10. Restart your browser and connect to the server, selecting `userA` certificate...success!
11. Restart your browser and connect to the server, selecting `userB` certificate...**Failure!**
12. _Optional_, edit the Node.js app to remove crl and restart server. You can now connect as both `userA` and `userB`.

This is a problem for me where in my workplace I have a few self-signed CAs but not all of them have CRLs. I need to use CRLs for security, but because one of the CAs doesn't have a CRL, I'm a bit stuck!
## Sample app.js

``` javascript
var fs = require('fs');
var https = require('https');
var privateKey = fs.readFileSync('/home/alan/ca1/private/localhost.key.pem', 'utf8');
var certificate = fs.readFileSync('/home/alan/ca1/certs/localhost.cert.pem', 'utf8');
var cas = [
    fs.readFileSync('/home/alan/ca1/certs/ca1.cert.pem', 'utf8'),
    fs.readFileSync('/home/alan/ca2/certs/ca2.cert.pem', 'utf8')
];
var crls = [
    fs.readFileSync('/home/alan/ca1/crl/ca1.crl.pem', 'utf8')
    ,fs.readFileSync('/home/alan/ca2/crl/ca2.crl.pem', 'utf8')
];

var credentials = {
    key: privateKey,
    cert: certificate,
    ca: cas,
    crl: crls,
    requestCert: true,
    rejectUnauthorized: true
};
https.createServer(credentials, function (req, res) {
    var clientCert = req.client.getPeerCertificate();
    res.writeHead(200);
    res.end('Certificate info!' + JSON.stringify(clientCert.subject, true, 2));
}).listen(8443);
```

**Comment by chiradip** [comment]
I faced the same issue. I think one way this behavior may be good as in security if you don't know whether something is allowed or not its better not to allow. Try this though and let me know if this works.

Generate CRLs for self-signed certificates 
openssl ca -gencrl -keyfile ca_key -cert ca_crt -out my_crl.pem

Add the CRLs to your CRL array.

**Comment by AlanUnderwood** [comment]
Therein lies my problem. I would if I could but I can't. I can't generate a CRL for the CA because I don't have access to the CA key and password. The CA is provided by an enterprise partner.

**Comment by chiradip** [comment]
In that case ask their CRL link. and download the file yourself. If you must use CRL, you have owner all the CAs CRLs - as revocation may happen at any level. Now there is a rub with CRLs, it hard to keep updated and when updated, server that is using those CRLs needs to either restart or have a mechanism to reload the CRLs. OCSP and OCSP stapling solve this issue beside many other issues of CRL.
