### ISSUE TITLE
test: test-fs-watch should be made non-flaky

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/node-v0.x-archive#25663]
simple/test-fs-watch is currently marked as flaky on Mac OS. It should be investigated and made non-flaky.

Quick command for testing:
```
time (OK=0; NOK=0; for i in `seq 10000`; do ./out/Release/node test/simple/test-fs-watch.js && OK=$(($OK+1)) || NOK=$(($NOK+1)); echo "$i   OK: $OK   NOT OK: $NOK"; done)
```

Links:
- File: https://github.com/joyent/node/blob/b8ac6584faf00f6bc9302913ea58e54dcf8f559c/test/simple/test-fs-watch.js
- File history: https://github.com/joyent/node/commits/b8ac6584faf00f6bc9302913ea58e54dcf8f559c/test/simple/test-fs-watch.js
- Marked flaky on: [Mar 10, 2015](https://github.com/joyent/node/commit/e8b21095670543ad6ee8e24e0a1b096b908e20b1)

/cc @joyent/node-collaborators

**Comment by brendanashworth** [comment]
This was [somewhat] resolved in io.js: https://github.com/nodejs/io.js/pull/1275
