### ISSUE TITLE
Highload ipc: process.send vs unix socket. Best way?

### ISSUE THREAD

**Issue by tonghae** [nodejs/node-v0.x-archive#25677]
Greetings! I'm trying to build a game server using cluster to achieve better usage of multi-core CPU. Since players connected via tcp to different workers, sometimes i need to send some data to player(s) which socket is connected to another worker process.

Heard that process.send is sync, and with big online there can be huge amount of these inter-process messages. Maybe unix-socket is better way to achieve the goal?

Thanks.

**Comment by Fishrock123** [comment]
Bookmarking out of interest. @Fishrock123

**Comment by dnakamura** [comment]
I would assume unix sockets would be the better way to go. An alternative would be to send the socket over to the other worker so it can send the data itself

**Comment by dayuoba** [comment]
how a about rpc? may someday  the instances run on different machines?
