### ISSUE TITLE
repl .load doesn't strip trailing whitespace

### ISSUE THREAD

**Issue by jonslenkooyala** [nodejs/node-v0.x-archive#25680]
if I type ".load foo.js " (extra space on the end) then it fails to load, I get "Failed to load:foo.js". But if I do not have the whitespace at the end, ".load foo.js" then it works.

**Comment by cjihrig** [comment]
It shouldn't strip trailing spaces. You can create a file whose name ends with a trailing space and then `.load` that. If you strip the trailing space, you can't load such a file.

**Comment by jonslenkooyala** [comment]
I understand that perspective. Personally, $0.02, I would have changed .load to require a quoted string. :-)

**Comment by thefourtheye** [comment]
Actually, it really is a bug. The whitespace trimming function has a buggy RegEx. I submitted a PR which fixes this as well https://github.com/joyent/node/pull/25664

**Comment by thefourtheye** [comment]
@cjihrig Would it be okay, if I submit a floating patch, till #25664 lands?
