### ISSUE TITLE
http.get responds with 404 with accented character on url

### ISSUE THREAD

**Issue by dinostheo** [nodejs/node-v0.x-archive#25685]
Hi,

Earlier today I posted an issue on the request module believing that the issue comes from the module https://github.com/request/request/issues/1678 

Requesting an image url with an ascii character in the filename responds with a 404 code, node versions `0.11.x` & `0.12.x` and with a 200 status code with version `0.10.x`.

As I mentioned above, I thought that the issue might come from the request module as I am using it in the application for make http requests. However, I tried the following simple script, which confirmed the results above per node version.

```
var http = require('http');

http.get('http://www.tecnofanatico.com/wp-content/uploads/2015/07/Sin-título-1-150x150.png', function (res) {
    console.log('Response: ' + res.statusCode);
}).on('error', function (err) {
    console.log('Error' + err.message);
});
```

**Comment by mvdwalle** [comment]
@dinostheo: I properly URL encoded the í and made it work.
