### ISSUE TITLE
Measure Data Rate of HTTP send?

### ISSUE THREAD

**Issue by dmoss733** [nodejs/node-v0.x-archive#25691]
I'm attempting to write an HTTP server that will do server-side pacing for HTTP video streaming. I'm encountering difficulty getting an accurate measurement of data rate of a given HTTP response. Accurate timing of the transmission seems impossible, since the stream provides only the 'end' and 'finished' events and those have no guarantee of being after the data has been received by other side. 

Is this impossible to accomplish accurately in node, due to the design of the stream? Or am I missing a feature that allows for this?

**Comment by dnakamura** [comment]
Have you tried using the callback on response.end?
https://nodejs.org/api/http.html#http_response_end_data_encoding_callback

**Comment by dmoss733** [comment]
Yes. that was the first thing I tired. 
After that I switched over to the "finished" event. But the event specifically states 
"Emitted when the response has been sent. More specifically, this event is emitted when the last segment of the response headers and body have been handed off to the operating system for transmission over the network. It does not imply that the client has received anything yet."

**Comment by dnakamura** [comment]
I'm not sure there is a way. The only thing I can think of is to keep sending, util you fill up the native send buffer, and resume once you drain the javascript buffer
