### ISSUE TITLE
Error: UV Failed assertion

### ISSUE THREAD

**Issue by rothn** [nodejs/node-v0.x-archive#25705]
I sometimes get this error while using node.

OS:
Linux 2.6.32-431.29.2.el6.x86_64
Error:
node: ../deps/uv/src/uv-common.c:143: uv_err_name: Assertion `0' failed.

**Comment by CGavrila** [comment]
Unfortunately, this is very difficult to diagnose unless you provide some example which at least intermittently reproduces this issue.

**Comment by brendanashworth** [comment]
Please see https://github.com/nodejs/node-v0.x-archive/issues/8490#issuecomment-143590256, closing.
