### ISSUE TITLE
Investigate v0.10 flaky test test-http-pipeline-flood

### ISSUE THREAD

**Issue by orangemocha** [nodejs/node-v0.x-archive#25709]
https://github.com/joyent/node/commit/a2f879f197f76d91a42ec0f8322f18948911a552 marked this test as flaky in v0.10 so that it doesn't block merges with Jenkins and node-accept-pull-request.

As a follow up, we should investigate why this test is failing in v0.10. Some of the tests marked as flaky in https://github.com/joyent/node/commit/a2f879f197f76d91a42ec0f8322f18948911a552 fail intermittently, while others fail persistently. For the latter, an explicit skip for the specific platform might be more appropriate.

My guess is that a good percentage of these tests fail because of issues with the test itself, not node. It's likely that those issues were fixed in v0.12, so it might be a good idea to look for changes to the same test in git history in v0.12, or even simply trying the v0.12 version of the test with node v0.10.

/cc: @joyent/node-collaborators

**Comment by dnakamura** [comment]
I've already been looking at this one. I can say that the test is flaky on windows due to the very small tcp buffer sizes. Also the test is not particularly well written. I'm working on a rewrite to better test desired behavior

**Comment by dnakamura** [comment]
Also, in v0.12 releases the number of requests asserted has been lowered to 250 instead of 500 (e3ec2f7dab). This seems to fix on platforms other than windows. Ultimately, asserting a specific number of requests does not make much sense, as in my testing when the desired behavior does not exists the test runs indefinitely

**Comment by misterdjules** [comment]
@orangemocha @dnakamura FYI, marking the test as flaky for Windows in v0.12 with https://github.com/joyent/node/pull/25707.

**Comment by misterdjules** [comment]
Created https://github.com/joyent/node/issues/25732 for Windows and v0.12.
