### ISSUE TITLE
resumeSession hangs when no session data passed to callback in 0.12

### ISSUE THREAD

**Issue by tlivings** [nodejs/node-v0.x-archive#25735]
Example, this will work in 0.10:

``` javascript
'use strict';

var Https = require('https');
var Fs = require('fs');

var server = Https.createServer({
    cert: Fs.readFileSync('server.crt'),
    key: Fs.readFileSync('server.key')
}, function (req, res) {
    res.writeHead(200);
    res.end("hello world\n");
});

server.on('resumeSession', function (id, callback) {
    console.log('resume requested');
    callback();
});

server.listen(8000);
```

And hang in 0.12.

Passing no session data back should cause a new session to be created.

**Comment by tlivings** [comment]
cc @indutny

**Comment by indutny** [comment]
Should be fixed by back-porting https://github.com/nodejs/io.js/commit/963f5e8a . @joyent/node-collaborators : may I ask you to give it a quick LGTM, if it LGTY?

**Comment by jasnell** [comment]
LGTM

**Comment by indutny** [comment]
@jasnell should I just cherry-pick it, or is there some tool that I need to run before doing this?

**Comment by tlivings** [comment]
Looks good. We should probably add a couple of tests covering the issues I opened.

**Comment by indutny** [comment]
Ok, I'll send a PR then.

**Comment by indutny** [comment]
@tlivings here you go https://github.com/joyent/node/pull/25739
