### ISSUE TITLE
Spawn communication via fd

### ISSUE THREAD

**Issue by frgc** [nodejs/node-v0.x-archive#25740]
Win7 32 bit
Node 0.12.5

Expected: bar sends after one second, foo sends after two.
Observed: bar will wait indefinitely until foo sends.

https://gist.github.com/frgc/b7fea1fea045720d14d8

My understanding of the documentation is that stdio[3] is a duplex socket and that Windows is supported. If that isn't the case could we get some clarification of how to use this?

**Comment by dnakamura** [comment]
still looking into the root issue, but if you make 2 pipes and only use them simplex, everything works as expected

**Comment by frgc** [comment]
I noticed that also and didn't post anything more because I wasn't sure duplex was supported.

I also noticed that if I send without the `setTimeout` in the child, it does work as expected (which made it a difficult one to reduce).
