### ISSUE TITLE
Segmentation fault in node 0.12.7 (cross-compiled for ARM)

### ISSUE THREAD

**Issue by sroka-sec** [nodejs/node-v0.x-archive#25747]
Hello,
recently i've compiled nodejs 0.12.7 on buildroot ARM (ARM926EJ-S rev 5 (v5l) ) platform - and after succesful compilation when i try to execute node, segmentation fault occurs.

Erlier, i've used node 0.10.28 and there was no souch problem, i've only modified js2c.py (removed import bz2).

strace below : 

 strace ./node
execve("./node", ["./node"], [/\* 16 vars _/]) = 0
brk(0)                                  = 0x1630000
uname({sys="Linux", node="001BC50A001B-LGC", ...}) = 0
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=16569, ...}) = 0
mmap2(NULL, 16569, PROT_READ, MAP_PRIVATE, 3, 0) = 0xb6f24000
close(3)                                = 0
open("/usr/lib/libssl.so.1.0.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0000\345\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=311540, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f23000
mmap2(NULL, 343116, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6eaf000
mprotect(0xb6ef6000, 32768, PROT_NONE)  = 0
mmap2(0xb6efe000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x47000) = 0xb6efe000
close(3)                                = 0
open("/usr/lib/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\200\261\3\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=1284492, ...}) = 0
mmap2(NULL, 1330520, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6d6a000
mprotect(0xb6e90000, 32768, PROT_NONE)  = 0
mmap2(0xb6e98000, 81920, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x126000) = 0xb6e98000
mmap2(0xb6eac000, 11608, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6eac000
mprotect(0xbecc7000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC|PROT_GROWSDOWN) = 0
close(3)                                = 0
open("/lib/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\360\27\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=26528, ...}) = 0
mmap2(NULL, 57908, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6d5b000
mprotect(0xb6d61000, 28672, PROT_NONE)  = 0
mmap2(0xb6d68000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0xb6d68000
close(3)                                = 0
open("/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\330\n\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=18008, ...}) = 0
mmap2(NULL, 49372, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6d4e000
mprotect(0xb6d52000, 28672, PROT_NONE)  = 0
mmap2(0xb6d59000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0xb6d59000
close(3)                                = 0
open("/usr/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\fV\4\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=755684, ...}) = 0
mmap2(NULL, 814308, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6c87000
mprotect(0xb6d3b000, 28672, PROT_NONE)  = 0
mmap2(0xb6d42000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb3000) = 0xb6d42000
mmap2(0xb6d48000, 23780, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6d48000
close(3)                                = 0
open("/lib/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\0>\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=632404, ...}) = 0
mmap2(NULL, 663728, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6be4000
mprotect(0xb6c7e000, 28672, PROT_NONE)  = 0
mmap2(0xb6c85000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x99000) = 0xb6c85000
close(3)                                = 0
open("/lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0(\320\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=133660, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6be3000
mmap2(NULL, 165176, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6bba000
mprotect(0xb6bdb000, 28672, PROT_NONE)  = 0
mmap2(0xb6be2000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x20000) = 0xb6be2000
close(3)                                = 0
open("/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0lZ\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=127839, ...}) = 0
mmap2(NULL, 131624, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6b99000
mprotect(0xb6bae000, 32768, PROT_NONE)  = 0
mmap2(0xb6bb6000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0xb6bb6000
mmap2(0xb6bb8000, 4648, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6bb8000
close(3)                                = 0
open("/lib/tls/v5l/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/lib/tls/v5l", 0xbecc73b0)      = -1 ENOENT (No such file or directory)
open("/lib/tls/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/lib/tls", 0xbecc73b0)          = -1 ENOENT (No such file or directory)
open("/lib/v5l/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/lib/v5l", 0xbecc73b0)          = -1 ENOENT (No such file or directory)
open("/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\274\201\1\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=1254532, ...}) = 0
mmap2(NULL, 1295760, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6a5c000
mprotect(0xb6b8b000, 32768, PROT_NONE)  = 0
mmap2(0xb6b93000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x12f000) = 0xb6b93000
mmap2(0xb6b96000, 9616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6b96000
close(3)                                = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6a5b000
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6a5a000
set_tls(0xb6a5b8e0, 0xb6a5a008, 0xb6f2b058, 0xb6a5b8e0, 0xb6f2b058) = 0
mprotect(0xb6b93000, 8192, PROT_READ)   = 0
mprotect(0xb6bb6000, 4096, PROT_READ)   = 0
mprotect(0xb6c85000, 4096, PROT_READ)   = 0
mprotect(0xb6d42000, 16384, PROT_READ)  = 0
mprotect(0xb6d59000, 4096, PROT_READ)   = 0
mprotect(0xb6d68000, 4096, PROT_READ)   = 0
mprotect(0xb6f2a000, 4096, PROT_READ)   = 0
munmap(0xb6f24000, 16569)               = 0
set_tid_address(0xb6a5b488)             = 2795
set_robust_list(0xb6a5b490, 12)         = 0
futex(0xbecc7cc8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0xbecc7cc8, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, b6a5b8e0) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGRTMIN, {0xb6b9e510, [], SA_SIGINFO|0x4000000}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0xb6b9e3a4, [], SA_RESTART|SA_SIGINFO|0x4000000}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=18014398505295872_1024, rlim_max=9223372039920411556}) = 0
futex(0xb6d4c1f8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0xb6d4c214, FUTEX_WAKE_PRIVATE, 2147483647) = 0
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP BUS FPE SEGV RTMIN RT_1], [], 8) = 0
rt_sigaction(SIGILL, {0xb6da8718, ~[ILL TRAP BUS FPE SEGV RTMIN RT_1], 0x4000000 /\* SA_??? _/}, {SIG_DFL, [], 0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, ~[ILL TRAP BUS FPE KILL SEGV STOP RTMIN RT_1], 8) = 0
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0xb6da8760} ---
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP BUS FPE KILL SEGV STOP RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, ~[ILL TRAP BUS FPE KILL SEGV STOP RTMIN RT_1], 8) = 0
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0xb6da8768} ---
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP BUS FPE KILL SEGV STOP RTMIN RT_1], NULL, 8) = 0
rt_sigaction(SIGILL, {SIG_DFL, [], 0x4000000 /_ SA_??? _/}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigaction(SIGUSR1, {0x474d20, [], 0x4000000 /_ SA_??? _/}, NULL, 8) = 0
brk(0)                                  = 0x1630000
brk(0x1651000)                          = 0x1651000
pipe2([3, 4], O_CLOEXEC)                = 0
write(4, "_", 1)                        = 1
futex(0x687848, FUTEX_WAKE_PRIVATE, 2147483647) = 0
clock_getres(CLOCK_MONOTONIC_COARSE, {0, 10000000}) = 0
clock_gettime(CLOCK_MONOTONIC, {1466, 159422714}) = 0
epoll_create1(EPOLL_CLOEXEC)            = 5
pipe2([6, 7], O_NONBLOCK|O_CLOEXEC)     = 0
eventfd2(0, O_NONBLOCK|O_CLOEXEC)       = 8
ioctl(0, FIOCLEX)                       = 0
ioctl(1, FIOCLEX)                       = 0
ioctl(2, FIOCLEX)                       = 0
ioctl(3, FIOCLEX)                       = 0
ioctl(4, FIOCLEX)                       = 0
ioctl(5, FIOCLEX)                       = 0
ioctl(6, FIOCLEX)                       = 0
ioctl(7, FIOCLEX)                       = 0
ioctl(8, FIOCLEX)                       = 0
ioctl(9, FIOCLEX)                       = -1 EBADF (Bad file descriptor)
ioctl(10, FIOCLEX)                      = -1 EBADF (Bad file descriptor)
ioctl(11, FIOCLEX)                      = -1 EBADF (Bad file descriptor)
ioctl(12, FIOCLEX)                      = -1 EBADF (Bad file descriptor)
ioctl(13, FIOCLEX)                      = -1 EBADF (Bad file descriptor)
ioctl(14, FIOCLEX)                      = -1 EBADF (Bad file descriptor)
ioctl(15, FIOCLEX)                      = -1 EBADF (Bad file descriptor)
ioctl(16, FIOCLEX)                      = -1 EBADF (Bad file descriptor)
gettimeofday({1437484236, 177367}, NULL) = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=4_1024}) = 0
prlimit64(0, RLIMIT_NOFILE, {rlim_cur=4_1024, rlim_max=4_1024}, NULL) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, ~[RTMIN RT_1], 0x4000000 /_ SA_??? _/}, NULL, 8) = 0
rt_sigaction(SIGINT, {0x474e90, ~[RTMIN RT_1], SA_RESETHAND|0x4000000}, NULL, 8) = 0
rt_sigaction(SIGTERM, {0x474e90, ~[RTMIN RT_1], SA_RESETHAND|0x4000000}, NULL, 8) = 0
rt_sigaction(SIGUSR1, {0x474e50, ~[RTMIN RT_1], 0x4000000 /_ SA_??? */}, NULL, 8) = 0
open("/proc/cpuinfo", O_RDONLY|O_LARGEFILE) = 9
fstat64(9, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f28000
read(9, "processor\t: 0\nmodel name\t: ARM92"..., 1024) = 271
read(9, "", 1024)                       = 0
read(9, "", 1024)                       = 0
close(9)                                = 0
munmap(0xb6f28000, 4096)                = 0
open("/proc/cpuinfo", O_RDONLY|O_LARGEFILE) = 9
fstat64(9, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f28000
read(9, "processor\t: 0\nmodel name\t: ARM92"..., 1024) = 271
close(9)                                = 0
munmap(0xb6f28000, 4096)                = 0
open("/proc/self/auxv", O_RDONLY|O_LARGEFILE) = 9
fstat64(9, {st_mode=S_IFREG|0400, st_size=0, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f28000
read(9, "\20\0\0\0\223\1\0\0\6\0\0\0\0\20\0\0\21\0\0\0d\0\0\0\3\0\0\0004\200\0\0"..., 1024) = 144
close(9)                                = 0
munmap(0xb6f28000, 4096)                = 0
open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_LARGEFILE) = 9
fstat64(9, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
poll([{fd=9, events=POLLIN}], 1, 10)    = 1 ([{fd=9, revents=POLLIN}])
read(9, "\216@:`h\335\275\355\330zx\213\343(\216\203\300\2227\224\376T\321:3\34j\2618p>\", 32) = 32
close(9)                                = 0
getuid32()                              = 0
gettimeofday({1437484236, 568560}, NULL) = 0
mmap2(0x424e5000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x424e5000
cacheflush(0x424e5000, 0x424e6000, 0, 0xbecbfb5c, 0xffff86dc) = 0
mprotect(0x424e5000, 4096, PROT_READ|PROT_EXEC) = 0
mmap2(0x5c651000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x5c651000
cacheflush(0x5c651000, 0x5c652000, 0, 0, 0xffff871c) = 0
mprotect(0x5c651000, 4096, PROT_READ|PROT_EXEC) = 0
mmap2(0x24871000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x24871000
cacheflush(0x24871000, 0x24872000, 0, 0, 0x24871000) = 0
mprotect(0x24871000, 4096, PROT_READ|PROT_EXEC) = 0
brk(0x1673000)                          = 0x1673000
brk(0x166b000)                          = 0x166b000
mmap2(0x3bfb3000, 33554432, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x3bfb3000
munmap(0x3bfb3000, 315392)              = 0
munmap(0x3d000000, 16461824)            = 0
mmap2(0x3c000000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x3c000000
mmap2(0x51752000, 196608, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x51752000
mmap2(0x4ced8000, 1048576, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x4ced8000
mmap2(0x4ced8000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x4ced8000
mmap2(0x51760000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x51760000
mmap2(0x43ebb000, 1228800, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x43ebb000
munmap(0x43ebb000, 282624)              = 0
munmap(0x43f2c000, 765952)              = 0
mmap2(0x43f00000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x43f00000
mprotect(0x43f09000, 4096, PROT_NONE)   = 0
mmap2(0x43f0a000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x43f0a000
mprotect(0x43f2b000, 4096, PROT_NONE)   = 0
mmap2(0x31147000, 1228800, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x31147000
munmap(0x31147000, 757760)              = 0
munmap(0x3122c000, 290816)              = 0
mmap2(0x31200000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x31200000
mprotect(0x31209000, 4096, PROT_NONE)   = 0
mmap2(0x3120a000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x3120a000
mprotect(0x3122b000, 4096, PROT_NONE)   = 0
mmap2(0x36b62000, 1228800, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x36b62000
munmap(0x36b62000, 647168)              = 0
munmap(0x36c2c000, 401408)              = 0
mmap2(0x36c00000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x36c00000
mprotect(0x36c09000, 4096, PROT_NONE)   = 0
mmap2(0x36c0a000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x36c0a000
mprotect(0x36c2b000, 4096, PROT_NONE)   = 0
mmap2(0x24b8e000, 1150976, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x24b8e000
munmap(0x24b8e000, 466944)              = 0
munmap(0x24c19000, 581632)              = 0
mmap2(0x24c00000, 102400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x24c00000
mmap2(0x56a0f000, 1282048, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x56a0f000
munmap(0x56a0f000, 987136)              = 0
munmap(0x56b39000, 61440)               = 0
mmap2(0x56b00000, 233472, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x56b00000
mmap2(0x34b3a000, 1544192, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x34b3a000
munmap(0x34b3a000, 811008)              = 0
munmap(0x34c79000, 237568)              = 0
mmap2(0x34c00000, 495616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x34c00000
mmap2(0x31f6b000, 1634304, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x31f6b000
munmap(0x31f6b000, 610304)              = 0
munmap(0x3208f000, 438272)              = 0
mmap2(0x32000000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x32000000
mprotect(0x32009000, 4096, PROT_NONE)   = 0
mmap2(0x3200a000, 540672, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x3200a000
mprotect(0x3208e000, 4096, PROT_NONE)   = 0
cacheflush(0x3200a040, 0x3200a190, 0, 0xe59fc12c, 0x3200a058) = 0
cacheflush(0x3200a1e0, 0x3200a224, 0, 0x7f, 0xbecc010c) = 0
cacheflush(0x3200a280, 0x3200a2c4, 0, 0x7f, 0xbecc010c) = 0
cacheflush(0x3200a320, 0x3200a350, 0, 0x7f, 0xbecc0114) = 0
cacheflush(0x3200a3a0, 0x3200a408, 0, 0x7f, 0xbecc0114) = 0
cacheflush(0x3200a460, 0x3200a5ec, 0, 0xe59fc168, 0x3200a478) = 0
cacheflush(0x3200a640, 0x3200a668, 0, 0xe59fc01c, 0x3200a640) = 0
cacheflush(0x3200a6c0, 0x3200a6ec, 0, 0xe59fc020, 0x3200a6c0) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xe2840010} ---
+++ killed by SIGSEGV +++
Segmentation fault

**Comment by eziante** [comment]
I got the exact same segmentation fault when I compiled it with:
OSELAS.Toolchain-2013.12.2/arm-v5te-linux-gnueabi/gcc-4.8.2-glibc-2.18-binutils-2.24-kernel-3.12-sanitized

**Comment by eziante** [comment]
I can add that my target also was an ARM926EJ-S core.
