### ISSUE TITLE
[doc] feature request: Add explanation for how to require modules.

### ISSUE THREAD

**Issue by colllin** [nodejs/node-v0.x-archive#25765]
For example:

`var querystring = require('querystring');`

Is there a good reason for not including this important information?

**Comment by jasnell** [comment]
PR? :-)

**Comment by brendanashworth** [comment]
Some core module documentation already provides this - but not all of them - so I suppose this would be worthy of a PR. However, I wouldn't say it is worthy of keeping this issue open, so I'll close this for now. Please open any new PRs towards https://github.com/nodejs/node.
