### ISSUE TITLE
SIGTRAP when using exec

### ISSUE THREAD

**Issue by martlin2cz** [nodejs/node-v0.x-archive#25771]
Hi, on my debian
Linux martlins 3.2.0-4-686-pae #1 SMP Debian 3.2.68-1+deb7u2 i686 GNU/Linux
with node v0.10.33
I allways get attached error when I am trying following:

``` javascript
var sys = require('sys')
var exec = require('child_process').exec;
...
cmd = "myscript.sh";
var child = exec(cmd, function (error, stdout, stderr) {
        console.info("\nExecuting " + cmd + ":");
        sys.print('stdout: ' + stdout);
        sys.print('stderr: ' + stderr);
        if (error !== null) {
          console.log('exec error: ' + error);
        }
    });
```

where `myscript.sh` starts with line:

``` bash
echo $$ > .pid
```

Here node crashes and prints http://pastebin.com/cVcChEBQ

**Comment by georgewhite5** [comment]
The problem seems to have occurred in `function createWriteReq(handle, data, encoding)`, which is part of the `http` library. Are you using this library in code that you haven't displayed?

**Comment by jasnell** [comment]
I'm sorry, but this is not quite enough information to help identify the problem. It would be helpful if you could provide a test case that is more complete.
