### ISSUE TITLE
Adding intermediate ca to https server causes error in certain https requests

### ISSUE THREAD

**Issue by pke** [nodejs/node-v0.x-archive#25776]
Please backport https://github.com/nodejs/io.js/commit/6f7a9784eaef82a1aa6cf53bbbd7224c446876a0 to v0.12

See https://github.com/nodejs/io.js/issues/712#issuecomment-125685646

**Comment by jasnell** [comment]
@joyent/node-tsc

**Comment by indutny** [comment]
I'm +1 for this. It is a plain bug fix without any new features introduced.

**Comment by tom-canova** [comment]
+1

**Comment by leonard84** [comment]
:+1:

**Comment by felikf** [comment]
I hit the same issue on `v0.12.14`. How do I find out what minor version of v0.12.x should I use to get the fix? Unfortunately I can't switch to any major version now. 
Thanks a lot.

```
date=Wed Dec 07 2016 17:08:52 GMT+0100 (CET), pid=8893, uid=1000, gid=1000, cwd=/home/felix/work/appl/search-service, execPath=/home/felix/.nvm/versions/v0.12.14/bin/node, version=v0.12.14, argv=[node, /home/felix/work/appl/search-service/bin/server.js], rss=259932160, heapTotal=156686080, heapUsed=120447024, loadavg=[0.4501953125, 0.67529296875, 0.78564453125], uptime=123241, trace=[column=null, file=null, function=Error, line=null, method=null, native=true], stack=[Error: 140072064280448:error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table:../deps/openssl/openssl/crypto/x509/x509_lu.c:348:, ,     at Error (native)]
```

**Comment by bnoordhuis** [comment]
I don't think it was ever back-ported to v0.12 and it probably never will be now that v0.12 is in maintenance mode.

**Comment by felikf** [comment]
@bnoordhuis Thanks for answer.
