### ISSUE TITLE
Deprecate smalloc in v0.12

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-v0.x-archive#25784]
With the converged release coming, `smalloc` will simply cease to exist altogether, since it is not possible to make it work with v8 4.4+.

As such, it may be prudent to issue a deprecation warning for it in node v0.12 since people may have not gotten the message from io.js yet.

However, there's no alternatives that work on v0.12 directly, since the final required typed array APIs were added in v8 4.3.

See IRC disscussion with @misterdjules: http://logs.libuv.org/io.js/latest#17:14:09.960

See the following io.js PRs:

1. https://github.com/nodejs/io.js/pull/1564
2. https://github.com/nodejs/io.js/pull/1565
3. https://github.com/nodejs/io.js/pull/1566
4. https://github.com/nodejs/io.js/pull/1822
5. https://github.com/nodejs/io.js/pull/1835

cc @bnoordhuis, @trevnorris, etc

**Comment by trevnorris** [comment]
Unfortunately any deprecation will have to happen during the v0.12 release. We were going to do that for the v4.3 release, but took long enough that updated to v4.4.

If it's any consolation, it wasn't used heavily in the ecosystem. So deprecating it during v0.12 shouldn't cause much fuss.

**Comment by jasnell** [comment]
+1 to marking this as clearly deprecated in v0.12. To be honest, it may even be a good idea to add a deprecation notice into v0.10 (at least in the documentation)

**Comment by Fishrock123** [comment]
> it may even be a good idea to add a deprecation notice into v0.10 (at least in the documentation)

Afaik, `smalloc` only came around in 0.12. 0.10 had a different thing: "SlowBuffer".

**Comment by trevnorris** [comment]
@Fishrock123 Node always had `SlowBuffer`. I just reused the name because it was mostly equivalent to what I used it for. But yes, it was only introduced in v0.12.

**Comment by jasnell** [comment]
Ah right... forgot about that. Thanks for the reminder. :-)

**Comment by mhdawson** [comment]
Discussed in latest LTS meeting and we are not going to get to this an its not that important to just going to close
