### ISSUE TITLE
TLS feature request: Allow trusting different CAs than the default bundle

### ISSUE THREAD

**Issue by kelseyfrancis** [nodejs/node-v0.x-archive#25785]
The CA bundle is currently hardcoded to those provided by Mozilla. Globally trusting different CAs is a common need within large IT organizations, air-gapped environments, etc.

I propose an environment variable in the vein of NODE_TLS_REJECT_UNAUTHORIZED (and NPM_CONFIG_CAFILE) that allows specifying a different CA bundle file. Perhaps NODE_TLS_CAFILE?

**Comment by moellenbeck** [comment]
+1

**Comment by jasnell** [comment]
This is a good suggestion but it's not likely to happen in v0.10 or v0.12. It's something that we would need to do in the converged master going forward. I recommend opening the issue either over in http://github.com/nodejs/node or http://github.com/nodejs/io.js
