### ISSUE TITLE
Signal handlers are not removed/reverted with process.removeAllListeners([signal])

### ISSUE THREAD

**Issue by chjj** [nodejs/node-v0.x-archive#25781]
Handling signals in C has the advantage of calling the signal handler even if the main thread is blocked. Since javascript is limited in this area, I went for a workaround: unbind my SIGINT listener before doing my blocking operation. In doing so, I think I discovered a slight inconsistency.

``` js
process.on('SIGINT', function() {
  console.log('SIGINT');
  process.exit(0);
});
process.removeAllListeners('SIGINT');
console.log('start loop');
for (;;);
```

Even after **removing** the SIGINT listener, SIGINT still has no effect:

``` bash
$ node test-signal.js
start loop
...
^C^C^C^C^C^C
...
^\
Quit (core dumped)
$
```

However, if I _specifically_ remove the SIGINT listener, SIGINT reverts back to its original behavior:

``` js
var handle_sigint;
process.on('SIGINT', handle_sigint = function() {
  console.log('SIGINT');
  process.exit(0);
});
process.removeListener('SIGINT', handle_sigint);
console.log('start loop');
for (;;);
```

``` bash
$ node test-signal.js
start loop
...
^C
$
```

Node Version: `v0.12.7`

**Comment by jasnell** [comment]
Does not occur within io.js so possible backport
