### ISSUE TITLE
Assertion `parser->current_buffer_.IsEmpty()' failed.

### ISSUE THREAD

**Issue by fmsouza** [nodejs/node-v0.x-archive#25802]
I'm having this issue when receiving a great amount of HTTP requests in my application, which consists in an ExpressJS-based REST API.

node: ../src/node_http_parser.cc:445: static void node::Parser::Finish(const v8::FunctionCallbackInfov8::Value&): Assertion `parser->current_buffer_.IsEmpty()' failed.

My application depends on node 0.11.x, so I tried it in 0.11.x and 0.12.x environments and it happens intermittently. I still not sure why does it happen and don't know how to reproduce it exactly. The application justs outputs this error in the console and then quits with any other error output.

**Comment by fmsouza** [comment]
I'm developing the application in the OS X inside a Docker container running the official ```node:0.11.16``` or ```node:0.12.7```, which runs over debian. My testing and production servers are archlinux.

**Comment by jasnell** [comment]
Are you able to provide detail about the code? A test case that demonstrates the problem perhaps?

**Comment by fmsouza** [comment]
Sorry, actually I don’t. I’m still trying to figure out how does it happens. It’s happening occasionally and I didn’t caught it’s pattern yet.
When I manage to discover it I’ll update here, I’m working on it.
