### ISSUE TITLE
Linux APT contains obsolete version

### ISSUE THREAD

**Issue by ghost** [nodejs/node-v0.x-archive#25817]
I downloaded the binaries and followed the readme. It did not work, I guess because the readme is about how to build the binaries... 

I managed to install it by pasting the bash from this question: http://stackoverflow.com/questions/20028996/how-to-install-node-binary-distribution-files-on-linux I guess it copied the binaries to various locations (I started to use linux yesterday). It appears to be working properly now, but I am not sure, since I don't know what exactly the bash script does.

The apt-get can install only 0.10.25 which is very old. Isn't there a way to update that regularly?

**Comment by evanlucas** [comment]
https://github.com/nodesource/distributions#debinstall has instructions on using the nodesource distributions. They are updated quite regularly. You may want to check those out.

**Comment by jasnell** [comment]
@misterdjules @orangemocha
