### ISSUE TITLE
process.argv outputs differently on win 8,10 when single quote is used

### ISSUE THREAD

**Issue by eenagy** [nodejs/node-v0.x-archive#25814]
When using single quotes to group argument list, the returned list of arguments will be different. 

Here is an example:

test.js
```js 
console.log(process.argv)

```

```shell
node test.js 'first argument with spaces' 'second argument with spaces'
```
On linux (arch) : 
```
[ 'node',
  '/somedirectory/test.js',
  'first argument with spaces',
  'second argument with spaces' ]
```
On windows (8, 10)
```
[ 'node',
  'D:\\somedirectory\\test.js',
  '\'first',
  'argument',
  'with',
  'spaces\'',
  '\'second',
  'argument',
  'with',
  'spaces\'' ]
```

So basically, on windows grouped arguments will be splitted. 
Of course if double quote where used instead, then the contents of the arguments will be similar.

**Comment by orangemocha** [comment]
Hi @eenagy . On Windows, arguments that contain spaces must be enclosed with double quotes, not single quotes. This is because of the command shell differences and not really because of Node.js.

**Comment by cjihrig** [comment]
Closing this with @orangemocha's explanation.
