### ISSUE TITLE
DateTimeFormat error for Chilean Time

### ISSUE THREAD

**Issue by tomascharad** [nodejs/node-v0.x-archive#25834]
(node v.0.12.7)
On chrome's V8 the output of the following code:
date = new Date('Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)')
formatter = Intl.DateTimeFormat('En-us', { hour: 'numeric', hour12: false })
formatter.format(date)
Is "21".

However if I do the same on a node console I obtain '20'.

In Chile we've faced a change of our "Winter time" and this might be causing this issue.

Maybe there is something needed to be updated in the Intl module?

**Comment by dnakamura** [comment]
I believe its a discrepency in the timezone parsing. From chrome js console
'''
date = new Date('Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)')
Mon Jun 15 2015 20:43:11 GMT-0400 (Eastern Daylight Time)
'''
It seems to be picking up the 'CLT' (which is actually GMT-0400).
From node:
'''
 > date = new Date('Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)')
Mon Jun 15 2015 20:43:11 GMT-0400 (Eastern Daylight Time)
'''
seems to be using the 'GMT-0300' string rather than recognizing 'CLT'

**Comment by tomascharad** [comment]
@dnakamura I think you meant this on your second code block:

Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)

**Comment by dnakamura** [comment]
@tomascharad  Ah apparently I got confused. chrome and node seem to be in agreement parsing "Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)" into "Mon Jun 15 2015 20:43:11 GMT-0400 (Eastern Daylight Time)" . Are you running chrome and node on the same machine?
Also apparently I'm wrong. They changed CLT to be GMT-0300 (I didn't think you could do that).

**Comment by tomascharad** [comment]
Look, here is the full log of the actions on chrome:

date = new Date('Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)')
Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)
formatter = Intl.DateTimeFormat('En-us', { hour: 'numeric', hour12: false })
Object {resolved: Object}
formatter.format(date)

"21"

And on Node:

> date = new Date('Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)')
Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)
> formatter = Intl.DateTimeFormat('En-us', { hour: 'numeric', hour12: false })
{}
> formatter.format(date)
'20'

**Comment by tomascharad** [comment]
Also, just for having more background, if I do on Chrome: 
new Date()
Thu Aug 13 2015 09:21:45 GMT-0300 (CLT)

and then on Node:

> new Date()
Thu Aug 13 2015 09:22:55 GMT-0300 (CLT)

**Comment by srl295** [comment]
May be fixed by #25855 if the timezone data was in ICU 55

**Comment by srl295** [comment]
@tomascharad can you try the upgrade procedure in https://github.com/joyent/node/wiki/Intl#updating-timezone-data ?

**Comment by tomascharad** [comment]
@srl295 Could you please let me know where should I change ICU_TIMEZONE_FILES_DIR?

**Comment by srl295** [comment]
Set it in the environment. With set or setenv before node  starts.

**Comment by srl295** [comment]
@tomascharad sorry for the slow confirmation. It is due to the tz version. In the latest released node which has ICU 55 it seems to be working:

```
$ env TZ=America/Santiago node
> process.version
'v3.3.0'
> process.config.variables.icu_ver_major
'55'
> date = new Date('Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)')
Mon Jun 15 2015 21:43:11 GMT-0300 (CLT)
> formatter = Intl.DateTimeFormat('En-us', { hour: 'numeric', hour12: false })
{}
> formatter.format(date)
'21'
```

Above I discuss how to update the tz data. If it's not working, please reopen https://github.com/nodejs/node/issues/2372 or a new issue. Thanks!
