### ISSUE TITLE
Math.random() base9 unexpected output

### ISSUE THREAD

**Issue by alexindigo** [nodejs/node-v0.x-archive#25859]
I can reproduce it this bug in `node@0.12.4` and `chrome@44.0`, but not in Safari.

Here how it goes:

```
Math.random().toString(8)
// => "0.40556507362"

Math.random().toString(10)
// => "0.728570100152865"

Math.random().toString(9)
// => "0.0827732187366627667757170678236484038136048078814333065003273475748823847052171505611745607131107775207264584450514430015045848810260884402854460545710123610180560420254670314355378040324234254371807147184782268386233707765468214036027400221665283600662327470517055372488331452573625436747586416472320135758616410480125571575128186018106771302258702311387174723583854613620414064252707610521084320604083158107814850408261118351134136042420656051432230271023038632483667287813104143501804530437677857800702418378151856753864260337348333626771102784763227152852152412073514384883341043635024681282680855725652011361101288818730870626807412515180721011558753700528516431638256216633145222014073687153461000157367686788415433786076034107172124101737883467507825555026358072200447606370760138778858157342802675600025362366176175752107284513664182760134667188055552867358360073844732540377024745342031316180555142182557020612006654255356586627712774478233665572780235785105615638546715172277637084700477431611300125377148225208376471737728356737132737442448517622656208545342183141308840668654334465064875"
```

Thank you.

**Comment by brendanashworth** [comment]
Seems to occur with all odd-numbered bases, not just 9.

**Comment by tunniclm** [comment]
This behaviour seems to be related to this code & comment: https://github.com/v8/v8-git-mirror/blob/b104a67ef0a50beab2dc85a6ac5732c696d07698/src/conversions.cc#L458. The `DoubleToRadixCString()` function will attempt a conversion generating digits until it reaches an exact answer or the max. buffer length (1099 characters for decimal part).

**Comment by alexindigo** [comment]
Yep, I discovered it too after I opened this issue. 

Thanks for the link, too bad I can't open issues in that repo. :)

**Comment by brendanashworth** [comment]
This isn't really an issue with node, more of an issue with v8 - so I'll close this here for now. If you think its important enough to have the node maintainers keep track of it, you can open a new issue at github.com/nodejs/node - but v8 is probably the best way from here.

**Comment by alexindigo** [comment]
This is the closest place to V8 I could find where I could open bug ticket. :)

**Comment by targos** [comment]
@alexindigo it is possible to open a ticket directly in the V8 project: https://code.google.com/p/v8/issues/list

**Comment by brendanashworth** [comment]
@alexindigo if you don't want to open a v8 issue, please _do_ open a new issue on nodejs/node. There, someone will probably pay some attention to it, but it sitting here won't do much.

**Comment by bnoordhuis** [comment]
> if you don't want to open a v8 issue, please do open a new issue on nodejs/node.

Fixing V8 bugs is not really in our remit.  This should be directed to the V8 bug tracker.

I'm not sure if it qualifies as a bug.  I don't think it's a spec violation but you can argue it's a quality-of-implementation issue.
