### ISSUE TITLE
node does not propagate the module.paths to the require('module')

### ISSUE THREAD

**Issue by wyattbiker** [nodejs/node-v0.x-archive#25861]
I start my main.js application and push into module.paths the global module folder. When i require a 3rd party module (in this case cmod.js) that also requires a module which is in my globals module folder, it does not find the module and fails. Is there some way to force module.paths updated in main.js to be used also by the module cmod.js below:

so for example:

**mymain.js**

```
//global modules path
module.paths.push('C:\Users\xuser\AppData\Roaming\npm');
// finds ws in global modules path. Works!
wsmain=require('ws') 
// Now load a 3rd party module, which also requires('ws');
C = require('cmod.js');
```

**cmod.js**

```
ws=require('ws');  // **fails to find global path**
```

**Comment by a0viedo** [comment]
Use the [`NODE_PATH`](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) environment variable instead. I'm not sure if `module.paths` is supposed to be an alternative for what you're trying to do.
