### ISSUE TITLE
Investigate v0.10 flaky test test-dgram-multicast-multi-process

### ISSUE THREAD

**Issue by orangemocha** [nodejs/node-v0.x-archive#25865]
https://github.com/joyent/node/commit/841a6dd264d2dd7559cf0f0d3a6ed052ad0b4ca5 marked this test as flaky in v0.10 so that it doesn't block merges with Jenkins and node-accept-pull-request.

cc: @joyent/node-collaborators

**Comment by cjihrig** [comment]
If this still needs to be addressed, I suggest moving it to nodejs/node.
