### ISSUE TITLE
An error caused

### ISSUE THREAD

**Issue by visoft-viscrop** [nodejs/node-v0.x-archive#25863]
Makefile:
../deps/v8/src/heap-snapshot-generator.cc:2914:54:   required from here
../deps/v8/src/heap-snapshot-generator.cc:2862:44: error: invalid use of incomplete type 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2827:30: error: declaration of 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2862:44: error: invalid use of incomplete type 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2827:30: error: declaration of 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2862:44: error: invalid use of incomplete type 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2827:30: error: declaration of 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc: In function 'int v8::internal::utoa(T, const v8::internal::Vector<char>&, int) [with T = v8::internal::HeapEntry::Type]':
../deps/v8/src/heap-snapshot-generator.cc:2865:1: warning: control reaches end of non-void function [-Wreturn-type]
../deps/v8/src/heap-snapshot-generator.cc: In function 'int v8::internal::utoa(T, const v8::internal::Vector<char>&, int) [with T = v8::internal::HeapGraphEdge::Type]':

**Comment by brendanashworth** [comment]
@visoft-viscrop it isn't very clear what you're trying to say here / what the issue is. I'd go for rebuilding from source completely with a new tarball or going for one of the distributions. If you still have an issue, please open a new issue @ https://github.com/nodejs/node with more info on the bug you have. Thanks.
