### ISSUE TITLE
Investigate v0.10 flaky test test-tls-securepair-client

### ISSUE THREAD

**Issue by orangemocha** [nodejs/node-v0.x-archive#25866]
https://github.com/joyent/node/commit/a7fee30da123953e68bafc835fe6ce1818a5dc44 marked this test as flaky in v0.10 so that it doesn't block merges with Jenkins and node-accept-pull-request.

My guess is that a good percentage of these tests fail because of issues with the test itself, not node. It's likely that those issues were fixed in v0.12, so it might be a good idea to look for changes to the same test in git history in v0.12, or even simply trying the v0.12 version of the test with node v0.10.

/cc: @joyent/node-collaborators

**Comment by dnakamura** [comment]
I have also seen this issue arise on windows.

**Comment by cjihrig** [comment]
If this still needs to be addressed, I suggest moving it to nodejs/node.
