### ISSUE TITLE
fs.unlink doesn't work, but there is no error created.

### ISSUE THREAD

**Issue by vucuong12** [nodejs/node-v0.x-archive#25867]
I have a .zip file, I want to extract it, but this file has a problem that it cannot be extracted. When that error is emitted, I want to delete(unlike) .zip file but I cannot do that. This is the code:

var unzipExtractor = unzip.Extract({ path: dir });
var source = fs.createReadStream(dir + 'sub.zip');
var unZip = source.pipe(unzipExtractor);
unZip.on('error', function(err) {
   fs.unlink(dir + 'sub.zip', function(err){
       if (err) console.log(err); else console.log('File extracted !');
   })
})
"File extracted !" is printed out, but the file sub.zip is not deleted.

**Comment by brendanashworth** [comment]
If the callback is being called with `fs.unlink`, it was probably deleted. If you're 100% sure of this, I'd suggest opening an issue @ github/nodejs/node for further debugging. Thanks.
