### ISSUE TITLE
An error caused in make

### ISSUE THREAD

**Issue by visoft-viscrop** [nodejs/node-v0.x-archive#25869]
ete type 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2827:30: error: declaration of 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2862:44: error: invalid use of incomplete type 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2827:30: error: declaration of 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2862:44: error: invalid use of incomplete type 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2827:30: error: declaration of 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc: In instantiation of 'int v8::internal::utoa(T, const v8::internal::Vector<char>&, int) [with T = v8::internal::HeapEntry::Type]':
../deps/v8/src/heap-snapshot-generator.cc:2914:54:   required from here
../deps/v8/src/heap-snapshot-generator.cc:2862:44: error: invalid use of incomplete type 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2827:30: error: declaration of 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2862:44: error: invalid use of incomplete type 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2827:30: error: declaration of 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2862:44: error: invalid use of incomplete type 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc:2827:30: error: declaration of 'struct v8::internal::{anonymous}::ToUnsigned<1u>'
../deps/v8/src/heap-snapshot-generator.cc: In function 'int v8::internal::utoa(T, const v8::internal::Vector<char>&, int) [with T = v8::internal::HeapEntry::Type]':
../deps/v8/src/heap-snapshot-generator.cc:2865:1: warning: control reaches end of non-void function [-Wreturn-type]
../deps/v8/src/heap-snapshot-generator.cc: In function 'int v8::internal::utoa(T, const v8::internal::Vector<char>&, int) [with T = v8::internal::HeapGraphEdge::Type]':
../deps/v8/src/heap-snapshot-generator.cc:2865:1: warning: control reaches end of non-void function [-Wreturn-type]
make[1]: *** [/root/node-v0.12.7/out/Release/obj.target/v8_base/deps/v8/src/heap-snapshot-generator.o] Error 1
make[1]: Leaving directory `/root/node-v0.12.7/out'
make: *** [node] Error 2

**Comment by aratic** [comment]
please offer your system/version and environment, gcc/python version, kinds of( or just your config.mk)
and most importantly, you should paste the very first screen of the error

**Comment by brendanashworth** [comment]
Yes, please see https://github.com/nodejs/node-v0.x-archive/issues/25863#issuecomment-147552091, I'll close this for now.
