### ISSUE TITLE
a little mistake in document about modules

### ISSUE THREAD

**Issue by enginechang** [nodejs/node-v0.x-archive#25864]
I found a little error while reading node document.

as the following link
https://nodejs.org/api/modules.html#modules_exports_alias

``` js
function require(...) {
  // ...
  function (module, exports) {
    // Your module code here
    exports = some_func;        // re-assigns exports, exports is no longer
                                // a shortcut, and nothing is exported.
    module.exports = some_func; // makes your module export 0
  } (module, module.exports);
  return module;
}
```
I am confused with the last line "return module". I think it should be "return module.exports" rather than "return module".

**Comment by brendanashworth** [comment]
Hi!

This repo is now an archive, mostly where issues go to die. If you'd like this to get any attention, I'd recommend opening an issue where development is now: https://github.com/nodejs/node.

I'll close this for now as I don't think a doc change like this would be backportable to 0.x.
