### ISSUE TITLE
Deprecate Array#values() in 0.12.x

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-v0.x-archive#25877]
It's simply not going to exist in io.js. Who knows how many people are using it, so our best course of action is probably to issue a deprecation over here.

Somewhat related in concept to https://github.com/joyent/node/issues/25784

cc @joyent/node-collaborators @joyent/node-tsc

**Comment by jasnell** [comment]
:+1:

**Comment by trevnorris** [comment]
+1

**Comment by bnoordhuis** [comment]
V8 tracking bug: https://code.google.com/p/v8/issues/detail?id=4247

EDIT: the tl;dr is that it probably won't appear in V8 again anytime soon.

**Comment by indutny** [comment]
+1

**Comment by mhdawson** [comment]
Discussed in latest lts meeting.  Nobody's going to get to this and we don't feel its that important so we agreed to close
