### ISSUE TITLE
https server dynamic secure context

### ISSUE THREAD

**Issue by petkaantonov** [nodejs/node-v0.x-archive#25880]
All incoming TLS connections are [hard coded to use the initial secure context](https://github.com/joyent/node/blob/master/lib/_tls_wrap.js#L637) but API should be exposed so that the secure context can be updated e.g. `setSharedCredentials(secureContext)`.

I would use SNICallback for this but it doesn't work with ip address domains.

**Comment by cvillerm** [comment]
I think that there is another potential limitation of using SNICallback as a way to dynamically load a secure context as if we want to use it to update the CRL file used to check client certificate revocation, requests not using SNI (what an attacker could use with a revoked client certificate) would still be using the initial CRL loaded at server startup time, what may be outdated
