### ISSUE TITLE
ignoring part of require's request

### ISSUE THREAD

**Issue by quirinpa** [nodejs/node-v0.x-archive#25881]
Hello guys thanks for this amazing tool!

I'm trying to implement webpack's code splitting in an isomorphic project. In webpack, i do something like *require('bundle?lazy!./Home')* in order to make a split in my code base and lazy load the *Home.js* file. In node (server-side), i don't want such behaviour, i just want node to ignore what's behind the exclamation point and require Home.js like any other module.

I've realised a couple of things. If i use this:
```js
if (__SERVER__)
  require('./Home');
else
  require('./bundle!./Home');
```
webpack messes up when it looks up requires in the file (also it's a lot of comparisons to add to my logic). And hooking into *require.extensions* wouldn't solve a thing because at that point the filename is already resolved.

Can i hook into the require's resolve algorithm? Thanks in advance.

**Comment by quirinpa** [comment]
I just realized i could hook into require directly in the file in which i need the custom behaviour to occur. close

**Comment by brendanashworth** [comment]
closing per request
