### ISSUE TITLE
Node.js (Windows) - NPM Install Error msbuild.exe fails

### ISSUE THREAD

**Issue by Cypher278999** [nodejs/node-v0.x-archive#25906]
I can't get (npm install) to run without error (see below) on an existing grunt project that I was given. I have tried running command prompt as admin, used node.js command prompt, installed visual studio 2013 then using switch (npm install --msvs_version=2013), tried visual studio 2008 too, environment variable is (C:\Users\Sales4\AppData\Roaming\npm), msbuild.exe exists. I have really been struggling with this and would greatly appreciate any help. Thank You.

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack  at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack  at ChildProcess.emit (events.js:110:17)
gyp ERR! stack  at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd W:\work\Projects\website\gruntproject\node_modules\grunt-sass\node_modules\node-sass
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2013"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! node-sass@0.8.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.8.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     W:\work\Projects\website\gruntproject\npm-debug.log

**Comment by ghost** [comment]
Fixed. I had to uninstalled Node .12 and instead use 0.10.36 - I was told that the latest version of Node.js may not support the node-sass version I had in use.
