### ISSUE TITLE
require.resolve() should allow providing a custom starting path

### ISSUE THREAD

**Issue by callumlocke** [nodejs/node-v0.x-archive#25905]
As far as I can tell there's no safe way to locate a **dependency of a dependency**, because require.resolve can only use the current file as its starting point.

---

**Example use case:** as the author of `my-module`, I want to load `bar` so I can monkey-patch it before `foo` uses it:

```
my-module
 ┗━foo
   ┗━bar
```

Calling `require.resolve('foo/node_modules/bar')` won't work if the deps have been flat-installed using npm 3 (or if my node_modules tree has been deduped in some way).

There's no way for me to find out where `bar` is located. I can use `require.resolve()` to find where `foo` is located, but I can't then call it from that new location to find out where `bar` is.

---

**Solution:** add an optional 2nd parameter: `require.resolve(request, fromFile)`

This would allow: `require.resolve('bar', require.resolve('foo'))`

**Comment by jasnell** [comment]
The dependency isolation you're trying to work around is actually a feature. If you truly want to expose a sub-dependency in this way, then your parent module (`bar`) should use `module.export` to do so as opposed to modifying the module loader system.

**Comment by sindresorhus** [comment]
I agree it's a bad pattern. You could use [`resolve-from`](https://github.com/sindresorhus/resolve-from) if you insist on doing it that way.

**Comment by callumlocke** [comment]
Thanks @sindresorhus, that solves my problem. I agree it's a bad pattern too, I guess a module is the way to go.
