### ISSUE TITLE
Error while reading tcp port in andriod node js

### ISSUE THREAD

**Issue by amitg2291632** [nodejs/node-v0.x-archive#25901]
Hi,

 i am opening a  tcp  port in unix and trying to read it from android node js
But while reading tcp port its giving error 
in below code

```javascript
wss.on('connection', function(ws) {
  console.info('Got a client')

  var stream = net.connect({
    port: 9002
  })

  stream.on('error', function() {
    console.error('Error in port reading`')

  })
```

Please help me how i can read a tcp port android node js.

Let me know for any more information.

Thanks & Regards,
Amit Garg

**Comment by brendanashworth** [comment]
@amitg2291632 there really isn't enough information here to help you. We need both information on the error and a short, concise test case that only uses core modules (i.e. `net`, `stream`). I'm going to close this issue for now, but if you can come up with both of those things, please open a new issue @ https://github.com/nodejs/node where this can be discussed.
