### ISSUE TITLE
Linking with fcgi_stdio.h ?

### ISSUE THREAD

**Issue by kevmuret** [nodejs/node-v0.x-archive#25909]
Hello, i'm very interessted to build a node version which can be used as a FastCGI binary to use it in mixed languages environments.

I want to link the librairy with

[code]#include "fcgi_stdio.h" // Replacing <stdio.h> in all codes including dependecies[/code]

I don't know if there is a solution to add the -lfcgi flags on generated Makefiles ?

I will next add FCGI functions to the globalTemplate, to be able to do the work.

I don't know yet but will it be still possible to have cluster, child_process, http, ... working correctly with that kind of binary ?

I will remove unecessary things and maybe write designed modules to be usable in two modes.

Thanks for your future help, i will publish a public project if all can be done and work.

I hope my english is correct, i'm from france ;)

EDIT: Found solution for link librairy but got a lot of warnings and an error...

![node-link-fcgi](https://cloud.githubusercontent.com/assets/7468255/9562894/1abe2b3e-4e79-11e5-9c0b-b3575b96a5da.png)

I was on Radxa Rock Arm singleboard computer with latest ubuntu server image and updated.

Sorry for the screenshot, i was unable to select text in the console on windows.

**Comment by rafis** [comment]
This will require good knowledge of C/C++ Developer from you.

I recommend you to use nodejs solutions:
https://www.npmjs.com/package/fastcgi
https://www.npmjs.com/package/node-fastcgi
https://www.npmjs.com/package/fastcgi-server
https://www.npmjs.com/package/fastcgi-stream

**Comment by srl295** [comment]
@kevmuret : 
@rafis ' links (besides https://www.npmjs.com/package/fastcgi which is the opposite scenario) are the right approach here. `FCGI_Accept` is a different event loop than what Nodejs is expecting.
