### ISSUE TITLE
build error, already fix by hand, there should be some configure/makefile generate problem, need help to allocate/fix

### ISSUE THREAD

**Issue by aratic** [nodejs/node-v0.x-archive#25911]
environment: virtual machine, Gentoo 64 bits, and python3.3/2.7

problem 1, system use python3.3 as default and think ''' block comments invalid, not a issse
problem 2, when python2.7 ./configure done, I met some "TypeError: object of type 'filter' has no len()" during make, and i believe this is still a python2/3 problem, i grep out that  among following makefiles, some were automatically geneated as python2.7, but some still left as python, which evokes python3,

./config.mk: ./* use python2.7, fine */
./out/deps/v8/tools/gyp/postmortem-metadata.target.mk  /* use python, not ok */
./out/deps/v8/tools/gyp/js2c.target.mk  /* use python, not ok */
./out/node_js2c.host.mk  /* use python2.7, fine */

i fix these makefiles by hand and pass the build, but it seems they were automatically generated or fetch(svn) from somewhere else, need help

**Comment by ChALkeR** [comment]
https://github.com/nodejs/node/issues/418
https://github.com/nodejs/node/issues/2735
Especially, https://github.com/nodejs/node/issues/2735#issuecomment-138473322.

Hope this helps. If it doesn't — report an issue in [nodejs/node](https://github.com/nodejs/node) repository, this is an archive.

**Comment by aratic** [comment]
as the nodejs/node#418 says this seems been hardcoded somewhere else.. whatever.
Thx for organizing and the reference,~
