### ISSUE TITLE
nodejs.org blacklisting User-Agent from Java client

### ISSUE THREAD

**Issue by whampop** [nodejs/node-v0.x-archive#25912]
We're using maven to fetch nodejs as a dependancy, and the request to download http://nodejs.org/dist/v0.12.6/node-v0.12.6-darwin-x64.tar.gz (or any other version) results in a 403 Error. 

When I removed the User-Agent header from the GET request (or changed it to anything other than 'Java/1.X') the request succeeds.

<img width="731" alt="screen shot 2015-08-30 at 9 04 07 pm" src="https://cloud.githubusercontent.com/assets/1829001/9570884/b18fdbfc-4f5a-11e5-8459-b9d38566b05c.png">

<img width="670" alt="screen shot 2015-08-30 at 9 05 04 pm" src="https://cloud.githubusercontent.com/assets/1829001/9570898/d2f51f78-4f5a-11e5-9a93-d7b0e51fd494.png">

**Comment by cristian04** [comment]
This is a Critical issue as one of the most important plugins from Jenkins is not working now. https://issues.jenkins-ci.org/browse/JENKINS-30218

**Comment by cristian04** [comment]
wget "http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz"  --user-agent="Java/1.6.0_45"
--2015-08-31 23:58:31--  http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz
Resolving nodejs.org... 104.20.22.46, 104.20.23.46, 2400:cb00:2048:1::6814:172e, ...
Connecting to nodejs.org|104.20.22.46|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-08-31 23:58:31 ERROR 403: Forbidden.

➜  Documents
wget "http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz"  --user-agent="Java/1.8.0_45"
--2015-08-31 23:58:34--  http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz
Resolving nodejs.org... 104.20.22.46, 104.20.23.46, 2400:cb00:2048:1::6814:172e, ...
Connecting to nodejs.org|104.20.22.46|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-08-31 23:58:34 ERROR 403: Forbidden.

➜  Documents
wget "http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz"  --user-agent="Java/1.7.0_80"
--2015-08-31 23:58:39--  http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz
Resolving nodejs.org... 104.20.22.46, 104.20.23.46, 2400:cb00:2048:1::6814:172e, ...
Connecting to nodejs.org|104.20.22.46|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-08-31 23:58:39 ERROR 403: Forbidden.

➜  Documents
wget "http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz"  --user-agent="Something here"
--2015-08-31 23:58:46--  http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz
Resolving nodejs.org... 104.20.22.46, 104.20.23.46, 2400:cb00:2048:1::6814:172e, ...
Connecting to nodejs.org|104.20.22.46|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9696397 (9.2M) [application/octet-stream]
Saving to: 'node-v0.12.4-linux-x64.tar.gz.4'

0.12.4-linux-x64.ta   8%[>                     ] 790.45K   567KB/s

**Comment by zackb** [comment]
Help, this is a critical issue for us

**Comment by targos** [comment]
/cc @rvagg @nodejs/website 
Is it related to the website migration ?

**Comment by Fishrock123** [comment]
> Is it related to the website migration ?

Probably.

Does it help if you copy a web browser's user-agent and try?

**Comment by Fishrock123** [comment]
Also this issue probably belongs on https://github.com/nodejs/nodejs.org. cc @nodejs/build

**Comment by Fishrock123** [comment]
The hosting is now done via CloudFlare if that explains anything..

**Comment by robtayl0r** [comment]
@zackb Depending on your environment, setting Java's system user-agent header to anything other than "Java/1.*" will workaround this issue. This can be done a few ways.

**Comment by zackb** [comment]
Ya, setting Jenkins user agent to 'not java' fixes the problem. For anyone else in /etc/defaults/jenkins add -Dhttp.agent='not java' to the JENKINS_ARGS var and restart jenkins

**Comment by robtayl0r** [comment]
Likewise, anyone using Maven we've used something along the lines of export MAVEN_OPTS=$MAVEN_OPTS" -Dhttp.agent=GrumbleGrumble"

**Comment by Fishrock123** [comment]
Ok. Please do that for now.

@orangemocha do you have access to any of the CloudFlare stuff?

**Comment by orangemocha** [comment]
I do, and made a configuration change. Is it working now?

**Comment by scott-phillips-sp** [comment]
wget "http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz" --user-agent="Java/1.6.0_45"

Works for me now.

**Comment by scott-phillips-sp** [comment]
And my Jenkins jobs are now successfully downloading node. Thanks.
