### ISSUE TITLE
Add a `pty` option or equivalent to `cp.spawn()`

### ISSUE THREAD

**Issue by TooTallNate** [nodejs/node-v0.x-archive#2754]
My main concern is that there is no longer a way to spawn a child process where this would run successfully, _without_ sharing stdio with the node process:

``` js
var assert = require('assert').ok;
var tty = require('tty');

assert(tty.isatty(0));
```

This is a problem for any node app trying to have its child processes generate ANSI color codes, as most well behaved programs test for that property. This used to be available I believe as `tty.open()` but was removed in `0.5.x`.

So I'm thinking adding a `pty: true` option to `cp.spawn()` would be a nice API. Would probably require libuv changes but this is a needed feature IMO.

``` js
var spawn = require('child_process').spawn;

var child = spawn('bash', [], { pty: true })
child.stdout.pipe(process.stdout);
child.stderr.pipe(process.stderr);
```

Thoughts?

**Comment by malandrew** [comment]
+1

**Comment by jasnell** [comment]
@TooTallNate ... is this still something you'd like to see happen?

**Comment by TooTallNate** [comment]
Yes, but from what I understand Windows more or less makes this
impossible...

**Comment by jasnell** [comment]
Ok, will keep it open for now. @orangemocha ... any thoughts on the windows angle?

**Comment by Calderis** [comment]
+1

**Comment by olalonde** [comment]
+1

**Comment by GongT** [comment]
+2017
