### ISSUE TITLE
os.arch should be the architecture of the OS not of the process

### ISSUE THREAD

**Issue by joshwilsdon** [nodejs/node-v0.x-archive#2862]
In lib/os.js:

```
exports.arch = function() {
  return process.arch;
};
```

Which means that on a system that's running a 64 bit kernel but a 32 bit node binary you get:

```
> os.arch()
'ia32'
```

when you would have expected 'x64'.

**Comment by jasnell** [comment]
@isaacs ... have there been any updates on this one?

**Comment by jasnell** [comment]
Doesn't appear to be a bug. Marking as a feature-request. For backwards compatibility, recommend no changes to the current behavior but it may be worthwhile to add a new `process.sysarch()` API that always returns the arch of the underlying kernel independently of the process arch.

**Comment by Fishrock123** [comment]
+1 deprecate `os.arch()` and add `os.sysarch()`
