### ISSUE TITLE
Windows installer: add support for side-by-side installations

### ISSUE THREAD

**Issue by mcartoixa** [nodejs/node-v0.x-archive#2924]
On windows, it should be possible to find information about node installation (version, path) in the registry.

Basic use case: the development of a MSBuild task that would encapsulate _node.exe_ (and its output) without relying on it being in the current PATH (very convenient in continuous integration scenarios).

**Comment by jasnell** [comment]
@orangemocha ... still relevant?

**Comment by orangemocha** [comment]
Yes. Changing the title based on this comment: https://github.com/joyent/node/pull/2948#issuecomment-13387465

>Only partially. Please keep issue #2924 open, because we're still working on figuring out the right way to let multiple versions live side by side, and we'll get more registry structure created correctly then. Meanwhile, there is a registry key being created, but it's not quite what you originally requested--i.e. it's installer-specific and doesn't include a version number yet.
