### ISSUE TITLE
fs.watch() unreliable when using vim

### ISSUE THREAD

**Issue by scribu** [nodejs/node-v0.x-archive#3172]
I'm trying to build a continuous recompilation utility for LESS files and I'm getting errant results.

Sample code:

``` js
fs.watch('example.less', function(event, fname) {
  console.log(+(new Date), arguments);
});
```

First file edit: nothing.
Second file edit:

```
1335280930608 { '0': 'change', '1': 'example.less' }
1335280930610 { '0': 'rename', '1': 'example.less' }
1335280930610 { '0': 'rename', '1': 'example.less' }
```

Subsequent edits: nothing.

My environment: vim 7.3, Ubuntu 11.10, node 0.6.15

**Comment by IonicaBizau** [comment]
I created [`fwatcher`](https://github.com/IonicaBizau/node-fwatcher), a tiny wrapper for `fs.watch` which tries to reapend the listeners after rename event. I did it for the same reason: editing files in VIM.

```js
var watcher = require("fwatcher");
watcher.watch('example.less', function(err, event, path) {
  console.log(+(new Date), arguments);
});
```

This doesn't solve the root problem, but it is a solution for the VIM users. :smile: 

/cc @scribu

**Comment by jasnell** [comment]
Is this still an issue?

**Comment by scribu** [comment]
I don't have an Ubuntu instance handy, but on OSX 10.10.2 and node 0.10.36 I'm still getting inconsistent events:

First edit:

```
1426721530261 { '0': 'rename', '1': null }
```

Second edit:

```
1426721535949 { '0': 'rename', '1': null }
```

Subsequent edits:

nothing

**Comment by scribu** [comment]
@IonicaBizau Thanks. Not long after opening this issue I found some other library that seemed to work better than the builtin fs.watch (I don't remember the name anymore).

**Comment by IonicaBizau** [comment]
@jasnell Still reproducing on Ubuntu 15.04.

**Comment by jasnell** [comment]
Definitely see continued inconsistency here.

**Comment by jasnell** [comment]
Marking this as a P-3 (low priority) and labeling as defer-to-convergence. This means we'll add this to the list of things to look at after we've completely merged into nodejs/node.

**Comment by pugnascotia** [comment]
Noticed this using webpack and vim. Would be great to see a fix.

**Comment by ekkis** [comment]
I'm using NPM's `grunt-contrib-watch` and saving a file in vim fires events twice running on OSX 10.11.2 (El Capitan).  looking for a solution...
