### ISSUE TITLE
Connections closed by node stay permanently in FIN_WAIT2

### ISSUE THREAD

**Issue by ghost** [nodejs/node-v0.x-archive#3613]
Hi

I love using node :)

Normally when node closes a connection (using socket.end()), the following packets are exchanged:
node > client [AF]
client > node [A]
client > node [AF]
node > client [A]

However, sometimes the client does not respond well, and I get only these packets:
node > client [AF]
client > node [A]

With node, this results in connections _permanently_ (not temporarily) in FIN_WAIT2 (netstat -nop):
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name Timer
tcp        0      0 XX.XX.XX.XX:80       XX.XX.XX.XX:17863      FIN_WAIT2   26375/node       off (0.00/0/0)
tcp        0      0 XX.XX.XX.XX:80       XX.XX.XX.XX:17832      FIN_WAIT2   26375/node       off (0.00/0/0)
[very long list]
tcp        0      0 XX.XX.XX.XX:80       XX.XX.XX.XX:17992      FIN_WAIT2   26375/node       off (0.00/0/0)
tcp        0      0 XX.XX.XX.XX:80       XX.XX.XX.XX:17851      FIN_WAIT2   26375/node       off (0.00/0/0)

The problem here is that the timer is set to off, so the socket stays _indefinitely_ in this state, eventually exhausting the server.

I wanted to know why I see this problem only with node (and not with nginx and perl POE). I read the following interesting information (source http://alldunne.org/2010/07/tcp-connection-is-permanently-in-fin_wait2-state/):
"When programming sockets in C, it’s useful to know an important difference between the shutdown (either READ or WRITE) and close of a socket.
Shutting down the socket will cause the connection to go into the FIN_WAIT2 state while the TCP/IP stack waits for the connection to be closed at the other end of the connection. But if the other side doesn’t shutdown/close the connection, then the connection will remain in the FIN_WAIT2 state indefinitly (assuming of course that your process hasn’t been terminated).
If your process where to close the connection, rather than call shutdown on it, then the connection will fall into FIN_WAIT2 as before, however, the TCP/IP stack will time the connection out after a certain period."

Having read this, maybe node is shutting down the socket instead of closing it and causes the socket to exist forever, when it was not closed well on the client side.

Best regards

**Comment by jasnell** [comment]
@trevnorris @saghul ... do either of you happen to recall the status of this one?

**Comment by luckydrq** [comment]
Thanks guys. I am recently writing a tcp client and as i dive into TCP details i found this issue. I wonder if this is fixed in modern nodejs versions, so i move this issue to https://github.com/nodejs/node/issues/11572 for further discussion. I'd be very happy to hear from you.
