### ISSUE TITLE
Allow Steam.prototype.setEncoding() to be reverted

### ISSUE THREAD

**Issue by Rush** [nodejs/node-v0.x-archive#3639]
Expected behaviour: `socket.setEncoding(null)` sets `socket._encoder = undefined;`
Current behaviour: No behaviour.

Should be very easy to fix, should I send a patch for it? I am a bit unsure on how you work in here so I am a bit hesitant.

**Comment by jasnell** [comment]
@joyent/node-coreteam ... this had a pull request but never seems to have landed (for unknown reasons). There doesn't seem to have been any objections noted so is this something we'd like to do or not?

**Comment by jasnell** [comment]
@joyent/node-tsc ... ping
