### ISSUE TITLE
Support SourceMap

### ISSUE THREAD

**Issue by gfx** [nodejs/node-v0.x-archive#3712]
There comes more and more JavaScript source generation tools.
If nodejs support [SourceMap](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?hl=en_US&pli=1&pli=1), we'll be very happy. On Browsers, Chrome (19+) supports SourceMap and it works well.
(cf.  [INTRODUCTION TO JAVASCRIPT SOURCE MAPS](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/))

(This ticket might be related to #2537)

**Comment by gsikorski** [comment]
+1 For production server it is nice to browserify + minify the code of the backend as well (even including all node_modules installation), so that it occupies less space. Would be great if node supports printing the stack using provided source map.

**Comment by bnoordhuis** [comment]
Closing, continues in https://github.com/nodejs/node/issues/6471.
