### ISSUE TITLE
windows: EACCES listening on domain socket

### ISSUE THREAD

**Issue by isaacs** [nodejs/node-v0.x-archive#3827]
In a "run as Administrator" command prompt:

```
c:\node-v0.8.5>cat socket-listen.js
var net = require('net');
var path = require('path');

net.createServer(function (socket) {
  socket.end('hello\n');
}).listen(path.resolve('teh-socket'));

c:\node-v0.8.5>node.exe repl-server.js

events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EACCES
    at errnoException (net.js:781:11)
    at Server._listen2.self._handle.onconnection (net.js:904:28)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

Either:

1. Domain sockets are not supported on windows, in which case this fact needs to be documented, and listen() should raise ENOTSUP or ENOSYS instead of EACCES.  Or:
2. This is just broken.

**Comment by jasnell** [comment]
@orangemocha @isaacs ... is this still an issue?

**Comment by joaocgreis** [comment]
Closing, since this is already documented: https://nodejs.org/api/net.html#net_server_listen_path_callback
