### ISSUE TITLE
Nested async callbacks and "domain" error handling

### ISSUE THREAD

**Issue by lancejpollard** [nodejs/node-v0.x-archive#3908]
Say you have some ORM accessing a database asynchronously. If you bind to the callback, the node `require('domain')` module works fine:

``` javascript
var domain = require('domain');

var globalDomain = domain.create();

App.Post.all(globalDomain.bind(function() {
  throw new Error('an error');
}));
```

The issue is, this doesn't work using `run`, because run calls the `bind` function, and `bind` expects it to be async (unless it's a core `EventEmitter` like `process`, so `run` works on `process.nextTick`, not sure how this is working...). So in the following, the error is crashes node because it's not caught:

``` javascript
globalDomain.run(function() {
  App.Post.all(function() {
    throw new Error('an error');
  });
});
```

Because `run` doesn't work here, you might think to just wrap _all_ functions in `globalDomain.bind`, such as this (which does work):

``` javascript
App.Post.all(globalDomain.bind(function() {
  App.Post.all(globalDomain.bind(function() {
    throw new Error('an error');
  })); 
}));
```

The main issue is that the [`Domain#bind` function](https://github.com/joyent/node/blob/master/lib/domain.js#L200) expects the callback to be _synchronous_. Here is where the callback passed to `bind` is called:

``` javascript
self.enter();
var ret = cb.apply(this, arguments);
self.exit();
```

That `Domain#exit` function sets the "active domain" (`exports.active`) to `stack[stack.length - 1]`, which can be empty from what it looks like:

``` javascript
Domain.prototype.exit = function() {
  if (this._disposed) return;

  // exit all domains until this one.
  var d;
  do {
    d = stack.pop();
  } while (d && d !== this);

  exports.active = stack[stack.length - 1];
  process.domain = exports.active;
};
```

If there's only 1 item in the stack, it will `pop` it, so `exports.active` is undefined. This makes it so you can't get use this domain functionality.

Sorry for the rambling, just trying to figure out if this can work. Just realized the error may be b/c of that `var d = stack.pop()`, but initially thought it may be that there should be some callback functionality implemented in the `bind` method, such as:

``` javascript
self.enter();
cb(function() {
  self.exit();
  return ret;
});
```

Then the `bind` or `run` API would require a `done` callback:

``` javascript
globalDomain.bind(function(done) {
  App.Post.all(function() {
    App.Post.all(function() {
      throw new Error('an error');
      // if it never gets here that's fine, uncaughtException will handle it
      done();
    });
  });
});
```

Although looking at it now maybe that would be an easy way to create a garbage collection problem. Hmm... What are your thoughts about this?

**Comment by jasnell** [comment]
@joyent/node-tsc ... any reason to keep this one open?
