### ISSUE TITLE
child_process.spawn with stdio blows up with invalid argument

### ISSUE THREAD

**Issue by davepacheco** [nodejs/node-v0.x-archive#4030]
I expected the following program to be equivalent to "ls > foo.txt":

```
var child = require('child_process');
var fs = require('fs');

child.spawn('ls', [], {
    'stdio': [ null, fs.createWriteStream('foo.txt') ]
});
```

but instead, it blew up:

```
child_process.js:768
      throw new TypeError('Incorrect value for stdio stream: ' + stdio);
            ^
TypeError: Incorrect value for stdio stream: [object Object]
    at child_process.js:768:13
    at Array.reduce (native)
    at ChildProcess.spawn (child_process.js:723:17)
    at Object.exports.spawn (child_process.js:618:9)
    at Object.<anonymous> (/Users/jclulow/dap.js:4:7)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
```

This is on node v0.8.9 on OS X, and I've also seen it on 0.8.4 on OS X and SmartOS.

I imagine this doesn't work because the file descriptor for the underlying stream hasn't been allocated yet.  But the docs for child_process.spawn say this about the "stdio" argument to "spawn":

```
Stream object - Share a readable or writable stream that refers to a tty, file, socket, or a
pipe with the child process. The stream's underlying file descriptor is duplicated in the
child process to the fd that corresponds to the index in the stdio array.
```

It doesn't say anything about the stream having to be open already.  That's probably not an unreasonable constraint, but the docs should probably mention this.

**Comment by jasnell** [comment]
@davepacheco ... a quick test shows that the reported behavior is still in v0.12. Is this still an issue for you? Do we need to keep this open?

**Comment by davepacheco** [comment]
If the behavior and documentation have not changed, it sounds like this is still an open issue.

**Comment by masaeedu** [comment]
Any chance of this being fixed? I think there's also a race if you try to register handlers for the I/O streams *after* invoking `spawn`, so basically anyone trying to run a short-lived process and capture output is SOL.
