### ISSUE TITLE
windows: addons cannot use the bundled OpenSSL

### ISSUE THREAD

**Issue by TooTallNate** [nodejs/node-v0.x-archive#4051]
Basically, on Unix, addons can use functions from node's bundled openssl rather easily. So there's no problem there

But on Windows, the openssl functions are not exported it seems. We explicitly export the libuv symbols for addons to use so it would be nice to do the same for OpenSSL.

This wiki article explains the current state of affairs in more detail: https://github.com/TooTallNate/node-gyp/wiki/Linking-to-OpenSSL

@piscisaureus you, me and @ry talked about this privately over email a while back and thought it was something we should get fixed.

**Comment by jasnell** [comment]
@joyent/node-coreteam @mscdex @orangemocha ... where are we at on this one?

**Comment by mscdex** [comment]
@jasnell I never worked on it, so I really have no idea.

**Comment by LinusU** [comment]
@tjfontaine Do you have any more updated on this? I would love to get this working :)

If there is anything I can do to help I will gladly do so. Unfortunately, I have very limited experience with gyp :(

**Comment by LinusU** [comment]
Ehh, I in no way meant to unassign you from the bug. I don't even have sufficient privileges in this repo to do so. Seems like a bug in github...

**Comment by johnnyman727** [comment]
I'm also happy to help out. Would need some guidance though.

**Comment by jasnell** [comment]
@TooTallNate ... any further thoughts on this one?

**Comment by TooTallNate** [comment]
I still consider it a desirable feature. It would be nice if all the bundled libraries could be linked to by native addons.

But I don't think gyp has the necessary skill for it still, as @bnoordhuis was mentioning above, so not sure what we want to do with this issue.

**Comment by jasnell** [comment]
@TooTallNate ... given that, I'm going to mark this as a `feature-request` and `defer-to-converged`. I'll keep the issue open to future tracking, but it's something that likely won't happen in v0.10 or v0.12 ever unfortunately.

**Comment by vladimir-shcherbakov** [comment]
@TooTallNate, do you have an example/sample of an add-on that can use functions from node's bundled openssl on Linux but not on Windows - I'd like to have a repro to experiment with.

**Comment by TooTallNate** [comment]
@vladimir-shcherbakov Sure, this "works" on OS X and Linux, since `SSLv23_method()` is a function that is used in the Node.js codebase, and thus gets included in the resulting binary:

https://github.com/TooTallNate/node-openssl-addon-example/blob/master/binding.cc

Windows does not currently work with that ^
