### ISSUE TITLE
No way to set TCP keepalive interval

### ISSUE THREAD

**Issue by deanm** [nodejs/node-v0.x-archive#4109]
Currently the TCP keepalive support (socket setKeepAlive) allows an argument to set the initial delay (aka tcp_keepalive_time / TCP_KEEPIDLE), which is implemented in uv__tcp_keepalive.  However there is no support for TCP_KEEPINTVL or TCP_KEEPCNT, which means you cannot change the time between keepalive probes or the number of failed probes before a connection is considered broken.

Is there a reason it was decided to only allow configuration of the initial delay?

**Comment by davepacheco** [comment]
As others have mentioned, this would be pretty useful for us for detecting certain failure modes in networked systems (e.g., a remote system panicked or lost power).  It doesn't have to be instant, but KeepAlive appears to be a fine mechanism for detecting such situations in the order of tens of seconds. (Whether those are false positives is entirely use-case-specific, and it's up to users to configure this to suit their environment.  The docs can always link to appropriate resources on the subject.)

**Comment by hertzg** [comment]
I've written a module using FFI to set those values per connection using the `socket._handle.fd` (which is available only on linux).

https://github.com/hertzg/node-net-keepalive

**Comment by davepacheco** [comment]
I forgot this had not been mentioned earlier: SunOS systems (at least including illumos, and probably Solaris) support TCP_KEEPINTVL and TCP_KEEPCNT in addition to the other parameters mentioned above.  It just translates them appropriately.  No special support should be needed for this platform.
