### ISSUE TITLE
Add statvfs functions to the `fs` module

### ISSUE THREAD

**Issue by mikedeboer** [nodejs/node-v0.x-archive#4151]
A 'missing' feature or binding in the filesystem abstraction, compared to other dynamic language runtimes is statvfs.

I would like to propose the following API:

``` javascript
var fs = require("fs");

var s = fs.statvfsSync("/");
console.log("statvfsSync Free: " + formatSize(s.bfree * s.bsize));
var fd = fs.openSync(__filename, "r", 0666);
s = fs.fstatvfsSync(fd);
console.log("fstatvfsSync Free: " + formatSize(s.bfree * s.bsize));

fs.statvfs("/", function(err, s) {
    if (err) {
        console.log("statvfs error: " + err);
        return;
    }
    console.log("statvfs Free: " + formatSize(s.bfree * s.bsize));
});

fs.fstatvfs(fd, function(err, s) {
    if (err) {
        console.log("fstatvfs error: " + err);
        return;
    }
    console.log("fstatvfs Free: " + formatSize(s.bfree * s.bsize));
});

function formatSize(n) {
    var suffixes = ["b", "kb", "mb", "gb", "tb"];
    var index = 0;
    while (n > 768 && index + 1 < suffixes.length) {
        n /= 1024;
        index++;
    }
    return n + suffixes[index];
}
```

The use case I can think of is reporting the free diskspace of a directory in a WebDAV PROPFIND response (part of the RFC). Right now, I can not display this information without using a terribly slow recursive directory traversal algo that sums the used space of file nodes. Remaining free space is impossible to calculate.

References:
PHP
- http://www.php.net/manual/en/function.disk-free-space.php
- http://nl3.php.net/manual/en/function.disk-total-space.php

Python
- http://docs.python.org/library/os.html#os.statvfs

And there are probably more out there.

**Comment by jasnell** [comment]
@chrisdickinson ... what's the status on this?

**Comment by chrisdickinson** [comment]
I haven't worked on it in a while.
