### ISSUE TITLE
Windows installer sets global bin PATH incorrectly.

### ISSUE THREAD

**Issue by cowboy** [nodejs/node-v0.x-archive#4228]
I witnessed this issue when helping a client install v0.8.14 two days ago:

A number of people (not everyone) downloaded the `.msi` installer from the website. Everything appeared to install fine; both `node` and `npm` were in the path, and runnable.

Running `npm install -g grunt` installed grunt into the correct global location, but `grunt` wasn't available as a command. Upon further inspection, **I noticed that, in the command shell, the `PATH` wasn't set correctly; instead of it containing an entry referencing the user's `%APPDATA%\npm` directory,  it referenced almost the exact same path, but with a _different user name_.**

Maybe the user name belonged to the admin? I don't know; I didn't have time to delve in too deeply.

I had the users run this in their shell, which solved the problem, albeit temporarily:

```
path=%PATH%;%APPDATA%\npm
```

I do know that these users have a managed login system, maybe Active Directory or something similar. Perhaps there's an issue setting the `PATH` correctly in circumstances like this.

I did have them restart their shells to no avail. Restarting their computers was not an option, so I don't know if that would have fixed the issue.

Also, I'm not there anymore, so I don't really have the facility to troubleshoot this further, I just thought you should know that a bunch of Windows users had the wrong `PATH` and that affected the running of globally-installed module bin scripts.

I've done this with them before back when v0.6 was the latest, and we never had this problem. At least, nobody ever complained about it. Maybe a regression was introduced in the installer between v0.6.x and v0.8.x.

**Comment by kriskate** [comment]
I had this problem also, and when typed path into cmd editor, it showed user\Appdata\Roaming\npm with a space before the previous path's '**;**'. 
So I went to environment variables and deleted the space after the **;** .

**Comment by liveorgandonor** [comment]
I'm not sure if this is helpful or not, but I noticed this from [this SO post](http://stackoverflow.com/questions/19135561/grunt-on-windows-8-grunt-is-not-recognized) and thought I'd mention it here: "Apparently, programs that change the PATH environment variable must broadcast a WM_SETTINGCHANGE message. The Windows' System settings window does it correctly when you change the PATH variable, but the NPM installer doesn't. That's why you have to restart explorer (or log off or restart, which has the same effect)."

**Comment by adamveld12** [comment]
![image](https://cloud.githubusercontent.com/assets/2166475/8764448/4550979c-2d9f-11e5-9092-5fda1fa9eb63.png)


![image](https://cloud.githubusercontent.com/assets/2166475/8764452/95e48b5a-2d9f-11e5-98c6-e4d3173fbbb0.png)


As you can see, my $NPM path variable (this is what NPM adds to the system environment variables on windows) is set to a different location than what NPM is installing modules to. I'm using windows 8.1.
