### ISSUE TITLE
os.networkInterfaces() causes slient crash on Windows during interfaces change

### ISSUE THREAD

**Issue by duanyao** [nodejs/node-v0.x-archive#4353]
If the os.networkInterfaces() is called during network interfaces change (add or remove), the node process may crash silently, no exception can be caught, no error message is shown.

This is my test code, just call os.networkInterfaces() repeatedly:

```javascript

var os = require('os');

process.on('uncaughtException', function(err) {
	console.log('uncaughtException: ' + err.stack);
});

function testnic() {
	for(var i = 0; ; i++) {
		try {
			var nics = os.networkInterfaces(); //can crash sliently here?
			if (i % 300 == 0)
				console.log("networkInterfaces :" + JSON.stringify(nics));
		} catch(err) {
			console.log("testnic" + err.stack);
		}
	}
}
testnic();
```
Run this script with node, and plug in and out your ethernet wire (or disconnect/connect your wifi) several times (usually ~ 10 times) , the program will crash silently.

Whether the computer's IP is static or DHCPed is irrevlant.

I have tested node 0.8.6, 0.8.15, and 0.9.3 on Windows 7 32bit, all have this problem.

**Comment by brendanashworth** [comment]
This hasn't been touched in a while, and https://github.com/joyent/libuv/pull/643 says that it fixed this, so I'll close this. Please reopen if I'm mistaken :)
