### ISSUE TITLE
domains: need an upgrade(emitter) method. Can not upgrade implicit emitter to explicit one by just adding it.

### ISSUE THREAD

**Issue by nirandas** [nodejs/node-v0.x-archive#4711]
Here I am running a function in a domain's context. In it I am creating an Emitter which I add to the domain for clean up during disposing. However, add() does not add the emitter because emitter is already bound to the domain implicitly. Hence the dispose() call does not clean up the emitter.

``` javascript
var d = require("domain").create();
var Emitter = require("events").EventEmitter;
var e=null;

d.run(function(){
e = new Emitter();
e.on("test", function(msg){
console.log("got test ", msg);
});

console.log("Members before explicitly adding ",d.members.length , ". should be 0");
d.add(e);
console.log("Members after explicitly adding ",d.members.length, ". should be 1");
});

console.log("disposing");
d.dispose();
//emit test event. no handler should be invoked.
e.emit("test","Should not get this as e was disposed");
```

A work around could be to remove the emitter before adding...

d.remove(e);
d.add(e);

The best way would be to
- add() method also checks if the emitter is in the members array before returning.
  if (ee.domain === this && this.members.indexOf(e) > -1) return;
- Or provide an upgrade(arg1,arg2,...) method to domain which can be used to upgrade implicit emitters to explicit ones.

**Comment by jasnell** [comment]
@nirandas ... is this still an issue for you? Given the scope at which `e` is declared, the code appears to be working as expected.
