### ISSUE TITLE
Not possible to set multicast send interface in dgram module

### ISSUE THREAD

**Issue by kanongil** [nodejs/node-v0.x-archive#4722]
Essentially I need an interface to `setsockopt(socket, IPPROTO_IP, IP_MULTICAST_IF, ...)`.

I can currently work-around this limitation by telling the OS which interface to use for the multicast data, however I need sudo privileges to do this, and would much prefer to specify it through the `dgram` module.

**Comment by jasnell** [comment]
@piscisaureus @joyent/node-coreteam ... was there ever any action on this one? PR doesn't look to have ever landed.

**Comment by austinf** [comment]
The libuv side landed, but not node side

**Comment by jasnell** [comment]
Ok, the node PR appears to be quite a bit out of date. @austinf ... are you interested in updating the PR rebasing against master or v0.12?

**Comment by austinf** [comment]
I'll take a look at it
