### ISSUE TITLE
More useful web socket upgrade API

### ISSUE THREAD

**Issue by isaacs** [nodejs/node-v0.x-archive#4813]
It's inconvenient right now that we automatically upgrade all upgradeable requests and do `server.emit('upgrade', req, req.socket, bodyHead);`
- It presumes that you _want_ to upgrade all upgradeable connections, rather than only some of them.
- There is no way to do `res.statusCode = 403; res.end('Sorry, no websockets for you!')`, since a response object is never created.
- It breaks the assumptions of systems like Restify and Express that want to have a stack of functions doing stuff like auth and such.
- It emits on the server for servers, but on the request for clients.  Kind of odd.
- It prevents the `server.emit('request')` or `request.emit('response')`.

And basically, this is all just to prevent the overhead of creating a response object, which is cheap anyway.

However, changing this interface too dramatically is going to break some stuff pretty badly.

Idea:
- Server:
  1. Change the `'request'` event signature to add the socket as well: `server.emit('request', req, res, socket)`
  2. Do not automatically upgrade requests.  Instead, add `request.upgradeable = true` flag.
  3. If the user calls `req.upgrade()` then unhook all the HTTP machinery, and now it's an upgraded connection.
  4. For backwards compatibility, when the user calls `req.upgrade()`, emit the `'upgrade'` event on the server with the req, socket, and the bit of the body that has already been read in.
- Client:
  1. Change the `'response'` event signature to add the socket as well: `request.emit('response', response, socket)`
  2. Do not automatically upgrade responses.  Instead, add `response.upgradeable = true` flag.
  3. If the user calls `response.upgrade()`, then unhook all the HTTP machinery, and now it's an upgraded connection.
  4. For backwards compatibility, when the user calls `response.upgrade()`, emit the `'upgrade'` event on the request with the response, socket, and the bit of the body that has already been read in.

This should be changed in v0.12.  The `bodyHead` change might not be an issue, if we refactor the parser/etc to take advantage of streams2 more effectively, so that we don't automatically pull everything out of the socket readable stream object.

/cc @substack @jclulow

**Comment by stuartpb** [comment]
Any plans for this to be integrated into node (io.js) next.0? I'm not seeing any pingbacks to this issue apart from nodejs/io.js#550 which seems to addressing a completely different feature.

**Comment by stuartpb** [comment]
Also, to make sure I'm understanding this correctly, this would make it possible to mount WebSocket-based libraries like ws and engine.io as middleware (rather than having to pass them the http server)?

**Comment by miksago** [comment]
From the brief amount I've read on this, it sounds good…
