### ISSUE TITLE
Public flag for ObjectMode

### ISSUE THREAD

**Issue by ForbesLindesay** [nodejs/node-v0.x-archive#5064]
I want to be able to tell whether an arbitrary stream is in Object Mode, as it affects how I choose to handle the stream.

``` javascript
stream._readableState.objectMode
```

seems to do the trick, but I was wondering if it could be made public.  It also could be nicer if it was exposed as `stream.objectMode` or similar.

**Comment by mk-pmb** [comment]
:+1:
