### ISSUE TITLE
readline should provide a way to stop echoing keypresses

### ISSUE THREAD

**Issue by bpytlik** [nodejs/node-v0.x-archive#5092]
As part of my project, I want to take control from readline for a bit to display a stream of data. I can use rl.pause and disable the prompt so that the output looks as desired. However, when the user types a key, the key still shows up on the screen, which is not what's desired. By monkey patching stdout.write, I was eventually able to discover that this was happening because readline was still listening to the "keypress" event (which I couldn't find documentation of). I was only able to achieve what I desired by removing all the listeners to the keypress event and adding my listener in. When I'm done streaming the data, I removed my listener and restored the previously existing listeners.

While I achieved my goals, the steps to get there were not obvious or documented. I'd like to see functionality exposed via a function (stopEcho?) but I could accept better documentation of the keypress event in the readline api.

All of this was done using node 0.8.15.

**Comment by jasnell** [comment]
Going to assume this one is safe to close. Can reopen if new information is received.

**Comment by bpytlik** [comment]
Why was this closed? What new information would you like? The original issue still stands as far as I know which is this:
`
It's hard to dynamically adjust whether keypresses are echoed by readline, and the only way to do so is to use an undocumented interface.
`
If the documentation has been improved or the interface requested has been added, then please include a link to that information. Thanks.

**Comment by jasnell** [comment]
Because I wasn't able to determine if it was still necessary to keep open. We can reopen and mark as a feature request if you'd like.

**Comment by bpytlik** [comment]
Thanks. Please reopen it.

Brock
