### ISSUE TITLE
domain problem

### ISSUE THREAD

**Issue by scgywx** [nodejs/node-v0.x-archive#5168]
Unable to catch exceptions when using shared variables

test case from the url
http://cnodejs.org/topic/51448937069911196d8fbc97

**Comment by jasnell** [comment]
@scgywx ... is this still an issue for you?

**Comment by scgywx** [comment]
@bnoordhuis  @jasnell 
in the latest version, this issue still exists.

in this test case, it had a net connection variable,i use domain wrapped the var,,in the first request, the domain  could catch the exception when the net connection throw error and print the error message.but,in the second request,the domain couldn't catch the exception when the net connection throw error,so the error message can't got.

i expect:
  in the second request can catch the exception.

thx.
