### ISSUE TITLE
Passing an invalid cert/key pair to tls.createServer doesn't generate an error

### ISSUE THREAD

**Issue by tjfontaine** [nodejs/node-v0.x-archive#5190]
If you create a tls socket with an incorrect cert/key pair a generic socket error isn't emitted, but when a client tries to connect a clientError is emitted but not necessarily with enough information for you to take action.

`Error: 140735180325248:error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher:../deps/openssl/openssl/ssl/s3_srvr.c:1355:`

We should be able to detect when a key doesn't match a cert

**Comment by jasnell** [comment]
@tjfontaine ... did anything ever happen with this one? was there a specific test case to reproduce?
