### ISSUE TITLE
configure script fails with empty prefix

### ISSUE THREAD

**Issue by rofl0r** [nodejs/node-v0.x-archive#5197]
``` sh
./configure --prefix=
```

is the canonical way to use the prefix "/" without getting nasty double-slashes everywhere.

with node's configure, it will silently create /local directory structure in the DESTDIR.

**Comment by jasnell** [comment]
@rofl0r ... is this still an issue for you?

**Comment by rofl0r** [comment]
yes. with --prefix= the latest nodejs release creates a /usr/local dir structure in DESTDIR

**Comment by jasnell** [comment]
@misterdjules @orangemocha ... thoughts?

**Comment by orangemocha** [comment]
@rofl0r would passing --prefix=/. work for you?

**Comment by rofl0r** [comment]
that appears rather hackish. is it that hard to check whether --prefix= was passed but the string after the = has length 0 ?

**Comment by orangemocha** [comment]
Not that hard but not that simple either :wink: The makefile invokes a python script, tools/install.py, passing those parameters positionally, so with the current strategy we cannot distinguish zero-length from missing/undefined. We could change the way we pass arguments to instally.py, or simply have it expect all arguments to be present and take the prefix argument as is, without having its own default value for it. 

The tricky part is that I am not sure if there are any tools/people out there using install.py directly that would be affected by this change... but my guess is that it's going to be ok.

I would suggest you open a pull request for it. Given that this a low severity issue with a viable workaround, it's unlikely that the collaborators will get to this with a short turnaround.
