### ISSUE TITLE
Need way to disable REPL ANSI escape codes

### ISSUE THREAD

**Issue by jart** [nodejs/node-v0.x-archive#5344]
The repl.js module needs to be smarter about how it sends ansi escape codes. For example if I run "coffee -i" (a command which uses the standard repl module) inside a dumb terminal that doesn't support ansi escape sequences, I see the following:

```
^[[1G^[[0Jcoffee> ^[[9G
```

This is ugly! Those ansi escape codes are unnecessary. Furthermore the repl module is not respecting the fact that I set NODE_NO_READLINE=1 to try and get rid of those escape codes. Because I'm running the coffee command, I do not have the ability to pass the "terminal: false" parameter to the repl.start() function so I have no way of making these codes go away.

Therefore I propose:
1. If NODE_NO_READLINE is set, repl will not print ansi codes.
2. If process.env['TERM'] is 'dumb' then repl will not print ansi codes.

**Comment by jonslenkooyala** [comment]
I'm running node v0.12.2 on Mac OS X 10.9.5, inside a bash instance inside emacs Ok, make fun of me). I am still getting (color) escape codes, I think??

tmp 509 $ echo $NODE_DISABLE_COLORS
1
tmp 510 $ node -v
v0.12.2
tmp 511 $ node
^[[1G^[[0J> ^[[3G
tmp 512 $ echo $TERM
dumb
