### ISSUE TITLE
use hrtime instead of Date.now for timeouts

### ISSUE THREAD

**Issue by isaacs** [nodejs/node-v0.x-archive#5497]
Semantically, we're doing something like "Do this in 1234ms", rather than "Do this at 10:45:53", so using a wall clock time for this makes hardly any sense.

At least, exposing `uv_default_loop()->now` to JS-land would be a big improvement, since that saves an extra gettimeofday syscall.

**Comment by jasnell** [comment]
@misterdjules ... what is the status on this one?

**Comment by Fishrock123** [comment]
This is fixed in any timers code I've interacted in (e.g. io.js 1.0.0+), everything uses `Timer.now()`.

0.x is EOL, so I think there is nothing left to be done. Closing.
