### ISSUE TITLE
Readline: workaround for #3860 was removed by commit 94284e7d (incorrect prompt on vt control chars)

### ISSUE THREAD

**Issue by OJezu** [nodejs/node-v0.x-archive#5628]
The following code:

``` javascript
var rl = require('readline').createInterface(process.stdin, process.stdout);
rl.setPrompt('\u001b[31m> \u001b[39m', '> '.length);
rl.prompt();
rl.on('line', function(){
        rl.prompt();
});
```

in v0.10.6 will put the cursor in correct position (right after '> '), and will not in v0.11.2 due to second argument of rl.setPrompt being removed.
While I agree that second argument of setPrompt is redundant, it should not be removed until the prompt length calculation handles all cases, vt control chars included.

See issue #3860, commit 94284e7d and pull request #4994 for reference

Also, in v0.10.6 there was some weirdness event when promptLength was provided, due to readline code sometimes referencing this._prompt.length instead of this._promptLenght (line wrap) and this._promptLength being lost after rl.question call

**Comment by jasnell** [comment]
@OhJeez ... is this still an issue for you?

**Comment by OhJeez** [comment]
In v0.12 everything seems ok. In v0.10 there are still problems, as far as I can tell.

**Comment by jasnell** [comment]
@OhJeez ... what is the behavior you are seeing in v0.10? When I run using v0.10.39~pre, the behavior is identical to what I see under v0.12.3~pre.

**Comment by OhJeez** [comment]
In v0.10.38 things get broken with colored prompt when line wraps due to its length. Text does not appear on new line (overwrites bottom-most line), moving cursor and removing text is broken. It's OK in v0.12.3.

I cannot find tag or branch for v0.10.39-pre in repo - I don't know how to test it :confused:
