### ISSUE TITLE
fs.readSync(0, new Buffer(0), 0, 0, 0) throws Error: Offset is out of bounds

### ISSUE THREAD

**Issue by eahutchins** [nodejs/node-v0.x-archive#5685]
Reading 0 bytes into a 0 sized buffer should be a no-op to make it more like read(2):

> If count is zero, read() returns zero and has no other results.

**Comment by jasnell** [comment]
@trevnorris ... any further thoughts on this one?

**Comment by trevnorris** [comment]
@jasnell If it hasn't been fixed yet then should be easy to do. Just need to change the range checks, and return early if the operation is a noop.
