### ISSUE TITLE
IsString checks in node_file.cc are too restrictive...

### ISSUE THREAD

**Issue by MarcusPope** [nodejs/node-v0.x-archive#5714]
As it stands this code won't work in Nodejs

```
var fs = require('fs');
var x = new String("test.txt");
var y = new String("test2.txt");
fs.rename(x, y);
```

I could use standard strings or call .toString() before passing in, but I don't think I should have to (though I'm open to convincing :D).  But it's not always so obvious, for instance in String.prototype functions referencing "this" is also a string object not a string value.  The current behavior requires adding .toString() to every parameter interface for any file/system function calls, which seems un-DRY. 

Perhaps a better IsString check or just always casting toString would be more appropriate in the core?

**Comment by jasnell** [comment]
I'm going to mark this as a confirmed bug as it definitely is surprising behavior. However, fixing it means an API change.
