### ISSUE TITLE
node debug -p fails

### ISSUE THREAD

**Issue by julien51** [nodejs/node-v0.x-archive#5903]
Hello,

We have a _stuck_ node.js process. We suspect it may be due to some kind of infinite loop somwhere. Since we have no idea where to look it up, we tried using node debug -p <pid>. No luck:

```
# node debug -p 13974
connecting.............There was an internal error in Node's debugger. Please report this bug.
connect ECONNREFUSED
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

The output makes me think that the node debug process can't connect to our process precisely because our event loop is stuck. Could that be the case? 
In [another thread](https://github.com/joyent/node-panic/issues), @davepacheco indicates that this should not be a problem:

> That's not a problem. We modified Node back in the 0.4 days to support opening the debugger port even if the Node program itself is stuck in an infinite loop, and V8 is able to evaluate expressions in this context. 

Can someone clarify things? Why are we unable to connect to our "stuck" node.js process? Any idea on how to debug that? (we're on debian... so all tools requiring us to use Solaris won't do :()

**Comment by jasnell** [comment]
@trevnorris @bnoordhuis ... any reason to keep this one open?

**Comment by bnoordhuis** [comment]
I'm fairly sure this is fixed in io.js.  Don't know about joyent/node.

**Comment by jasnell** [comment]
An initial quick test on v0.12 doesn't show any connection error but things are still less than useful. It's worth investigating further.
