### ISSUE TITLE
crypto.pbkdf2 callback is called with error === undefined

### ISSUE THREAD

**Issue by PiusLT** [nodejs/node-v0.x-archive#5931]
[crypto.pbkdf2](http://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_callback) passes-in `undefined` as the error for the callback function. I think, it should be `null` for the sake of consistency.

It is a pretty common practice to pass-in `null` as an `error` parameter in callbacks when everything goes fine. Even [NPM's coding guidelines](https://npmjs.org/doc/coding-style.html#Callbacks-Sync-async-Style) state so.

Many people don't even notice it because they check it like `if (error) { ... }` but some (I believe), like me, prefer checking it `if (error !== null)` because it's a little bit more efficient and strict. Of course, `if (error !== undefined)` works just fine but again, *consistency* comes to mind.

Node version: 0.10.15
OS: Ubuntu 13.04 x64

**Comment by brendanashworth** [comment]
Yeah, I'd say any falsy value is a non-error. This is probably true elsewhere in the codebase, too, so I'm going to close this as a non-issue. If you'd like to pursue it further, you can open a new issue @ https://github.com/nodejs/node.
