### ISSUE TITLE
cluster: implement API for pluggable distribute() for round-robin scheduler

### ISSUE THREAD

**Issue by kaero** [nodejs/node-v0.x-archive#6001]
Looks usefull to provide API in the cluster module to define user own [`distribute`](https://github.com/joyent/node/blob/22c68fdc1dae40f0ed9c71a02f66e5b2c6353691/lib/cluster.js#L161) method.

Something like following:

``` javascript
cluster.setupMaster({
  schedulingPolicy: cluster.SCHED_RR,
  distributeRequest: function() {
    // ...
    return worker;
  }
});
```

Previous discussion with @bnoordhuis in the issue #4435 (after closing)

**Comment by defunctzombie** [comment]
@indutny @bnoordhuis One thing this would help with is users who want to use servers which require "sticky session" like functionality. We have this issue with socket.io users that want to use cluster module. Having access to a distribute method would allow us to support that use case.

While it may be a bit "dangerous" to expose this with certain edge cases, not exposing this or a way to control request endpoints makes cluster unusable for certain  classes of modules which confuses users who expect things shipped with core to work pretty transparently (even tho the docs for cluster do indeed call out sticky session limitations).

**Comment by Fishrock123** [comment]
@defunctzombie +1
