### ISSUE TITLE
Cluster worker.kill(signal) does not pass the signal parameter

### ISSUE THREAD

**Issue by BorePlusPlus** [nodejs/node-v0.x-archive#6042]
When calling worker.kill(signal) and passing a signal, the signal does not get sent to worker process as per documentation. 

http://nodejs.org/api/cluster.html#cluster_worker_kill_signal_sigterm

Example:

``` javascript
var cluster = require('cluster');

if (cluster.isMaster) {
    cluster.fork();

    cluster.on('exit', function(worker, code, signal) {
        console.log('Worker exited:', worker.process.pid);
    });

    setTimeout(function () {
        for (var id in cluster.workers) {
            var worker = cluster.workers[id];
            worker.kill('SIGUSR2');
        }
    }, 2000);
} else {
    process.on('SIGUSR2', function() {
        //WHY DOES THIS NOT GET CALLED? http://nodejs.org/api/cluster.html#cluster_worker_kill_signal_sigterm
        console.log('SIGUSR2 called', process.pid);
    });
    console.log('Worker listening for SIGUSR2', process.pid);
}
```

**Comment by jasnell** [comment]
@sam-github @bnoordhuis ... is this resolved?

**Comment by sam-github** [comment]
Not resolved. `cluster.destroy()` getting renamed to `kill()` still makes no sense. It disconnects before sending the signal to its child, pretty much guaranteeing the signal won't get delivered, or at least will be racy.

**Comment by diegoperini** [comment]
Regarding a workaround, how safe is it to kill a child process via `worker.process.kill()`?

**Comment by sam-github** [comment]
doing so just sends the signal. whether that is "safe" or not just depends on whether the signal does what you want, which is up to your code.  worker.process and its methods are public APIs of worker/cluster, and can be used as doced

**Comment by diegoperini** [comment]
Thank you for the quick response @sam-github
