### ISSUE TITLE
Unchecking "npm" still installs it with .pkg

### ISSUE THREAD

**Issue by tregusti** [nodejs/node-v0.x-archive#6116]
I just downloaded the .pkg installer for v0.10.17 for OSX (on 10.8.4), and unchecked "Install npm" option, but it still said that it installed it, and sure thing, it was added in /usr/local/bin.

``` bash
$ ls -l /usr/local/bin/npm
lrwxr-xr-x  1 glenn  staff  38 23 Aug 20:46 /usr/local/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

The timestamp is from 6 minutes ago.

**Comment by jasnell** [comment]
@tregusti ... I know it's been a while, but is this still an issue for you?

**Comment by Fishrock123** [comment]
this sounds like that problem where the scripts don't even run and PackageMaker just copies the files regardless
