### ISSUE TITLE
forked processes ends socket connection if the child takes too long to load

### ISSUE THREAD

**Issue by williamkapke** [nodejs/node-v0.x-archive#6203]
### The problem:

A forked process `end`s connections when these 2 conditions exist in the `child`:
1) The child process thread takes longer than ~2 seconds to start.
2) The child makes a `http` request.

NOTES:
- This is only happens to the sockets that are given to the `child` before the `child` is done loading.<br>
  UPDATE: Further testing indicates a behavior where it will hangup the connection even after loading has completed.
- I'm running `node v0.10.18` and have not tried on any other versions (yet).
- NODE_DEBUG="net http" didn't reveal anything helpful.
- This is on OSX 10.7.5

[As discussed in the google group](https://groups.google.com/forum/#!topic/nodejs/4_RvoCtTfHg) this may only be an issue on OSX.

I put together a small gist to demonstrate:
https://gist.github.com/williamwicks/6477189

**Comment by jasnell** [comment]
@williamkapke ... unable to verify if this is still an issue because the gist seems to have disappeared. Is this still an issue for you?

**Comment by williamkapke** [comment]
Sry. I had a the username changed. Here's it is updated:
https://gist.github.com/williamkapke/6477189

**Comment by jasnell** [comment]
Ok, I'm seeing the described behavior still on v0.12.3~pre.

**Comment by williamkapke** [comment]
This is a very old issue of mine! @jasnell do you think there is any reason to keep this open on this archive repo? I don't even know if this is still valid. :/

**Comment by cjihrig** [comment]
It looks like this is still an issue on master, although the output from the gist could be clearer :-)
