### ISSUE TITLE
Connection.pipe raises ECONNRESET on afterWrite

### ISSUE THREAD

**Issue by majek** [nodejs/node-v0.x-archive#6211]
So there is this simple server code:
```
var net = require('net');

var server = net.createServer();
server.on('connection', function(c) {
    c.pipe(c);
});
server.listen(10007);
```

And it fails with:
```
events.js:80
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at exports._errnoException (util.js:676:11)
    at TCP.onread (net.js:529:26)
```

I'm using node from git sources:
```
$ cd node
$ git log -1 HEAD^|head -n1
commit 204228b57f06ece34b61d69c5e3b58218bbfed0e
```

To reproduce:

1. start server: `$ node server.js`
2. run client: `$ cat /dev/zero | nc localhost 10007`
3. Ctrl+c client
4. see the traceback

**Comment by brendanashworth** [comment]
I don't think this is a bug. On some systems, writing to a socket after it is closed will trigger an ECONNRESET error. Otherwise, you wouldn't know what happened. I'd suggest adding an `'error'` listener for this sort of thing.

I'll close this, please reopen if you disagree.
