### ISSUE TITLE
inconsistency: should or shouldn't streams destroy consumers when closed?

### ISSUE THREAD

**Issue by jonathanong** [nodejs/node-v0.x-archive#6220]
per https://github.com/joyent/node/blob/master/lib/stream.js#L87, if a stream emits a `close` event, any consumers will be `.destroy()`'d if possible. However, if you use a [Stream.Readable](https://github.com/joyent/node/blob/master/lib/_stream_readable.js#L461), consumers are not destroyed, just `unpipe()`d.

i am not sure if this is by design or not. personally, i would rather have the `pipe` implementations consistent, so either destroy destinations in both or neither, but i much prefer if `close` events propagated.

**Comment by jasnell** [comment]
@trevnorris ... any thoughts?

**Comment by trevnorris** [comment]
This would require a change in functionality in streams. So even if it is implemented, shouldn't land until next minor release.
