### ISSUE TITLE
process.stdout and process.stderr get flushed out-of-order in Windows when piped

### ISSUE THREAD

**Issue by cowboy** [nodejs/node-v0.x-archive#6249]
When `process.stdout` and `process.stderr` are not piped, writes to them are output in order, as written. When piped, they are written out-of-order. While there seems to be a workaround for the draining issue in #3584, I can't figure out a workaround for this issue.

Given this `translation-party.js` file:

``` js
// Test code
var words = "this is a happy test sentence of words".split(" ");

// Test code
for (var i = 0; i < words.length; i += 2) {
  process.stdout.write("[stdout] " + words[i] + "\r\n");
  process.stderr.write("[stderr] " + words[i + 1] + "\r\n");
}
```

In Windows, I see the following behavior.

```
C:\test>node translation-party.js
[stdout] this
[stderr] is
[stdout] a
[stderr] happy
[stdout] test
[stderr] sentence
[stdout] of
[stderr] words

C:\test>node translation-party.js | find "std"
[stdout] this
[stderr] is
[stderr] happy
[stderr] sentence
[stderr] words
[stdout] a
[stdout] test
[stdout] of
```

Can you guys _please_ prioritize fixing these stdio piping issues?

**Comment by Fishrock123** [comment]
Fixed by https://github.com/nodejs/node/commit/20176a98416353d4596900793f739d5ebf4f0ee1 a couple years ago.
