### ISSUE TITLE
'--with-mips-float-abi' doesn't configures the float ABI for node.js

### ISSUE THREAD

**Issue by selina0937** [nodejs/node-v0.x-archive#6315]
I have a mipsel system and I tried to configure

I thus tried to configure with 'with-mips-float-abi=soft' and then make.
I got lots of warnings like below:
/opt/compiler/stbgcc-4.5.3-2.4/bin/../lib/gcc/mipsel-linux-uclibc/4.5.3/../../../../mipsel-linux-uclibc/bin/ld:
Warning: /home/selina/node-v0.10.20/out/Release/node uses hard float,
/home/selina/node-v0.10.20/out/Release/obj.target/deps/v8/tools/gyp/libv8_nosnapshot.a(snapshot-empty.o) 

No make errors. 
And after 'make install', I execute './node hello.js'
I got 'illegal instruction' error.

**Comment by jasnell** [comment]
@selina0937 ... I know it's been a while, but is this still an issue for you?
