### ISSUE TITLE
unbuildable on diskstation DS211+, need ARM patch ?

### ISSUE THREAD

**Issue by Paul-Antoine** [nodejs/node-v0.x-archive#6377]
When I build node on my DS211+ I got the same error as this old issue:
https://github.com/joyent/node/issues/4584 
As the V8 engine was updated is it needed to apply the ARM patch again ?
Thank for you help
Paul-Antoine

**Comment by jasnell** [comment]
@Paul-Antoine ... I know it's been a while, is this still an issue for you?
