### ISSUE TITLE
Should lstatSync return execute bit on directories for Windows?

### ISSUE THREAD

**Issue by juj** [nodejs/node-v0.x-archive#6381]
Consider the following code:

```
var fs = require('fs');
var s = fs.lstatSync('.');
console.log(s.mode);
```

On Windows, when I save this to a file in a directory in which my current user has full permissions (right-click on the directory -> Properties -> Security -> my username has checkboxes Full Control, Modify, Read & execute, List folder contents, Read and Write), and run it with node.js, I get a return value of 16822, which corresponds to "rw-rw-rw". On linux, if I do the same on a directory that has full 0777 chmod, I get 16895, which is "rwxrwxrwx" as expected.

Shouldn't lstatSync (and its variants) Windows give execute bit on the directory that the current user has full permissions in as well? Or does it have some other special reserved meaning on Windows?

**Comment by cookch10** [comment]
+1

Running _fs.stat on a directory or file created with node with the mode parameter set to 0777 returns a mode value of 16822, equivalent to 0666 octal.
