### ISSUE TITLE
Aborted unbinded ClientRequests stays on Agent queue and close sockets

### ISSUE THREAD

**Issue by jmendiara** [nodejs/node-v0.x-archive#6493]
node v0.11
 When the Agent reach the maxSockets limit, new requests are pushed to the `Agent.requests[name]` list. At that time, there is not any socket/connection attached to the request. 

If I externaly 'abort' the request, the requests stays in the list and when a socket becomes available, is processed. Then, cause `ClientRequest.abort` makes a 
`this._deferToConnect('destroy', []);` the socket is destroyed when assigned to the request, when it should be available to other pending request.

2 undesired behavior arises: one request waiting that never will be executed, and an unneeded socket close.   

Maybe could be solved with a new 'abort' event? As the `abort` API is not Stream one, makes sense for me to have this event also on ClientRequest

**Comment by jasnell** [comment]
@trevnorris ... did you ever get around to looking at this?

**Comment by trevnorris** [comment]
nope. don't even remember this one.

**Comment by jasnell** [comment]
@jmendiara ... I know it's been a while, is this still an issue for you? If so, would you be able to provide a test case that demonstrates the problem?
