### ISSUE TITLE
vm: memory leak in vm.runInNewContext

### ISSUE THREAD

**Issue by crosleyj** [nodejs/node-v0.x-archive#6552]
There is a memory leak in vm.runInNewContext. If you call it in a loop your machine will quickly run out of memory. It can be reproduced with the code below. Run with "node --trace-gc"--trace-gc-verbose to see garbage collection start to have problems. Running a few processes with the code below will likely cause your box to stop working when it runs out of memory. Use "top" in another console to see the memory usage quickly go up.

We have a use case where we want to use vm.runInNewContext on each request to a web service, so we quickly run out of memory and the service stops working under load.

We are running node v0.10.18.

```
var vm = require('vm');

var i = 0;
while (true) {
    i++;
    console.log(process.pid + ' still running ' + i);
    vm.runInNewContext('helpers="hello"');
}
```

**Comment by andreialecu** [comment]
+1 

Note that this also occurs with `runInContext()` even if you reuse the same context that was created just once. 

`runInThisContext()` however has no issues.

**Comment by astoilkov** [comment]
+1 for the issue. The solution for deployd does not work for me because I am executing a script that is assigning a global variable and then is not using this to reference it:
```javascript
this.newValue = 'value';

// fails with newValue is not defined
console.log(newValue);
```

**Comment by andreialecu** [comment]
I'm not sure what issue you are referring to? This was fixed with https://github.com/deployd/deployd/commit/578bd28d0feee81caa1bcb7045c259b8e0d44797

If you want to use variable and functions you can now use `requires`. Make a `.js` file somewhere, reference it in your event script with a `requires` call, then call functions. It should all work.

**Comment by astoilkov** [comment]
My problem is that I am executing a client-side JavaScript code using runInContext which is leaking about 1 MB every time i call runInContext. I am creating browser variables like window and document in the context. I am not aware of another solution which could run the code in a context where window and document could be available in the global context and in the same time the Node.js global scope to not be accessible.

```javascript
function executeCode(browserEnv, html, code) {
  var context = vm.createContext(browserEnv.getObject());
  var script = vm.createScript(code);

  extend(context, {
    server: {
      html: html,
      data: {},
      rendered: '',
      applications: []
    }
  });

  script.runInContext(context);

  return context.server.rendered;
}
```

Tell me if you need more information on the problem.

**Comment by andreialecu** [comment]
@astoilkov Sorry, I got confused about what issue this project is in. :)

If this is a blocking bug or you and you can use io.js instead of node, it should have this fixed, see here: https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#vm

**Comment by jasnell** [comment]
@joyent/node-coreteam ... looks like a fix may have gone into io.js. We may want to investigate further and backport

**Comment by viking** [comment]
This is still a problem with Node 4 and 5. Any updates?

**Comment by viking** [comment]
Here is a test script:

``` javascript
var vm = require("vm");

function run(index) {
  var context = vm.createContext();
  vm.runInContext("1+1", context);
  console.log("run " + index + ":", process.memoryUsage().heapTotal);
}

for (var i = 0; i < 20; i++) {
  run(i);
}
```

**Comment by viking** [comment]
Sorry, just realized this project was archived. I'll look in the new project.

**Comment by ChALkeR** [comment]
Is this issue the same as https://github.com/nodejs/node/issues/3113 + https://github.com/nodejs/node/issues/1741?
If so, I guess that this could be closed and discussion moved there.
