### ISSUE TITLE
child_process: stdout data is lost if not read quick enough

### ISSUE THREAD

**Issue by malern** [nodejs/node-v0.x-archive#6595]
Unread data that is still in the child_process stdout stream when the process exits seems to be deleted. So if you attempt to read the data after the process has exited then the read() function returns null rather than the expected data.

For example, the following code always gets null from proc.stdout.read(), even though the child process is actually outputting data.

``` javascript
var proc = require('child_process').spawn('ls');

proc.stdout.on('readable', function() {
    console.log('readable');

    setTimeout(function() {
        while (true) {
            var data = proc.stdout.read();
            console.log('read: '+data);
            if (data == null) { break; }
        }
    }, 1000);
});
```

The problem here is this means you must read the data as quickly as it's produced, so there's no opportunity to put back pressure on the stream.

version: 0.10.22-linux-x64

**Comment by jasnell** [comment]
@trevnorris ... any thoughts on this one?

**Comment by trevnorris** [comment]
I think there was a libuv patch that went in recently that helped with this.
