### ISSUE TITLE
http: allow response.cork()/uncork()

### ISSUE THREAD

**Issue by trevnorris** [nodejs/node-v0.x-archive#6622]
It might have been an oversight, but right now user's can't do:

``` javascript
http.createServer(function(req, res) {
  res.cork();
  res.write('hello, ');
  res.end('world');
});
```

This seems like a necessary API.

Also, internally `OutgoingMessage#write()` will `cork()`/`uncork()` just before and after a write in specific cases. This is pretty useless since it's still only sending a single chunk of data. It probably needs to be removed.

Pretty straight forward change. Going to assign this to myself.

**Comment by bsnote** [comment]
Will `req.socket.cork()` do the trick?
