### ISSUE TITLE
Potential Memory leak in either NET or HTTP

### ISSUE THREAD

**Issue by naegelin** [nodejs/node-v0.x-archive#6625]
I'm re-submitting this test case below as #6598 had other issues and was closed. 

When running a much larger version of this script we found a memory leak that would clog up the entire available memory of the machine (32 gigs). We decided to trim it down and try to replicate the memory leak. With the minimal script below, the same behavior is witnessed. The script is just a basic "proxy" for HTTPS CONNECT requests(http://nodejs.org/api/http.html#http_event_connect).

We are **ONLY sending HTTPS CONNECT requests as part of our testing - this is as basic as we could get it, and as far as we can tell we're not throwing any CONNECT requests at it that would cause exceptions (such as EADDRINFO errors or similar) and if an exception were to occur the process hopefully will just die (if I understand node correctly).

We throw a fair number of clients (2000-3000) making connections at it for a period of N time (5 minutes is fine) and watch the memory utilization grow and grow. Let the connections die off, and witness no change in memory utilization.

``` javascript
var url = require('url'),
net = require('net'),
http = require('http');

var server = http.createServer(function (req, res) {
});

server.on('connect', function(req, socket, head) {
  var parts = req.url.split(':', 2);
  // open a TCP connection to the remote host
  var conn = net.connect(parts[1], parts[0], function() {
    // respond to the client that the connection was made
    socket.write("HTTP/1.1 200 OK\r\n\r\n");
    // create a tunnel between the two hosts
    socket.pipe(conn);
    conn.pipe(socket);
  });
});

server.listen(3333);
```

**Comment by jasnell** [comment]
@naegelin ... I know it's been a while, but is this still an issue for you?
