### ISSUE TITLE
Make fs.watch recursive actually useful

### ISSUE THREAD

**Issue by paulmillr** [nodejs/node-v0.x-archive#6655]
0.11 adds support for recursive fs watcing with fsevents.

This is great, except that even with the change `fs.watch` is useless crap as it was before. There are just two events that are triggered randomly: `change` and `rename` (even for deletion / creation)

Can we make it more useful at least when it's in fsevents mode?

FSEvents callback should return `flags` (`FSEventStreamEventFlags`) property. Flags are super useful — we can tell all sorts of things by them. Whether it was created, modified, deleted, whether it was a file or dir or a symlink, whether it was renamed or its finder attr was changed. Like this:

``` javascript
function getFileType(flags) {
  if (kFSEventStreamEventFlagItemIsFile & flags) return 'file';
  if (kFSEventStreamEventFlagItemIsDir & flags) return 'directory';
  if (kFSEventStreamEventFlagItemIsSymlink & flags) return 'symlink';
}
```

So, **tl;dr**: Introduce `flags` integer argument that is returned when watching through `fs.watch`

**Comment by jasnell** [comment]
@indutny @trevnorris ... was there ever any resolution on this one?

**Comment by paulmillr** [comment]
@jasnell I don't think there was any resolution. The way to do this now is to stick to 3rd party file watchers — chokidar etc.

**Comment by jorangreef** [comment]
@jasnell There is actually a pull request which has been waiting in libuv to add full recursive support to Windows. It needs a few tweaks and review. It would be great if this could be finished.

Recursive support is especially needed on Windows as the watch locks the watched directory (i.e. it's not possible to setup a tree of watches).

With recursive support on Mac and Windows, it will finally be possible to build a much better third party watch module (using a tree of watches for Linux + increasing the system watch limit). Most of the modules currently rely on scanning and this requires keeping the whole watched tree in memory.

**Comment by jorangreef** [comment]
https://github.com/libuv/libuv/pull/198

**Comment by jasnell** [comment]
Ok, going to mark this as a defer to the converged repo, then. Will keep this open, however.

**Comment by jorangreef** [comment]
Thanks.
