### ISSUE TITLE
net: memory retention with unwritten data to destroyed client

### ISSUE THREAD

**Issue by trevnorris** [nodejs/node-v0.x-archive#6719]
This script will continue to grow in memory usage indefinitely. Running `gc()` doesn't prevent growth.

``` javascript
var net = require('net');

var PORT = 8000;
var str = (new Array(1024)).join('a');
var cntr = 0;
var conn;

var s = net.createServer(function(c) {
  conn = c;
  cntr++;

  for (var i = 0; i < 1e2; i++)
    c.write(str);

  s.getConnections(function(err, cnt) {
    if (err)
      throw err;
    if (cnt > 1)
      throw new Error('more than 1 connection');
  });

  cycleConnection();
});

s.listen(PORT, cycleConnection);

function cycleConnection() {
  if (conn)
    conn.destroy();
  conn = net.connect(PORT);
}

setInterval(function() {
  process._rawDebug('total connections: ' + cntr);
}, 2000);
```

/cc @tjfontaine This is probably your area of expertise. :)

**Update**: What I'm seeing is that while there is never more than 1 client/server connection alive, the number of total connections increases up to the maximum number of open file descriptors then CPU usage drops to 0. All messages that were queued to be written, but weren't, are retained. Other services can still connect and receive the message from the server, but memory usage still doesn't drop.

Going to investigate where that memory is chilling.

**Comment by jasnell** [comment]
@trevnorris ... was there any further activity on this?

**Comment by trevnorris** [comment]
@jasnell I never figured out what was going on. The original script still fails hard while using a lot of memory.
```
$ /usr/bin/time iojs /tmp/s.js 
total connections: 2667
...
total connections: 26778
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: connect EADDRNOTAVAIL 127.0.0.1:8000 - Local (127.0.0.1:0)
    at Object.exports._errnoException (util.js:843:11)
    at exports._exceptionWithHostPort (util.js:866:20)
    at connect (net.js:824:14)
    at net.js:952:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
Command exited with non-zero status 1
11.96user 11.43system 0:21.35elapsed 109%CPU (0avgtext+0avgdata 1922048maxresident)k
0inputs+0outputs (0major+503929minor)pagefaults 0swaps
```
When that crashed it was using 1.83 GB of memory. This happens with latest node and latest iojs.

@indutny Since this also affects io.js, want to take another look? :)
