### ISSUE TITLE
Windows: Error Spawning Process That Requires Elevated Privileges

### ISSUE THREAD

**Issue by Jeff-Mott-OR** [nodejs/node-v0.x-archive#6797]
When UAC is on:

```
require('child_process').spawn('regedit');
```

This will throw `Error: spawn Unknown system errno 740` (ERROR_ELEVATION_REQUIRED). Is this expected behavior? I would think this should trigger Windows to prompt the user for elevated privileges rather than kill the script.

**Comment by timmarinin** [comment]
@cjihrig: so, apparently this issue should be closed.

**Comment by cjihrig** [comment]
Heh, thanks.
