### ISSUE TITLE
Feature request: partial reading option in .readFile / .readFileSync

### ISSUE THREAD

**Issue by Mithgol** [nodejs/node-v0.x-archive#6805]
Sometimes a file starts with a fixed header of a known size, and that header is the only interesting part of that file to be read.

(That's how [`file(1)`](http://unixhelp.ed.ac.uk/CGI/man-cgi?file) or “[MIME magic](http://httpd.apache.org/docs/2.2/mod/mod_mime_magic.html)” happens, for example.)

Is it possible to implement a support for this task? Imagine a new option in the `options` object passed as the second argument to [`.readFile`](http://nodejs.org/docs/latest/api/fs.html#fs_fs_readfile_filename_options_callback) or [`.readFileSync`](http://nodejs.org/docs/latest/api/fs.html#fs_fs_readfilesync_filename_options).

That option (named `limit` or similarly) should contain an integer value (a number of bytes). When it appears, it should prevent the file from being read entirely and instead only the given number of bytes would be read (or less, if the file is actually even shorter).

I suppose this change is backwards compatible with the current `fs` API, and thus suitable for a `Stability: 3 - Stable` core module.

The question is: would it make a good and simple addition to the core, or is it a feature that should stay in the userland?

**Comment by tinybug** [comment]
@trevnorris `var buf = new Buffer(end - start);` should be `var buf = new Buffer(end - start + 1);` and `fs.readSync(fd, buf, 0, end - start, start);` should be `fs.readSync(fd, buf, 0, end - start + 1, start);`. If start = 0, end = 1, the length is 2.

**Comment by Mithgol** [comment]
Would it be appropriate for me to reintroduce this reature request in the newest repository of Node.js?
