### ISSUE TITLE
cpplint is silent about things @indutny complains about

### ISSUE THREAD

**Issue by ghost** [nodejs/node-v0.x-archive#6853]
It is apparently quite easy to create changes that are styled reasonably and pass cpplint but will result in style-related review comments.  See for example the commentary in joyent/node#6851.  This kind of aggravation on both sides could be easily avoided by adjusting the cpplint target to enforce whatever style standards reviewers expect.

**Comment by jasnell** [comment]
@tjfontaine ... was there ever any progress on this?
