### ISSUE TITLE
util.inspect() on process.config() and os.networkInterfaces() contains escaped line breaks "\n" 

### ISSUE THREAD

**Issue by HansHammel** [nodejs/node-v0.x-archive#6943]
1. problem:  log entries contain "\n" instead of line breaks 
2. problem: while on windows, line break should be "\r\n"

reproduced like so:

```
Logger.info('PROCESS: ' + util.inspect(process.config, {
  showHidden: false,
  depth: null,
  colors: false,
  customInspect: false
}));
```

outputs in log file:

```
{"level":"info","message":"PROCESS: { target_defaults: \n   { cflags: [],\n     default_configuration:      [...]
```

should be:

```
{"level":"info","message":"NETWORK: { target_defaults: 
   { cflags: [],
     default_configuration:      [...]
```

Logger is a Winston File Logger
while e.g. `util.inspect(process.memoryUsage()));` and others are fine, the output of `util.inspect(os.networkInterfaces())` and `util.inspect(process.config())` are broken (^)

Maybe a Winston problem (Winston uses unix line breaks only) !?

**Comment by jasnell** [comment]
Marking this as a feature request as it does not actually appear to be a bug. Rather, the discussion aims towards making the line length configurable somehow.
