### ISSUE TITLE
http: master ignores createConnection arg to http.request()

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/node-v0.x-archive#7014]
I touched on this in #7012 but I'll report it as a separate bug so it doesn't get snowed under.

``` javascript
var http = require('http');
var net = require('net');

http.createServer(function(req, res) {
  this.close();
  res.end();
}).listen(8000, '127.0.0.1', function() {
  http.get({ agent: false, createConnection: createConnection });
});

function createConnection() {
  return net.createConnection(8000, '127.0.0.1');
}
```

Works with v0.10 but always fails with ECONNREFUSED with master because apparently it ignores the createConnection property:

```
$ v0.10/out/Release/node t.js

$ master/out/Release/node t.js 

events.js:82
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:683:11)
    at Object.afterConnect [as oncomplete] (net.js:950:19)
```

It's also kind of silly that you need to set `{ agent: false }` in order for the http client library to pick it up.  If you specify a createConnection argument, then you don't want node to ignore that.

**Comment by jasnell** [comment]
@bnoordhuis @indutny ... I note that the reported behavior still happens in v0.12. Did you have any further thoughts on this? Do you happen to know if any further investigation happened?

**Comment by bnoordhuis** [comment]
Not that I'm aware of.
