### ISSUE TITLE
net: unref() is not persistent

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/node-v0.x-archive#7077]
```javascript
var net = require('net');
var server = net.createServer();
server.unref();
server.listen();
net.connect(server.address().port).unref();
```

It hangs because of the unref() that comes before listen() and the one after connect().  In that vein:

```javascript
require('net').connect(42).unref();
```

It fails with ECONNREFUSED because the unref() is a no-op.  The expected behavior for both scripts is that they simply quit.  Affects v0.10 and master.

The documentation doesn't mention when it's okay to call unref().  For the sake of user friendliness, net.Socket and net.Server should remember the ref state and retroactively apply it when the handle is created.  Probably applies to other handle types as well.

**Comment by cjihrig** [comment]
https://github.com/nodejs/io.js/commit/85d99830096a48b7d50cc3b0e5c3fba4172c2d02 just landed. It can either be ported, or we can close this and pick up the changes in the converged branch.
