### ISSUE TITLE
share TLS sessions in HTTPS client agent

### ISSUE THREAD

**Issue by othiym23** [nodejs/node-v0.x-archive#7113]
TLS session creation is expensive in high-load scenarios (like SSL termination on load balancers). It would be very useful for core to offer an option on the agent to pool TLS connections or otherwise minimize session creation for clients that are going to be sending lots of SSL traffic to a specific host. This can be worked around with a custom Agent, but it's a common enough use case (and has a small enough API surface) that it would be worth the effort to bring into core.

**Comment by jasnell** [comment]
@othiym23 @indutny ... any further thoughts on this?

**Comment by indutny** [comment]
Going to take a look.

**Comment by indutny** [comment]
Fix is here: https://github.com/nodejs/io.js/pull/2228
