### ISSUE TITLE
[domain] [feat-req] domain.run function with parameters

### ISSUE THREAD

**Issue by micnic** [nodejs/node-v0.x-archive#7193]
It would be great to be able to define the parameters for the function that is called inside the `domain.run(fn)` method.

I propose this API change:
`domain.run(fn, [arg1], [arg2], [...])`

An example of use:
```javascript
function justDoSomething(a, b, c) {
    /* do something else */
    return a + b + c;
}

mathDomain.run(justDoSomething, 1, 2, 3);
```

This approach would allow to use values from the current context and run a function that is outside of this context as it is implemented in `setTimeout()` or `setInterval()`.

**Comment by brendanashworth** [comment]
This was implemented in https://github.com/nodejs/node/pull/15, and won't be backported to v0.x, so I'll close this.
