### ISSUE TITLE
http: setTimeout() should use .once('timeout')

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/node-v0.x-archive#7297]
IncomingMessage#setTimeout(), OutgoingMessage#setTimeout(), etc. should use `socket.once('timeout', cb)` instead of `socket.on('timeout', cb)`.

That makes it possible to rearm the timeout without having to resort to `req.socket.removeListener('timeout', cb)` and importantly, it avoids memory leaks when the timeout callback is a closure that's captured a big environment.

Affects v0.10 and master.

**Comment by jasnell** [comment]
@cjihrig ... how did this one end up?

**Comment by cjihrig** [comment]
The issue is probably still valid. I closed the PR I had for it, and never got around to updating it.

**Comment by jasnell** [comment]
@cjihrig ... how would you classify this? bug or feature request / improvement? Should we do this in v0.10 and v0.12 or defer?

**Comment by cjihrig** [comment]
@jasnell it is an enhancement. It's not really a bug, and it doesn't add new functionality.
