### ISSUE TITLE
0.11.12 vs. 0.11.11: console output visually truncated on process.exit(0) after console.log()

### ISSUE THREAD

**Issue by rse** [nodejs/node-v0.x-archive#7314]
I don't know whether it is intentional or a bug, but I noticed a small nasty difference between 0.11.11 and 0.11.12 (which occurred for me when, during debugging, I printed something and stopped processing just after the printing):

<pre>
$ cat test.js 
var txt = "";
for (var i = 0; i &lt; 10*1024; i++)
    txt += "X";
console.log(txt);
process.exit(0);
$ /usr/opkg/bin/node --version
v0.11.12
$ /usr/opkg/bin/node test.js
XXXXX[....output of just 1KB of text...]XXXXX
$ /openpkg/bin/node --version
v0.11.11
$ /openpkg/bin/node test.js
XXXXX[...output of all 10KB of text...]XXXXX
</pre>

This is under FreeBSD 9, BTW.
Seems like under Node 0.11.12 there is a difference when it comes to the console buffering. Interesting is that on stdout itself (on redirecting the output) both Node versions really output the 10KB of "X". But with Node 0.11.12 on process.exit(0) after console.log() the console (a Mac OS X terminal here) deterministically stops showing the output after about the 1KB while with Node 0.11.11 it always outputs the whole stdout content. 

Strange. Perhaps you have a clue what difference in Node 0.11.12 introduced this new behaviour...

**Comment by jasnell** [comment]
@rse ... is this still an issue for you?
