### ISSUE TITLE
maintain a node-tick-processor; install it along with header files or binaries

### ISSUE THREAD

**Issue by othiym23** [nodejs/node-v0.x-archive#7332]
It's sort of arcane figuring out how to find the correct version of `node-tick-processor` that works with the binary you have installed, so frequently you have to grab a copy from some random repo or module and then hack it up to work properly with your version. The profiler is useful enough and this interface is frangible enough that it's worth the effort to make this a part of core and have it installed as part of the standard installer process.

/cc @sh1mmer

**Comment by brendanashworth** [comment]
This was done in https://github.com/nodejs/node/pull/2090, closing.
