### ISSUE TITLE
fs.lchown not available on Linux

### ISSUE THREAD

**Issue by snoack** [nodejs/node-v0.x-archive#7382]
`fs.lchown` is implemented as `fchown(open(path, O_SYMLINK), ...)` and therefore only avialable on Mac OS X. However Linux doesn't have `O_SYMLINK` but [`lchown`](http://linux.die.net/man/2/lchown).

Also I'm not sure what happens when you run `open(path, O_SYMLINK)` on a directory on Mac OS X, but on other UNIX systems you get `EISDIR` when attempting to open a directory.

**Comment by jasnell** [comment]
@joyent/node-tsc ... thoughts?
