### ISSUE TITLE
streams: synchronous unpipe() causes data stalls

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/node-v0.x-archive#7451]
Test case:

```javascript
var assert = require('assert');
var stream = require('stream');

var a = new stream.Duplex;
var b = new stream.Writable;
var chunks = [];

a._read = function() {};
a._write = a.push.bind(a);
b._write = chunks.push.bind(chunks);

a.pipe(b);
a.write('ping');
a.unpipe(b);

process.on('exit', function() {
  assert(chunks.length > 0);
});
```

The unpipe() stops the data from propagating down the chain.  That's problematic because I, as a streams2 user that gets slotted somewhere in the chain of handlers, don't know if or when unpipe() gets called.

The observable behavior is that sometimes your pipeline stalls without a clue why.  It took me long enough to debug so I strongly doubt that an average user could figure it out.

Affects v0.10, works with master (fortunately.)  Frankly, I'm amazed and not a little appalled that such a basic bug managed to sneak in. :-/

/cc @indutny - it's really an @isaacs bug but he's inactive, you're not and after Isaac you know the most about streams2.

**Comment by jasnell** [comment]
@bnoordhuis ... do you know if anything progressed on this? testing on v0.12 and io.js shows the assertion still failing.

**Comment by bnoordhuis** [comment]
I can confirm it's still broken (broken again in the case of v0.12, it used to work in v0.11.)

**Comment by bnoordhuis** [comment]
Closing, continues in https://github.com/nodejs/node/issues/6890.
