### ISSUE TITLE
Autocompletion in debugger is extremely slow

### ISSUE THREAD

**Issue by IonicaBizau** [nodejs/node-v0.x-archive#7458]
Autocompletion in debugger is extremely slow:

![](http://i.imgur.com/Uz8yVvB.gif)

The value of `jointDbReq.query` was showed about 1 minute...

Why is this happening?

**Comment by IonicaBizau** [comment]
Any progress on this issue?

**Comment by jasnell** [comment]
@IonicaBizau ... is it possible to provide a simple test case that reliably demonstrates the issue?

**Comment by IonicaBizau** [comment]
@jasnell Sure!

```js
require("http").createServer(function (req, res) {
    debugger
}).listen(8000);
```

Just create a big object. In this example we can choose `req` or `res`.

Run the process:

```sh
$ node debug script.js
```

And then do:

```sh
$ curl localhost:8000
```

The debugger will be triggered. Write `req.` and press <kbd>Tab</kbd>. On a powerful machine (16 GB RAM, Intel Core i7 processor, 120GB SSD) it is still slow: ~3sec.

Where is the code which shows the autocompletion suggestions?

**Comment by jasnell** [comment]
Thanks! I'd have to investigate a bit more to say for sure what's happening. I'll assign this to me and try to get to it as soon as possible.

**Comment by IonicaBizau** [comment]
@jasnell Do you have any updates on this?

**Comment by jasnell** [comment]
Not yet but haven't forgotten. I've got a long list of items I'm working
through.

**Comment by IonicaBizau** [comment]
I opened this in the new node repository: https://github.com/nodejs/node/issues/2875
