### ISSUE TITLE
Referencing process.stdin causes EPIPE

### ISSUE THREAD

**Issue by mafintosh** [nodejs/node-v0.x-archive#7481]
I recently ran in to this very strange bug. I have a node program that produces a decent amount of output to stdout. When I piped it to another another program it would start failing with `EPIPE`. After some debugging I found out that the `EPIPE` was caused by a reference to `process.stdin`.

To illustrate the problem I've boiled it down to the following test-case.

``` js
var stdin = process.stdin; // this line breaks things

var buf = new Buffer(512);
var cnt = 0;

buf.fill(97); // fill it with 'a' for nicer output

setInterval(function() {
    console.log(buf.toString()+' #'+(cnt++));
}, 5);
```

Save the above program as `example.js` and run

```
node example.js | cat -
```

The program fails almost instantly with

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

**BUT!** If we remove `process.stdin` from the start of the program:

``` js
var buf = new Buffer(512);
var cnt = 0;

buf.fill(97);

setInterval(function() {
    console.log(buf.toString()+' #'+(cnt++));
}, 5);
```

And rerun the example the program keeps running without errors and produces a lot of output.

Is this intended behaviour? After a bit of digging I noticed that `process.stdin` is actually a getter which is probably why I'm seeing the weird side effects.

**Comment by Fishrock123** [comment]
I can't repo this (using macOS 10.10.5) on `master` or `0.10.48` either. It is possible there was a streams bug that was fixed, or perhaps there was a bug between your specific terminal version and `cat`.

(This error usually points to the `fd` being closed IIRC.)
