### ISSUE TITLE
repl: String objects are printed as a key/value dictionary

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/node-v0.x-archive#7518]
```
$ node
> new String('abc')
{ '0': 'a',
  '1': 'b',
  '2': 'c' }
```

Only affects v0.10, master prints it as `[String: 'abc']`.  With v0.10, trying to print a a large String object will bring down the REPL.

**Comment by brendanashworth** [comment]
I don't think this was ever backported - but according to our [current LTS guidelines](https://github.com/nodejs/LTS), only "critical bugs" are backported to maintenance lines (which is 0.10), so I'm going to close this for now as not applicable anymore.
