### ISSUE TITLE
Use of domains crashes program if `undefined` is thrown

### ISSUE THREAD

**Issue by fresheneesz** [nodejs/node-v0.x-archive#7550]
This demonstrates the problem:

```
var domain = require('domain').create

var d = domain()
d.on('error', function(err) {
    console.log('wut') // never gets here
})

d.run(function() {
    setTimeout(function() {
        throw undefined
    },0)
})
```

Instead of getting a console log 'wut', I get the following output:

```
node.js:237
        er.domain = domain;
                  ^
TypeError: Cannot set property 'domain' of undefined
    at process._fatalException (node.js:237:19)
```

Some bug in my code was causing it to throw undefined instead of a useful error, but that doesn't mean domains should crash because of it (obscuring the information that would have much more quickly lead to finding the mistake).

I'm using node v0.10.26 on windows 7 64 bit

**Comment by fresheneesz** [comment]
What's the status on this? This is still happening in node v0.10.29

**Comment by fresheneesz** [comment]
+1 for backporting - i just ran into this again

**Comment by Mithgol** [comment]
Node 0.12.0 (stable) is [released](http://blog.nodejs.org/2015/02/06/node-v0-12-0-stable/) and it is likely to contain this change.
