### ISSUE TITLE
allow recursive/nested ticks

### ISSUE THREAD

**Issue by eghteentwelve** [nodejs/node-v0.x-archive#7555]
Please allow for recursive/nested ticks, i.e. functions registered with process.nextTick(). Specifically I'm talking about modifying below node.cc code to remove in_tick guards:

``` cpp
if (tick_info->in_tick()) {
  return ret;
}

// …

tick_info->set_in_tick(true);

env->tick_callback_function()->Call(process, 0, NULL);

tick_info->set_in_tick(false);
```

I'm asking this to enable correct operation of add-ons utilizing libuv nested loops. If this request cannot be done, please explain how recursive/nested ticks can happen today in user-land or, perhaps, it's only an issue in node-core?

many thanks

**Comment by jasnell** [comment]
@vkurchatkin ... any further thoughts on this?

**Comment by vkurchatkin** [comment]
@jasnell I want to return to https://github.com/joyent/node/issues/7323 once worker threads land. Not sure if it addresses OPs problems, but I think it is as close as we can get

**Comment by jasnell** [comment]
Ok, marking this as a defer to converged then
