### ISSUE TITLE
requiring a script with certain errors confuses the repl

### ISSUE THREAD

**Issue by SheetJSDev** [nodejs/node-v0.x-archive#7600]
```
$ cat t.js
var x = {
        y, 3
};
$ node
> require('./t')

t.js:2
        y, 3
         ^
...
```

And from that point on, it echoes what you type (showing the prompt `...`) until you end the process:

```
1
1
... 2
2
... 3
3
... foo
foo
... bar
bar
... baz
baz
... qux
qux
```

**Comment by jasnell** [comment]
@joyent/node-coreteam ... this has been fixed in v0.12 but still happens in v0.10. Do we want to backport or is it ok?
