### ISSUE TITLE
link a latest.tar.gz file for each major release in http://nodejs.org/dist/

### ISSUE THREAD

**Issue by kiranos** [nodejs/node-v0.x-archive#7627]
It would be great if we could get a latest.tar.gz for old releases aswell from http://nodejs.org/dist/

like:

v0.8.26/ -> nodejs-v0.8-latest.tar.gz

etc.. it would make it easier to retrieve the latest package available for every supported major version.

**Comment by brendanashworth** [comment]
Hi!

This repository is turning into an archive and issues are no longer maintained. I think the correct spot to open a new issue would be: https://github.com/nodejs/new.nodejs.org.

Closing for now.
