### ISSUE TITLE
Document req.connection

### ISSUE THREAD

**Issue by LinusU** [nodejs/node-v0.x-archive#7645]
I'm very confused by the documentation for the http module. A simple task as getting the remote ip-address of a connection seem quite complicated.

Under `http.IncomingMessage` the `connection` field is never documented, however using that field seems to be the accepted best practice to get the `remoteAddress`.

It's also unclear what the difference between `.connection` and `.socket` is. It seems like they are the same from a quick look at the source.[1] However, a note is given in the documentation that indicates this might not be the case when using https. [2]

I still don't know *the right way™* to extract the remote ip and port from an incoming http request.

[1]: https://github.com/joyent/node/blob/master/lib/_http_incoming.js#L46-L47
[2]: https://github.com/joyent/node/blob/master/doc/api/http.markdown#messagesocket

**Comment by brendanashworth** [comment]
I don't believe there is a difference between `.socket` and `.connection` ([on master at least](https://github.com/nodejs/node/blob/2e6ece44e176f70a9c5c03879f4c98b912c7afbd/lib/_http_server.js#L138-L139)), http or https. I wouldn't say it needs to be documented more, but if you'd like to send in a PR you can @ https://github.com/nodejs/node where it can be discussed.
