### ISSUE TITLE
Format of utimes' atime/mtime arguments is not documented

### ISSUE THREAD

**Issue by pornel** [nodejs/node-v0.x-archive#7689]
Format of [utimes](http://nodejs.org/docs/v0.11.13/api/fs.html#fs_fs_utimes_path_atime_mtime_callback)' arguments is not documented.

There's a [vague allusion](http://nodejs.org/docs/v0.11.13/api/fs.html#fs_class_fs_stats) to them being `Date`, but even that is not complete information, because `utimes` also accepts `Number` for the timestamps, but it interprets it as unix timestamp in second resolution, which is a slight gotcha, as it's different than a simple cast between `Date` and `Number`.

**Comment by brendanashworth** [comment]
I'm going to consider this as fixed in node v4 docs as of https://github.com/nodejs/node/commit/1f842c2c613545ba69ad5b9ab48c49ac1f77d8d3. If you disagree, please open a new issue @ https://github.com/nodejs/node. I'll close this issue.
