### ISSUE TITLE
no support for "connected" UDP sockets

### ISSUE THREAD

**Issue by raybellis** [nodejs/node-v0.x-archive#769]
UDP sockets also support `connect` and can then subsequently be used with `send` and `recv` (instead of `sendto` and `recvfrom`).

If exchanging lots of messages with one peer, supporting `connect` would be better than the current `dgram.send(buf, offset, length, port, address, [callback])` which AIUI it will attempt a host lookup for `address` on each call.  If talking to multiple peers, this also allows one socket per peer, with no need to figure out which peer sent the response.

**Comment by guymguym** [comment]
:+1:
