### ISSUE TITLE
Fail to install nodejs on Windows 8.1

### ISSUE THREAD

**Issue by ldlchina** [nodejs/node-v0.x-archive#7720]
I tried to install http://nodejs.org/dist/v0.10.28/x64/node-v0.10.28-x64.msi on Windows 8.1, but failed.
Pop up a windows err msg box something likes "can't install, please contract the provider of the app". Anyone install nodejs on Windows 8.1 successfully? I did install it on Windows 7 successfully.

Does anyone meet this issue? How to resolve it?

**Comment by lozh88** [comment]
I ran the installer file from command prompt and it worked
