### ISSUE TITLE
deadlock on getaddrinfo

### ISSUE THREAD

**Issue by ianshward** [nodejs/node-v0.x-archive#7729]
On:
- node v0.10.26
- AWS EC2 paravirtual host
- Ubuntu 14.04 LTS guest
- Linux kernel 3.13.0-24-generic

I get what looks like a deadlock:

https://gist.github.com/ianshward/996fc78f091e96f33472

The user land error comes from a node.js nano client, which uses a default node.js ./lib/https.js socket pool.  Error there looks like:

``` plain
Error: error happened in your connection
at errnoException (dns.js:37:11)
at Object.onanswer [as oncomplete] (dns.js:124:16)
name: Error
scope: socket
errid: request
code: ENOTFOUND
errno: ENOTFOUND
syscall: getaddrinfo
description: getaddrinfo ENOTFOUND
```

I have not been able to create a smaller test case, but, I may be able to gather additional information when it occurs again.

Looks similar to https://github.com/joyent/node/issues/5488

**Comment by dunkelrot** [comment]
I had a similar issue during may HTTP req/s. I guess there are simply too many open connections at the same time. Replacing the DNS name with the IP just gave a similar error message. 
I solved it by using async.queue (https://github.com/caolan/async#queue). As the task is not time critical this works quite good for me.

**Comment by prcongithub** [comment]
What is the final conclusion on this? 
I have also started facing the same problem on CentOS release 6.4 (Final).
node: v0.10.4
npm: 2.14.3

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

This happens when I am load testing the app with just 10 requests per second

**Comment by leegee** [comment]
Seeing this after a few hundred requests when making only 5 requests per second on Node v4.4.5 on OSX (Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64)

Is the current thinking that this is not something Node can/will address?

**Comment by bnoordhuis** [comment]
Correct.  The root cause was that the DNS server stops responding.  I'll close out the issue.
