### ISSUE TITLE
net/tls: un-deprecate socket.readyState

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/node-v0.x-archive#7783]
I propose reinstating `net.Socket#readyState()` or something like it as supported API because figuring out whether a socket is connected or closed is currently not possible with any of the sanctioned APIs.  For a use case, imagine you're being handed a socket that comes from a library, i.e. is not under your direct control.

.readyState is somewhat inelegant in that it partially overlaps with the .readable and .writable properties so an alternative is to add a new .state or .connectionState property that reflects just the connection status.  Then again, yet another property might not be such a great idea.

Thoughts?

**Comment by jasnell** [comment]
@bnoordhuis ... any updates on this? still something we should do?

**Comment by bnoordhuis** [comment]
I still think it's a good idea but it's not something I have time to work on right now.
