### ISSUE TITLE
fs.realpath 70x slower than native

### ISSUE THREAD

**Issue by joliss** [nodejs/node-v0.x-archive#7902]
The [`fs.realpath`](http://nodejs.org/api/fs.html#fs_fs_realpath_path_cache_callback) function is 70x slower than native C [realpath](http://man7.org/linux/man-pages/man3/realpath.3.html). On my system, `fs.realpath` takes 32 µs, while C `realpath` takes 0.45 µs.

This is a real problem in the Broccoli build tool, where we need to resolve symlinks in hot code paths. Resolving 1000 symlinked files - not an unusual case - would take 45 ms, slowing down the build considerably. [1]

As for a solution: I haven't looked at the `fs.js` source in detail, but it seems we might be able to call the `realpath` function in the C standard library, where available, instead of using [our own implementation](https://github.com/joyent/node/blob/df205360f5cdf3310a69748e74c636ec011d2e64/lib/fs.js#L1216-L1433).

Benchmark code for Node:

``` js
var fs = require('fs')

var start = Date.now()
var n = 10000
for (var i = 0; i < n; i++) {
  if (fs.realpathSync('.') === 'dummy') throw new Error('never happens')
}
console.log(((Date.now() - start) * 1000 / n) + ' us') // => 32 us on Node 0.11.13
```

Benchmark code for C:

``` c
#include <limits.h> /* PATH_MAX */
#include <stdio.h>
#include <stdlib.h>

// Adapted from http://stackoverflow.com/a/1563237/525872

int main(void) {
  char buf[PATH_MAX + 1]; /* not sure about the "+ 1" */
  int i;
  for (i = 0; i < 1000000; i++) {
    char *res = realpath(".", buf);
    if (res) {
      // printf("This source is at %s.\n", buf);
    } else {
      perror("realpath");
      exit(EXIT_FAILURE);
    }
  }
  return 0;
}
```

Run with `gcc -std=gnu99 realpath-benchmark.c -o realpath-benchmark && time ./realpath-benchmark`. This yields 0.45 µs per iteration on my Linux system.

[1] We cannot work around this by using naïve string concatenation, because [path_resolution(7)](http://man7.org/linux/man-pages/man7/path_resolution.7.html) requires that we resolve symlinks in all path components. Here is [a gist](https://gist.github.com/joliss/3292eda35cd4d564cdd7) to show why this matters.

**Comment by jasnell** [comment]
@trevnorris ... any further updates on this?

**Comment by trevnorris** [comment]
Haven't tried latest v0.12, but io.js v2.3.0 now runs this in ~9us. Still not near optimal, but better. I'll take a quick look.

**Comment by trevnorris** [comment]
Hm. Difference my be from my box. The native code runs at 120ns/op, while the script on io.js v2.3.0 runs in 3430ns/op (which is less than the 9us I was getting before a small change to the test). Either way, that is significant overhead. Going to take a peek at the code.

**Comment by trevnorris** [comment]
That method is substantial. Not really sure what's going on. It's outside the realm of trivial fix, and not exactly sure why we aren't just linking to `realpath(3)` on supported platforms.

@jasnell I'll let you decide whether to keep this open. Did a comparison on the tip of v0.12 branch and it runs in the same amount of time as io.js v2.3.0. So what I thought was a performance improvement was from a faster hd.

**Comment by joliss** [comment]
I agree that linking to `realpath(3)` would be awesome.

**Comment by jasnell** [comment]
Ok, I'm going to mark this as a defer but keep it open. The fix would likely be made over in io.js or the converged repo then backported here.

**Comment by stefanpenner** [comment]
@jasnell is the issue safe here, or should we open a new one on a non-archive repo ? I just want to prevent it from being forgotten.

**Comment by jasnell** [comment]
Either way. It's safe here. The only downside is that it's going to be as visible sitting here as a new issue would be over in nodejs/node.

**Comment by stefanpenner** [comment]
> The only downside is that it's going to be as visible sitting here as a new issue would be over in nodejs/node.

i dont see a downside (or was that the point)

**Comment by jasnell** [comment]
lol.. I mean _not_ going to be as visible sitting here... there aren't that many people looking over these older issues.

**Comment by trevnorris** [comment]
IIRC there wasn't any opposition to using `realpath(3)` directly on supported systems. If the issue is opened just ping me and I'll keep it on the list.

**Comment by thefourtheye** [comment]
Can this be done in uv?

**Comment by stefanpenner** [comment]
@trevnorris should I reopen one different repo?

**Comment by jasnell** [comment]
Opening a new issue or PR over in nodejs/node would likely be good.
