### ISSUE TITLE
require('buffer').INSPECT_MAX_BYTES usage is off-by-one

### ISSUE THREAD

**Issue by natevw** [nodejs/node-v0.x-archive#7995]
```js
require('buffer').INSPECT_MAX_BYTES = 2;
console.log(new Buffer([0,1,2,3]));
```

Expected:
> \<Buffer 01 02 ...>

Actual:
> \<Buffer 01 02 03 ...>

Looks like there used to be some tests for this: https://github.com/joyent/node/blob/a18c9b7dde22cce6cec5d47cfd6a16694c9992e8/test/simple/test-buffer-inspect.js

**Comment by brendanashworth** [comment]
I guess, based on that, this can be closed then.
