### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by JacksonTian** [nodejs/node-v0.x-archive#7997]
My test file.

``` javascript
var http = require('http');
var buf = new Buffer(1024 * 10);
buf.fill('a');

http.createServer(function (req, res) {
  res.writeHead(200);
  res.end(buf);
}).listen(8000);
```

test command:

```
$ ab -n 50000 -c 100 http://127.0.0.1:8000/
```

Node 0.11.13
qps: 3415.56

Node v0.10.29
qps: 3818.66

Node v0.8.27
qps: 4425.15

**Comment by jasnell** [comment]
@trevnorris ... were you ever able to look into this? should we keep this open?

**Comment by trevnorris** [comment]
not much further. trying to unravel the streams JS code was nightmarish, and I wasn't up to the task of overhauling how HTTP headers are handled.
