### ISSUE TITLE
A *plea* to include binary API required by socket.io into NodeJS core.

### ISSUE THREAD

**Issue by tohagan** [nodejs/node-v0.x-archive#8005]
### The Problem

There is unending pain on Windows for anyone attempting to use the beloved `socket.io` library. This is rooted in the fact that you're forced to perform a compile and worse in a SDK (Visual Studio 2010) most Windows devs ditched some years ago. You can kinda/maybe/possibly hack around it if you have admin privs and a lots of Window experience but basically any app that dares to use this wonderful lib is in for a ton of support issues and pain and most end users won't be able to get it working.

Just google search for "win7 nodejs socket.io" and feel the pain out there. 

Today I'm hitting this issue yet again as I'm trying to use a new PhoneGap component that would be _very cool_ with remote logging if not for this `ten pound gorilla` standing in my path.  

It's not just Windows that experiences this pain. Other platforms also suffer but for me today it's another Windows issue and this is a recurring nightmare for anyone doing node on Windows.
### The Solution

IMHO I think the right solution is to remove the need for compiling for what I think is now a frequently used CORE feature of node by adding the API required by socket.io into the node core code.  So the fix then just just a Node upgrade rather than a two day torture test.  
### The Plea

Socket.io is FAB!  It opens tons of **cool trick** doors for node. Please remove the pain.  All the node community will rejoice.

**Comment by sevin7676** [comment]
+1 Please fix this

**Comment by the-shank** [comment]
+1 Please !

**Comment by amcdnl** [comment]
+1

**Comment by gregt590** [comment]
+1 - We need to have a "npm install --save socket.io" on Windows 8.1 work correctly without generating a whole lot of node-gyp errors.

**Comment by piscisaureus** [comment]
I think the websocket protocol is sufficiently common that we could ship it in core.

On bunding gcc - it's GPL-licensed so forget about it. A clang-based solution would work.
However, other components that are needed to successfully build an addon on windows (a linker, msvcrt, the windows sdk headers) aren't available with an appropriate license.

Less than two weeks ago I had a short back-and-forth with an msvcrt developer who told me that the c runtime would not be open sourced (*). So I guess the bad news is that native addons on windows will continue to suck and we can't do anything about it. Make yourself heard [here](http://visualstudio.uservoice.com/forums/121579-visual-studio).

(*) The source is available, but it ships visual studio, and redistribution is only permitted under prohibitive terms.

**Comment by llafuente** [comment]
LLVM has a linker (windows), not fully featured but almost. [lld](http://lld.llvm.org/windows_support.html)
I really believe that Clang don't need MSVC anymore, long time ago they are trying to be ABI compatible so it looks like the are already able to fully compile and link. (i could be wrong)

And I don't think NPM should "have" a compiler for native module rather than understanding one and do the compile staff as part of "postinstall".

**Comment by ayesha-ma** [comment]
+1

**Comment by hussainb** [comment]
+1 for removing the VS dependency, I tried setting MSVS_VERSION to 2012, but there are still lots of errors being reported in YELLOW and RED during the installation. Need a solution or some alternative urgently.

**Comment by Clarkey** [comment]
+1 for removing VS

**Comment by dayuoba** [comment]
+1,on windows it is hard for newers to install compiled modules.
finally i have to change to unix environment

**Comment by vwnb-school** [comment]
+1 <3

**Comment by baad** [comment]
+1 for removing VS dependency

**Comment by IntranetFactory** [comment]
+1 for removing VS dependency, it makes the whole npm install process brittle e.g.  https://github.com/PolymerElements/polymer-starter-kit/issues/69#issuecomment-107054068

**Comment by tomcgn** [comment]
+1 for removing VS

**Comment by jasnell** [comment]
@orangemocha @TooTallNate ... any further thoughts on this one?

**Comment by filipnaumovic** [comment]
+1 removing Win dependencies

**Comment by tohagan** [comment]
A workaround for now is to spin up a Node Docker container using ~~[Boot2Docker for Windows](https://docs.docker.com/installation/windows/)~~  [Docker for Windows](http://docs.docker.com/windows/started/). 

Safest to select an [official Node base image](https://registry.hub.docker.com/_/node/) as the starting point for your Dockerfile. While developing, mount your Node source directory as a Docker volume so you avoid having to constantly rebuild your Docker image. When you're ready to deploy, you can use a different Dockerfile to that copies your Node source directory into a final build image (or just npm install it if it's pushed to a registry server). 

Take care to ensure that your final deployment is [running node as non-root user](http://stackoverflow.com/questions/24308760/running-app-inside-docker-as-non-root-user)

More info: 
-  [Docker for Windows](http://docs.docker.com/windows/started/)
- https://registry.hub.docker.com/_/node/

**Comment by Sogl** [comment]
+1

**Comment by bastervrugt** [comment]
+1

**Comment by orangemocha** [comment]
This would be solved by https://github.com/nodejs/build/issues/151

**Comment by Chowarmaan** [comment]
+1 - Ability to build 'out of the box' would be great.

**Comment by dsschnau** [comment]
+1

**Comment by dhasilva** [comment]
+1 for removing VS.
I don't use VS, I never used VS and I will never use VS. The only reason I have to keep this behemoth using space in my notebook is to install node modules and it does not even work properly, since I lost two work days trying to install memwatch and karma unsuccesfully.

**Comment by howardyang2009** [comment]
+1 for removing VS dependency

**Comment by fcagalj** [comment]
+1 against VS. If I wanted VS then I wouldn't use NodeJS!

**Comment by jloramas** [comment]
+1 for removing VS dependency

**Comment by LeeU1911** [comment]
I found this topic by digging through a whole lot of pages in order to solve my problem with installing mongodb via npm. It also requires VCBuild.exe in the build path, aka Visual Studio dependency. 
As a Java developer, my organization obviously won't understand why I need to get a ~4GB+ copy of Visual Studio if I don't have a valid reason. This problem got worse since now I'm working on a new computer in a remote location and I have to go through all the pains with this again.

So I also vote +1 for removing VS dependency.

Sorry for the long rant.

**Comment by justinshea** [comment]
+1

**Comment by cheoAlejo** [comment]
+1

**Comment by AngelEyesChina** [comment]
+1

**Comment by akreienbring** [comment]
+1

**Comment by Marcoevich** [comment]
+1 for removing VS dependancy

**Comment by bexoss** [comment]
+1 It should be.

**Comment by jacolaisen** [comment]
+1 you shall remove VS dependancy and leave the door open!

**Comment by er-sandeepsingh** [comment]
+1

**Comment by cherryliu** [comment]
+1. Thanks @tohagan! I thought I was blocked on build error on windows too, although sockets all works well. +1 to the point that the build errors could be changed to warnings instead! Socket.io is really an amazing tool that opens so many doors, it just needs this touchup on installation UX.

**Comment by tohagan** [comment]
Was delighted this week to discover that the latest npm performs binary installs and creates a package-lock.json containing SHA checksums.  Excellent work! 
   - https://docs.npmjs.com/files/package-lock.json
   - https://w3c.github.io/webappsec-subresource-integrity/
   - https://github.com/npm/npm/pull/16441

After reviewing the [breaking changes](http://blog.npmjs.org/post/161081169345/v500) in npm v5.0, I recommend you  `npm -g install npm` today!

**Comment by Mithgol** [comment]
Does the latest npm really perform binary installs? What part of http://blog.npmjs.org/post/161081169345/v500 does mention it?

(It seems to me that the only place where http://blog.npmjs.org/post/161081169345/v500 mentions any binary is the phrase “One binary to rule them all: `./cli.js` has been removed in favor of `./bin/npm-cli.js`”.

That's why I ask.)

**Comment by gibfahn** [comment]
>(It seems to me that the only place where http://blog.npmjs.org/post/161081169345/v500 mentions any binary is the phrase “One binary to rule them all: ./cli.js has been removed in favor of ./bin/npm-cli.js”.

That refers to the npm "binary" that you run, there's less "script calling script calling script" in `npm5`. It's not actually a binary (compiled) file though.

As for native modules, npm will compile them using the system C++ compiler. However a lot of modules include prebuilt binaries for most platforms, using something like [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp). Other than having a `package-lock.json` that notes down the dependency versions, I don't think npm5 is doing anything different.

So if you want some package that's written in C++ to magically install without compiling, then you need the module developers to include prebuilt binaries in their npm package.

There have been a number of improvements for people using Node on Windows (many led by Microsoft). 
- You can now just download the C++ compiler parts of Visual Studio (Visual C++ Build tools), there's even a one-liner that gives you everything you need to build native modules, see [here](https://github.com/nodejs/node-gyp/#on-windows).
- You can use NuGet (i.e. Chocolatey) to get the compiler
- As mentioned above, you can run in Docker containers, which gives you a Linux environment
- You can use the Windows Subsystem for Linux, which gives you Ubuntu on your Windows box

Also this repo is archived, issues with Node should be raised in https://github.com/nodejs/node. The only part of this that might be worth raising in `nodejs/node` is the discussion about either bundling a compiler, or moving to `llvm` ( @bnoordhuis how did that go?)

For general questions about node, please raise issues in https://github.com/nodejs/help instead.

I'll close this.
