### ISSUE TITLE
npm man pages not accessible

### ISSUE THREAD

**Issue by kojiwakayama** [nodejs/node-v0.x-archive#8129]
npm man pages are not working when installing node from source.

see: https://github.com/creationix/nvm/issues/495

**Comment by ljharb** [comment]
@jasnell why is this closed? Can the `./configure && make && make install` not invoke the https://github.com/joyent/node/blob/master/tools/install.py#L88-L119 command somehow?

**Comment by jasnell** [comment]
Hmm... May have hit the close button by mistake.
