### ISSUE TITLE
Feature request: process.handleEvents()

### ISSUE THREAD

**Issue by ghost** [nodejs/node-v0.x-archive#8138]
Hi. I'd like to request the addition of something like `process.handleEvents()`. The purpose of this function would be to to process all queued events, next ticks, timeouts, etc. In other words go over the main loop as if the script reached its end, but then resume from the current point. This would add some flexibility and would allow to implement things like `somethingSync()` in JS as well as to use use async calls inside sync calls.

Maybe `process.handleEvents( true )` would mean to not return until some events are processed, otherwise we can get into intensive CPU wasting loop.

For example, lets pretend I want to hijack `require()` and replace it with a version that is able to load scripts from the internet. Obviously `require()` needs to be synchronous but the HTTP functions are async.

``` js
var _og_require = require;
require = function ( url ) {
    var ready = false;
    http.request( url, function () {
        // ...do some stuff
        ready = true;
    } );

    while ( !ready ) {
        process.handleEvents( true );
    }
};

require( 'http://google.com/cdn/nodejs.api.js' );
```

Regards.

**Comment by jasnell** [comment]
@ghost @indutny ... is there reason to keep this one open?
