### ISSUE TITLE
Feature request: readdir() to report the type of the entry

### ISSUE THREAD

**Issue by ghost** [nodejs/node-v0.x-archive#8146]
`readdir()` and `FindNextFile()` both return if the dir entry is file or directory, but node.js returns only the list of the names. This means if you have directory of 1000000 entries you need to call `fs.stat()` 1000000 times to find the types of the entries which is big waste. This addition would positively impact applications like recursive walking of directories and recursive deletion of directories.

And basically one needs to stat the result of `readdir()` almost 100% of the time because folders and files needs to be treated separately. The only common thing you can do with them is basically `exists()`. Even `rename()` is different because existing files are replaced with rename and folders are not.

**Comment by jasnell** [comment]
@indutny ... any updates on this one?

**Comment by bobef** [comment]
Hey guys. What happened with this one. I thought it was getting into node 0.12. Now is node 4.2 and it still not in.
