### ISSUE TITLE
(cluster) --debug-port is forced

### ISSUE THREAD

**Issue by soyuka** [nodejs/node-v0.x-archive#8159]
Hi,

https://github.com/joyent/node/blob/master/lib/cluster.js#L291
```
    if (!hasDebugArg)
      execArgv = ['--debug-port=' + debugPort].concat(execArgv);
```

Why is debugging forced in the cluster module? Is it a wanted behavior? Did someone forgot to remove it?

It's breaking some code of ours (https://github.com/Unitech/pm2/issues/610#issuecomment-51937563) and leading to a memory leak:
- restart a cluster a lot
- debug port is going crazy and breaks node and the V8 engine

May I PR on this to remove those debug forcing stuff?

**Comment by mjseidel** [comment]
@joyent/node-coreteam nominate:0.12.3

This is a nasty surprise for callers of cluster.fork().

**Comment by nikmartin** [comment]
I'm not positive I understand all of the above posts, but on node v0.12.2 my worker processes are being forked with debug set:

```
2232 ?        Ssl    0:00 /usr/local/bin/node /usr/local/lib/node_modules/forever/bin/monitor boot.js
 7094 ?        S      1:03  \_ /usr/local/bin/node /var/myapp-server/boot.js
 7095 ?        Sl    11:49      \_ /usr/local/bin/node --debug-port=5859 /var/myapp-server/app.js
 7096 ?        Sl    13:07      \_ /usr/local/bin/node --debug-port=5860 /var/myapp-server/app.js
```

Is there a way to stop this from happening in this version? This app is in production and even though these ports are closed, I'm concerned about the performance implications of this, and the fact that this port cycling could eventually overflow if enough workers are [re]started

**Comment by cjihrig** [comment]
Debug port is no longer set by default as of https://github.com/nodejs/io.js/commit/309c0f4c58dc3365c7c3a68971745687fca75b11.

**Comment by misterdjules** [comment]
@cjihrig Can https://github.com/nodejs/io.js/commit/309c0f4c58dc3365c7c3a68971745687fca75b11 be backported to joyent/node in some form, or is everything in there a breaking change?

**Comment by cjihrig** [comment]
@misterdjules conservatively, I would say not to backport it. It's only related to debugging, and has a very simple workaround to get the old behavior (pass a debug flag to the cluster master), but it's technically still a behavior change. Your call :-)

**Comment by sam-github** [comment]
It is a behaviour change, but the existing behaviour causes problems with 0.12. Also, the debug port passing to cluster workers was a feature introduced in 0.12, that started to cause problems when it was used in production, so fixing this kind of thing will make 0.12 more stable, I  think.

**Comment by euskode** [comment]
Specifically, what are these _production problems_?

Isn't this simply setting the port but not actually putting each cluster worker into full debug mode?

**Comment by nikmartin** [comment]
My main concern about --debug in production is that there might be a lot more plumbing wired up inside node when the debug flag is set that causes more overhead than necessary

**Comment by sam-github** [comment]
@nikmartin there is not

**Comment by sam-github** [comment]
@euskode https://github.com/joyent/node/blob/master/src/node.cc#L2903, node fails to start if port is out-of-bounds, even if debugging is never turned on and the port is never used.

**Comment by soyuka** [comment]
My issue here was a memory leak, consequence of the debug port increasing
on each cluster instance reload.
Le ven. 19 juin 2015 à 22:15, Sam Roberts <notifications@github.com> a
écrit :
