### ISSUE TITLE
name 'arm_version' is not defined while evaluating condition 'arm_version==7'

### ISSUE THREAD

**Issue by thisboyiscrazy** [nodejs/node-v0.x-archive#8161]
I am getting 

name 'arm_version' is not defined while evaluating condition 'arm_version==7'

when compiling 0.11.13  on a beaglebone black armv7h

**Comment by jasnell** [comment]
@thisboyiscrazy ... I know it's been a while but is this still an issue for you? If so, interested in helping out with a pull request?

**Comment by thisboyiscrazy** [comment]
I'll have try try it again. It was on my beagle bone black.
