### ISSUE TITLE
node app randomly cannot connect to Amazon s3

### ISSUE THREAD

**Issue by dstibrany** [nodejs/node-v0.x-archive#8172]
My node.js webapp will randomly enter a state where I cannot get data from Amazon s3.

When in this state and trying to download a document from s3:
- tcpdump shows no packets being sent to or received from s3
- the net.js logs show "NET: _onTimeout" rather than the usual "NET: connect: find host 123.s3.amazonaws.com"
- ~~running lsof always shows at least one socket connected to s3 in state CLOSE_WAIT (sometimes when this happens I will see multiple s3 sockets in CLOSE_WAIT)
  eg. TCP localhost:58957->s3-1-w.amazonaws.com:http (CLOSE_WAIT)~~
- I can connect to other hosts without any problems. We hardcoded an endpoint to make a request to example.com, and it works fine.

When I restart the node server, everything works as expected.

I've added some more logging at the node socket level, (onConnect, onTimeout, onError, onClose) so maybe that will give me some more info.

Has anyone experienced anything like this using node and s3?
Does anybody have tips on how I can further debug this the next time it happens?

By the way, I'm running node v0.10.29 on Linux and I'm using the [noxmox](https://github.com/nephics/noxmox) library to make requests to s3. (It's just a wrapper around node http.ClientRequest)

**Comment by jasnell** [comment]
@dstibrany ... are you able to provide the test case? The AWS auth information is not necessary, you can blank out those details and we should be able fill them in with our own details for testing. Or, if this is no longer an issue for you, we can close.

**Comment by dstibrany** [comment]
Yep it's still an issue. I'll dig up the test case and verify that it still works. Will get back to you.

**Comment by dstibrany** [comment]
I was still able to recreate the issue with the reduced case, but it doesn't work every time I run the script. I'd suggest running the script a few times and you should (hopefully) see sockets not closing.

By the way, I recreated this on node v.0.10.36 on OSX, but the issue is also happening on our Ubuntu 12.04.4 LTS  server (also node v0.10.36).

Here's the gist: (https://gist.github.com/dstibrany/a13f33555083adc23cb5)

I had to include an auth helper module from the knox library for creating aws headers.
