### ISSUE TITLE
CHECK_EQ(0, result) failed

### ISSUE THREAD

**Issue by bendavis78** [nodejs/node-v0.x-archive#8198]
I'm trying to build node for my NAS device (ARMv7l, Cortex-A9), and I'm getting the following error when running the node binary (whether using script or without arguments):

```
#
# Fatal error in ../deps/v8/src/platform-linux.cc, line 776
# CHECK_EQ(0, result) failed
#   Expected: 0
#   Found: 22
#


==== Stack trace is not available ==========================


==== Isolate for the thread is not initialized =============
```

My build process currently looks like this:

```
export BASE=/home/ben/Hardware/wdmycloud/build
export PATH=${BASE}/toolchain/bin:$PATH
export PREFIX=${BASE}/usr/local
export HOST=arm-linux-gnueabihf
export CC=${HOST}-gcc
export CXX=${HOST}-g++
export LINK=${HOST}-g++
export RANLIB=${HOST}-ranlib
export AR=${HOST}-ar
export LD=${HOST}-ld
export CCFLAGS="-march=armv7l -mtune=cortex-a9 -mfpu=neon -mfloat-abi=hard"
export ARM_TARGET_LIB="${BASE}/toolchain/${HOST}/libc"

./configure --dest-cpu=$HOST --without-snapshot --dest-cpu=arm --with-arm-float-abi=hard

make -j 2
```

Also, I'm not sure if it's related to the problem, but my device's kernel PAGESIZE is set to 64k. The toolchain I'm using includes the recent binutils with support for 64k page size.

**Comment by jasnell** [comment]
@bendavis78 ... I know it's been a while but is this still an issue for you?

**Comment by hertzg** [comment]
@jasnell I've written a [bash script to cross compile node using rpi-tools](https://gist.github.com/hertzg/12c2d7fc40f68ff6deeb)  (rpi1 - armv6hf). 
But I have not used it since rpi2 came out.
