### ISSUE TITLE
events: Introducing a third "context" argument to eventemitter.on

### ISSUE THREAD

**Issue by 3rd-Eden** [nodejs/node-v0.x-archive#8210]
#### Problem

The `EventEmitter` calls the supplied functions with it's own context. If you want to pass in a function to an event emitter from your own class you either need to wrap or bind your function which causes loss of performance. See the following example:

``` js
function Foo() {}
Foo.prototype.handle = function handle(req, res) {
  this.headers(res);
  res.end('bar')
};
Foo.prototype.headers = function headers(res) {
  res.setHeader('foo', 'bar');
}

var http = require('http').createServer(),
   foo = new Foo();

http.on('request', foo.handle.bind(foo));
// or
http.on('request', function (req, res) { foo.handle(req, res) })
```

This isn't just a problem with http modules but everything in node that inherits from the eventemitter.
#### Solution

The solution is to add an extra `context` argument to the `EventEmitter.on` method which will 
ensure that the eventlistener is called with the supplied context instead of the context of the eventemitter. It would be fully backwards compatible as the third argument is not used:

``` js
http.on('request', foo.handle, foo);
```

An example implementation of this could be found in the `eventemitter3` module https://github.com/3rd-Eden/EventEmitter3/blob/master/index.js#L32-L102

As for the performance gain:

```
Node's EventEmitter using bind
Count (66192), Cycles (6), Elapsed (5.485), Hz (1272665.3236835978)

EventEmitter3 with using the 3rd argument for context
Count (363111), Cycles (4), Elapsed (5.412), Hz (6888645.436669402)

EventEmitter3 using bind
Count (70391), Cycles (6), Elapsed (5.4), Hz (1339867.5996333812)
```

**Comment by jasnell** [comment]
@trevnorris @3rd-Eden ... any updates on this one?

**Comment by trevnorris** [comment]
With this specifically, not really on my end. I'm still +1 for this type of improvement, and plan on it being discussed in the API WG. Though that will be a ways off.

**Comment by jasnell** [comment]
Ok, going to defer this to the converged repo then.

**Comment by 3rd-Eden** [comment]
Not sure what else i can do, the use cases are here. A working pull request was made which also speed up performance of emitting. So its just waiting until yay or nope is given by working groups

**Comment by jasnell** [comment]
@3rd-Eden ... yep, understood. Right now I'm largely going through and triaging / organizing the various open issues. Next step is to decide which things land here (in joyent/node) vs. landing in io.js or the converged stream. joyent/node is largely targeted for maintenance for v0.12 and v0.10 so this is likely something that would need to be retargeted to the converged repo. Will keep the issue open for now, however.
