### ISSUE TITLE
Child_process execFile() silently failing

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [nodejs/node-v0.x-archive#8249]
This is not a bug, more of an inconvenience and pain to debug.

If you call Child_process's `execFile(file, [args], [options], [callback])` with arg being a string (rather than an array like the API specifies), it will fail silently.

What I mean is that the process will hang and nothing will come out of either `error`, `stdout` or `stderr`. So not output to work with like a `[Error: Command failed: ]` or `ENOENT`.

I'd imagine that other, more recent versions of Node.js as well as other `child_process` module functions would be impacted by this issue.

Node version: v0.10.28

**Comment by jasnell** [comment]
@chrisdickinson ... any updates on this?
