### ISSUE TITLE
Memory Leak on uv_queue_work

### ISSUE THREAD

**Issue by batobolg** [nodejs/node-v0.x-archive#8255]
I find out this sample code from node source tree.  it is a sample C++ addon code for uv_queue_work . 
node-v0.10.31/test/addons/async-hello-world/binding.cc

then I change  
node-v0.10.31/test/addons/async-hello-world/test.js to
/////////////////////////////////////////////////////////////////////////////
var assert = require('assert');
var binding = require('./build/Release/binding');
var called = false;

process.on('exit', function () {
  assert(called);
});

binding(5, function (err, val) {
  assert.equal(null, err);
  assert.equal(10, val);
  process.nextTick(function () {
    called = true;
  });
});

var http = require("http");
var server = http.createServer();
server.on("request", function(req, res) {
        if (req.url === '/favicon.ico') {
                return;
        }
        res.writeHead(200, {'Content-Type': 'text/plain'});
        res.write("hello world !!");

binding(5, function (err, val) {
  assert.equal(null, err);
  assert.equal(10, val);
  process.nextTick(function () {
    called = true;
  });
});
        res.end();
        console.log("call ----> 3?");
        //console.log(req);
});
server.listen(8090);
console.log("server start 8090");
/////////////////////////////////////////////////////////////////////////////
after million times apache bench I found memory leak. 
ab command like this
ab -c 100 -n 1000000 http://server:8090/
I try to fix it and add some my code on binding.cc and compile test again but it still memory leak.
linux top command RES increase and increase. can you confirm it ? thank you.

**Comment by avdg** [comment]
Does this issue still occur? I can only see closed issues over here https://github.com/libuv/libuv/issues?utf8=%E2%9C%93&q=is%3Aissue+Memory+leak

**Comment by batobolg** [comment]
I did not test it on new version. you can try it.

**Comment by avdg** [comment]
I won't be able to do load testing though, I don't know the tools for that

**Comment by batobolg** [comment]
OK,  May be I if have some time to do it again later. But now I have no time to test it again. sorry.

**Comment by batobolg** [comment]
NO, not yet node-v0.12.4 solve the problem. I test it again. but still leak. almost same as before !!

**Comment by avdg** [comment]
Good to know!

**Comment by batobolg** [comment]
I am not nodejs or libuv developer, so I don't know how to fix it. I am wandering why this problem takes so long time to be solved.

**Comment by jasnell** [comment]
@indutny ... were you ever able to get around to investigating this one?

**Comment by ChALkeR** [comment]
Reopened as https://github.com/nodejs/node/issues/5029, discussion should move there.
