### ISSUE TITLE
Differentiate failing (or bad) code visually in docs

### ISSUE THREAD

**Issue by asyncanup** [nodejs/node-v0.x-archive#8313]
Here, someone skimming through the docs (without reading all text) might assume `module.exports` can be assigned inside a `setTimeout`

![image](https://cloud.githubusercontent.com/assets/77941/4140467/5a8c6fa4-33a5-11e4-8836-e88ebd2ec19c.png)

Visually differentiating bad code from good code in the examples would solve the problem.

I can provide a pull request with consistent visual distinction for all such cases in the docs, if you agree.

**Comment by brendanashworth** [comment]
I think "This does not work: .." should be enough, even if you're just skimming the code examples. But if you'd like to submit a pull request, it should be done @ https://github.com/nodejs/node. Thanks!
