### ISSUE TITLE
Method pause() on ReadLine should pause 'line' events

### ISSUE THREAD

**Issue by jimlloyd** [nodejs/node-v0.x-archive#8340]
This is a duplicate of #3628 which was closed without investigation. I believe the issue is valid and should be fixed, or the documentation should be changed. 

See the last comment on #3628 for information on how to reproduce the bug. It's fine with me if you reopen #3628 and then close this issue as a duplicate.

FYI I'd like to be able to pause the input to a REPL, but fixing readline seems to be a prerequisite.

**Comment by jasnell** [comment]
@jimlloyd ... is this still an issue for you?

**Comment by jimlloyd** [comment]
I've long since worked around this issue, so I have no personal urgency to see it be addressed. But I still believe that it truly is a flaw and in an ideal world resources would be allocated to fix it. Given that this is not an ideal world, I'll leave it up to you as to whether this issue (that supposedly was going to be fixed as far back as 0.9) will ever be fixed.

**Comment by jasnell** [comment]
@jimlloyd ... will at least mark it as a defer to the converged repo. That will at least keep it on the radar but we'll need someone to step up with a PR to make progress on it.

**Comment by jimlloyd** [comment]
+1

**Comment by silkentrance** [comment]
@jimlloyd what exactly was your work around?

**Comment by jimlloyd** [comment]
@silkentrace At the time I filed this issue, my workaround was to use [repl-promise](https://github.com/jimlloyd/repl-promise). But the full truth is that not long after filing the issue I abandoned the main use case ([gremlin-repl](https://github.com/jimlloyd/gremlin-repl)) I had for a repl that can be deterministically driven from file input. As such, repl-promise never became a mature package. Let me know if you evaluate repl-promise and decide that it or something like it would serve your needs, as I might be willing to invest some more time into it.

**Comment by ACV2** [comment]
problem is easily replicated here...
/*CODE*/
```
var lineReader = require('readline').createInterface({
  terminal: false,
  input: require('fs').createReadStream('data.json')
});

lineReader.on('line', function (data) {
    lineReader.pause(); 
    syncP(data);
    
});


lineReader.on('pause', function (data) { 
    console.log('Waiting for event to finish:');
});

function syncP(data) {
    
    setTimeout(function() {
      console.log('Line from file:', data);
      lineReader.resume();
    },rand(100,3000));
}


function rand(min, max) {
  var argc = arguments.length;
  if (argc === 0) {
    min = 0;
    max = 2147483647;
  } else if (argc === 1) {
    throw new Error('Warning: rand() expects exactly 2 parameters, 1 given');
  }
  return Math.floor(Math.random() * (max - min + 1)) + min;

} 0-1; 
```
/*CODE*/

data file:
data.json
```
{"id":0,"name":"line 0","value":489}
{"id":1,"name":"line 1","value":148}
{"id":2,"name":"line 2","value":798}
{"id":3,"name":"line 3","value":766}
{"id":4,"name":"line 4","value":70}
{"id":5,"name":"line 5","value":825}
{"id":6,"name":"line 6","value":353}
{"id":7,"name":"line 7","value":175}
{"id":8,"name":"line 8","value":12}
```

you will see clearly the output should be 1,2,3,4,5,6... which is not the case so the semantic and the process ARE wrong.. (maybe is not meant for this kind of processing but still would be a really usefull fix)

**Comment by sterpe** [comment]
This is still jacked up in node 8.5.0.

```
Waiting for event to finish:
Line from file: {"id":5,"name":"line 5","value":825}
Waiting for event to finish:
Line from file: {"id":6,"name":"line 6","value":353}
Line from file: {"id":1,"name":"line 1","value":148}
Line from file: {"id":7,"name":"line 7","value":175}
Line from file: {"id":8,"name":"line 8","value":12}
Line from file: {"id":3,"name":"line 3","value":766}
Line from file: {"id":2,"name":"line 2","value":798}
Line from file: {"id":0,"name":"line 0","value":489}
Line from file: {"id":4,"name":"line 4","value":70}
```

I agree with @jimlloyd and @ACV2 -- I was thinking about using node's Readline to build some kind of `ed`-like line editor, but the inability to lock input briefly to complete any async processing makes the implementation absolutely useless.
