### ISSUE TITLE
generating RSA key pairs

### ISSUE THREAD

**Issue by xpepermint** [nodejs/node-v0.x-archive#8343]
I don't see a way on how to easily create a private-public RSA key pair as I would do it with `openssl` (bits: 1024, exponent: 65537).

**Comment by jasnell** [comment]
@xpepermint ... is this still an issue for you?

**Comment by xpepermint** [comment]
Hey @jasnell. Well... I'm not sure because my focus is elsewhere ... But yes... I would be happy if key generation would be possible by using no extra packages (e.g. part of crypto).
