### ISSUE TITLE
fs.watch on Windows: Watching a directory blocks external rename

### ISSUE THREAD

**Issue by jorangreef** [nodejs/node-v0.x-archive#8371]
Using fs.watch to watch a directory on Windows currently blocks that directory from being deleted or renamed by the user.

https://github.com/adobe/brackets/issues/6551 has more discussion on the issue:

Using "FILE_SHARE_DELETE in the CreateFile() call will keep the code from locking the folder that you're wanting to watch with ReadDirectoryChangesW(). However, even if you use that flag, the parent folder of the watched folder will be locked by the ReadDirectoryChangesW() call."

This is not so much a problem (and is probably to be expected on Windows), except that fs.watch is also not recursive on Windows, so watching an entire tree requires recursive watches on all subdirectories. But then these cannot be renamed or deleted by the user either and this is a problem.

Also that same discussion refers to a recursive flag for ReadDirectoryChangesW?

**Comment by bpasero** [comment]
Can this be given a second thought: Please expose the recursive option for windows at least. The current way of installing another watcher on each subdirectory is so bad, that you should rather not expose it. For one, it locks folders, and for other, it consumes so much CPU and memory to walk down the directory structure that it is useless. The native option to recurse is so much more efficient.

**Comment by Elephant-Vessel** [comment]
Is this still an issue in the newer versions of node?

**Comment by jorangreef** [comment]
It's not actually an issue in Node, but the way that Windows works. Newer versions of Node now support recursive watchers on Windows, so only the watched directory (and possibly the parent of that dircetory) is locked from being deleted on Windows.
