### ISSUE TITLE
Buffer re-use in streams

### ISSUE THREAD

**Issue by laino** [nodejs/node-v0.x-archive#8457]
Hello,

currently at Volafile we're using some custom code to 'stream' data to a http client that appears to outperform just using 'pipe' by a factor of up to 5 (CPU time).

I believe the main reason for this is that we are re-using the 'read' buffer, which can safely be done
after 'write' reported all data has been flushed to the underlying system.

Actually we're using 2 buffers, one that is currently being consumed by write, and the second one to keep reading data in the meantime... but anyways.

My proposal is to add a special option upon creation of a ReadStream that allows nodejs's internals to re-use the buffers it uses for reading data AFTER all destinations report that they've completely consumed the data. This would be a feature that will not break any existing code as the user would have to explicitly state that he wished to use this feature (thereby saying 'Hey! I promise I will not use this buffer after I reportedly consumed it!').

Here's the code we currently use @ Volafile:
https://gist.github.com/laino/cdd483eec0fa84dfc95c
It has some fancy features like rate limiting and automatically growing buffers which can be ignored for now.

Also it uses my own [bastardized variant of JavaScript](https://github.com/laino/designtojs) - which shouldn't be too much of a problem (It is almost vanilla JavaScript).

**Edit**: I should also mention that on top of being much easier on the CPU, it runs with a 'static' amount of memory (except when growing buffers). Before you could see node.js' memory usage grow to something roughly equivalent to your file size (if the GC didn't kick in before the serving finished), now you barely can see anything at all.

**Comment by jasnell** [comment]
@laino... is this still an issue for you?

**Comment by laino** [comment]
Have there been any significant changes to the way streams work in node recently?
At Volafile we still use our own implementation, but I'd switch back to nodejs' streams the instant they're comparable performance-wise.

**Comment by trevnorris** [comment]
Not in the way you've asked. For custom high performance scenarios you'll probably have to stick with your own implementation. I do the same for my libraries.

**Comment by laino** [comment]
If there'd be any kind of guarantee that my code would be merged, provided my code adheres to nodejs' standards, I can show there are actual improvements to nodejs' performance (memory or cpu wise) and it doesn't break anything, then I could imagine myself reserving some time to implement this.

With `this` I mean my second proposal, about adding another argument to the `_write` callback.

**Comment by trevnorris** [comment]
If the patch is written then it will be taken into consideration, but no guarantee that it will land.

**Comment by jasnell** [comment]
@laino ... the best bet would likely be to submit a PR against nodejs/io.js or nodejs/node so I would focus the efforts there. Will keep this issue open but marking it as a defer to the converged stream.
