### ISSUE TITLE
process.memoryUsage reporting garbage heapTotal over time...

### ISSUE THREAD

**Issue by mman** [nodejs/node-v0.x-archive#8525]
Hi guys,

I'm using process.memoryUsage to plot memory usage of my node apps. Recently I noticed something strange. The reported heapTotal starts growing over time and eventually exceeds RSS. RSS and heapUsed appear to be inline with what the app is really using.

The break happens after some time and randomly, I have three instances running identical node and identical linux versions and once the instance 1 stars reporting garbage, another time its instance 3. Can't think of anything that would cause this.

I'm attaching the charts representing memory usage of three instances over past months and over the past day. You can see that over the past months I could never leave the node process running longer than a week, typically due to various memory leaks that get plugged over time...

This screenshots shows that during the week 37 and 38 the memory usage were stable and slightly growing... after that I updated to node master and started leaking... frequent restarts every couple days, then around week 39 the leaks were fixed but now you see the dark red (heapUsed) exponentially growing after some time...)

![screenshot 2014-10-07 11 15 21](https://cloud.githubusercontent.com/assets/249814/4540238/a752207a-4e05-11e4-9050-5b04ad3e4a9e.png)

Here is the detailed image from yesterday where dark blue (heapTotal on instance 3) started growing out of control...

please note that heapUsed actually remains stable over time... 

![screenshot 2014-10-07 11 15 34](https://cloud.githubusercontent.com/assets/249814/4540264/eba2e1ec-4e05-11e4-9dfa-5b76d9e3572f.png)

Please let me know if you need more details...

**Comment by Olegas** [comment]
Have similar problem. My app's memory useage suddenly gets strange. I log rss, heapUsed and heapTotal over time.
Sometimes (I don't know what causes this) my heapUsed is growing up to 1.9 GB (this is my --max-old-space-size value) while my RSS and heapTotal staying around 380 and 300 Mb respectively.
My app runs with the following switches
--expose-gc (I perform gc manually)
--nouse-idle-notification
--max-old-space-size=1900

My app is a express-based web server. It also uses crypto (for md5 calculation) and performs many outgoing http/https requests. I'm running node 0.10.33 on CentOS.
