### ISSUE TITLE
Bad URI are dropped immediately, causing errors to show up in log.

### ISSUE THREAD

**Issue by iamkoby** [nodejs/node-v0.x-archive#8537]
A request URI cannot start with ?. It would need at least a / to begin the URI. However some bots are not following this spec and causing errors to show on our logs. Node server will immediately close any HTTP request that start the URI portion with ?. 

``` javascript
// Load the http module to create an http server.
var http = require('http');

// Configure our HTTP server to respond with Hello World to all requests.
var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.end("Hello World\n");
});

// Listen on port 8000, IP defaults to 127.0.0.1
server.listen(8000);

// Put a friendly message on the terminal
console.log("Server running at http://127.0.0.1:8000/");
```

And call with bad uri: 

```
$ telnet localhost 8000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1

HTTP/1.1 200 OK
Content-Type: text/plain
Date: Tue, 30 Sep 2014 04:11:45 GMT
Connection: keep-alive
Transfer-Encoding: chunked

c
Hello World

0

GET ? HTTP/1.1
Connection closed by foreign host.
```

For instance, in our case issue causes thousands of log rows with calls from twitterbots.

**Comment by jasnell** [comment]
@joyent/node-coreteam ... I doubt this is something that we'd ever land in v0.12. Recommend that we defer to the work going on in io.js around the js http parser implementation: https://github.com/nodejs/io.js/pull/1457
