### ISSUE TITLE
util: formatValue() should check if 'inspect' is in 'value' before trying to read 'value.inspect'.

### ISSUE THREAD

**Issue by graphicore** [nodejs/node-v0.x-archive#8539]
I'm using proxies to implement a whitelisting mechanism for objects. The whitelisting is very strict. It throws an error if a key is not whitelisted. This however is triggered by `utils.js formatValue` when it tries to read `inspect` from the object in https://github.com/joyent/node/blob/master/lib/util.js#L216

A fix for this would be to check: `'inspect' in value`, because that can be controlled by by the proxies.

Note: I'm using here node v0.10.25 with --harmony and the Proxies are replaced by https://github.com/tvcutsem/harmony-reflect.
However, they behave correct in this example, as far as the current ES6 draft is concerned.

**Comment by jasnell** [comment]
@joyent/node-coreteam @vkurchatkin @graphicore ... do we still need this?

**Comment by graphicore** [comment]
I'm still using this stuff, so yes. However, the proxy support in node/v8 seems to get rather worse. If proxies are one of those dying es6 proposals, maybe I have to change my implementation.
