### ISSUE TITLE
Node crashes in V8 on Raspberry Pi

### ISSUE THREAD

**Issue by deanm** [nodejs/node-v0.x-archive#8549]
Problem is that v8 generates an mls instructions (arm ARMv6T2).

This was fixed upstream:

commit 70d11c79c7833b9ab1ee185625fcf707b9480a40
Author: machenbach@chromium.org <machenbach@chromium.org@ce2b1a6d-e550-0410-aec6
Date:   Mon Jun 16 00:04:47 2014 +0000

```
Version 3.27.29 (based on bleeding_edge revision r21835)

Emulate MLS on pre-ARMv6T2. Cleaned up thumbee vs. thumb2 confusion.

X87: Fixed flooring division by a power of 2, once again.. (issue 3259).

Fixed undefined behavior in RNG (Chromium issue 377790).

Performance and stability improvements on all platforms.

git-svn-id: https://v8.googlecode.com/svn/trunk@21848 ce2b1a6d-e550-0410-aec
```

**Comment by andig** [comment]
Very much not helpful:

	Setting up nodejs (0.10.34-1nodesource1~wheezy1) ...
	pi@prodpi ~ $ node
	Segmentation fault

**Comment by bahamat** [comment]
@andig it's fixed in source, so you really need to take this up with nodesource, since you're getting node from them. 

And it looks like they already have an open issue for it: nodesource/distributions#44

**Comment by andig** [comment]
Which source do I need to compile for 0.11? Which branch?

**Comment by bahamat** [comment]
This should have it: https://github.com/joyent/node/tree/v0.12

**Comment by andig** [comment]
Cloned git, checked out v0.12 branch. configure/make:

	pi@prodpi ~/node $ make
    ...
	make -C out BUILDTYPE=Release V=1
	make[1]: Entering directory '/home/pi/node/out'
	  LD_LIBRARY_PATH=/home/pi/node/out/Release/lib.host:/home/pi/node/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps/v8/tools/gyp; mkdir -p /home/pi/node/out/Release/obj.target/v8_snapshot/geni; "/home/pi/node/out/Release/mksnapshot" --log-snapshot-positions --logfile "/home/pi/node/out/Release/obj.target/v8_snapshot/geni/snapshot.log" "/home/pi/node/out/Release/obj.target/v8_snapshot/geni/snapshot.cc"
	Illegal instruction
	deps/v8/tools/gyp/v8_snapshot.target.mk:13: recipe for target '/home/pi/node/out/Release/obj.target/v8_snapshot/geni/snapshot.cc' failed
	make[1]: *** [/home/pi/node/out/Release/obj.target/v8_snapshot/geni/snapshot.cc] Error 132
	make[1]: Leaving directory '/home/pi/node/out'
	Makefile:45: recipe for target 'node' failed
	make: *** [node] Error 2
	
Looks like a node tool is running during the make process???

**Comment by andig** [comment]
PS.: whoever is stuck on RasPi/ Raspbian can download working node 0.10 packages at http://node-arm.herokuapp.com/

**Comment by deanm** [comment]
I had successfully built and run Node/V8 on the Raspberry Pi, there were a few changes necessary, this bug was only one of them.  Without checking I don't remember all of the details, but it is likely some of the build settings are wrong, for example, I vaguely remember something like

https://github.com/joyent/node/blob/v0.12/configure#L495

I believe vfpv3 is ARMv7, while the rpi is ARMv6.

**Comment by magic890** [comment]
Here is the official patch from V8 team: https://github.com/v8/v8-git-mirror/blob/master/src/base/cpu.cc#L483-L499

I have created a pull request to solve this issue: #25625

**Comment by Fishrock123** [comment]
all v4.x+ release these days are tested on RPIs in the CI. This should be fixed.
