### ISSUE TITLE
fs.realpath does not follow links and relative paths

### ISSUE THREAD

**Issue by schmod** [nodejs/node-v0.x-archive#8563]
When calling `fs.realpath()` with a relative path inside of a symlink, I expect that path segments will be resolved and processed in order, from left-to-right.

For example, if I call, 

``` js
fs.realpathSync('foo/bar/..');
```

I would expect the result to be `"foo"` if `bar` is a normal directory.  

However, if `bar` is a symlink to the directory `/home/baz/bar`, I would expect `fs.realpath('foo/bar/..')` to resolve the symlink _before_ processing the relative path component, and return `"/home/baz"`.

Currently, node 0.10.32 appears to normalize the path before resolving any symlinks.  Thus, the above example would always return `"foo"`, regardless of whether or not `bar` is a symlink.  

This does **not** match the  behavior of the C realpath implementation, nor does it match the intuitive understanding for how this function should work.  
### Example

Create file structure:

``` sh
mkdir -p /project/foo/bar
mkdir -p /project/baz
ln -sf /project/baz /project/foo/bar/bazLink
```

which yields this directory structure:

```
/project
  - foo
    - bar
      - bazLink
  - baz
```

node test script:

```
process.chdir('/project/foo')

fs.realpathSync('bar')
  > "/project/foo/bar"

fs.realpathSync('bar/bazLink')
  > "/project/baz"

fs.realpathSync('bar/bazLink/..')
  > "/project/foo/bar"
```

same thing with "native" realpath:

```
cd /project/foo

realpath bar
  > "/project/foo/bar"

realpath bar/bazLink
  > "/project/baz"

realpath bar/bazLink/..
  > "/project"
```

**Comment by jasnell** [comment]
@joyent/node-coreteam ... any thoughts on this one?

**Comment by Announcement** [comment]
path.resolve
