### ISSUE TITLE
net: socket options ignored before connect

### ISSUE THREAD

**Issue by mscdex** [nodejs/node-v0.x-archive#8572]
Currently if you try setting socket options (e.g. via `socket.setKeepAlive()`) on a new TCP socket before calling `socket.connect()`, the arguments are silently ignored.

To avoid confusion about this I suggest two separate solutions:
- Throw an error if no handle is created yet
- Save the arguments on the socket object for applying after a handle is created

**Comment by misterdjules** [comment]
Referencing #21079 which describes the same issue and has some very useful information too.

**Comment by misterdjules** [comment]
https://github.com/iojs/io.js/pull/1518 seems to be moving towards the right direction, we might be able to backport it soon.

**Comment by misterdjules** [comment]
Adding to the 0.13.1 milestone as I would expect it could break v0.10.x and v0.12.x users, but I'm open to other opinions.

**Comment by cjihrig** [comment]
https://github.com/nodejs/io.js/commit/85d99830096a48b7d50cc3b0e5c3fba4172c2d02 just landed. It can either be ported, or we can close this and pick up the changes in the converged branch.

**Comment by brendanashworth** [comment]
This isn't really a "critical bug", so it isn't applicable for a v0.10 backport. Does anyone have strong feelings for backporting to v0.12? It has been a while.
