### ISSUE TITLE
SegFault when calling .end() on a socket

### ISSUE THREAD

**Issue by rcrichton** [nodejs/node-v0.x-archive#8597]
I'm trying to keep track of active connections from my http server in node and when stopping the servers I want to `.end()` the active sockets so that my http servers can shutdown without waiting for the keep-alive connections to timeout. I want to use `.end()` rather than `.destroy()` as I just want to notify the client that I want to end the connection but not disrupt any data currently being sent.

At the moment when I call `.end()` on any active socket it seg faults with the following stacktrace:

```
PID 973 received SIGSEGV for address: 0x58
/home/ryan/git/openhim-core-js/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x1185)[0x7f6bf895e185]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7f6bfc167340]
node(_ZN4node10StreamWrap8ShutdownERKN2v820FunctionCallbackInfoINS1_5ValueEEE+0x166)[0x9d1846]
node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0x9b)[0x616d9b]
node[0x6356b6]
[0x3528b0060a2]
```

Here is a SO question where I explain more: http://stackoverflow.com/questions/26507393/why-cant-i-end-an-active-socket-in-node-js-without-causing-a-segmentation-fault

If I use `.destroy()` it works but I a change this to `.end()` I get the seg fault. The code is open source if anyone wants to take a look: https://github.com/jembi/openhim-core-js/blob/close-connections-on-restart/src/server.coffee#L255-L267

(Using node 0.11.13)

**Comment by indutny** [comment]
I can't tell for sure, but may be http://github.com/iojs/io.js/commit/cb4ed3c78fd6c795c29ff67df19d358a90c777cc and some consequent commits?

**Comment by trevnorris** [comment]
Assigning to myself. Will try to get to it soon.
