### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by xizhao** [nodejs/node-v0.x-archive#8601]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with node. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable node on @Sourcegraph by going to https://sourcegraph.com/github.com/joyent/node and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by brendanashworth** [comment]
This is no longer the repository for this sort of issue - it is now an archive - but if you'd still like this, please open an issue @ https://github.com/nodejs/node. Thanks.
