### ISSUE TITLE
assert.doesNotThrow should throw an AssertionError

### ISSUE THREAD

**Issue by netpoetica** [nodejs/node-v0.x-archive#8628]
It seems like the `assert` module is (mistakenly?) passing the error from the function being tested through to be thrown by the `assert.doesNotThrow` function instead of an AssertionError. Is this intentional or accidental? Also, if its intentional, would be helpful to know the reasoning behind it

``` javascript
var a = require('assert');

function CustomError(message){
   this.name = 'CustomError';
   this.message = message || "Custom Error Message";
}
CustomError.prototype = Error.prototype;

a.doesNotThrow(function(){ throw new CustomError(); }, 'should throw an assertion error')
// CustomError: Custom Error Message
```

From the [CommonJS spec](http://wiki.commonjs.org/wiki/Unit_Testing/1.0#Assert):

> 1. All of the following functions must throw an AssertionError when a corresponding condition is not met, with a message that may be undefined if not provided. All assertion methods provide both the actual and expected values to the assertion error for display purposes.

**Comment by jasnell** [comment]
@joyent/node-coreteam ... any further thoughts on this one?
