### ISSUE TITLE
Multiline input doesn't work if user overrides "eval" in REPL.start

### ISSUE THREAD

**Issue by zenparsing** [nodejs/node-v0.x-archive#8640]
As of b5175003bca45e23bd20d9559096dafda3e0ad7c, multiline input is triggered when the `eval` callback is executed with an instance of `Recoverable`.  However, `Recoverable` is not exported from the "repl" module.  It is therefore no longer possible (AFAICT) to trigger multiline input when overriding "eval" in `REPL.start`.

**Comment by jasnell** [comment]
@zenparsing ... I know it's been a while, but could you provide a simple test case that demonstrates the problem?

**Comment by mikeybox** [comment]
I've run in to the same problem which is caused a number of users of [Babel - (#1741)](https://github.com/babel/babel/issues/1741) to report the issue. The exact issue is that the finish callback function requires the error passed to have been wrapped in a RecoverableError object which is only available in the repl scope. I'm submitting a pull request to make this more generic allowing the recoverableError check to be passed as an option. This should allow other libraries to modify what passes as recoverable.

**Comment by mikeybox** [comment]
@jasnell I created a pull request that has had no traction. Do you know anything about this issue and it being resolved?

**Comment by davidchambers** [comment]
Thanks for submitting a fix, @mikeybox! I hope the pull request gets some attention soon.

**Comment by ggentzke** [comment]
FWIW `babel-node` with node version 0.12 and beyond (latest tested was v5.0.0) still does not support multiline function definitions. This issue is a blocker for that functionality.

**Comment by ghost** [comment]
I cannot use babel-node because of this issue.
