### ISSUE TITLE
Fails to build when '--without-ssl' configure option set

### ISSUE THREAD

**Issue by amudukutore** [nodejs/node-v0.x-archive#8645]
I see the following error message in the build log:
out/Release/obj.target/node/src/node.o: In function `ParseArgs':
out/../src/node.cc:2583: undefined reference to`node::SSL2_ENABLE'
out/../src/node.cc:2586: undefined reference to `node::SSL3_ENABLE'
collect2: error: ld returned 1 exit status
gmake[1]: **\* [out/Release/node] Error 1

The following patch appears to fix this:
diff --git a/src/node.cc b/src/node.cc
index 18c743f..44026e2 100644
--- a/src/node.cc
+++ b/src/node.cc
@@ -2544,8 +2544,10 @@ static void PrintHelp() {
          "  --trace-deprecation  show stack traces on deprecations\n"
          "  --v8-options         print v8 command line options\n"
          "  --max-stack-size=val set max v8 stack size (bytes)\n"
+#if HAVE_OPENSSL
          "  --enable-ssl2        enable ssl2\n"
          "  --enable-ssl3        enable ssl3\n"
+#endif
          "\n"
          "Environment variables:\n"
 #ifdef _WIN32
@@ -2579,12 +2581,14 @@ static void ParseArgs(int argc, char *_argv) {
       p = 1 + strchr(arg, '=');
       max_stack_size = atoi(p);
       argv[i] = const_cast<char_>("");
+#if HAVE_OPENSSL
     } else if (strcmp(arg, "--enable-ssl2") == 0) {
       SSL2_ENABLE = true;
       argv[i] = const_cast<char*>("");
     } else if (strcmp(arg, "--enable-ssl3") == 0) {
       SSL3_ENABLE = true;
       argv[i] = const_cast<char*>("");
+#endif
     } else if (strcmp(arg, "--help") == 0 || strcmp(arg, "-h") == 0) {
       PrintHelp();
       exit(0);

**Comment by OsamaAbbas** [comment]
Same error occurs in Ubuntu 14.04.

**Comment by Borchmann** [comment]
Same error on Gentoo when emerging with the above flags:
> net-libs/nodejs-0.12.6::gentoo  USE="npm snapshot -debug -icu -ssl" PYTHON_TARGETS="python2_7"

**Comment by Borchmann** [comment]
Same error on Gentoo when emerging with the disabled ssl flag:
`../src/node.cc: In function ‘void node::ParseArgs(int*, const char**, int*, const char***, int*, const char***)’:
../src/node.cc:3007:7: error: ‘SSL2_ENABLE’ was not declared in this scope
       SSL2_ENABLE = true;
../src/node.cc:3009:7: error: ‘SSL3_ENABLE’ was not declared in this scope
       SSL3_ENABLE = true;`
(net-libs/nodejs-0.12.6::gentoo)

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/node/pull/3825
