### ISSUE TITLE
promises prevent domain propagation

### ISSUE THREAD

**Issue by vkurchatkin** [nodejs/node-v0.x-archive#8648]
Test case:

``` javascript
var domain = require('domain').create();

function asyncStuff(cb) {
  new Promise(function(resolve) {
    setImmediate(resolve);
  }).then(cb);
}

domain.run(function() {

  asyncStuff(function() {
    setImmediate(function() {
      throw new Error;
    });
  });

});

domain.on('error', function() {
  console.log('caught');
});
```

**Comment by ajklein** [comment]
@vkurchatkin Hi there, @rafaelw pointed me at this thread. From a v8 point-of-view https://github.com/joyent/node/issues/8648#issuecomment-61720414 looks pretty invasive. If Node wants to have this much control over execution, I tend to lean towards something more like @piscisaureus's suggestion of letting the embedder get a callback every time a task is enqueued, though that may not be a good long-term solution as ECMAScript's execution model gets more fleshed out in ES7.

But I know little about Node, so it's possible that there's some way to support what Domains need without a change to V8's API, which would of course be the most ideal from my point of view.

**Comment by vkurchatkin** [comment]
@ajklein I was thinking about abstract class (`MicrotaskQueue` or `JobQueue` or something like that) that can be implemented to handle all microtask related operations. v8 would provide default implementation which could be overriden per isolate.

**Comment by trevnorris** [comment]
@vkurchatkin Still isn't there a problem that V8's Microtask runner swallows all errors?

**Comment by vkurchatkin** [comment]
@trevnorris it's not a problem for promises since they don't throw inside of microtasks

**Comment by roberttaylortech** [comment]
Hoping someone will take note and check out the issues I referenced -- and add anything useful please! :) 
- https://github.com/tj/co/issues/239
- My long post here: https://github.com/nodejs/node/issues/66
- Session middleware fix: https://github.com/othiym23/node-continuation-local-storage/issues/29

**Comment by ORESoftware** [comment]
+1 this seems to still be a problem

**Comment by syrnick** [comment]
How about removing domains in node 7?

With the current state of affairs domains are absolutely unusable. It's impossible to guarantee that a library that you use doesn't use native promises somewhere deep inside and breaks the domain propagation. Unless you do something like `global.Promise = require("bluebird");` and the library doesn't find a different way to grab the native promise constructor. As native promises make its way into the user-facing methods like https://github.com/nodejs/node/issues/5020, it'll be impossible to guarantee that no code uses native promises.

**Comment by the1mills** [comment]
Has anyone successfully monkey patched native promises to work with domains?

**Comment by ORESoftware** [comment]
this works:

```js

const then = Promise.prototype.then;
Promise.prototype.then = function (fn1, fn2) {

  if (process.domain) {
    fn1 = fn1 && process.domain.bind(fn1);
    fn2 = fn2 && process.domain.bind(fn2);
  }

  return then.call(this, fn1, fn2);
};

process.on('uncaughtException', function(err){
    console.log(' This is uncaught => ', err);
});


const domain = require('domain');

const d = domain.create();

d.on('error', function(err){
  console.error(' => Domain caught => ',err);
});


d.run(function(){

  Promise.resolve().then(function(){
     process.nextTick(function(){
       throw new Error('rah');
     });

  });

});
```

be curious if there's more we should patch though

**Comment by ChrisCinelli** [comment]
Thanks @ORESoftware.

This seems to fix it for me:

```
const then = Promise.prototype.then;
Promise.prototype.then = function (fn1, fn2) {

  if (process.domain) {
    fn1 = fn1 && process.domain.bind(fn1);
    fn2 = fn2 && process.domain.bind(fn2);
  }

  return then.call(this, fn1, fn2);
};
```

But what about  the `catch` and the `constructor`?

**Comment by ORESoftware** [comment]
@ChrisCinelli  sure thing, let me know if you see anything wrong with that patch, it seems to work fine, but ya never know.  By the way I think there is something in the works at Node core to achieve this at more granular level - in V8 itself - https://github.com/nodejs/node/pull/12489

**Comment by the1mills** [comment]
I think in the catch and constructor you'd do essentially the same thing, let me whip something up.

**Comment by ORESoftware** [comment]
Yeah `Promise.prototype.catch` should be straightforward, but patching the Promise constructor is a bit trickier (Promise.resolve needs to work too, etc.). I am not sure if touching the constructor is a great idea but I will experiment.

```js

const katch = global.Promise.prototype.catch;
global.Promise.prototype.catch = function (fn1) {
  if (process.domain) {
    fn1 = fn1 && process.domain.bind(fn1);
  }
  return katch.call(this, fn1);
};

```

Bluebird Promises should already propagate domains, so I don't believe there is a need to patch Promise = require('bluebird');... I have always been surprised that Bluebird chose to propagate domains considering how performance focused Bluebird has always been...weird.

The one thing that's sort of caveat here is that process.domain.bind() doesn't seem to complain if the argument is not a function, which is strange.

**Comment by ORESoftware** [comment]
An apparent leaky Promise - to model a monkey patch after https://github.com/nodejs/node/blob/ca480719199d2ff38223aff8e301aced25d7e6f1/deps/v8/test/mjsunit/regress/regress-5476.js

**Comment by ORESoftware** [comment]
For the constructor, you could try this:

```js
const PromiseConstructor = global.Promise;
global.Promise = class PatchedPromise extends PromiseConstructor {
  constructor(executor) {
    if (process.domain) {
      executor = executor && process.domain.bind(executor);
    }
    super(executor); // call native Promise constructor
  }
};
```

and transpile it how you will/must. Note that the vanilla JS version works, but if you try to transpile the TypeScript version of this - there is a bug - https://github.com/Microsoft/TypeScript/issues/15294#issuecomment-295876654

**Comment by ORESoftware** [comment]
Maybe I am incorrect (someone please correct me), but it seems like to get domains to work with promises, it's enough to do this:


```js
process.on('unhandledRejection', (reason: any, p: Promise<any>) => {

  if (p && p.domain) {
      p.domain.emit('error', reason);
      return;
  }

  if(process.domain){
      process.domain.emit('error', reason);
      return;
   }

    // oh well, do something else
});
```


It appears that only on recent versions of Node.js, will promises have a domain pinned to them, so the first if statement will only evaluate to true on newer versions. But process.domain should always work anyway?
