### ISSUE TITLE
read ECONNRESET on child process stdin stream

### ISSUE THREAD

**Issue by mscdex** [nodejs/node-v0.x-archive#8652]
I ran into an issue that occurs on both node v0.10.33 and v0.11.14 where the `stdin` stream of a child process emits a `read ECONNRESET` error despite the process exiting with a code of 0 and normal output.

The below example only requires `libav-tools` and [this](http://www.quirksmode.org/html5/videos/big_buck_bunny.webm) test video. With invalid input (e.g. a javascript file instead of actual media), the process exits with a non-zero exit code and no `error` event is emitted.

``` javascript
var fs = require('fs'),
    spawn = require('child_process').spawn,
    inspect = require('util').inspect;

function checkFile(data) {
  var child = spawn('avprobe', ['-of', 'json', '-show_format', '-v', 'quiet', 'pipe:0']);

  child.stdout.on('data', function(d) {
    console.log('STDOUT: ' + inspect(''+d));
  });
  child.stderr.on('data', function(d) {
    console.log('STDOUT: ' + inspect(''+d));
  });
  child.on('close', function(code) {
    console.log('CLOSE -- CODE ' + code);
  });
  child.stdin.on('error', function(err) {
    console.dir(err);
  });
  child.stdin.end(data);
}

var data = fs.readFileSync('big_buck_bunny.webm');
checkFile(data);
```

**Comment by jasnell** [comment]
@mscdex ... I assume this is still an issue?

**Comment by mscdex** [comment]
@jasnell Yes, it is still happening even with the current io.js master branch.

**Comment by MylesBorins** [comment]
I think I might have stumbled across this edge case while attempting to write a test for https://github.com/nodejs/node/pull/4819

https://ci.nodejs.org/job/node-test-pull-request/1494/

**Comment by alejandro-rivera-y** [comment]
Same trouble here, i only had to do this `buffer.slice(0, buffer.length*.1)` and now my application doesn't crash.

Probably would be nice to know whats the minimum size to get it running. (I'm working with ffprobe)
