### ISSUE TITLE
A single http.createServer([options], [listener]) interface for http/s

### ISSUE THREAD

**Issue by hueniverse** [nodejs/node-v0.x-archive#8670]
Here's a silly question: why do we have to require different submodules and call the same method with slightly different arguments when we can easily merge the two into a single call? Every place where http/https is an option, we repeat the same silliness of checking for TLS options and based on that requiring a different agent, etc.

Can we just enhance http.createServer() to accept options, and if those options include `tls`, to return the right server? This will be fully backwards compatible, but will make for much cleaner code elsewhere.

**Comment by natewatson999** [comment]
I'm working on this. I have a working version published here: https://github.com/natewatson999/httpx/tree/master

**Comment by natewatson999** [comment]
Given that a working module to deal with this issue has been published, I think this issue should be closed.
