### ISSUE TITLE
Error in dns.js "Cannot call method 'indexOf' of undefined"

### ISSUE THREAD

**Issue by aviynw** [nodejs/node-v0.x-archive#8698]
I'm getting the following error in my application.

Uncaught TypeError: Cannot call method 'indexOf' of undefined
FROM
Object.onanswer [as oncomplete] (dns.js:121:51)

My application is continuously making a lot of requests to two different servers, this error happens on average like once every several hours, but is inconsistent and I can go a day without it happening.  I'm running the 64-bit version of node 10.33 on LInux (Ubuntu 14.04).

I've had this error crop up every now and then for a while (I think I first encountered it a couple of months ago) but is used to happen like once every few days, I'm not sure what has changed recently to make it happen more frequently now

**Comment by goldfire** [comment]
We had this issue twice in production today and we didn't come anywhere close to running out of memory, so I'm inclined to think that isn't related. Unfortunately I was literally in the middle of nowhere when this happened and wasn't able to see what was going on live, but so far looking through the logs nothing looks out of the ordinary.

What is odd is that we've been running 0.10.36 for about 3 weeks on Ubuntu 14.04 with the same level of requests, and this is the first time this has happened. In fact, nothing in our stack has changed during this time.

**Comment by johntmyers** [comment]
This is happening for me now too. On 0.12. Cannot reproduce because it happens very randomly.

**Comment by johntmyers** [comment]
@goldfire is this still a problem for you?

**Comment by misterdjules** [comment]
@goldfire @johntmyers Is it possible for you to run node with `--abort-on-uncaught-exception` so that it generates a core file when an error is thrown and not caught? That would allow us to investigate the state of the program at the time the exception was thrown. If you start doing that, you'll want to make sure first that your environment allows the OS to generate a core file for your node programs first.

I'll be more than happy to help you with this if you need.

**Comment by goldfire** [comment]
We haven't had this happen since I last posted. Still running the same version of node, so not sure what that says.

**Comment by johntmyers** [comment]
Hi, yes, I can do that. However we did find one bug that was causing the
dns.js crash on a mongoose connection -- but that is something we are
fixing. Once we have that bug fixed I'll see if we still have an issue.

**Comment by SyRenity** [comment]
Happens in our case periodically, when we create a lot of parallel promises (with Q) working with remote resources.

Any chance it's a multi-threading issue?

**Comment by whoeverest** [comment]
I get this error too, when running the script below:

https://gist.github.com/whoeverest/2e1d3771b4d489cd932c

Similar to what happens @SyRenity the problem happens when there are a lot of requests going on in parallel.

**Comment by misterdjules** [comment]
Adding the `confirmed-bug` label, because this code throws an error when it's actually dealing with an operational error, not a programmer error.

**Comment by barn3y** [comment]
(continuing from #25327)

Got the same crash again, but some useful information too. At the same time the crash occurred, the same process was repeatedly hitting two handled errors which were logged:

Error: connect EMFILE
Error: getaddrinfo EMFILE

I'm guessing this is related to addresses[0] being null or undefined in dns.js

**Comment by barn3y** [comment]
This has happened a few more times in production, I have not yet confirmed, but circumstantially it does appear that running out of available sockets (eg. max open files hitting it's limit) triggers the crash.

**Comment by repunck** [comment]
running ubuntu 14.04, node v0.10.38, meanjs stack, it happens regularly and we've not beeing able to find out why... we will try the --abort-on-uncaught-exception thing

**Comment by pepkin88** [comment]
I just had this error and 15 minutes earlier I had EMFILE errors for connects.

node v0.12.0

**Comment by rhengles** [comment]
I also run into this issue today. My app runs flawlessly in Windows, but in Linux it threw this error.

Node 0.10.38, Amazon Linux AMI 2015.03

**Comment by geoff448** [comment]
Ran into this issue today and we solved by upping the soft and hard ulimit value of ubuntu from 4096 to 524288
