### ISSUE TITLE
uid & gid are not uint32 on all supported platforms.

### ISSUE THREAD

**Issue by muddletoes** [nodejs/node-v0.x-archive#8717]
## why are you bugging us?

I was trying to get npm to run _my_ way, and I found a bug in _node.cc_.
### are you _sure_?

I am pretty sure but you should check my homework.
## what is your platform and version?

`BSD` > `Darwin` > `OS X 10.10`

`node --version` `v0.10.30`

`npm version`

`{ http_parser: '1.0',
  node: '0.10.30',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.28',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1h',
  npm: '2.1.7' }`
## what is this so-called bug?

This is a bug that affects the setting of uid/gid specifically when a process attempts to set one of these values to the uid/gid `nobody:nobody`.
### how do I replicate it?

```
some-shell% sudo node
Password:
> process.setuid(-2)
TypeError: setuid argument must be a number or a string
    at repl:1:10
   [et cetera]
```
### what is the substance of the error?

~~**An error of fact**.~~   The file _node.cc_ clearly believes that all pid and gid numbers are unsigned 32 bit integers.  This is extensively detailed by the typechecking and comments in the static functions `GetUid()` and `GetPid()`.  

[_edit: @cjhrig has noted below that OS X / Darwin does also represent them as uint32 internally, even though they are represented as follows externally._]

~~Either node does not support OS X / BSD systems, or this is false.~~ This is not entirely sufficient, because this representation does not match the actual usage.  On my machine, UID and GID of `nobody:nobody` are both -2, which are traditional values that predate Linux.

It will fail for any user/group with a uid or gid that is less than zero, but the only such user that I am familiar with is the `nobody` user.
### why does it ever work at all?

As an api call, `process.setuid()` and `process.setgid()` will succeed when passed an name rather than a number.
Internally, the results of the api call work just fine because somewhere/somehow the PID -2 is being represented smoothly as 2^32 - 2. 

```
some-shell% sudo node 
Password:
> process.getuid()
0
> process.setuid('nobody')
undefined
> var nobody = process.getuid()
4294967294
> nobody - Math.pow(2,32)
-2
```

I've checked the details of the tty in which node is being run in the shell, it's being handled smoothly as -2 over there. 
## this is not a very good bug

I know, and I am very sorry.  But it cost me time and effort and would be trivial to fix.
## if it normally never happens, how did you find this bug?

I modified /etc/sudo so that a selected group of users could execute processes as the `nobody` user.  It was working well in shell tests, but continued to draw permission errors when npm was run.  While tracking this down I realized that node was not able to accept a negative integer as GID or PID;  it would respond to `process.setuid(-2)` with an error message saying that the parameter had to be a name or a number.
## we do not think you are as clever as you think you are,  but why did you not submit a patch for this?

I would have been working way outside of the bounds of my competence, and as it was I could not even get node to compile on OS X.  
## what excuse do you have for that?

The availability of the required compatibility library _libexecinfo_ is rather sketchy and perhaps whatever you're using to build the OS X package should be hosted here or included with the node distribution.

**Comment by jasnell** [comment]
@cjihrig @trevnorris ... whatcha want to do with this one?

**Comment by cjihrig** [comment]
> This still seems a bit like a can of worms that I'm not sure I want to open, when `process.setuid('nobody')` works so nicely.

I recommend closing.
