### ISSUE TITLE
memory growing when piping stdout of child_process.spawn

### ISSUE THREAD

**Issue by tcwalther** [nodejs/node-v0.x-archive#8720]
This is similar to https://github.com/joyent/node/issues/7666, but the memory leak appears when piping the output of a long-running child process. Use case: pipe output of ffmpeg directly to AWS S3.

Example script below pipes to `/dev/null`, and requires `ffmpeg` to run:

``` javascript
var spawn = require('child_process').spawn;
var fs = require('fs');

var duration = 300;
var inputUrl = 'rtsp://wmlive-nonacl.bbc.net.uk/wms/bbc_ami/radio1/radio1_bb_live_int_ep1_sl0';
var outputStream = fs.createWriteStream('/dev/null', { flags: 'a' });

var child = spawn('ffmpeg', [
  '-i', inputUrl,
  '-t', duration,
  '-acodec', 'libmp3lame',
  '-f', 'mp3',
  '-loglevel', 'fatal',
  '-'
]);

child.stdout.pipe(outputStream);
child.stderr.on('data', function(data) { console.log("stderr: " + data) });
```

Here is the output of `vmmap`: http://pastebin.com/6FSwEbN2. According to _bradleymeck_ on IRC, the leak could be in V8 instead of Node, but checking on that is way out of my league. I thought I'd mention his thought anyway, in case it helps.

This bug occurs on both the latest stable and latest dev release, v0.10.33 and v0.11.14.

**Comment by prashathsenthil** [comment]
@tcwalther  I stepped into the same issue now, like i'm using spawn-command npm package to spawn a shell where i run a binary which emits stdout's constantly for the given stdin. The node process is eating up lot of memory because of that, my code would look something like this,

``` javascript
var spawnCommand = require('spawn-command');
var cmd = 'path to the binary file'; 
module.exports = function (app) {
  var child     = spawnCommand(cmd);
  srvc = {
   get: function(req, res) {
     child.stdin.write('a json object in a format that is expected by binary' + '\n');
     child.stdout.on('data', function() {
      console.log(''+ data);
    });
  }
 }
}
```
