### ISSUE TITLE
Calling a strict-scoped function defined via eval in a non-strict context forgoes it's closure

### ISSUE THREAD

**Issue by amasad** [nodejs/node-v0.x-archive#8721]
- Create foo.js and add:

``` js
var code = [
'function x() {',
  '"use strict";',
  'console.log(x);',
'}',
'x();'
].join('\n');

eval(code);
```
- Run using node v0.10.x or v0.11.x `node foo.js`
- Expected output: `[Function x]`
- Actual output: 

```
undefined:3
console.log(x);
            ^
ReferenceError: x is not defined
```

This repros in v0.10.x and v0.11.x (including v0.11.14) but not in v0.8.x. Additionally, this doesn't repro in latest stable chrome.

**Comment by jasnell** [comment]
Interestingly, this doesn't happen within the repl. @joyent/node-coreteam ... thoughts?

**Comment by jasnell** [comment]
@domenic ... any thoughts? @a0viedo ... can you give this a quick test on the latest io.js?

**Comment by a0viedo** [comment]
@jasnell Using Node 0.10.39, 0.12.5 and iojs 2.3.1 the result is the same:
```
undefined:3
console.log(x);
            ^
ReferenceError: x is not defined
```

**Comment by trevnorris** [comment]
Just built and ran from io.js `next` branch. Which uses V8 4.4. Got same error.

/cc @domenic This also affects io.js.

**Comment by domenic** [comment]
That's bizarre. I wonder what we are doing to confuse V8 about this.

Maybe it has to do with how all Node code is wrapped in a (sloppy) module-closure?

**Comment by trevnorris** [comment]
@domenic Good point. I'll test the code in d8 and see if we get the same result.

**Comment by trevnorris** [comment]
@domenic I just ran the following slightly modified example on latest d8 4.2:
```js
var code = [
'function x() {',
  '"use strict";',
  'print(x);',
'}',
'x();'
].join('\n');

eval(code);
```
And there was no issue. Though I tried the following:
```js
var code = [
'(function (exports, require, module, __filename, __dirname) {',
  'function x() {',
    '"use strict";',
    'print(x);',
  '}',
  'x();',
'\n})();'
].join('\n');

eval(code);
```
Which also didn't have an issue. Thoughts?

**Comment by domenic** [comment]
Well,  the latter should not evil the wrapper,  to better emulate io.js. But yeah,  if that doesn't show the difference,  I've got nothing off the top of my head...

**Comment by trevnorris** [comment]
Another slight variation that does work:
```js
var code = [
  '"use strict"',
  'function x() {',
    '"use strict"',
    'console.log(x);',
  '}',
  'x();',
].join('\n');
eval(code);
```
I tested this all the way back to v0.10 and it succeeds with the extra `'use strict'` put in. This must be something to do with variable scope. The following also succeeds:
```js
var code = [
'(function() {',
  'function x() {',
    '"use strict"',
    'console.log(x);',
  '}',
  'x();',
'}())',
].join('\n');
new Function(code)();
```

I'm out of ideas. Though this does appear to be a bug.

**Comment by domenic** [comment]
To be clear, now that I'm at a computer, I was suggesting testing

```js
(function (exports, require, module, __filename, __dirname) {

var code = [
  'function x() {',
    '"use strict";',
    'print(x);',
  '}',
  'x();',
].join('\n');

eval(code);

}();
```

since that is closer to how modules work. But yeah, my next guess is that vm.runInThisContext (which is used for modules, I believe) is responsible.

**Comment by amasad** [comment]
Actually, it worked using the vm module. See my earlier comment https://github.com/joyent/node/issues/8721#issuecomment-62907770

**Comment by domenic** [comment]
Right, but I mean that Node executes modules via `vm.runInThisContext(fs.readFileSync(...))`, instead of directly like d8 does.
