### ISSUE TITLE
url.format not url-encode special characters in path

### ISSUE THREAD

**Issue by Antronin** [nodejs/node-v0.x-archive#8725]
I have file urls served by a 3rd party server, and their paths contains "{}" characters. If I say 

``` javascript
var specURI = url.format(url.parse(uri_with_brackets));
```

the `specURI` will contain the brackets as is. However using these URLs in browsers or in an AJAX request results in Error code 500, as the special characters should be encoded.

**Comment by jasnell** [comment]
@joyent/node-coreteam ... this is fixed in v0.12 but not in v0.10. Do we want to backport?

**Comment by trevnorris** [comment]
If trivial, yes.
