### ISSUE TITLE
child_process ipc send should communicate back pressure

### ISSUE THREAD

**Issue by tjfontaine** [nodejs/node-v0.x-archive#8745]
In v0.10 `child_process` `target.send` sometimes returns if the `writeQueueSize` is smaller than some "arbitrary" value https://github.com/joyent/node/blob/v0.10/lib/child_process.js#L481 but not all code paths do this.

In v0.12 we don't even bother trying to report the value https://github.com/joyent/node/blob/v0.12/lib/child_process.js#L415

We should make the code paths consistent for v0.10, merge the branch into v0.12, and then fix the v0.12 issue.

**Comment by cjihrig** [comment]
As far as I can tell, this is resolved.
