### ISSUE TITLE
docs: missing `prefinish` writable stream event

### ISSUE THREAD

**Issue by mscdex** [nodejs/node-v0.x-archive#8767]
This bit me tonight. I had a script that worked fine in node 0.10.33 but 0.11.14 was calling `finish` on next tick or later, causing unexpected behavior. After diving into the code I found that there is now also a `prefinish` event that I now listen on for node 0.11+.

It seems like if backwards compatibility can't be kept here, that `prefinish` should at least be publicly documented along with information comparing it to `finish` and how it all deviates from node 0.10 behavior.

**Comment by jasnell** [comment]
@mscdex ... still something you'd like to see? have time to do a PR?

**Comment by mscdex** [comment]
@jasnell Yes, it is still something I'd like to see. However I don't know the reasons for the change in behavior and all that, so I'm probably not the best one to write documentation for it.

**Comment by jasnell** [comment]
@chrisdickinson @trevnorris ... are either of you able to clarify the change that was made here?
