### ISSUE TITLE
Missing a way to get local IP address for received UDP message

### ISSUE THREAD

**Issue by net147** [nodejs/node-v0.x-archive#8788]
server.address().address returns 0.0.0.0 for a UDP server with multiple network interfaces listening on all interfaces. It would be useful to be able to determine the local IP address of the interface a UDP message is received on.

**Comment by davequick** [comment]
Another scenario where this is applicable: 

Dual nic'd machine: 1.2.3.4 = public side, 192.168.1.1 = rack local side.  Write a DHCP server in node.js and run it on your dual nic'd machine - you have to accept broadcast packets but you'd like to know all of them that come in on the NIC related to your rack local side and issue addresses ONLY to those on your rack local side.  You're screwed with the current implementation.  You don't actually know which nic the incoming broadcast packet actually came from.  I guess you _could_ just respond to all incoming DHCP broadcasts to your private side and time out the conversations that don't respond back - but it feels sloppy.  Just wanted to add some fuel to the fire.  It seems like it would be ideal to find a way to expose the nic the broadcast came from up to the developer writing in node.js.

**Comment by bnoordhuis** [comment]
Closing, continues in https://github.com/nodejs/node/issues/1649.
