### ISSUE TITLE
Master dies when worker crashes using round robin

### ISSUE THREAD

**Issue by greenboxal** [nodejs/node-v0.x-archive#8792]
I'm running node 0.11.14 on Ubuntu Server 14.04.

Sometimes when a cluster worker crashes with an unhandled exception the master crashes with the exception bellow.
```
Error: channel closed
    at ChildProcess.target.send (child_process.js:413:26)
    at sendHelper (cluster.js:657:8)
    at RoundRobinHandle.handoff (cluster.js:198:3)
    at RoundRobinHandle.distribute (cluster.js:184:20)
```

I couldn't reproduce the issue locally on my Mac, but I can cause similar behaviour with the following script: https://gist.github.com/greenboxal/02d5e78bd5ec3178c5e2
You can test using `ab -t 20 -c 30 http://127.0.0.1:8080/`

The workers keep crashing randomly until sometime they all stop receiving requests.

In my investigations, the problem is caused by the `fork` method of the master cluster, it installs two event handlers on the worker process, `exit` and `disconnect`.

When `disconnect` is fired, it removes the worker from all handles(`removeHandlesForWorker `), when `exit` is fired, it doesn't.
The problem is that a lot of times, only `exit` is fired thus keeping the worker in the handle worker list.

You can check this behaviour with my script.

**Comment by bartspedden** [comment]
+1 - we are also seeing this issue in prod (3 times in the last 3 weeks) - we have identified and fixed a number of places where we not properly handling exceptions. Hopefully these defect fixes will reduce the number of times we see this issue.

**Comment by sam-github** [comment]
There is a lot more messaging back and forth with RR than with the 0.10 cluster, so more opportunity for workers to exit in the middle of a message exchange. Having workers not die is a good idea, and reduces windows of unexpected failure.

But its still a core bug. A worker exiting at any time, for any reason, should NOT cause the master to abort. The RR code goes through much effort to not lose handles when communication breaks down to a worker, but it's still too fragile, every place it sends to a child it needs to handle failure, and do whatever the right thing is. I took a shot at this, but there isn't one right answer for what that right thing is. Sometimes, that's nothing (sending an ack back to a worker, its ok to just drop the ack, the worker is gone and doesn't care), sometimes there is more to do. So it requires careful analysis of context to get it right. I'd no time.

And so far, nobody has had the time/energy to go through the RR code and do that, unfortunately.

**Comment by marcosbergamo** [comment]
+1 sometimes I have the same problem!

**Comment by Smbc1** [comment]
@sam-github so, is it better to not use the RR in cluster?

**Comment by cjihrig** [comment]
Should be fixed in nodejs/node. Open an issue there if it's not fixed.
