### ISSUE TITLE
always display "writing files" as I am installing Nodejs on my newly-bought Macbook

### ISSUE THREAD

**Issue by santiagochen** [nodejs/node-v0.x-archive#8804]
I download the node-v0.10.33 apk file from your official site, and the problems comes as I installing it.
My macbook is the lastest Yosemite system.
and I don't know what I should deal with it, it seems the apk files is not suitable for my MAC. :(
could you please give me a solution for it? thanks in advance!

**Comment by jasnell** [comment]
@santiagochen ... is this still an issue for you ?
