### ISSUE TITLE
FATAL ERROR: Evacuation Allocation failed - process out of memory

### ISSUE THREAD

**Issue by Nekle** [nodejs/node-v0.x-archive#8812]
whatever I run on my ubuntu server, I always get this error.
```
$ node app.js
FATAL ERROR: Evacuation Allocation failed - process out of memory
Aborted (core dumped)

$ npm install
FATAL ERROR: Evacuation Allocation failed - process out of memory
Aborted (core dumped)

$ grunt -grunfile Gruntfile-online.js
FATAL ERROR: Malloced operator new Allocation failed - process out of memory
Aborted (core dumped)
```

this is my problem, and server info: http://stackoverflow.com/questions/27271330/fatal-error-evacuation-allocation-failed-process-out-of-memory

**Comment by brendanashworth** [comment]
I'm going to close this from a lack of activity and information, there isn't really anything to go off of here. Please ping me if this is still an issue you'd like to pursue.
