### ISSUE TITLE
search_path used by Child_Process spawn fails to locate executables on UNC paths

### ISSUE THREAD

**Issue by jvoccia** [nodejs/node-v0.x-archive#8821]
When the Path Environment Variables contains UNC paths, they are not searched properly.  It looks like this might be a known issue given:
https://github.com/joyent/node/blob/28eee0adb7884e21217c99cbf10a681c7d91b64a/deps/uv/src/win/process.c#L334
Specifically discusses this problem.

It would be great to have parity with the Windows Shell when locating files to spawn.  I assume SearchPath cannot be used because the environment being used by the spawn process may not match the current Windows environment, or is there an opportunity to use it if the current environment path matches the process.env.PATH being passed into the spawn?

**Comment by mk-pmb** [comment]
For easier reading, I'll copy the linked source comments:

In the first link, `deps/uv/src/win/process.c` stated
```c
  * TODO: correctly interpret UNC paths
```

In current master, that is
```c
 * UNC path support: we are dealing with UNC paths in both the path and the
 * filename. This is a deviation from what cmd.exe does (it does not let you
 * start a program by specifying an UNC path on the command line) but this is
 * really a pointless restriction.
```

I'm not sure whether it might help non-windows devs tackle the issue, but could you provide an example PATH setting with UNC paths, and a minimal example of trying to spawn a program from there?

**Comment by jvoccia** [comment]
A quick test has confirmed a change has half-fixed the UNC issue:
https://github.com/joyent/node/commit/c5f5d4cd11c2aec74fa03985405122d1ecb06f69
Since the changeset is large - it looks like: 
  174         if (dir_len > 2 && dir[0] == L'\\' && dir[1] == L'\\') {
  175	    /* It's a UNC path so ignore cwd */
  176	    cwd_len = 0;
  177	  } else if (dir_len >= 1 && (dir[0] == L'/' || dir[0] == L'\\')) {
In process.c addresses UNC paths.  
And it seems to work with the traditional Windows method of:
  PATH=%PATH%;\\server\share\directory

However, the change fails to take into account the "forward slash" use cases the if statements seem to be willing to accept, and CMD also is perfectly happy with.  So when using:
  PATH=%PATH%;//server/share/directory
Files in directory are not found.
Whereas, on the CMD line in Windows they will be found.

To test open CMD, add a mapped UNC path to the PATH env variable using forward slashes:
  PATH=%PATH%;//server/share/directory
Add an executable with a unique name, that outputs text on the command line, I copied net.exe into the folder and renamed it testnet.exe

Notice from a folder like C:\test you can type testnet.exe and see output.

Now create a file like:
        var process = require('child_process');
	var n = process.spawn("testnet");
	
	n.stdout.on('data', function (data) {
	  console.log('stdout: ' + data);
	});
	
	n.stderr.on('data', function (data) {
	  console.log('stderr: ' + data);
	});
	
	n.on('close', function (code) {
	  console.log('child process exited with code ' + code);
	});
Save it, and run it via node.
Notice node is unable to locate the executable file.

Parity would be great, and could be added by changing the line:
    if (dir_len > 2 && dir[0] == L'\\' && dir[1] == L'\\') {
To
     if (dir_len >= 2 && ((dir[0] == L'/' && dir[1] == L'/') || (dir[0] == L'\\' && dir[1] == L'\\')) {'
