### ISSUE TITLE
Inconsistency in stringification of parsed query with valueless key

### ISSUE THREAD

**Issue by neverfox** [nodejs/node-v0.x-archive#8825]
See #3058 

``` javascript
var query = querystring.parse('api&uid=1234&pwd=abc1234');
// { api: '', uid: '1234', pwd: 'abc123' }
querystring.stringify(query);
// api=&uid=1234&pwd=abc1234
```

Note the `=` after `api`. The two methods aren't consistent. My concern here is twofold. The inconsistency itself is worrisome. I also need to be able to stringify valueless keys without the `=` or the API I'm writing against will `404`. Is there a way to accomplish this? And is there a way to make the two methods consistent so that moving back and forth between string and object representations doesn't require intervention? It would make the most sense for `api&...` to parse to `undefined` but there's already default behavior to treat `undefined` as a request to drop the key. So perhaps it comes down to making a call about how to treat `null` and `''`. Right now, stringify treats them the same.

If anyone has a monkey patch for this already worked out, I would appreciate it.

**Comment by jasnell** [comment]
Given the input `var query = querystring.parse('api&uid=1234&pwd=abc1234');`, then `api` really ought to expand to `{api:null}`, not a blank string. The two really are quite different in many RESTful APIs. There may be a backwards compatibility concern here, however. So if the changes in #8829 are made, perhaps adding an `omitnull` option that defaults to `false` would be helpful here. If `omitnull` is `false` on `querystring.parse`, then the current behavior is followed. If `omitnull` is `true`, then `api` is set to null. Likewise on `stringify`, if `omitnull` is `true`, then `api` is emitted without the value separator and empty string.

```javascript
var query = querystring.parse('api&uid=1234&pwd=abc1234');
// { api: '', uid: '1234', pwd: 'abc1234' }
var query = querystring.parse('api&uid=1234&pwd=abc1234',{omitnull:true});
// { api: null, uid: '1234', pwd: 'abc1234' }
querystring.stringify(query,{omitnull:true});
// api&uid=1234&pwd=abc1234
querystring.stringify(query);
// api=&uid=1234&pwd=abc1234
```

**Comment by cjihrig** [comment]
I don't think an `omitnull` option is necessary. How to handle certain values is very subjective. If the changes I proposed in were implemented, then the developer could write a function to handle `null`, `undefined`, and the empty string however they choose.
