### ISSUE TITLE
ability to serve both HTTP and HTTPS on the same port

### ISSUE THREAD

**Issue by andrewrk** [nodejs/node-v0.x-archive#8827]
Consider the use case of an HTTPS server which is not running on port 80 or 443.

If a user connects using HTTP, the connection hangs since the server is listening for the HTTPS protocol only. A more ideal scenario would be sending an HTTP response redirecting them to use the HTTPS protocol instead.

It's possible to serve both HTTP and HTTPS on the same port. A TLS handshake record starts with byte 22, so you can use that to determine which protocol the client is trying to speak.

Node.js's internal HTTP(S) parser(s) should incorporate this into their state machine and expose this API.

See https://github.com/andrewrk/groovebasin/pull/401 for an example use case.
See also http://stackoverflow.com/questions/22453782/nodejs-http-and-https-over-same-port/23975955

**Comment by natewatson999** [comment]
I'm working on this. I have a working version published here: https://github.com/joyent/node/issues/8827

I still need to add it to NPM, document it, and a couple of other things, but it's on the right track.
