### ISSUE TITLE
Inconsistent 'readable' event in HTTP client response stream between local and internet connections

### ISSUE THREAD

**Issue by bradisbell** [nodejs/node-v0.x-archive#8831]
HTTP requests' response streams have strange behavior with their `readable` event.  Consider the following script:

``` javascript
var http = require('http');

// Create test server that returns arbitrary 16KB data chunks regularly
var srv = http.createServer(function (req, res) {
  setInterval(function () {
    res.write(new Buffer(16384));
  }, 500);
});

srv.listen(1337, function() {
  // Client code to connect to our random data HTTP server
  http.get('http://localhost:1337/', function (res) {
    res.on('readable', function () {
      console.log('readable fired');
      console.log('res._readableState.length', res._readableState.length);
      var chunk8K = res.read(8192);
      if (chunk8K !== null) {
        console.log('Read ' + chunk8K.length + ' bytes');
      }
      res.read(0);
    });
  });

});
```

In this example, there is an HTTP server that returns junk data at regular intervals.  (This is to simulate a progressive streaming media server.)  The client reads from this data, utilizing the `readable` event on the response stream.  In practice, this client has a wire protocol parser which reads specific sizes with `.read()`.  For our purposes in this example, we will read 8KB chunks.  At the end of reading off an 8KB chunk, `res.read(0)` is called to ensure that `readable` will be fired again.  Also in the code, I am echoing out the length of `res._readableState.length`, which I believe to be the size of the internal buffer.  (Please correct me if I am wrong on that.)

Now, for the inconsistency.  If I run this script directly, with Node.js connecting to itself via localhost., the buffer size grows indefinitely.

```
$ node src/testNodeBug.js
readable fired
res._readableState.length 16384
Read 8192 bytes
readable fired
res._readableState.length 24576
Read 8192 bytes
readable fired
res._readableState.length 32768
Read 8192 bytes
readable fired
res._readableState.length 40960
Read 8192 bytes
readable fired
res._readableState.length 49152
Read 8192 bytes
readable fired
res._readableState.length 57344
Read 8192 bytes
readable fired
res._readableState.length 65536
Read 8192 bytes
readable fired
res._readableState.length 73728
Read 8192 bytes
readable fired
```

If I run this script on another server **over the internet**, and then modify the client portion so it connects to that remote server, the buffer size does **not** grow.

```
$ node src/testNodeBug.js
readable fired
res._readableState.length 1454
readable fired
res._readableState.length 13134
Read 8192 bytes
readable fired
res._readableState.length 8192
Read 8192 bytes
readable fired
res._readableState.length 1454
readable fired
res._readableState.length 16384
Read 8192 bytes
readable fired
res._readableState.length 12566
Read 8192 bytes
readable fired
res._readableState.length 16384
Read 8192 bytes
readable fired
res._readableState.length 11106
Read 8192 bytes
readable fired
res._readableState.length 8754
Read 8192 bytes
readable fired
res._readableState.length 8192
Read 8192 bytes
readable fired
res._readableState.length 4374
```

In the case of localhost, it _seems_ that `readable` is only fired when the remote server sends another packet.  It doesn't mater if there is data in the client's buffer, `readable` won't be fired until more data is sent to it.  In the case of a connection to a remote server over the internet, `readable` fires when there is data to be read, as-expected.

I have also observed that simply using a VirtualBox VM and connecting to the remote source server via the VirtualBox host-only network adapters is not enough.  Only when connecting to servers over the internet do I see this problem go away.

Finally, if I add the following underneath `res.read(0)`:

``` javascript
      process.nextTick(function () {
        res.read(0);
      });
```

... the problem mostly goes away.

```
$ node src/testNodeBug.js
readable fired
res._readableState.length 16384
Read 8192 bytes
readable fired
res._readableState.length 24576
Read 8192 bytes
readable fired
res._readableState.length 16384
Read 8192 bytes
readable fired
res._readableState.length 24576
Read 8192 bytes
readable fired
res._readableState.length 16384
Read 8192 bytes
```

Node.js v0.10.33, Ubuntu 14.04 and Windows 7

**Comment by jasnell** [comment]
@chrisdickinson @trevnorris

**Comment by jasnell** [comment]
Fairly certain it's operating as designed but it's not entirely clear exactly why ;-) ...  I don't think there's an actual bug here but perhaps @chrisdickinson or @trevnorris could clarify.

**Comment by trevnorris** [comment]
What do the numbers look like if you place the `res.read(0)` in a `setImmediate` and also a `setTimeout` of 10 ms?

**Comment by jasnell** [comment]
Wrapping the res.read(0) in either setImmediate or setTimeout causes only two readable events to be fired then the test hangs. However, *adding* another res.read(0) immediately after either the setImmediate or setTimeout seems to work.

```javascript
var http = require('http');

// Create test server that returns arbitrary 16KB data chunks regularly
var srv = http.createServer(function (req, res) {
  setInterval(function () {
    res.write(new Buffer(16384));
  }, 500);
});

srv.listen(1337, function() {
  // Client code to connect to our random data HTTP server
  http.get('http://localhost:1337/', function (res) {
    res.on('readable', function () {
      console.log('readable fired');
      console.log('res._readableState.length', res._readableState.length);
      var chunk8K = res.read(8192);
      if (chunk8K !== null) {
        console.log('Read ' + chunk8K.length + ' bytes');
      }
      setImmediate(function() {res.read(0);});
      //setTimeout(function() {res.read(0);}, 10);
      res.read(0);
    });
  });

});
```
