### ISSUE TITLE
cluster: resource leak when using shared handles and worker exits before it disconnects

### ISSUE THREAD

**Issue by misterdjules** [nodejs/node-v0.x-archive#8860]
The following code:
```
var cluster = require('cluster');
var net = require('net');
 
if (cluster.isMaster) {
  var worker = cluster.fork().on('online', function workerOnline() {
    worker.disconnect();
  });
} else {
  net.createServer(function(client) {}).listen(8000);
}
```

When run like following:
```
NODE_CLUSTER_SCHED_POLICY=none ./node ~/dev/test-cluster-tcp-close.js
```
asserts with the following error:
```
assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: Resource leak detected.
    at removeWorker (cluster.js:346:9)
    at ChildProcess.<anonymous> (cluster.js:366:34)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

Tested with node built from the tip of v0.12 on MacOS X.

The problem is that the [`exit` event's handler](https://github.com/joyent/node/blob/v0.12/lib/cluster.js#L360) is called before the [`disconnect` event handler](https://github.com/joyent/node/blob/v0.12/lib/cluster.js#L374), but the [`Worker.prototype.isConnected` method](https://github.com/joyent/node/blob/v0.12/lib/cluster.js#L366) returns false since [`worker.process.connected` has already been set to false](https://github.com/joyent/node/blob/v0.12/lib/child_process.js#L515).

So we haven't had the time to [remove the handle](https://github.com/joyent/node/blob/v0.12/lib/cluster.js#L380) before [removing the worker](https://github.com/joyent/node/blob/v0.12/lib/cluster.js#L366), and thus we [assert](https://github.com/joyent/node/blob/v0.12/lib/cluster.js#L346).

My recommendation would be to change the [`Worker.prototype.isConnected` method](https://github.com/joyent/node/blob/v0.12/lib/cluster.js#L71-L73) to an internal `hasDisconnected` method that returns true only after the `disconnect` event handler has run.

__EDIT__: We could maybe just add an internal `hasDisconnected` method instead of replacing the `Worker.prototype.isConnected` method.

**Comment by jshkurti** [comment]
#9409

**Comment by cjihrig** [comment]
Closing. Appears to be fixed in nodejs/node.
