### ISSUE TITLE
Documentation for error.domainThrown is unclear

### ISSUE THREAD

**Issue by mikesigs** [nodejs/node-v0.x-archive#8865]
In the section [Additions to Error Objects](http://goo.gl/MaE3yS) in the Domain documentation the following confusing definition is given for `error.domainThrown`:

> A boolean indicating whether the error was thrown, emitted, or passed to a bound callback function.

I don't know about you, but in my world booleans only indicate two possibilities ;) How is it that this can have three different meanings? Is it true, false, or undefined? If so, the documentation should be more explicit about that, or perhaps a boolean isn't the right datatype to use here. Regardless, this is confusing and could use some fixing.

**Comment by mk-pmb** [comment]
:+1:
