### ISSUE TITLE
Make `process` requireable

### ISSUE THREAD

**Issue by malandrew** [nodejs/node-v0.x-archive#8866]
Ideally (IMHO) there would be no globals besides the 4 node keywords required for the module system to function: `require`, `module`, `__dirname` and `__filename`.

For many of the other modules that are typically globals, you can require them out of the box, such as

```
var console = require('console');
var setTimeout = require('timers').setTimeout; // same with clearTimeout, setInterval and clearInterval
var Buffer = require('buffer');
// etc...
```

One of the few standard parts of node that cannot be loaded via `require()` is `process`.

The popularity of this npm module: https://www.npmjs.com/package/process , with almost a million downloads in the last month shows that a lot of people would benefit from having `process` be requireable. By making it requireable, browserify can then treat it as one of the special compatibility modules and list it here: https://github.com/substack/node-browserify#compatibility

**Comment by cjihrig** [comment]
@tjfontaine thoughts on this?

**Comment by Mickael-van-der-Beek** [comment]
:+1:

**Comment by malandrew** [comment]
https://github.com/iojs/io.js/issues/157
https://github.com/iojs/io.js/pull/206

**Comment by brendanashworth** [comment]
This is now in node 4 (https://github.com/nodejs/node/commit/d8586eab7e62304f6087fd1b531aa525a5f14c2c) and probably won't be backported, so I'll close this for now.
