### ISSUE TITLE
Transform stream in objectMode disallows null

### ISSUE THREAD

**Issue by freeformsystems** [nodejs/node-v0.x-archive#8872]
When a Transform stream has `objectMode` enabled the `_transform` method is never called when a `null` value is written to the stream.

I believe that when `objectMode` is enabled a `null` value should pass through because many serialisation formats need to represent `null`, interestingly `undefined` does get passed to `_transform` and I believe it still should (I handle it for my use case).

I believe the culprit is here:

https://github.com/joyent/node/blob/master/lib/_stream_transform.js#L177

And the fix is to test against `this._readableState.objectMode`, a quick patch I whipped up against an earlier version of that file for my immediate scenario where I absolutely needed to be able to write `null` now:

```javascript
if ((ts.writechunk !== null || this._readableState.objectMode)
  && ts.writecb && !ts.transforming)
```

Incidentally, while reading the code it looks to me like:

https://github.com/joyent/node/blob/master/lib/_stream_transform.js#L79-L80

Are never used and should be removed, legacy code I think.

**Comment by brendanashworth** [comment]
I don't think this is a bug - but if you'd like to pursue this further, you'd do better to open a new issue here: https://github.com/nodejs/node. This repo is now an archive and nobody really pays attention to it :).
