### ISSUE TITLE
Port #8666 from v0.10 to v0.12

### ISSUE THREAD

**Issue by misterdjules** [nodejs/node-v0.x-archive#8877]
Recently, when merging v0.10 into v0.12, the commits from #8666 could not be merged because v0.10 and v0.12 diverged a lot in the areas that this PR touches.

Thus, we should manually forward port #8666 from v0.10 to v0.12 as soon as possible.

**Comment by misterdjules** [comment]
I'm available to guide anyone willing to pick this issue up and submit a PR that fixes it. Ping me on GitHub by mentioning @misterdjules or find me on IRC (jgi in #libuv on Freenode).

**Comment by whitlockjc** [comment]
If no one else has jumped on this, I'd love to do this.

**Comment by misterdjules** [comment]
@whitlockjc That's awesome, thank you! :+1:

Just a few recommendations before you tackle this one:

  1. I would start by getting `test/simple/test-domain-top-level-error-handler-throw.js` to work in v0.12.      Just `git checkout upstream/v0.10 test/simple/test-domain-top-level-error-handler-throw.js` from a local checkout of v0.12, build node and run `./node test/simple/test-domain-top-level-error-handler-throw.js` to reproduce the problem.

  Make sure you understand the goal of this test as described in the inline comments. The changes that fix this test in the original PR (#8666) are only the changes made to ` process._fatalException` in `src/node.js`. The implementation of domains and the way exceptions are handled by node is a bit different in v0.12 compared to v0.10, so even though the changes you'll need to make will be similar, they will probably need to be adapted/moved to the proper place.

  2. Once 1) is done, I would try to get `test/simple/test-domain-with-abort-on-uncaught-exception.js` to pass too in the same manner.  In the original PR (#8666), the changes that fix this problem are all the changes but the ones in src/node.js. Basically, in v0.10 it meant adding a `SetAbortOnUncaughtException` function to V8's APIs, which sets a callback that [is called when a JavaScript exception is thrown](https://github.com/joyent/node/pull/8666/files#diff-2f958c3c5c7c9b1aa11a1f2297548145R1164). That callback determines if either there's no domain active currently, or if the active domain is at the top of the domains stack. If so it aborts, if not it doesn't. I believe we can probably adapt this almost as is for V8 and node in v0.12.

  Once that test pass, you'll want to make sure that when the process aborts, it aborts at the right time. One way to do this is to run a node program similar to the following:

  ```
var domain = require('domain');
var d = domain.create();
var fs = require('fs');
d.on('error', function() {
   throw new Error('from domain error handler');
});

d.run(function doStuff() {
  process.nextTick(function() {
      throw new Error('from nextTick callback');
  });
});
  ```
  and make it generate a core dump. Then load that core dump with mdb_v8 on SmartOS and run `::jsstack` and make sure the callstack makes sense (that is the last JavaScript frame is the domain error handler, etc.).

 But we can go through that latest part once the rest is done.

Please let us know if you need anything else!

**Comment by misterdjules** [comment]
Fixed by 1982ed6e6356070241d695f77888a7681fd3c23c and f0453caea2c47405625236cf42ae11ae2a857142. Thank you @whitlockjc!

**Comment by whitlockjc** [comment]
Is there a next step for getting this into `nodejs/node`?

**Comment by whitlockjc** [comment]
Any time.  Thanks for the help.
