### ISSUE TITLE
https requesting peer's certificate in base64 PEM format. 

### ISSUE THREAD

**Issue by reijosirila** [nodejs/node-v0.x-archive#8882]
Please add support for requesting peer's certificate in base64 PEM format. Currently getPeerCertificate() method returns json object only.

**Comment by iamthechad** [comment]
This would be a great addition. I'm currently using the `openssl-wrapper` module to convert the DER encoded `raw` property of the peer certificate into PEM. I'd love to skip that step.

**Comment by naqoyqatsi** [comment]
var pem = '-----BEGIN CERTIFICATE-----\n' + req.getPeerCertificate().raw.toString('base64') + '\n-----END CERTIFICATE-----';
