### ISSUE TITLE
nodejs + socket.io latest versions = ERR_EMPTY_RESPONSE 324 when 500+ users connect

### ISSUE THREAD

**Issue by flashmandv** [nodejs/node-v0.x-archive#8939]
I'm using nodejs version 0.10.32 and Socket.IO 1.2.1 to build app. When the server is working for couple of hours, at some point it stops accepnting connections and returns error 324 ERR_EMPTY_RESPONSE. The strange thing is that it does not completely stops, but it stops in most cases. After the 5-10th connection attempt - it succees. 

The url that my flash client is loading is this:
http://HOST:PORT/socket.io/?EIO=2&time=1419436839425&transport=polling

I don't know what to do. How can I at least debug this ?
Please help

**Comment by cjihrig** [comment]
Can you provide a test that reproduces the issue? The test should not include any external dependencies, such as Socket.IO.

**Comment by flashmandv** [comment]
It happens now - try to open http://boardgamesonline.net/socket.html

**Comment by flashmandv** [comment]
Well..It is not possible to reproduce it without the socket.io. This is prod server and it happens when there is many people playing & trying to connect to socket.io

**Comment by jasnell** [comment]
Without additional detail it's not going to be possible to debug this.
