### ISSUE TITLE
File permissions not working in Synchronous calls 

### ISSUE THREAD

**Issue by thejhh** [nodejs/node-v0.x-archive#8949]
I noticed that my old tests in [nor-fs](https://github.com/sendanor/nor-fs) were failing and it looks like synchronous calls for file permissions in Node's fs module are no longer working as expected -- at least on my Ubuntu Linux 12.04 system.

I made also a small test scripts which aren't using nor-fs, so I don't think the problem is in my library: https://gist.github.com/jheusala/c390acba36532eb2d3d4

The asynchronous versions do not have this problem.

**Comment by jasnell** [comment]
@jheusala ... is this still an issue for you?
