### ISSUE TITLE
dgram addMembership doesn't work v0.11.14

### ISSUE THREAD

**Issue by bbsalsero** [nodejs/node-v0.x-archive#8955]
hello , i'm programming actually an udp program,but when i'm binding on a specific address , i can't receive multicast message.

exemple:

server.bind(41234,'192.168.3.165',function(){

 server.addMembership('224.0.0.114');
})

server.on("message", function (msg, rinfo) {
  console.log("server got: " + msg + " from " +
    rinfo.address + ":" + rinfo.port);})

this one will not work but,

server.bind(41234,'0.0.0.0',function(){

 server.addMembership('224.0.0.114');
})

server.on("message", function (msg, rinfo) {
  console.log("server got: " + msg + " from " +
    rinfo.address + ":" + rinfo.port);})

this one will.

so am i doing something wro,g?

**Comment by jasnell** [comment]
@bbsalsero ... I know it's been a while but is this still an issue for you?
