### ISSUE TITLE
Timers sometimes fire early on Windows

### ISSUE THREAD

**Issue by orangemocha** [nodejs/node-v0.x-archive#8960]
Test simple/test-timers-first-fire.js occasionally fails on Windows, because timers fire early. I have seen the timer in the test fire up to 15ms early.

This was supposed to be fixed for the most part by https://github.com/joyent/libuv/commit/6ced8c2cc76b7951d25cf1a7c376b18750ffbab7 and for small rounding errors by https://github.com/joyent/node/pull/7211.

When I opened the original PR against libuv (https://github.com/joyent/libuv/pull/1165) it did fix the issue, but I guess that by the time it was accepted and finally merged into node (https://github.com/joyent/node/commit/c5f5d4cd11c2aec74fa03985405122d1ecb06f69) something else must have changed that still causes timers to fire early.

**Comment by Fishrock123** [comment]
Just got a timer to fire -1.25ms early on the io.js CI...:

https://github.com/iojs/io.js/pull/1272#issuecomment-86627704

**Comment by misterdjules** [comment]
@orangemocha Do you have an idea of how often this problem can be reproduced on Windows? Basically, is there anything we need to know to be able to reproduce it (Windows version, etc.)?

**Comment by Fishrock123** [comment]
@trevnorris mentioned that he though the time was in `us` not `ms`

**Comment by Fishrock123** [comment]
Also, we had an interesting post that i'm going to attempt to look into (with my limited C knowledge) about QPC floating-point rounding issues: https://github.com/iojs/io.js/pull/1272#issuecomment-86644307

**Comment by orangemocha** [comment]
The test output is actually in ms, not us.
When I opened this issue I could repro just by running the test in a loop on a Win 8.1 machine. I just tried the same on a Windows Server 2012 R2 machine and couldn't reproduce it.
I will look into this further...

**Comment by orangemocha** [comment]
This is also flaky in v0.10 (and https://github.com/joyent/node/commit/a2f879f197f76d91a42ec0f8322f18948911a552 marked it so).
