### ISSUE TITLE
Document string coercion behavior in process.env

### ISSUE THREAD

**Issue by DavidSouther** [nodejs/node-v0.x-archive#8975]
`process.env` coerces all accessors to be `string` when returned, but this isn't documented in http://nodejs.org/api/process.html#process_process_env

**Comment by brendanashworth** [comment]
I'm not sure what else they would be - they come from the system as `char*`, afaik. But if you think this is an issue worth pursuing, I'd recommend opening a new issue @ https://github.com/nodejs/node.
