### ISSUE TITLE
Include full ICU data in binary installers

### ISSUE THREAD

**Issue by misterdjules** [nodejs/node-v0.x-archive#8995]
If and when https://github.com/joyent/node/pull/8994 lands, binary installers will ship with _small_ ICU data embedded in the executable file, with data included only for the English language.

Eventually, we want to ship binary installers with _full_ ICU data included as a separate `.dat` file that is loaded on startup.

This depends on #8983 to be able to load the separate `.dat` file from a directory relative to the location where node is installed.

Some parts of the implementation of https://github.com/srl295/node/pull/15 could be reused.

cc @srl295 @tjfontaine

**Comment by piscisaureus** [comment]
>If and when #8994 lands, binary installers will ship with small ICU data embedded in the executable file, with data included only for the English language.
> Eventually, we want to ship binary installers with full ICU data included as a separate .dat file that is loaded on startup.

But what's the benefit over just building with icu-full, then?

**Comment by srl295** [comment]
@piscisaureus a couple..  
- mac can have 1 copy of the data instead of 2 (fat binaries would have a 32 and a 64 bit)
- can easily update the data by replacing the file

downside is the data has to be located relative to the binary.
