### ISSUE TITLE
Confusing error message when requiring a script with an unmatched open brace

### ISSUE THREAD

**Issue by SheetJSDev** [nodejs/node-v0.x-archive#9025]
```
$ cat t.js
{
$ node -pe 'require("./t")'

/tmp/t.js:3
});
 ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
```

FWIW the chrome console generates a syntax error with message "Unexpected end of input".

**Comment by cjihrig** [comment]
Thanks for reporting this, but it seems like a very reasonable error message.

**Comment by SheetJSDev** [comment]
@cjihrig where in the source does `});` appear?  It's certainly not in the source file, given that the offending line number is 2 more than the number of lines in the file:

```
$ wc -l t.js
       1 t.js
```

Where is this line 3 from the error message coming from?

**Comment by ashnur** [comment]
If this is a **reasonable** error message for this error, I am very curious about the **reasoning**.

**Comment by misterdjules** [comment]
@SheetJSDev Modules are [wrapped](https://github.com/joyent/node/blob/master/lib/module.js#L441) into [a function](https://github.com/joyent/node/blob/master/src/node.js#L795-L798) when they are loaded.

**Comment by cjihrig** [comment]
Thanks @misterdjules. I was just responding with this. If you print what is actually run, you get something like this:

```javascript
(function (exports, require, module, __filename, __dirname) { {
});
```

**Comment by SheetJSDev** [comment]
@misterdjules that part is well-understood, but the error message presupposes that you know the wrapper behavior of require.  That's why I disagree with the assessment that the error is reasonable -- you need to know the node internals to understand the error.

Out of curiosity, is there a way to print out the code being evaluated without having to dig through the node source or monkey-patch node?

**Comment by jhartikainen** [comment]
+1 on this. I would have no idea that node wraps things into functions internally. I've never even seen it documented anywhere.

**Comment by cjihrig** [comment]
After discussing, I'm going to reopen. This is an **expected** error, but not the most intuitive.
