### ISSUE TITLE
Node v0.11.14 eat more memory than v0.10.30.

### ISSUE THREAD

**Issue by JacksonTian** [nodejs/node-v0.x-archive#9041]
![image](https://cloud.githubusercontent.com/assets/327019/5773981/b31f1e4c-9da3-11e4-8775-95818dafc431.png)

My production code running node v0.10.30 long time. Recently, we upgrade one of servers to v0.11.14, the same source code, but v0.11.14 need 2.5x RSS.

The v0.10.30 use ~100M RSS, the v0.11.14 use ~250M RSS.

**Comment by misterdjules** [comment]
Thanks @JacksonTian. Did you see the same issue with development releases < 0.11.14? Also, do you think you could come up with a minimal repro for this issue (that is, code that does not depend on external modules and that is as small as possible)?

**Comment by JacksonTian** [comment]
We checked the program, not caused by memory leak. The memory don't increase again.

**Comment by JacksonTian** [comment]
following is my test script.
```js
var http = require('http');

var str = "Honeywell invents and manufactures technologies to address some of the world's toughest challenges initiated by revolutionary macrotrends in science, technology and society. A Fortune 100 company, we create solutions to improve the quality of life of people around the globe: generating clean, healthy energy and using it more efficiently. Increasing our safety and security. Enabling people around the world to connect, communicate, and collaborate. And equipping our customers to be even more productive. With approximately 132,000 employees worldwide, including more than 22,000 engineers and scientists, we have an unrelenting commitment to quality and delivering results in everything we make and do.\n\
Aerospace Advancements\n\
\n\
Honeywell Aerospace mechanical and electrical innovations are used today on virtually every commercial and defense aircraft platform. Our aerospace team invents and integrates thousands of products and services that deliver safe, efficient, productive and comfortable experiences worldwide.\n\
Automation Smart Technology and Control Solutions\n\
\n\
Families, businesses, and communities use Honeywell environmental controls, life safety, security, sensing, scanning, and mobility products, as well as building and process solutions in homes, buildings, industrial facilities, and public and private utilities around the world.\n\
Cutting-Edge Performance Materials and Technologies\n\
\n\
Honeywell is a global leader in designing and creating high-purity, high-quality performance chemicals and materials. Our technologies can do everything from reducing emissions to stopping bullets. They enable the production of cleaner, more efficient fuels, increase capacity in oil refineries, speed drug discovery, and protect medicines.\n\
Efficient Transportation Systems\n\
\n\
Honeywell Transportatio n Systems provides world-class technologies and solutions to automakers, their suppliers, and the public. Our technologies make passenger and commercial vehicles throughout the world perform better and more efficiently.\n\
\n\
hello world - 你好世界!\n\
"

var count = 0;

http.createServer(function (req, res) {
    res.writeHead(200);
    res.write(str);
    res.write('rss:' + process.memoryUsage()['rss']);
    res.write('    heapTotal:' + process.memoryUsage()['heapTotal']);
    res.write('    heapUsed:' + process.memoryUsage()['heapUsed']);
    res.end('\nhello world this is a test!  ' + count + '\n\n');
    count += 1;
}).listen(51001);
```

**Comment by JacksonTian** [comment]
Node Version | RSS | heap total
------------ | ------------- | -------------
0.10.30 | 64233472 | 45864704 
0.10.34 | 64360448 | 45864704
0.11.0 | 66400256 | 45864704
0.11.1 | 69275648 | 54447872
0.11.2 | 64610304 | 44832768
0.11.3 | 64790528 | 44832768
0.11.4 | 60461056 | 44898304
0.11.6 | 62623744 | 46962176
0.11.8 | 59502592 | 46962176
0.11.11 | 58101760 | 47027712
0.11.12 | 57921536 | 47027712
0.11.13 | 69713920 | 54251264
0.11.14 | 69955584 | 55479808

**Comment by JacksonTian** [comment]
The hello world class demo just shown heap total increase between 0.11.12 to 0.11.13.

**Comment by misterdjules** [comment]
Thanks for the additional info @JacksonTian! @tjfontaine @cjihrig @chrisdickinson @trevnorris @jasnell Do you have some time to look into it to determine if this needs to be added to the 0.11.16 milestone?

**Comment by trevnorris** [comment]
I doubt there's much we can do. The increased usage is probably from V8's usage of the heap. Try running the app `--max-old-space-size=150` and let us know what the result is.

**Comment by JacksonTian** [comment]
![2015-01-27 2 34 19](https://cloud.githubusercontent.com/assets/327019/5914507/a731c238-a631-11e4-9319-dd445e3f5f5c.png)

Provide a heap trend here. The issue maybe caused by `old_data_space_committed`, the old data space doesn't release the memory. Committed is twice of max used.
