### ISSUE TITLE
[DISCUSS] Stability of process API

### ISSUE THREAD

**Issue by robertkowalski** [nodejs/node-v0.x-archive#9055]
Today we got a request regarding the stability of the process API at https://github.com/joyent/node-website/issues/66 from @sjcrank

I asked @tjfontaine today and he said he would like to discuss that topic with a lot of people. As this is more an API topic it belongs more into this repo.

**Comment by brendanashworth** [comment]
@robertkowalski you could probably send in a PR @ https://github.com/nodejs/node adding just a basic stability block in the docs. Now that node is on semver, there won't be significant backwards compatible changes - the stability blocks have mostly been removed / made outdated, minus deprecated and frozen APIs.

I'll close this for now.
