### ISSUE TITLE
Offer libdir and mandir configure options.

### ISSUE THREAD

**Issue by ryanpcmcquen** [nodejs/node-v0.x-archive#9058]
http://slackbuilds.org/cgit/slackbuilds/tree/network/node/node.SlackBuild

To get around being unable to change the library and man paths, we currently have this in the Slackware build script:
```
# Fix man page path.
sed -i 's|share/||' tools/install.py
sed -i '/var manRoot/ s/"share",//' deps/npm/lib/{,un}build.js

# Fix libdir for 64-bit.
sed -i "s|lib/|lib${LIBDIRSUFFIX}/|g" tools/install.py
sed -i "s/'lib'/'lib${LIBDIRSUFFIX}'/" lib/module.js
sed -i "s|\"lib\"|\"lib${LIBDIRSUFFIX}\"|" deps/npm/lib/npm.js
```

It'd be nice if node offered a typical configure flag option like ```--libdir``` and ```--mandir```.

Thanks!

**Comment by brendanashworth** [comment]
I'll close this in favor of discussion at the nodejs/node issue: https://github.com/nodejs/node/issues/504.
