### ISSUE TITLE
if package.json's "main" does not resolve, no error reported and resolution continues

### ISSUE THREAD

**Issue by nicks** [nodejs/node-v0.x-archive#9118]
Create a node_modules/a/package.json that looks like this:

``` json
{
  "name": "a",
  "main": "typo.js"
}
```

where `typo.js` does not resolve to a file. Then execute `require('a')`

Expected behavior:
- something should warn that "typo.js" does not resolve to anything
- module resolution should halt and report an error

Actual behavior:
- require() fails quietly, and continues to search all the module paths for a module

This is particularly bad due to the OS-dependent case-sensitivity problems with require(), because you can have a module that resolves to one version on one platform, and to another version on another platform.

**Comment by jasnell** [comment]
Confirmed and agree that it's rather odd. @tjfontaine thoughts?

**Comment by danny2394** [comment]
I am using v0.13.0-pre on Ubuntu 14.04 where there is an error popping up on terminal.
What version are you getting this bug on. @tjfontaine

**Comment by cjihrig** [comment]
This seems like a valid bug to me, but the module system is the most frozen thing in Node, AFAIK.
