### ISSUE TITLE
socket name of unix domain sockets

### ISSUE THREAD

**Issue by timkuijsten** [nodejs/node-v0.x-archive#9120]
It is currently impossible to get the path of a connected unix domain socket. `socket.address()` returns an empty object if it's not connected over AFINET.

I've looked at lib/net.js, src/tcp_wrap.cc, src/pipe_wrap.cc and libuv and it looks like libuv has support for returning the name of the socket and it is *only* pipe_wrap.cc that misses something like GetPeerName (I'm not a C coder so I might be wrong on this).

**Comment by brendanashworth** [comment]
Closing in favor of discussion at https://github.com/nodejs/node/issues/954.
