### ISSUE TITLE
HeapTotal grows while heapUsed doesn't, is this a bug or caused by my code?

### ISSUE THREAD

**Issue by mmqmzk** [nodejs/node-v0.x-archive#9129]
I have a app runs ok when startup, but rss and heapTotal begin to grow after several hours. When this        happens, heapUsed is stable stay at about 200MB, rss and heapTotal  grow to 1.4GB and then CPU usage grow to 100%, then process lose response.
I'm using node 0.10.36.
Anyone can tell me what are the possible reasons caused this?

**Comment by misterdjules** [comment]
Could you please post some minimal code that reproduces the issue? Ideally, this code would not use any external dependency.

**Comment by mmqmzk** [comment]
Thanks for reply.
My app is a game server, I'm not sure which part caused this issue. I checked log files, my app  lost response without throwing any error, CPU usage just suddenly grow to 100%. The only strange point is heapTotal is far larger than heapUsed.
By the way, I'm using eval in my code for some reason, is eval a possible reason  cause this issue?

**Comment by jasnell** [comment]
Without a test case to reproduce it's going to be difficult to diagnose any problem.
