### ISSUE TITLE
Reading from character devices issue

### ISSUE THREAD

**Issue by pkuznets** [nodejs/node-v0.x-archive#9132]
i want to read events from /dev/input/*

i have prototype in python which works just by simple select polling,
and it works good.

I try to read it through the fs.createReadStream and have a problem.
if i open more then 3 devices node skip huge number or events...

how can i solve it ?? and why this problem takes place.

**Comment by misterdjules** [comment]
Could you please post some minimal sample code that shows both the python program that works and the node program that doesn't, along with the expected and actual outputs?

Also, what version of node are you using? Which platform does it run on (I assume it's Linux, but which distribution/version)? 

Thank you!

**Comment by pkuznets** [comment]
```python
import glob
import select
import sys

def open_or_none(f):
    try:
        return open(f, 'r', buffering=0)
    except:
        pass

devices = filter(None, map(open_or_none, glob.glob("/dev/input/event*")))

while True:
    r, _, _ = select.select(devices, [], [])
    for device in devices:
        sys.stdout.write(".")
        sys.stdout.flush()
        device.read(16)
```

```javascript
var fs = require("fs"),
    path = require("path");

function is_device(device_path) {
    return (
        device_path.indexOf("event") >= 0 &&
        fs.statSync(device_path).isCharacterDevice()
    );
}

function list_devices(base_dir) {
    return fs.readdirSync(base_dir).map(function(device){
        return path.join(base_dir, device);
    }).filter(is_device);
}

list_devices("/dev/input").map(function(device_name){
    return fs.createReadStream(device_name, {defaultEncoding:"binary"})
    .on("readable", function(chunk){
        this.read(16);
        console.log(".");
    })
    .on("error", function(){
        console.log("error with:", device_name);
    });
});

console.log('start listen the devices...');
```

**Comment by pkuznets** [comment]
python 2.7.3
node 0.10.36
operating system was openembeded linux on arm processor,
but it seems working same on intel and ubuntu 14.10 


code which u see is from my mind, i will send u more good variant later.
but u can try to slice list_devices to 3 device and number of catched events have to  grow up...

**Comment by pkuznets** [comment]
If you run this codes with root privilledges you can see some "."  in stdout,
if you press button on keyboard it produce three events  'keydown' 'keyup' and 'sync'.

**Comment by fivdi** [comment]
This issue is very likely to be related to the thread pool size. In the JavaScript code above `fs.createReadStream` is called to open `/dev/input/event<some-number>`. The file will remain open indefinitely and will therefore keep one of the threads from the thread pool occupied indefinitely. If this is done for multiple files, as is the case here, all 4 threads from the thread pool will be blocked most of the time. One solution to this issue if to set UV_THREADPOOL_SIZE to a value higher than the number of files that are kept open indefinitely, for example on Linux:

```
UV_THREADPOOL_SIZE=10 node app
```
