### ISSUE TITLE
Upstream fix to dictionary properties access to V8

### ISSUE THREAD

**Issue by misterdjules** [nodejs/node-v0.x-archive#9147]
The [lastest update to mdb_v8 in v0.12](https://github.com/joyent/node/commit/4312f8d760bdf574b5a461e426331f0b4d298f18) fixed dictionary properties access. This commit touches `deps/v8/tools/gen-postmortem-metadata.py` with the following changes:
```
    'Map, instance_size, int, kInstanceSizeOffset',
     'Map, bit_field, char, kBitFieldOffset',
     'Map, bit_field2, char, kBitField2Offset',
-    'Map, bit_field3, SMI, kBitField3Offset',
+    'Map, bit_field3, int, kBitField3Offset',
     'Map, prototype, Object, kPrototypeOffset',
     'NameDictionaryShape, prefix_size, int, kPrefixSize',
     'NameDictionaryShape, entry_size, int, kEntrySize',
```
These changes should probably be upstreamed to V8.

**Comment by misterdjules** [comment]
cc @davepacheco

**Comment by jasnell** [comment]
Updated the priority on this to P-1 per https://github.com/nodejs/node/issues/28

**Comment by misterdjules** [comment]
@davepacheco @jasnell Created https://codereview.chromium.org/1296743003.

**Comment by misterdjules** [comment]
Done with https://github.com/nodejs/node/pull/2959 and https://codereview.chromium.org/1296743003.
