### ISSUE TITLE
Assertion failed: (err) == (0), file src\agent.cc, line 164

### ISSUE THREAD

**Issue by ben-page** [nodejs/node-v0.x-archive#9155]
I'm randomly getting that error on 0.11.16. All of my code (except the code that creates the domains) runs in a domain. The error is killing the entire node process.

**Comment by cjihrig** [comment]
Can you please provide example code with no external dependencies that reproduces the problem.

**Comment by ben-page** [comment]
I can't reproduce it. I just happens periodically with no apparent cause. Sometime it happens as soon as I start my program. Other times it happens after it has been running a while. I never saw this behavior on 0.11.14. I never used 0.11.15, so I can't comment on that.

**Comment by ben-page** [comment]
Someone appears to have figured out how to reproduce it using node-inspector. Please note, I'm not using node inspector, but this is the only way that I've been able to reliably recreate the error. https://github.com/node-inspector/node-inspector/issues/549

**Comment by ben-page** [comment]
FYI, v0.12.0 is affected as well.

**Comment by jonathandelgado** [comment]
+1

**Comment by MrVoltz** [comment]
+1, even on 0.11.15

**Comment by trevnorris** [comment]
Related: https://github.com/iojs/io.js/issues/781
