### ISSUE TITLE
`child_process.spawnSync()` throws an error when `options` argument is shared

### ISSUE THREAD

**Issue by hail2u** [nodejs/node-v0.x-archive#9158]
Calling `child_process.spawnSync()` 3 times with shared `options` argument throws an error.

`test.js`:

```javascript
var spawn = require('child_process').spawnSync;
 
var ls;
var opts = {
  stdio: 'inherit'
};
 
ls = spawn('ls', [], opts);
ls = spawn('ls', [], opts);
ls = spawn('ls', [], opts);
```

This bug has been fixed on io.js v1.1.0.

See also: iojs/io.js#576, iojs/io.js#579

**Comment by hail2u** [comment]
Tested on Node.js v0.12.0 (x64) on Windows 7 (64bit)

**Comment by jasnell** [comment]
Confirmed on v0.12.0 on Mac OSX 10.10 as well.

**Comment by cjihrig** [comment]
Landing https://github.com/iojs/io.js/pull/579 here will fix it.

**Comment by jasnell** [comment]
Will queue that one up and and do a PR tomorrow

**Comment by jasnell** [comment]
Had a quick moment so pulled it in.
