### ISSUE TITLE
Error Compiling Armv6 (Raspberry Pi B+)

### ISSUE THREAD

**Issue by nathanjohnson320** [nodejs/node-v0.x-archive#9163]
Tried compiling version 0.12.0 and get this error:

```
  flock /home/pi/node_arm/scripts/node/node-0.12.0/out/Release/linker.lock g++ -pthread -rdynamic  -o /home/pi/node_arm/scripts/node
/node-0.12.0/out/Release/mksnapshot -Wl,--start-group /home/pi/node_arm/scripts/node/node-0.12.0/out/Release/obj.target/mksnapshot/d
eps/v8/src/mksnapshot.o /home/pi/node_arm/scripts/node/node-0.12.0/out/Release/obj.target/deps/v8/tools/gyp/libv8_base.a /home/pi/no
de_arm/scripts/node/node-0.12.0/out/Release/obj.target/deps/v8/tools/gyp/libv8_nosnapshot.a /home/pi/node_arm/scripts/node/node-0.12
.0/out/Release/obj.target/deps/v8/tools/gyp/libv8_libplatform.a /home/pi/node_arm/scripts/node/node-0.12.0/out/Release/obj.target/de
ps/v8/tools/gyp/libv8_libbase.a -Wl,--end-group -lrt
  LINK(target) /home/pi/node_arm/scripts/node/node-0.12.0/out/Release/mksnapshot: Finished
  touch /home/pi/node_arm/scripts/node/node-0.12.0/out/Release/obj.target/deps/v8/tools/gyp/postmortem-metadata.stamp
  LD_LIBRARY_PATH=/home/pi/node_arm/scripts/node/node-0.12.0/out/Release/lib.host:/home/pi/node_arm/scripts/node/node-0.12.0/out/Rel
ease/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps/v8/tools/gyp; mkdir -p /home/pi/node_arm/scripts/node/node-0.12
.0/out/Release/obj.target/v8_snapshot/geni; "/home/pi/node_arm/scripts/node/node-0.12.0/out/Release/mksnapshot" --log-snapshot-posit
ions --logfile "/home/pi/node_arm/scripts/node/node-0.12.0/out/Release/obj.target/v8_snapshot/geni/snapshot.log" "/home/pi/node_arm/
scripts/node/node-0.12.0/out/Release/obj.target/v8_snapshot/geni/snapshot.cc"
Illegal instruction
deps/v8/tools/gyp/v8_snapshot.target.mk:13: recipe for target '/home/pi/node_arm/scripts/node/node-0.12.0/out/Release/obj.target/v8_
snapshot/geni/snapshot.cc' failed
make[1]: *** [/home/pi/node_arm/scripts/node/node-0.12.0/out/Release/obj.target/v8_snapshot/geni/snapshot.cc] Error 132
make[1]: Leaving directory '/home/pi/node_arm/scripts/node/node-0.12.0/out'
Makefile:45: recipe for target 'node' failed
make: *** [node] Error 2
```

**Comment by misterdjules** [comment]
How did you build node? More specifically, what options did you pass to `configure`? The `configure` script creates a `config.gypi` file at the root of the source directory that contains all configuration options. Could you please paste the content of this file in this issue?

If you didn't disable V8 snapshots with `configure --without-snapshot`, could you please try to run `./configure --without-snapshot`, build node and let us know if it built successfully?

**Comment by nathanjohnson320** [comment]
I did ./configure without args. I'll try again with the no snapshot setting.

**Comment by fivdi** [comment]
The same issue was fixed recently in io.js. In additon to the `--without-snapshot` option two changes were required; [https://github.com/bnoordhuis/io.js/commit/8afcc5e701538e5a442a0334d781eac202cc4e1d](https://github.com/bnoordhuis/io.js/commit/8afcc5e701538e5a442a0334d781eac202cc4e1d) and [https://github.com/bnoordhuis/io.js/commit/6f7494292e22b1f1050abeaa43f257ac466edf2b](https://github.com/bnoordhuis/io.js/commit/6f7494292e22b1f1050abeaa43f257ac466edf2b).

See [Getting 'illegal instruction' error on armv6](https://github.com/iojs/io.js/issues/283).

**Comment by nathanjohnson320** [comment]
Yep those changes fixed it for me. Thanks fivdi

**Comment by wilson0x4d** [comment]
https://github.com/joyent/node/pull/9068 - pull request for nodejs, though part of the problem is in v8, and not node itself.

**Comment by Fishrock123** [comment]
RPI B+ are now in the Node.js CI for 4.x+, try using a newer version if you have not already.
