### ISSUE TITLE
how to configure with mips-float-abi (soft, hard) option

### ISSUE THREAD

**Issue by artynet** [nodejs/node-v0.x-archive#9167]
Hi there, is there a way to set the floating point to 'soft' for mips architecture again ? In the configure step I'm not able anymore to set : 

**--dest-cpu=mips --with-mips-float-abi=soft**

do I have to omit these fields in the configure step ? 

Regards, Arturo

**Comment by misterdjules** [comment]
What version of node are you using?

**Comment by artynet** [comment]
I'm currently working on the latest tarbal released, node v0.12.0. However I noticed that this option has been missing since the unstable 0.11.X series.

The v8 libraries source is the one embedded in the tarball (since MIPS is fully supported) while teh cross-compiling toolchain is the one for openwrt-12.09 Atheros ar71xx architecture. Take a look at this picture...

![floating](https://cloud.githubusercontent.com/assets/175003/6131312/3fb72498-b14b-11e4-9b22-e7dc1e778b15.png)

any hints for this exception ?

**Comment by misterdjules** [comment]
A [merge from v0.10 to v0.12](https://github.com/joyent/node/commit/fcca3585fea09ab4a5a86628dceeb248ff82b1ff) removed the `configure_mips` function and the rest of the mips related configure code.

Note that you'll have to use `git show -m fcca3585fea09ab4a5a86628dceeb248ff82b1ff` to show the removal of the mips related code, GitHub diffs show only the first parent for merge commits.

@tjfontaine Was it intentional, or an issue with the merge?

**Comment by artynet** [comment]
which is the easiest way to revert it on the 0.12 tarball itself ?

**Comment by misterdjules** [comment]
@artynet If I understand correctly, the node binary you built loads V8 as a shared library? If so, did you make sure that `-msoft-float` was passed to the compiler, and that `CAN_USE_FPU_INSTRUCTIONS` was not defined when building V8?

**Comment by artynet** [comment]
I usually build the V8 libraries with this setting :

```GYPFLAGS="-Dv8_use_mips_abi_hardfloat=false -Dv8_can_use_fpu_instructions=false"```

and I totally see the `-msoft-float` flag when the code is compiling...

**Comment by misterdjules** [comment]
@artynet To "revert" the part of the merge that exposes `--with-mips-float-abi=soft`, you would have to manually revert a small part of fcca3585fea09ab4a5a86628dceeb248ff82b1ff. I [created a patch that does just that](https://gist.github.com/misterdjules/87e38851c9397018d01e) and ran `./configure --dest-cpu=mips --with-mips-float-abi=soft` on my x86 OS X setup. It seems to correctly pass `-D__mips_soft_float=1` to the compiler. However, I have no idea if that would sove your issue.
