### ISSUE TITLE
utimesSync not always working in 0.12.0 on Windows 8.1

### ISSUE THREAD

**Issue by CycoPH** [nodejs/node-v0.x-archive#9168]
got a stat of two files:
a has got mtime = Fri Dec 12 2014 15:03:32 GMT+0200 (South Africa Standard Time)
b has got mtime = Fri Dec 12 2014 15:03:32 GMT+0200 (South Africa Standard Time)

Comparing the two times we get this:
a.mtime.getTime() = 1418389412886
b.mtime.getTime() = 1418389412000

The last three digits are different.  In earlier node versions this is not happening.

So trying to apply utimesSync with the correct mtime does not work

**Comment by misterdjules** [comment]
Could you please show us some minimal code (using no external dependencies) that reproduces the issue? I'm not sure I understand what you're trying to do and what does not work as you would expect.

Thank you!

**Comment by CycoPH** [comment]
Here is a simple test program.  Saved it as test_utimesSync.js
When I run it I get the folllwing:
mtime of file is:1423550151372
mtime of file is:1423550151000

See the last 3 digits not being the same


var fs = require("fs");
var filename = "test_utimesSync.js";
var target = filename+".copy";

var firstStat = fs.statSync(filename);
console.log("mtime of file is:" + firstStat.mtime.getTime() );

// copy the file
var rd = fs.createReadStream(filename);
var wr = fs.createWriteStream(target);
    
wr.on('open', function() {rd.pipe(wr);});
wr.once('finish', function() {
	fs.utimesSync(target, firstStat.atime, firstStat.mtime);

	// Now get the stat data again and check that the mtime is correct
	var secondStat = fs.statSync(target);
	console.log("mtime of file is:" + secondStat.mtime.getTime() );
});
