### ISSUE TITLE
i18n: use backup URLs for downloading ICU.

### ISSUE THREAD

**Issue by srl295** [nodejs/node-v0.x-archive#9184]
ICU's download links aren't working now due to a sourceforge problem. Should allow backup URLs.

**Comment by misterdjules** [comment]
Just to provide more context, downloading the ICU tarball works now after you removed the redirect from icu-project.org to SourceForge. The original issue was that SourceForge was in "disaster recovery mode" and would not allow direct downloads. It seems direct downloads from SourceForge are working again now, so it would be safe to put the redirection back.

Having fallback ICU download URLs would certainly help mitigate this type of issues in the future.

**Comment by jasnell** [comment]
@srl295 ... do we need to keep this one open?

**Comment by srl295** [comment]
Closed in favor of https://github.com/nodejs/node/issues/2746
