### ISSUE TITLE
IncomingMessage.socket.setEncoding() throws exception on next request

### ISSUE THREAD

**Issue by petersirka** [nodejs/node-v0.x-archive#9210]
Hello,
I found a problem. My framework receives data and I manually set the socket encoding because once I've had a problem with diacritics.

I downloaded the latest version v0.12.0 and the application crashes on OSX. The console shows (on a second request):
`Assertion failed: (Buffer::HasInstance(args[0]) == true), function Execute, file ../src/node_http_parser.cc, line 392.`

This is the problem:
`req.socket.setEncoding('utf8');`

I haven't any problem on my server Ubuntu Server with node.js `v0.10.33`. Is there my mistake or is there a bug?

Thanks :+1:

**Comment by kevdez** [comment]
The fix I had for this was to comment out the encoding of the response, in my case: 

    var request = http.request(post_options, function (response){
        var body = "";
	console.log('STATUS: ' + response.statusCode)

	//response.socket.setEncoding('utf8')

	response.on('data', function (chunk){
		// console.log(JSON.stringify(JSON.parse(chunk), null, 4))
		body += chunk
	})
    })
