### ISSUE TITLE
make repl generic

### ISSUE THREAD

**Issue by piranna** [nodejs/node-v0.x-archive#9224]
Node.js REPL module is mostly intended to create Javascript interpreters, but with some minominor changes (mostly move out the Javascript sanitiziers to the caller functions) would be used as a powerful general purpose REPL to be used for command lines inside apps, similar to how Python cmd & cmd2 packages can be used.

**Comment by a8m** [comment]
I think you're asking for something like [readline](http://nodejs.org/api/readline.html) module @piranna

**Comment by piranna** [comment]
Not exactly, on nsh we were using readline but moved to repl because readline was too simple and low level (and at the end, repl inherit from it :-D), I'm only asking about thing like the wrapping of the input command with parenthesis should be moved out and allow to get the raw input without loosing the other features. On nsh, we are doing it by monkeypatching the repl instance and get as a separate function the async eval, that's why I'm asking about this... :-/
