### ISSUE TITLE
Compiling node-v0.12.0 on FreeBSD-MIPS

### ISSUE THREAD

**Issue by seasox** [nodejs/node-v0.x-archive#9229]
I try to compile 0.12.0 on a MIPS processor running FreeBSD: FreeBSD csbuild.home.sezi.eu 10.1-STABLE FreeBSD 10.1-STABLE #2 r275563M: Tue Dec  9 14:16:11 CET 2014     root@build.home.sezi.eu:/usr/home/sz/cs_image/obj/mips/mips.mips/usr/home/sz/cs_image/src_10_stable/sys/CARAMBOLA2  mips

Anyway, the build fails with the following message:

  ln -f "/usr/home/jb/nodejs/node-v0.12.0/out/Release/obj.target/deps/uv/libuv.a" "/usr/home/jb/nodejs/node-v0.12.0/out/Release/libuv.a" 2>/dev/null || (rm -rf "/usr/home/jb/nodejs/node-v0.12.0/out/Release/libuv.a" && cp -af "/usr/home/jb/nodejs/node-v0.12.0/out/Release/obj.target/deps/uv/libuv.a" "/usr/home/jb/nodejs/node-v0.12.0/out/Release/libuv.a")
  g++ '-DV8_TARGET_ARCH_MIPS' '-DCAN_USE_FPU_INSTRUCTIONS' '-D__mips_hard_float=1' '-D_MIPS_ARCH_MIPS32R2' '-DENABLE_DISASSEMBLER' '-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC' '-DENABLE_HANDLE_ZAPPING' -I../deps/v8  -pthread -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -I/usr/local/include -EB -mhard-float -mips32r2 -Wa,-mips32r2 -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -MMD -MF /usr/home/jb/nodejs/node-v0.12.0/out/Release/.deps//usr/home/jb/nodejs/node-v0.12.0/out/Release/obj.target/v8_base/deps/v8/src/accessors.o.d.raw  -c -o /usr/home/jb/nodejs/node-v0.12.0/out/Release/obj.target/v8_base/deps/v8/src/accessors.o ../deps/v8/src/accessors.cc
../deps/v8/src/accessors.cc:1: error: -mips32r2 conflicts with the other architecture options, which specify a mips32 processor
deps/v8/tools/gyp/v8_base.target.mk:302: die Regel für Ziel „/usr/home/jb/nodejs/node-v0.12.0/out/Release/obj.target/v8_base/deps/v8/src/accessors.o“ scheiterte
gmake[1]: **\* [/usr/home/jb/nodejs/node-v0.12.0/out/Release/obj.target/v8_base/deps/v8/src/accessors.o] Fehler 1
gmake[1]: Verzeichnis „/usr/home/jb/nodejs/node-v0.12.0/out“ wird verlassen
Makefile:45: die Regel für Ziel „node“ scheiterte
gmake: **\* [node] Fehler 2

Is there a way to fix this?

**Comment by soulars** [comment]
Can you confirm that "g++" is a mipsel compiler or not? Please descirpe your configure and Makefile files.

**Comment by seasox** [comment]
I'm not sure how to determine if g++ is a mipsel compiler. Here is the output of ``g++ -v'', hope that helps:
> \# g++ -v
> Using built-in specs.
> Target: mips-undermydesk-freebsd
> Configured with: FreeBSD/mips system compiler
> Thread model: posix
> gcc version 4.2.1 20070831 patched [FreeBSD]

I'm using a Carambola2 by 8devices, which is big endian.

root@csbuild:~/node-v0.12.2 \# cat config.mk
> \# Do not edit. Generated by the configure script.
> PYTHON=/usr/local/bin/python
> BUILDTYPE=Release
> USE_XCODE=0
> USE_NINJA=0
root@csbuild:~/node-v0.12.2 \# 

root@csbuild:~/node-v0.12.2 \# cat config.gypi 
> \# Do not edit. Generated by the configure script.
>{ 'target_defaults': { 'cflags': [],
>                       'default_configuration': 'Release',
>                       'defines': [],
>                       'include_dirs': [],
>                       'libraries': []},
>  'variables': { 'clang': 0,
>                 'gcc_version': 42,
>                 'host_arch': 'mips',
>                 'icu_small': 'false',
>                 'node_install_npm': 'true',
>                 'node_prefix': '',
>                 'node_shared_cares': 'false',
>                 'node_shared_http_parser': 'false',
>                 'node_shared_libuv': 'false',
>                 'node_shared_openssl': 'false',
>                 'node_shared_v8': 'false',
>                 'node_shared_zlib': 'false',
>                 'node_tag': '',
>                 'node_use_dtrace': 'false',
>                 'node_use_etw': 'false',
>                 'node_use_mdb': 'false',
>                 'node_use_openssl': 'true',
>                 'node_use_perfctr': 'false',
>                 'openssl_no_asm': 0,
>                 'python': '/usr/local/bin/python',
>                 'target_arch': 'mips',
>                 'uv_library': 'static_library',
>                 'uv_parent_path': '/deps/uv/',
>                 'uv_use_dtrace': 'false',
>                 'v8_enable_gdbjit': 0,
>                 'v8_enable_i18n_support': 0,
>                 'v8_no_strict_aliasing': 1,
>                 'v8_optimized_debug': 0,
>                 'v8_random_seed': 0,
>                 'v8_use_snapshot': 'true',
>                 'want_separate_host_toolset': 0}}
> root@csbuild:~/node-v0.12.2 \# 


I did not modify any config or Makefiles, everything at default.
