### ISSUE TITLE
Error differences between async and sync API functions

### ISSUE THREAD

**Issue by trusktr** [nodejs/node-v0.x-archive#9232]
Why is there a difference in error produced by async vs sync methods?

For example

```
> fs.readdir('./blah', function(err, files) {console.log(err.toString())})
undefined
> Error: ENOENT, readdir './blah'
```

and

```
> fs.readdirSync('./blah')
Error: ENOENT, no such file or directory './blah'
 ... trace omitted.
```

The readdirSync error message is much more helpful. Why does there need to be a difference?

**Comment by trusktr** [comment]
This is apparently fixed in io.js already.

**Comment by brendanashworth** [comment]
I'm pretty sure the issue here is that `Error#toString` strips the Error of its stack trace. But since you say its fixed in io.js (node v4), and I don't think this would be backported, I'll close this for now.
