### ISSUE TITLE
Not clear from documentation how to use a Typed Array eg Float32Array in C++ addon

### ISSUE THREAD

**Issue by metabench** [nodejs/node-v0.x-archive#9247]
Also, the 'docs' part of node.js does not link to addon documentation as far as I can tell. I've used Google to find information on writing addons.

I have not seen anything on how to use a typed array, within C++, that has been passed in as an argument.

Advice on doing that would be appreciated, but it's worth having in the docs too.

**Comment by matthewbauer** [comment]
I've been running into the same problem. I think that v8's API should work find but adding something on top of Node like libchromiumcontent or libwebkit will run into some issues with conflicting versions of ArrayBuffers.
