### ISSUE TITLE
packaged npm-cli.js is different than if you run npm install -g to install a new version

### ISSUE THREAD

**Issue by Mardis** [nodejs/node-v0.x-archive#9249]
It looks like there are several differences between the npm-cli.js script packaged with node. This can cause issues if you upgrade npm via the recommended process.

**Comment by rjstires** [comment]
Open for over two years. Is this still an issue, and if so can you help me understand what the problem is so I can help?

**Comment by gibfahn** [comment]
I don't know what the differences were before, but they look identical to me now (v6.x). If this is still an issue can you reopen on https://github.com/nodejs/node?

[`npm-cli.js` in node](https://github.com/nodejs/node/blob/v6.x/deps/npm/bin/npm-cli.js)
[`npm-cli.js` in npm](https://github.com/npm/npm/blob/v3.9.3/bin/npm-cli.js)
