### ISSUE TITLE
test: Include sniff tests for most popular npm modules

### ISSUE THREAD

**Issue by jasnell** [nodejs/node-v0.x-archive#9262]
One bit that our current test suite does not cover is coverage of the ecosystem. Incorporating some kind of sniff test to make sure changes do not break the most depended on modules out on npm would be good. I've roughed together a very quick, inelegant way of doing so here (https://github.com/jasnell/npm-deps-test). It's not pretty and it's a bit incomplete in that not all of the packages actually have tests to run or use their own test harness but it's a start. This can be made far more intelligent. Ultimately we'd want something that ties into Jenkins but this at least get's us started.

**Comment by jasnell** [comment]
Just an fyi... @CGavrila is working on an expanded version of this that we're hoping to get a pull request in on shortly. The tool is up and running but has issues running on Windows. The plan is to get a few of the issues resolved, do some code cleanup, then get a PR in.

**Comment by sjmarshy** [comment]
is something still being planned for this?

**Comment by bnoordhuis** [comment]
Not only planned, it exists: https://github.com/nodejs/citgm

I'll close out the issue.
