### ISSUE TITLE
execSync and spawnSync do not return stdout if stdout is not 'pipe'

### ISSUE THREAD

**Issue by devTristan** [nodejs/node-v0.x-archive#9265]
```javascript
var c = require('child_process');

c.execSync('ls').toString(); //returns stdout
c.execSync('ls', {stdio: [0, 1, 2]}).toString(); //returns null
```

I want to run a command with the parent process' stdout+stderr while also capturing both.

**Comment by asyncanup** [comment]
I could do this and submit a pull request if core devs think this should be fixed.

**Comment by piscisaureus** [comment]
That's correct. If you let the child process inherit the parent's stdio, node is unable to capture the output.

> I want to run a command with the parent process' stdout+stderr while also capturing both.

So that's technically impossible.

**Comment by devTristan** [comment]
Not impossible, just non-trivial. I can think of a couple ways to achieve this, and apparently @asyncanup has an idea as well. Bare minimum, this is a wontfix + documentation issue.

**Comment by piscisaureus** [comment]
> Bare minimum, this is a wontfix + documentation issue.

The only thing node could do is "pipe" the stream to both stdout and capture it. That's something that could easily be done in userland as well, so I don't see why node should do it for you.

A documentation patch would be appreciated.

**Comment by devTristan** [comment]
That is a solution for exec and spawn, but not for execSync or spawnSync because they are sync.

**Comment by jasnell** [comment]
@piscisaureus +1

**Comment by hunterloftis** [comment]
+1

**Comment by devTristan** [comment]
I implemented it for shelljs, which is why I created this issue. Here's one unix-only solution:

```javascript
execSync('ls | tee ./output.txt')
var output = fs.readFileSync('./output.txt');
```

**Comment by BuddyLReno** [comment]
I'd love to see how this can be done.

**Comment by mattklein999** [comment]
@hunterloftis I may be missing something, but can't you just use:

```
var r = spawnSync('ls');
console.log(r.stdout.toString());
console.log(r.stderr.toString());
```

[doc](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options)

**Comment by cjihrig** [comment]
I'm going to close this, as this repo is no longer active. If anyone is interested in following up, please head over to nodejs/node. FWIW, I think this should a documentation patch.
