### ISSUE TITLE
http: add abort event request()

### ISSUE THREAD

**Issue by cjihrig** [nodejs/node-v0.x-archive#9278]
There doesn't seem to be a good way (or at least I haven't found one) to detect when `ClientRequest.prototype.abort()` is called. There is `ClientRequest.prototype.aborted`, but that would require observing the object. It would be nice to have an `abort` event emitted in this case.

As a test case, I would like to detect the abort in the following code:

```javascript
var assert = require('assert');
var http = require('http');
var server = http.createServer(function(req, res) {
  res.end();
});

server.listen(4000, function() {
  function connect(cb) {
    var req = http.request({
      port: 4000
    }, cb);

    return req;
  }

  var req = connect(function() {
    assert(false);
  });


  req.abort();
});
```

**Comment by cjihrig** [comment]
@misterdjules I propose landing https://github.com/iojs/io.js/commit/2ca22aacbdd11c572e71ee1b15af3bec1e04a0c1 to address this. Thoughts?

**Comment by geek** [comment]
@cjihrig and @misterdjules seems like a good addition to node

**Comment by misterdjules** [comment]
@cjihrig @geek I think I don't understand the use case correctly. Is it specific to when a request is aborted before the connection has been established?

**Comment by cjihrig** [comment]
@misterdjules if you want the back story, see https://github.com/hapijs/wreck/pull/73. Basically, a library passes an instance of `ClientRequest` around. If the request is constructed and then immediately aborted, there doesn't appear to be a way of triggering a callback. I brought it up on today's call (I think before you joined). TJ mentioned that it should be fine for the master branch.

**Comment by tjfontaine** [comment]
It's totally reasonable to emit an event for 'abort', though it's an API addition and therefore not something that can be included in v0.12.

Looking at the change @cjihrig does it make sense in the scheme of things for `abort` to be called more than once? If the API is idempotent then it should have an early return, and avoid the rest of the method body. That should make the emit logic much more straight forward to only happen once, and preserve the time at which abort was called.

**Comment by cjihrig** [comment]
@tjfontaine do you mean effectively adding an `else return;` after [this](https://github.com/iojs/io.js/blob/v1.x/lib/_http_client.js#L174) line (it could be rewritten in other ways)? If so, that makes sense to me.

**Comment by tjfontaine** [comment]
@cjihrig ya, I think my preference would be `if(this.aborted) return;` if multiple calls to `abort()` should be allowed to succeed.

**Comment by michaelnisi** [comment]
Why isn't this covered with an `'error'` event? It's unclear to me why it should be so specific.

**Comment by kanongil** [comment]
@michaelnisi Indeed. I had a similar concern towards the io.js issue.

**Comment by cjihrig** [comment]
Explicitly aborting a connection is not an error.

**Comment by kanongil** [comment]
@cjihrig True, but it is the only decent way to signal the condition within the existing api, and it matches the 0.10 behavior. Note that this does not exclude adding an 'abort' event at a later stage.

**Comment by jasnell** [comment]
@kanongil ... while that would likely allow us to get this into v0.12 without introducing an api change, it seems like a short term fix. @cjihrig is right, aborting is not an error and shouldn't be treated as such. This is definitely a good change but it's something that can push to v0.13 (let's just not take a long time to get v0.13 out ;-) ...)

**Comment by michaelnisi** [comment]
I don't question adding an `'abort'` event, but removing the `'error'` event.

**Comment by cjihrig** [comment]
Closing as 0.13 seems unlikely to be released.
