### ISSUE TITLE
Docs say Node always uses SO_REUSEADDR, but 0.11.3 and onward do not

### ISSUE THREAD

**Issue by jzwinck** [nodejs/node-v0.x-archive#9280]
On http://nodejs.org/api/net.html it says:

> (Note: All sockets in Node set SO_REUSEADDR already)

But since 0.11.3 this is no longer the case (see release notes which just mention the addition of the reuseAddr option in createSocket).

This breaks real applications in the wild...having such an API breakage in a point release is disruptive.  See for example: https://github.com/xat/node-mdns-js/commit/bc5598ff86c441cb256503e3d951e8b6b8079e8a

**Comment by jzwinck** [comment]
@jasnell Any update on this?  The docs seem to still be wrong, 1.5 years later.

**Comment by bnoordhuis** [comment]
You are linking to the documentation for the net module but the reuseAddr option is from the dgram module, where it is properly documented.  I'm going to close the issue, I don't see a bug.

Aside: v0.11.3 was a development release.  The rules about API stability didn't apply to those.

Aside aside: this repository has been archived.  Please file new issues at https://github.com/nodejs/node/issues.
