### ISSUE TITLE
v0.12 Binaries for sunos do not work on Solaris 11.2 - Error: listen EPROTOTYPE

### ISSUE THREAD

**Issue by GeorgeBailey** [nodejs/node-v0.x-archive#9282]
I tried on both the x86 and x64 versions with same results.

```
root@myhost:/mydir/opt# node-v0.10.36-sunos-x64/bin/node -e "require('http').createServer().listen(8080)"

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen Unknown system errno 98
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at [eval]:1:32
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
root@myhost:/surfn/opt# node-v0.12.0-sunos-x64/bin/node -e "require('http').createServer().listen(8080)"
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EPROTOTYPE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1112:19)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at [eval]:1:32
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
root@myhost:/mydir/opt# 
```

I've managed for now using Peter Tribble's build for Solaris 10, on my Solaris 11.2 machine. However, this should not be necessary, and I'd rather rely on the official build in case some of my work is brought into question down the road.

**Comment by piscisaureus** [comment]
Could it be that your Solaris version doesn't support IPv6?

**Comment by GeorgeBailey** [comment]
I have disabled IPv6 intentionally. Is this the problem? Is there a way I can tell my app not to listen on IPv6? I already tried specifying the IPv4 address to listen on but am not 100% sure if I did it thoroughly. Let me know if you want me to run some test code and post the results.

**Comment by cgalibern** [comment]
It looks like same issues as this one: https://github.com/joyent/node/issues/7004
you need to build manually node from source code.

**Comment by GeorgeBailey** [comment]
Does that commit solve the problem?

**Comment by GeorgeBailey** [comment]
@cgalibern, Does this commit solve the problem?

**Comment by cgalibern** [comment]
Yes you can try: 
```
git clone https://github.com/cgalibern/node.git
cd node
./configure --dest-cpu=x64  --dest-os=solaris --prefix=/opt/node --without-mdb
gmake
```

**Comment by GeorgeBailey** [comment]
I don't know whether I am set up correctly as last time I built from source "it didn't work".

I will try your commands and post results later on today.

**Comment by GeorgeBailey** [comment]
Thanks to the `--without-mdb` option, I got a lot further. However I received the following error
```Node.js compile error: could not find objdump```
```Check that GNU binutils are installed and included in PATH```

```which gobjcopy``` outputs ```/usr/bin/gobjcopy```

**Comment by cgalibern** [comment]
Hi George,
you will find it into pkg 'developer/gnu-binutils', so you need  'pkg install developer/build/gnu-make'
I have used developer/gcc-48 to compile

**Comment by cgalibern** [comment]
Hi George,
Any news about your issue ?

**Comment by jasnell** [comment]
@GeorgeBailey ... is this still an issue?

**Comment by GeorgeBailey** [comment]
@cgalibern, @jasnell Yes,

I tried again with Node.JS v0.12.5 (latest version) pre-compiled and am still getting `EPROTOTYPE` (new line numbers)

So I tried from source, and still got the
`Node.js compile error: could not find objdump`
`Check that GNU binutils are installed and included in PATH`
during compile.

**details on my building from source**

On `pkg install developer/build/gnu-make` I'm getting `No updates necessary for this image.`. Maybe it's redundant to the `pkg install gcc git mercurial` I ran previously.

Seeing the package is `'`=installed with `pkg list`, I tried to build from source.
    mkdir /gb/opt/github-cgalibern
    cd /gb/opt/github-cgalibern
    git clone https://github.com/cgalibern/node.git
    cd node
    export
    ./configure --dest-cpu=x64  --dest-os=solaris --prefix=`pwd` --without-mdb
    gmake

Followed by enormous output, ending in the same error.

      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_zlib.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_zlib.o ../src/node_zlib.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_i18n.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_i18n.o ../src/node_i18n.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/pipe_wrap.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/pipe_wrap.o ../src/pipe_wrap.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/signal_wrap.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/signal_wrap.o ../src/signal_wrap.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/smalloc.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/smalloc.o ../src/smalloc.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/spawn_sync.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/spawn_sync.o ../src/spawn_sync.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/string_bytes.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/string_bytes.o ../src/string_bytes.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/stream_wrap.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/stream_wrap.o ../src/stream_wrap.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/tcp_wrap.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/tcp_wrap.o ../src/tcp_wrap.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/timer_wrap.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/timer_wrap.o ../src/timer_wrap.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/tty_wrap.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/tty_wrap.o ../src/tty_wrap.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/process_wrap.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/process_wrap.o ../src/process_wrap.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/udp_wrap.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/udp_wrap.o ../src/udp_wrap.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/uv.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/uv.o ../src/uv.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/util.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/util.o ../src/util.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_crypto.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_crypto.o ../src/node_crypto.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_crypto_bio.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_crypto_bio.o ../src/node_crypto_bio.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_crypto_clienthello.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_crypto_clienthello.o ../src/node_crypto_clienthello.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/tls_wrap.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/tls_wrap.o ../src/tls_wrap.cc
      g++ '-D_GLIBCXX_USE_C99_MATH' '-DNODE_WANT_INTERNALS=1' '-DARCH="x64"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=1' '-DHAVE_DTRACE=1' '-D__POSIX__' '-DPLATFORM="sunos"' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/gb/opt/github-cgalibern/node/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/openssl/openssl/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -Wall -Wextra -Wno-unused-parameter -m64 -pthreads -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /gb/opt/github-cgalibern/node/out/Release/.deps//gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_dtrace.o.d.raw  -c -o /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_dtrace.o ../src/node_dtrace.cc
      LD_LIBRARY_PATH=/gb/opt/github-cgalibern/node/out/Release/lib.host:/gb/opt/github-cgalibern/node/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p /gb/opt/github-cgalibern/node/out/Release/obj/gen; tools/genv8constants.py "/gb/opt/github-cgalibern/node/out/Release/obj/gen/v8constants.h" "/gb/opt/github-cgalibern/node/out/Release/obj.target/deps/v8/tools/gyp/libv8_base.a"
    
          Node.js compile error: could not find objdump
    
          Check that GNU binutils are installed and included in PATH
          
      LD_LIBRARY_PATH=/gb/opt/github-cgalibern/node/out/Release/lib.host:/gb/opt/github-cgalibern/node/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p /gb/opt/github-cgalibern/node/out/Release/obj.target/node/src; dtrace -64 "-I/gb/opt/github-cgalibern/node/out/Release/obj/gen" -Isrc -C -G -s src/v8ustack.d -o "/gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_dtrace_ustack.o"
    dtrace: failed to compile script src/v8ustack.d: line 399: failed to resolve V8DBG_OFF_FP_CONTEXT: Unknown variable name
    gmake[1]: *** [/gb/opt/github-cgalibern/node/out/Release/obj.target/node/src/node_dtrace_ustack.o] Error 1
    gmake[1]: Leaving directory `/gb/opt/github-cgalibern/node/out'
    gmake: *** [node] Error 2

**Comment by jasnell** [comment]
@misterdjules ... any thoughts?

**Comment by misterdjules** [comment]
@GeorgeBailey That looks similar to https://github.com/joyent/node/issues/7933. Did you make sure that `objdump` is in your PATH when building node?

**Comment by GeorgeBailey** [comment]
Ah, I didn't realize `objdump` was the name of an executable. I will try again with `export PATH=$PATH:/usr/gnu/bin`.

I'll try it again next time I'm on this project, I'll post the results, hopefully June 18.

I'm using Peter Tribble's v0.10 build in the meantime.

**Comment by GeorgeBailey** [comment]
I tried building from cgalibern's fork again with `export PATH=$PATH:/usr/gnu/bin` and it worked. v0.12 is pretty old now. I posted [an issue on the new repo](https://github.com/nodejs/node/issues/3349) for v4.2.0.
