### ISSUE TITLE
dns.resolveTxt segfault 

### ISSUE THREAD

**Issue by maxtaco** [nodejs/node-v0.x-archive#9285]
To reproduce, run:

```javascript
var dns = require('dns');
dns.resolveTxt('www.ralphrooding.com', function(err, res) {})
```

Node version is v0.12.0

First reported here: https://github.com/keybase/keybase-issues/issues/1413

**Comment by iankronquist** [comment]
I was sent here by [code triage](http://codetriage.com/).
This issue appears to have been fixed for node 0.12.8 and above. See commit 261fa36 which references this issue. I recommend that it be closed.
