### ISSUE TITLE
Node v0.12: npm update -g deletes npm

### ISSUE THREAD

**Issue by jvilk** [nodejs/node-v0.x-archive#9291]
I upgraded from the latest v0.10 to v0.12 to see if my previous bug report (#9273) occurs on v0.12.

Post-upgrade, `npm update -g` totally failed and removed `npm`, so I completely removed Node from my system and reinstalled v0.12. That did not change its behavior; it's failing in the same way.

Here's what I am seeing:

```
$ npm update -g
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/npm']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/npm'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/local/lib/node_modules/npm']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/npm' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jvilk/Code/doppioj8/doppio/npm-debug.log
$ npm
-bash: /usr/local/bin/npm: No such file or directory
```

[Link to npm-debug.log](https://gist.github.com/jvilk/2bc9747340c6d96288c3)

It seems to be [this NPM issue](https://github.com/npm/npm/issues/5659), which is closed for some reason yet not apparently resolved...?

What's going on?

**Comment by smikes** [comment]
This is a known problem with `npm update` in versions prior to 2.6.1.  `npm update -g` in particular causes a problem because it tries to update all global packages and dependencies simultaneously to the latest version, asynchronously, while they are being used.

The safe way to update `npm` is with `npm install -g npm@latest`.

**Comment by jasnell** [comment]
@jvilk ... is this still an issue for you?

**Comment by jvilk** [comment]
Yes. Latest Node (v0.12.5) ships with npm 2.11.2.

Running `npm update -g` still nukes npm, at least on my Mac. It initially fails because global package update/installations must be run as root with `sudo`, which somehow cascades and causes npm to nuke itself.

**Comment by smikes** [comment]
can you test with npm 3.0.0 beta?

**Comment by jvilk** [comment]
3.1.0 beta does not nuke itself:

```
$ npm -v
3.1.0
$ npm update -g
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/karma/node_modules
karma@0.12.36 /usr/local/lib/node_modules/karma
└── karma@0.12.37  extraneous

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v0.12.5
npm ERR! npm  v3.1.0
npm ERR! path /usr/local/lib/node_modules/karma/node_modules
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, access '/usr/local/lib/node_modules/karma/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, access '/usr/local/lib/node_modules/karma/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/karma/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jvilk/npm-debug.log
$ npm

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, test,
    tst, un, uninstall, unlink, unpublish, unstar, up, update,
    upgrade, v, verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/jvilk/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.1.0 /usr/local/lib/node_modules/npm
```

I encourage you to keep this bug open, though, until Node ships with a version of NPM that doesn't have this issue.

**Comment by Saqib92** [comment]
Facing same issue on my Ubuntu 16.04.

name@laptop:~/Desktop$ npm install -g ionic
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/opt/node/bin/node" "/opt/node/bin/npm" "install" "-g" "ionic"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! path /home/saqib/.npm-global/bin/ionic
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/home/saqib/.npm-global/bin/ionic'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/home/saqib/.npm-global/bin/ionic']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/saqib/.npm-global/bin/ionic' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/home/saqib/.npm-global/bin/ionic'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/saqib/.npm-global/bin/ionic']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/saqib/.npm-global/bin/ionic' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/saqib/Desktop/npm-debug.log
name@laptop:~/Desktop$
