### ISSUE TITLE
EADDRINUSE does not specify address

### ISSUE THREAD

**Issue by kumavis** [nodejs/node-v0.x-archive#9294]
My error logs always look like:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
```

I understand what it means, but could the error please include the address attempted to be used?

**Comment by kumavis** [comment]
thanks :cat:

**Comment by jasnell** [comment]
This uses util._errnoException to look up the system error. In theory, _errnoException could be modified to accept additional information but that would be an API change, meaning it wouldn't hit until at least v0.13. Would need to check with @joyent/node-coreteam to see what they would think about this kind of change.

That said, if you enable debugging, the debugging output ought to give you all of the information you need and you can obviously catch the error and output those details yourself.

**Comment by kumavis** [comment]
thanks for the response. if i don't know what port it is, than its usually happening somewhere in someone else's code, and harder to catch.

**Comment by jasnell** [comment]
Yes, I agree that's a challenge. Let's see what the core team says. If they feel it would be appropriate to extend _errnoException with additional data then that's a quick addition I can make. Like I said, however, given that it's an API change, it wouldn't land until v0.13 at least

**Comment by trevnorris** [comment]
Interesting idea to automatically append all known fields added to the error. For example, if this error was caught then the port could be seen by `er.port`. I'm +/-0 right now. Anyone else?

**Comment by cjihrig** [comment]
io.js aded `util._exceptionWithHostPort()`, which provides some additional information on the error. I don't think that's exactly the same thing being discussed here, but it's a starting point.

**Comment by misterdjules** [comment]
@jasnell I believe that @kumavis got this error with node v0.10.x, not with node v0.12.x. In node v0.10.x, this error is thrown via [an internal `errnoException` function](https://github.com/joyent/node/blob/v0.10/lib/net.js#L901-L909). So fixing this in v0.10.x would not be an API change.

For v0.12.x, is `util._errnoException` considered as part of the public API?

**Comment by misterdjules** [comment]
@jasnell Ok, I think I understand what you meant by an API change. Adding properties to the error object would definitely be an API change.

However my understanding of what @kumavis meant in his original comment is that the _message_ that is written to the output should have more information, not the error object itself.

**Comment by jasnell** [comment]
:+1: I would either add an additional input parameter to `util._errnoException` to receive that input or, as @cjihrig mentions, pull over the `util._exceptionWithHostPort` from io.js. To avoid the api change, I can limit the change to just the message output, then look at extending the error object properties for v0.13.

**Comment by misterdjules** [comment]
@jasnell Sounds good to me! Bringing `util._exceptionWithHostPort` in sounds like a good idea too.
