### ISSUE TITLE
path.parse : basename + path.sep issue

### ISSUE THREAD

**Issue by AaronNGray** [nodejs/node-v0.x-archive#9298]
Hi,

Don't know whether this is really an issue or not but paths with no file specified and a trailing directory path separator make the 'base' value the last directory, rather than it being blank. This seems a might inconsistent ?

I am getting the same results on Windows and Linux.

```
var path = require("path");

function path_test() {
    var p = path.parse(path.sep + "test" + path.sep + "test2" + path.sep);

    console.log("root: ", p.root);
    console.log("dir: ", p.dir);
    console.log("base: ", p.base);
    console.log("name: ", p.name);
    console.log("ext: ", p.ext);
}

path_test();
```

gives 

```
root:  \
dir:  \test
base:  test2
name:  test2
ext:
```

as base and name are the same its a bit hard to differentiate all cases IMHO

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#17

**Comment by fastest963** [comment]
I think someone misconfigured the issue mover

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#18

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#19

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#20

**Comment by jasnell** [comment]
Likely not ideal but the documentation here seems to be lacking so it's not clear. / cc @tjfontaine thoughts?

**Comment by AaronNGray** [comment]
There don't seem to be any test cases for trailing slash, and the test
cases that are there are pretty minimal.
