### ISSUE TITLE
vm: custom `require` provided in sandbox not used on multi-level prototype chains

### ISSUE THREAD

**Issue by JeramieH** [nodejs/node-v0.x-archive#9309]
I created a sandbox with a custom shim for 'require'.

If the external script tries to create a multi-level prototype chain (child->parent->grandparent) which is separated into discrete files, the shim is only called on the first level of object creation (child->parent). The subsequent level (parent->grandparent) doesn't call the shim from the sandbox, but appears to use some native/internal require() instead.

Also, the "current directory" seems to change between levels (with regards to relative pathing on the require() calls). All three files are in a subdirectory off the application root called "scripts". On the child level (where the shim is called), the current directory seems to be the application root, so the child requires("./scripts/parent.js"). However on the parent level (when the shim isn't called), the current directory has now changed to the scripts subfolder, so the parent has to use requires("./grandparent.js"). Since all three files are in the same folder, it's very confusing why they'd require different relative paths to work.

**Comment by jasnell** [comment]
It's not clear from your description if you believe this is a node bug or not. Can you please clarify and possibly provide a test case?

**Comment by jasnell** [comment]
@JeramieH ... would you be able to provide a test case that demonstrates the issue?

**Comment by JeramieH** [comment]
http://stackoverflow.com/questions/28788947/node-vm-require-on-first-level-ok-fails-on-second-level
Date: Mon, 29 Jun 2015 12:45:09 -0700
