### ISSUE TITLE
v0.12.0 url utf8 chinese disorderly code 

### ISSUE THREAD

**Issue by cekimy** [nodejs/node-v0.x-archive#9312]
eg url = 'http://api.xxx.com/?boundary=region(深圳)&keyword=莲花山';
in node v0.10.x, when curl in the terminal, req.url displays normally:boundary=region(深圳)&keyword=莲花山
but in node v0.12.0, console.log(req.url) is boundary=region(æ·±å³)&keyword=è²è±å±±

**Comment by piscisaureus** [comment]
What platform is this on?

**Comment by cekimy** [comment]
Linux version 2.6.32.43-tlinux-1.0.8-state (kbuild@tlinux12) (gcc version 4.4.6 20110731 (Red Hat 4.4.6-3) (GCC) ) #1 SMP Tue Jul 9 17:52:58 CST 2013
Linux version 2.6.16.60-0.21-110407 (geeko@buildhost) (gcc version 4.1.2 20070115 (prerelease) (SUSE Linux)) #1 SMP Mon Apr 11 10:40:23 CST 2011
