### ISSUE TITLE
Native addons are compiled with asserts enabled in release mode

### ISSUE THREAD

**Issue by kobalicek** [nodejs/node-v0.x-archive#9314]
I noticed that native addons have always asserts enabled in release mode, at least on windows.

Is this intended?

**Comment by brendanashworth** [comment]
I think so. Assertions in core, afaik, are kept in to catch bugs.

**Comment by kobalicek** [comment]
Can it be at least stated somewhere that you have to define NDEBUG yourself to make release builds? I really thought that builds in "Release" directory should have asserts disabled.

**Comment by brendanashworth** [comment]
@kobalicek are you talking about using `ASSERT()` in a C++ addon or the ones in core? (also maybe see [here](https://github.com/nodejs/node/blob/b55e58042cb30388b6b70df58dd5dd26b12c67d7/src/util.h#L29-L38))

**Comment by kobalicek** [comment]
This is only related to native addons, not node itself. When I build my addon it has asserts enabled, I mean plain "C" `assert` is enabled, which slow downs everything, not just the binding glue.

**Comment by kobalicek** [comment]
I think this is still relevant to the latest node, should I open a new issue at `nodejs/node` instead?

**Comment by brendanashworth** [comment]
I see. Yeah, that'd be best - this is just an issue archive now where issues go to die. Please link to this one though, then I'll close this once the new issue is open.
