### ISSUE TITLE
Port fix for StringBytes::Write()

### ISSUE THREAD

**Issue by trevnorris** [nodejs/node-v0.x-archive#9323]
Ref: https://github.com/iojs/io.js/pull/1042

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#34

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#35

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#36

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#37

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#38

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#39

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#41

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#42

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#43

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#44

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#45
