### ISSUE TITLE
node debug -p id, bt = hangs

### ISSUE THREAD

**Issue by raitucarp** [nodejs/node-v0.x-archive#9350]
My issue is on the first post, generally I have 50k hits real user to my server, for more info
https://github.com/Unitech/PM2/issues/1072#issuecomment-77574575

Also I have one clue
- I can't do strace, since it returns empty output
- cpu is nearly 100%, 99%~

So, I curious what happens, I want debug my process
```node debug -p mypid

> bt
> 
> ```
> hangs here, I need reboot my server to get it up..
> 
> ```

Node version:
0.12.0

Suspect modules that causes my server hang:
- request (since I use 0.12.0 which is maxsocket infinity)
- http-client-socks5, I use tor, when grab data for my user

thanks

**Comment by cjihrig** [comment]
@raitucarp are you able to reduce your problem to a test case that doesn't involve any external dependencies such as `request` or `pm2`?

**Comment by raitucarp** [comment]
I think can't, because that is the main issue here. (maxsockets, etc)
