### ISSUE TITLE
_stream_writable : writeOrBuffer ignores encoding

### ISSUE THREAD

**Issue by jandrieu** [nodejs/node-v0.x-archive#9370]
_stream_writable : writeOrBuffer incorrectly ignores the encoding and sets the encoding to 'buffer' if the chunk is a Buffer, losing the encoding actually passed in to the function.

https://github.com/joyent/node/blob/master/lib/_stream_writable.js#L269

```
function writeOrBuffer(stream, state, chunk, encoding, cb) {
  chunk = decodeChunk(state, chunk, encoding);
  if (util.isBuffer(chunk))
    encoding = 'buffer';
...
```

**Comment by brendanashworth** [comment]
If the chunk is a buffer, then the encoding of the buffer doesn't matter - that only applies to strings, for streams. Buffers are just 8-bit chunks with data inside. If you want to keep track of an encoding to `.toString()`-anize it later with, you're out of luck with streams - they don't provide that functionality for you.
