### ISSUE TITLE
if network shared drive is not reachable, nodejs does not raise err

### ISSUE THREAD

**Issue by mike-aungsan** [nodejs/node-v0.x-archive#9373]
var fse   = require('fs-extra');
var util  = require('util');

fse.access('/mount_shared_drive', fse.W_OK, function(err) {

  if (err) {
    console.log('access err');  console.log();
    // should be able to catch err obj here, but nothing happen here.
    console.log(err);
  }

  //util.debug(err ? 'no access!' : 'can read/write');

});

```
node: ../deps/uv/src/uv-common.c:75: uv_err_name: Assertion `0' failed.
```

**Comment by jasnell** [comment]
Can you provide a test case that does not use a third party module (`fs-extra`)

**Comment by mike-aungsan** [comment]
It is the same with fs.

var fs   = require('fs');
var util = require('util');

fs.readFile('/mount_shared_drive/file.name', function(err, data) {

if (err) {
console.log('readFile err'); console.log();
// should be able to catch err obj here, but nothing happen here.
console.log(err);
}

//util.debug(err ? 'no access!' : 'can read/write');

});
