### ISSUE TITLE
child_process.exec doc is inconsistent with actual implementation

### ISSUE THREAD

**Issue by misterdjules** [nodejs/node-v0.x-archive#9434]
[child_process.exec' documentation](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) states that the `stdout` and `stderr` parameters are instances of `Buffer` by default, but it's actually not the case. They are instances of `Buffer` only if `{ encoding: null}` is passed as options.

The documentation of v0.12.x should be fixed to reflect this behavior.

The original intent was that `stdout` and `stderr` parameters would be instances of `Buffer`. If that still holds true, then the change in behavior should be done in master post v0.12.x.

Adding to milestone 0.12.2 as it's a quick change.

**Comment by tyleranton** [comment]
@misterdjules I can grab this.

**Comment by misterdjules** [comment]
@tyleranton That's great :+1: Please do and submit a PR when you're ready. Also feel free to ping me on #libuv if you need help. Thank you!
