### ISSUE TITLE
Documentation missing for "fs" callback errors

### ISSUE THREAD

**Issue by dead-claudia** [nodejs/node-v0.x-archive#9436]
In the API documentation for the "fs" module, the `err` parameter for any of the callbacks is largely undocumented. [This function](https://github.com/joyent/node/blob/master/src/node.cc#L731-L774) creates the object, which is a direct instance of Error. Could this be fixed?

**Comment by cjihrig** [comment]
What do you mean by fixed?

**Comment by impinball** [comment]
As in the documentation added.
