### ISSUE TITLE
Problem with IPv6 addresses in http.request

### ISSUE THREAD

**Issue by natewatson999** [nodejs/node-v0.x-archive#9440]
http.request does not allow for IPv6 addresses on Windows 8.1 x86_64 with Node version 0.10.35. The problem may exist on other platforms. 

Here's some sample code to test the issue:
server.js: 
var http = require("http");
var server = http.createServer(function(req, res){
    res.write("response");
    res.end();
});
server.listen(80);

client.js:
var http = require("http");
var options = {};
options.port= 80;
//options.host = "0:0:0:0:0:0:0:1";
options.host = "127.0.0.1";
options.method = "GET";
options.path = "/";
console.log("config loaded");
var req = http.request(options, function(res){
    var result = "";
    res.on("data", function(segment){
        result += segment;
    });
    res.on("end", function(){
        console.log(result);
    });
});
req.end();

It yields this error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete](net.js:896:19)

**Comment by natewatson999** [comment]
I fixed the copypaste error in the error

**Comment by cjihrig** [comment]
This problem does not appear to be specific to Windows. I'm seeing it on OS X as well. However, the bug has been fixed in later versions, as it does not appear to be present in 0.12.

**Comment by bahamat** [comment]
You need to use `server.listen(80, '::');`.

**Comment by jasnell** [comment]
@cjihrig ... is this something we want to backport to v0.10?

**Comment by cjihrig** [comment]
I can't really say without knowing what commit(s) fixed the problem.
