### ISSUE TITLE
Backport support for http statusMessage to 0.10.x

### ISSUE THREAD

**Issue by xaka** [nodejs/node-v0.x-archive#9442]
Hi there,

I'm wondering whether it's possible to backport a35a2f0192f78c762ed1009025e673cf09862d4d from 0.12.x to 0.10.x. There are few reasons "why":
1. There are enterprise REST APIs that prefer to leverage HTTP status codes >5xx with custom status messages
2. Most of high level node.js HTTP client libraries, including superagent, are based on "http" core module, which means it's impossible to add a support to those libraries until it's supported by core modules. Another option is to re-implement HTTP parser in JS, which is overkill.
3. Due to nature of business and applications most people are developing for enterprise it's very difficult to switch from 0.10.x to 0.12.x in the nearest feature, but having access to that status message is still very important for seamless integration with some of REST APIs.
4. Status message has been part of HTTP spec forever and it's kind of sad it's been missing in the core since the day one :)

Thanks!

**Comment by Mickael-van-der-Beek** [comment]
Not that it completely solves your problem, it might be useful in the meantime, but the ```http``` module has an object that maps HTTP status codes to their corresponding status codes:

```
require('http').STATUS_CODES
```

returns:

```
{ '100': 'Continue',
  '101': 'Switching Protocols',
  '102': 'Processing',

  // ...

  '509': 'Bandwidth Limit Exceeded',
  '510': 'Not Extended',
  '511': 'Network Authentication Required' }
```

**Comment by xaka** [comment]
@Mickael-van-der-Beek There is no problem with standard HTTP codes, but with custom ones, when service provider sends back something like `HTTP/1.0 699 Account Is Blocked`.

**Comment by Mickael-van-der-Beek** [comment]
@xaka I know, what I meant was that if you do:

```
require('http').STATUS_CODES['699'] = 'Account Is Blocked';
```

doing a:

```
res.status(699).end()
```

in Express.js for example will automatically add the ```Account Is Blocked``` message to the response.

It's a dirty solution but at least it would work for your use case in the meantime that the patch is applied.

**Comment by xaka** [comment]
Service provider re-uses the same status code for different status messages so I cannot (and shouldn't due to bad practice) hard code anything I don't own.
