### ISSUE TITLE
[cluster.js] Include it like any other file

### ISSUE THREAD

**Issue by jshkurti** [nodejs/node-v0.x-archive#9449]
Hello,

I copied the content of cluster.js without changing anything and instead of using ```require('cluster')``` I used ```require('./cluster.js')```.
I have to admit that I didn't really expect this to work at first try out of the box, but sill, I'm curious, why wouldn't it ?

My sample code is : 
```javascript
var http    = require('http');                                 
var cluster = require('./cluster.js');

if (cluster.isMaster) {
  var worker = cluster.fork();

  setInterval(function keepAlive() {}, 1000);
  console.log('Im the master');

} else {
  console.log('Im the worker with pid', process.pid);

  setTimeout(function() {
    process.exit(0);
  }, 2000);

  http.createServer(function(req, res) {
    res.writeHead(200);
    res.end("Hello world\n");
  }).listen(8000);
}
```
It entered an infinite loop which says "Im the master".
I'm guessing ```process.env.NODE_UNIQUE_ID``` has to be set somewhere.
How does it work exactly and what do I have to change to make it work ?

Thanks :)

**Comment by brendanashworth** [comment]
I'm not really sure if this is a supported usecase - internal modules sort of reach into eachother's personal space a lot, which is probably the reason for the error. I'll close this issue though, as it isn't really applicable. Thanks for opening it!
